### ISSUE TITLE
KDateRange implementation in export usage data follow-up

### ISSUE THREAD

**Issue by LianaHarris360** [learningequality/kolibri#10156]
## Summary
Follow up to #10106 

## Expected behavior

The follow up work should address the PR review comments left on the original issue

**Comment by bjester** [comment]
Another issue I'm seeing would be to resolve this warning that appears to originate in the `KDateRange`:
```
console.warn
      It is highly recommended to set `predictableActionArguments` to `true` when using `createMachine`. https://xstate.js.org/docs/guides/actions.html

      12 | import Vuex from 'vuex';
      13 | import { i18nSetup } from 'kolibri.utils.i18n';
    > 14 | import KThemePlugin from 'kolibri-design-system/lib/KThemePlugin';
         | ^
      15 | import KContentPlugin from 'kolibri-design-system/lib/content/KContentPlugin';
      16 |
      17 | global.beforeEach(() => {

      at createMachine (node_modules/xstate/lib/Machine.js:19:13)
      at Object.<anonymous> (node_modules/kolibri-design-system/lib/KDateRange/ValidationMachine.js:100:47)
      at node_modules/kolibri-design-system/lib/KDateRange/index.vue:73:1
      at Object.<anonymous> (node_modules/kolibri-design-system/lib/KDateRange/index.vue:271:3)
      at Object.<anonymous> (node_modules/kolibri-design-system/lib/KThemePlugin.js:8:1)
      at Object.<anonymous> (packages/kolibri-tools/jest.conf/setup.js:14:1)
```

**Comment by LianaHarris360** [comment]
Yes, Richard alerted me to this [issue](https://github.com/learningequality/kolibri-design-system/issues/405) not too long ago. The fix is in this [PR](https://github.com/learningequality/kolibri-design-system/pull/406). This will be resolved once Kolibri is updated to include the newest KDS changes.
