### ISSUE TITLE
Server error when adding static network device

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#10267]
## Observed behavior

I accidentally swapped the address and name when manually adding a network address for a device, and it produced a 500 error which broke the form (wouldn't submit again)

## Errors and logs

```
ERROR    2023-03-16 10:45:51,888 Internal Server Error: /api/discovery/staticnetworklocation/
Traceback (most recent call last):
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/serializers.py", line 236, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/bjester/Projects/learningequality/pyenv/versions/3.9.13/envs/kolibri-3.9.13/lib/python3.9/site-packages/rest_framework/serializers.py", line 437, in run_validation
    value = self.validate(value)
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/serializers.py", line 51, in validate
    client = NetworkClient.build_for_address(data["base_url"])
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/utils/network/client.py", line 71, in build_for_address
    for url in get_normalized_url_variations(address):
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/utils/network/urls.py", line 158, in get_normalized_url_variations
    p_scheme, p_hostname, p_port, p_path = parse_address_into_components(address)
  File "/home/bjester/Projects/learningequality/kolibri/kolibri/core/discovery/utils/network/urls.py", line 147, in parse_address_into_components
    raise errors.InvalidHostname(p_hostname)
kolibri.core.discovery.utils.network.errors.InvalidHostname: local studio
```

## Expected behavior

Errors are appropriately handled

## Steps to reproduce

1) Import channel content
2) Choose local network or internet
3) Manually add a new device
4) Enter an invalid address

## Context

Kolibri develop

**Comment by bjester** [comment]
I likely broke this
