### ISSUE TITLE
Repeatedly getting ‘failed to resume sync sessions’

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10304]
## Observed behavior
Repeatedly getting ‘failed to resume sync sessions’ on facility device 

## Errors and logs
```jsx
INFO     2023-03-23 13:31:08,655 Attempting connections to variations of the URL: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:08,655 Attempting connection to: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:08,704 Success! We connected to: http://172.27.234.9:8080/api/public/info/?v=3
INFO     2023-03-23 13:31:08,711 Enqueuing a sync task for user 4efb706e51dbfd6a0c6f3e8d8824f845 with server http://172.27.234.9:8080/ in job 684f68d415132bf39b74aa00ff1513d5
INFO     2023-03-23 13:31:08,757 Attempting connections to variations of the URL: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:08,757 Attempting connection to: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:08,799 Success! We connected to: http://172.27.234.9:8080/api/public/info/?v=3
WARNING  2023-03-23 13:31:08,861 Failed to resume sync session for user 4efb706e51dbfd6a0c6f3e8d8824f845 to server http://172.27.234.9:8080/; queuing its cleanup
INFO     2023-03-23 13:31:08,866 Requeueing to sync with server http://172.27.234.9:8080/ for user 4efb706e51dbfd6a0c6f3e8d8824f845 in 5 seconds
INFO     2023-03-23 13:31:08,973 Closing SyncSession 1 of 1
INFO     2023-03-23 13:31:14,239 Attempting connections to variations of the URL: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:14,240 Attempting connection to: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:14,289 Success! We connected to: http://172.27.234.9:8080/api/public/info/?v=3
INFO     2023-03-23 13:31:14,295 Enqueuing a sync task for user 4efb706e51dbfd6a0c6f3e8d8824f845 with server http://172.27.234.9:8080/ in job 684f68d415132bf39b74aa00ff1513d5
INFO     2023-03-23 13:31:14,513 Attempting connections to variations of the URL: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:14,514 Attempting connection to: http://172.27.234.9:8080/
INFO     2023-03-23 13:31:14,599 Success! We connected to: http://172.27.234.9:8080/api/public/info/?v=3
INFO     2023-03-23 13:31:15,569 Remotely preparing data
INFO     2023-03-23 13:31:18,325 No records transferred
INFO     2023-03-23 13:31:19,093 127.0.0.1 - - "GET /api/device/usersyncstatus/" 200 0 "http://127.0.0.1:8080/en/device/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36"
INFO     2023-03-23 13:31:20,799 Locally preparing data to send
INFO     2023-03-23 13:31:23,287 No records transferred
INFO     2023-03-23 13:31:24,994 172.27.196.16 - - "GET /api/public/info/" 200 0 "" "python-requests/2.27.1"
INFO     2023-03-23 13:31:25,509 Requeueing to sync with server http://172.27.234.9:8080/ for user 4efb706e51dbfd6a0c6f3e8d8824f845 in 60 seconds
WARNING  2023-03-23 13:31:26,679 Zeroconf network service information could not be retrieved within 10.0 seconds
```

After clearing `UserSyncStatus`, I immediately synced, but then a subsequent synced hit:

```bash
INFO     2023-03-23 13:39:57,297 Attempting connections to variations of the URL: http://172.27.234.9:8080/
INFO     2023-03-23 13:39:57,298 Attempting connection to: http://172.27.234.9:8080/
INFO     2023-03-23 13:39:57,380 Success! We connected to: http://172.27.234.9:8080/api/public/info/?v=3
INFO     2023-03-23 13:39:57,385 Enqueuing a sync task for user 9861f334c2e0a9b8aa5df8ddc049fd25 with server http://172.27.234.9:8080/ in job 7db292f4c306bd6dc3d5269129ca304c
INFO     2023-03-23 13:39:57,574 Attempting connections to variations of the URL: http://172.27.234.9:8080/
INFO     2023-03-23 13:39:57,575 Attempting connection to: http://172.27.234.9:8080/
INFO     2023-03-23 13:39:57,662 Success! We connected to: http://172.27.234.9:8080/api/public/info/?v=3
WARNING  2023-03-23 13:39:57,742 Failed to resume sync session for user 9861f334c2e0a9b8aa5df8ddc049fd25 to server http://172.27.234.9:8080/; queuing its cleanup
INFO     2023-03-23 13:39:57,747 Requeueing to sync with server http://172.27.234.9:8080/ for user 9861f334c2e0a9b8aa5df8ddc049fd25 in 5 seconds
INFO     2023-03-23 13:39:57,785 Closing SyncSession 1 of 1
```

## Context
0.16.0-alpha10 bug bash; @rtibbles's classroom server

**Comment by bjester** [comment]
We should reproduce this after https://github.com/learningequality/kolibri/pull/10312 is merged, in case those issues are related

**Comment by marcellamaki** [comment]
@radinamatic let's do some follow up testing on this to reproduce, also connected to the issue that @jredrejo has had trouble reproducing

**Comment by pcenov** [comment]
Hi @jredrejo, using the latest 0.16.0a13 I was able to replicate the ‘failed to resume sync sessions’ error but unfortunately it's hard to provide any steps to replicate.

My setup was with 2 Ubuntu VMs - first one is a Full facility with 3 learners to whom I've assigned a lesson and a quiz. On the other VM I bulk imported the learners through the Learn-only flow. 

Out of the 3 users I am having trouble syncing with one of the users called 'b', for the other learners it's working fine. Attaching the logs so that you can hopefully see what's going on:

[LearnerLogs+DB.zip](https://github.com/learningequality/kolibri/files/11489037/LearnerLogs%2BDB.zip)

[ServerLogs+DB.zip](https://github.com/learningequality/kolibri/files/11489041/ServerLogs%2BDB.zip)

**Comment by jredrejo** [comment]
Reassigning this issue to Blaine as he's much more familiar with this part of the code. Looking at the logs it seems there's a locking problem in sqlite when trying to update the user data:
```
ERROR 2023-05-16 16:46:27,564 kolibri.core.tasks.job Job 4bb1708da0ec4f4aaacb2453601af584 raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 296, in execute
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/registry.py", line 239, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/tasks.py", line 697, in request_soud_sync
    handle_server_sync_response(response, server, user)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/tasks.py", line 713, in handle_server_sync_response
    UserSyncStatus.objects.update_or_create(user_id=user, defaults={"queued": True})
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist...... 
```

**Comment by bjester** [comment]
@jredrejo Could you provide reproduce steps for how you found the `database is locked` error is causing this?

**Comment by jredrejo** [comment]
@bjester I saw those errors in the logs @pcenov attached to a previous comment. I didn't reproduce the problem.

**Comment by bjester** [comment]
Possibly connected to https://github.com/learningequality/morango/issues/193
