### ISSUE TITLE
Network location model incompatible with previous kolibri versions

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#10401]
## Observed behavior

When running kolibri 0.16 in a network where previous kolibri versions exist, a database error appears always in the 0.16 server

## Errors and logs

```
INFO     2023-04-06 17:41:49,291 Kolibri instance 'd4fce40c265d81182f2fe7c0f16f2dd9' updated zeroconf network; device info: {'application': 'kolibri', 'kolibri_version': '0.15.8', 'instance_id': 'd4fce40c265d81182f2fe7c0f16f2dd9', 'device_name': 'raspi', 'operating_system': 'Linux', 'subset_of_users_device': False}
ERROR    2023-04-06 17:41:49,390 Job 93237cf97ee6b5ebfbbb38ed33fac231 raised an exception: Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 480, in update_or_create
    obj = self.select_for_update().get(**lookup)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 378, in get
    raise self.model.DoesNotExist(
kolibri.core.discovery.models.DoesNotExist: DynamicNetworkLocation matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 69, in execute
    return self.cursor.execute(sql, params)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: discovery_networklocation.min_content_schema_version

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datos/le/mio/kolibri/kolibri/core/tasks/job.py", line 296, in execute
    result = func(*args, **kwargs)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/registry.py", line 239, in __call__
    return self.func(*args, **kwargs)
  File "/datos/le/mio/kolibri/kolibri/core/discovery/tasks.py", line 150, in wrapped
    return func(*new_args)
  File "/datos/le/mio/kolibri/kolibri/core/discovery/tasks.py", line 233, in add_dynamic_network_location
    network_location = _store_dynamic_instance(broadcast_id, instance)
  File "/datos/le/mio/kolibri/kolibri/core/discovery/tasks.py", line 45, in _store_dynamic_instance
    network_location, _ = DynamicNetworkLocation.objects.update_or_create(
  File "/datos/le/mio/kolibri/kolibri/core/discovery/models.py", line 139, in update_or_create
    return super(DynamicNetworkLocationManager, self).update_or_create(
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 484, in update_or_create
    obj, created = self._create_object_from_params(lookup, params, lock=True)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 509, in _create_object_from_params
    six.reraise(*exc_info)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 500, in _create_object_from_params
    obj = self.create(**params)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/datos/le/mio/kolibri/kolibri/core/discovery/models.py", line 159, in save
    return super(DynamicNetworkLocation, self).save(*args, **kwargs)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/base.py", line 807, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/base.py", line 962, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1079, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 65, in execute
    with self.db.wrap_database_errors:
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 69, in execute
    return self.cursor.execute(sql, params)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: discovery_networklocation.min_content_schema_version

```

## Expected behavior
Running kolibri 0.16 in a network with previous versions should have a clean start.

## User-facing consequences

Undetected-bad detected previous versions of kolibri

## Steps to reproduce

1. Run a 0.15 instance in the network
2. Start a 0.16 instance and look at the server console

**Comment by bjester** [comment]
The field was later fixed to make it nullable by updating the existing migration https://github.com/learningequality/kolibri/pull/10261

Seems like you already ran that migration, so you'll need to take some manual action. I think deleting the `networklocation.sqlite3` file should do it.

**Comment by jredrejo** [comment]
In my case, deleting the networklocation db that produces this problem:
```
ERROR    2023-04-07 10:41:06,471 Job 100244d5e327162c226fc0f4ee55579c raised an exception: Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 69, in execute
    return self.cursor.execute(sql, params)
  File "/datos/le/mio/kolibri/venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: discovery_networklocation

The above exception was the direct cause of the following exception:
```
I know my environment might be quite particular because of so many versions and tests I've done, but it would be good if this scneario (one device running kolibri 0.15 in the network, and another device having previously 0.15 and upgraded to 0.16 ) can be tested @radinamatic to ensure this is not a general issue.
I  have checked the problem does not appear if the 0.16 is a clean installation, in my case, it only happens when I reuse the  kolibri environment that has been upgraded from 0.15 to 0.16. Hopefully, it's just my environment is damaged for some tests and it's not a migrations issue.

**Comment by pcenov** [comment]
@jredrejo I am not able to replicate the above described issues. I tested this with 0.15.12 installed on one VM and on the other I installed 0.15.12 which I then upgraded to 0.16.0a12. I then proceeded with testing various interactions between the two instances of Kolibri but I am not getting any exceptions in the logs. Let me know if you need anything else tested for this one.

**Comment by jredrejo** [comment]
Thanks @pcenov , it must be something related to my environment. It must have something wrong after so many tests and code changes. I'm closing this issue.
