### ISSUE TITLE
Can't run Kolibri in Python 3.5

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#1056]
## Summary

Having these error logs when I try to install and run this [Kolibri whl file](https://files.slack.com/files-pri/T0KT5DC58-F4GF6SQPP/download/kolibri-0.2.0.dev3-py2.py3-none-any.whl) in Python 3.5

```
(kolibri-test) users-MacBook-Air:~ user$ kolibri
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/kolibri-test/bin/kolibri", line 7, in <module>
    from kolibri.utils.cli import main
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.5/site-packages/kolibri/utils/cli.py", line 27, in <module>
    from . import server  # noqa
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.5/site-packages/kolibri/utils/server.py", line 6, in <module>
    import cherrypy
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.5/site-packages/kolibri/dist/cherrypy/__init__.py", line 64, in <module>
    from cherrypy._cperror import HTTPError, HTTPRedirect, InternalRedirect
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.5/site-packages/kolibri/dist/cherrypy/_cperror.py", line 118, in <module>
    from cgi import escape as _escape
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/cgi.py", line 42, in <module>
    import html
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.5/site-packages/kolibri/dist/html/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

**Comment by rtibbles** [comment]
Hrm - odd. I've not had this issue while running it in Python 3.4. Could you check in Python 3.4 as well?

**Comment by mrpau-richard** [comment]
@rtibbles the same issue in Python 3.4.3

```
Processing ./Downloads/kolibri-0.2.0.dev3-py2.py3-none-any.whl
Installing collected packages: kolibri
Successfully installed kolibri-0.2.0.dev3
(kolibri-test) users-MacBook-Air:~ user$ kolibri
Traceback (most recent call last):
  File "/Users/user/.virtualenvs/kolibri-test/bin/kolibri", line 7, in <module>
    from kolibri.utils.cli import main
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.4/site-packages/kolibri/utils/cli.py", line 27, in <module>
    from . import server  # noqa
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.4/site-packages/kolibri/utils/server.py", line 6, in <module>
    import cherrypy
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.4/site-packages/kolibri/dist/cherrypy/__init__.py", line 64, in <module>
    from cherrypy._cperror import HTTPError, HTTPRedirect, InternalRedirect
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.4/site-packages/kolibri/dist/cherrypy/_cperror.py", line 118, in <module>
    from cgi import escape as _escape
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/cgi.py", line 42, in <module>
    import html
  File "/Users/user/.virtualenvs/kolibri-test/lib/python3.4/site-packages/kolibri/dist/html/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
(kolibri-test) users-MacBook-Air:~ user$ python -V
Python 3.4.3

```

**Comment by rtibbles** [comment]
`Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.`

Could either of these things be true?

**Comment by mrpau-richard** [comment]
Hi @rtibbles thanks for the help. I think the cause of this issue is the kolibri whl file I installed is built in Python version 2.7.

I tried to build a Kolibri whl file using python 3.4 and it's working fine.
