### ISSUE TITLE
Errors observed during file export

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#10583]
## Observed behavior
Seems like for file copy operations, the new chunked file implementation is giving errors when trying to finalize the copy

## Errors and logs
```
ERROR 2023-04-27 16:36:20,277 kolibri.core.tasks.job Job 5a413705275b4968aabb8ce927b24384 raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 422, in _next
    chunk = next(self._content_iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 296, in execute
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/registry.py", line 239, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/tasks.py", line 380, in diskexport
    drive.datafolder,
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 28, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/exportchannel.py", line 35, in handle_async
    for block in copy:
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 388, in __next__
    return self.next()
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 465, in next
    return self._next()
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 429, in _next
    self.finalize()
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 540, in finalize
    self._move_tmp_to_dest()
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 470, in _move_tmp_to_dest
    self.chunked_file_obj.delete()
  File "/usr/lib/python3/dist-packages/kolibri/utils/file_transfer.py", line 304, in delete
    shutil.rmtree(self.chunk_dir)
  File "/usr/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 26] Text file busy: '/media/sf_VMShared/KOLIBRI_DATA/content/databases/95a52b386f2c485cb97dd60901674a98.sqlite3.chunks'
```

## Expected behavior
We should make sure to close out any possible file references in the chunks folder.

**Comment by Pursottam6003** [comment]
Hii @rtibbles  just curious to duplicate the issue could you help me :) and what i can think if its an error then we can show this error in a formatted way or in an alert `unable to export the file 

Ps: More curious to wait how you will fix this issue :)

**Comment by rtibbles** [comment]
I think maybe for the case of file export, we don't need to use this more complex file transfer mechanism, and could instead just do a direct file copy.
