### ISSUE TITLE
Unhandled error from the device provision endpoint

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#10598]
## Observed behavior
[Reported by @rtibbles in the alpha 13 bug bash ](https://www.notion.so/learningequality/Unhandled-error-from-the-device-provision-endpoint-6e4b0ac806304f45a09d120f12438b83?pvs=4)

> Seems to be happening because I had some saved state, and it was attempting to immediately do the provisioning at start.

## Errors and logs

```
ERROR 2023-04-27 09:37:35,307 django.request Internal Server Error: /api/device/deviceprovision/
Traceback (most recent call last):
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/core/device/api.py", line 91, in create
    data = serializer.save()
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/core/device/serializers.py", line 118, in create
    facility = Facility.objects.get(pk=facility_id)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/richard/.pex/install/kolibri-0.16.0a13-py2.py3-none-any.whl.5fde7692abbe85a2d3272cba207b2e678d7f19c6/kolibri-0.16.0a13-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
DoesNotExist: Facility matching query does not exist.
```

## Context
v0.16.0-a13

**Comment by rtibbles** [comment]
At the very least, we should raise a 400 from the backend for this scenario - and then revert to the most recent state where this could be rectified in the setup wizard.

**Comment by rtibbles** [comment]
Let's ensure that this scenario reported by @pcenov is fixed when this is resolved too: https://github.com/learningequality/kolibri/pull/10698#pullrequestreview-1428328997

**Comment by rtibbles** [comment]
Full comment:

1. Create a Full device with a Main facility and an imported one.
2. On a separate VM start the setup wizard and go through Learn-only device > Create a new user for an existing facility.
3. While at 'Select learning facility' chose the second facility.
4. Enter the credentials for an existing user on the Main facility - note that it incorrectly says that the user exists while that user exists only at the Main facility.
5. Enter the credentials for a brand new user not existing on any of the facilities and click Continue - a 500 error is displayed in the console.

Note that if you refresh the user's page at the Main facility the user will be listed there without a Full name value.

Video:

https://github.com/learningequality/kolibri/assets/79847249/89f76790-d30c-4837-8dce-45071a8a605c

Logs:
[Logs.zip](https://github.com/learningequality/kolibri/files/11487105/Logs.zip)
