### ISSUE TITLE
Kolibri channels fails to update and import

### ISSUE THREAD

**Issue by lsolesen** [learningequality/kolibri#10696]
## Observed behavior

I have setup 4 computers on the facility. One main computer and staff computers, I sync the content to. Recently the computers fail to update the channel, and it also fails to import content.

![20230512_131656](https://github.com/learningequality/kolibri/assets/148026/3923952f-aefb-4c10-ad07-ad390b56b147)

![20230512_142251](https://github.com/learningequality/kolibri/assets/148026/444371a7-8a87-4102-a97e-a4bc8d62e08d)

![20230512_134125](https://github.com/learningequality/kolibri/assets/148026/4305e60e-2e7f-4a5b-88cd-e4c620b3285b)

![20230512_155631](https://github.com/learningequality/kolibri/assets/148026/a121d8bb-b144-40d6-a57a-8d5b2ba2da82)

That makes it impossible to sync the Kolibri channels between the computers.

This used to work, but now it does not work on three of the local computers here. I have not switched Kolibri version on any of the computers.

Even if I try to sync the channel from the Kolibri studio on the affected computers, I will get the same error.

    TypeError: An id must be specified
…

## Errors and logs

Logs from one computer:

- [daemon.txt](https://github.com/learningequality/kolibri/files/11464858/daemon.txt)
- [debug.txt](https://github.com/learningequality/kolibri/files/11464859/debug.txt)
- [kolibri.txt](https://github.com/learningequality/kolibri/files/11464861/kolibri.txt)

Logs from the other computer affected by same issues:

- [debug.txt](https://github.com/learningequality/kolibri/files/11464978/debug.txt)
- [kolibri.txt](https://github.com/learningequality/kolibri/files/11464981/kolibri.txt)

…

## Expected behavior

…

## User-facing consequences

Kolibri is unusable when more people are using more devices to conduct teaching.
…

## Steps to reproduce

…

## Context

 * Kolibri version: 0.15.11
 * Operating system: Windows
 * Browser: Chrome
…

**Comment by rtibbles** [comment]
Hi @lsolesen - thanks for including the log files, this helps a lot with tracking down what is happening.

This seems to be an issue with the channel database file on disk being malformed after the download.
From the log file:
```
ERROR 2023-05-12 13:41:29,358 kolibri.core.tasks.worker Job 1e732804e2c24a40ae84505d2d900657 raised an exception: Traceback (most recent call last):
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\kolibri\core\tasks\worker.py", line 61, in handle_finished_future
    result = future.result()
  File "C:\Python36\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Python36\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Python36\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python36\lib\site-packages\kolibri\core\tasks\job.py", line 121, in execute_job
    result = func(*args, **kwargs)
  File "C:\Python36\Lib\site-packages\kolibri\dist\django\core\management\__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "C:\Python36\Lib\site-packages\kolibri\dist\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python36\lib\site-packages\kolibri\core\tasks\management\commands\base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "C:\Python36\lib\site-packages\kolibri\core\content\management\commands\importchannel.py", line 235, in handle_async
    self.copy_channel(
  File "C:\Python36\lib\site-packages\kolibri\core\content\management\commands\importchannel.py", line 116, in copy_channel
    self._transfer(
  File "C:\Python36\lib\site-packages\kolibri\core\content\management\commands\importchannel.py", line 169, in _transfer
    self._start_file_transfer(
  File "C:\Python36\lib\site-packages\kolibri\core\content\management\commands\importchannel.py", line 213, in _start_file_transfer
    import_ran = import_channel_by_id(
  File "C:\Python36\lib\site-packages\kolibri\core\content\management\commands\importchannel.py", line 26, in import_channel_by_id
    return channel_import.import_channel_from_local_db(
  File "C:\Python36\lib\site-packages\kolibri\core\content\utils\channel_import.py", line 1139, in import_channel_from_local_db
    import_manager = initialize_import_manager(
  File "C:\Python36\lib\site-packages\kolibri\core\content\utils\channel_import.py", line 1093, in initialize_import_manager
    channel_metadata = read_channel_metadata_from_db_file(
  File "C:\Python36\lib\site-packages\kolibri\core\content\utils\channels.py", line 85, in read_channel_metadata_from_db_file
    source = Bridge(sqlite_file_path=channeldbpath)
  File "C:\Python36\lib\site-packages\kolibri\core\content\utils\sqlalchemybridge.py", line 308, in __init__
    db_matches_schema(BASES[self.schema_version], self.engine)
  File "C:\Python36\lib\site-packages\kolibri\core\content\utils\check_schema_db.py", line 23, in db_matches_schema
    tables = iengine.get_table_names()
  File "<string>", line 2, in get_table_names
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\util\deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\reflection.py", line 202, in get_table_names
    tnames = self.dialect.get_table_names(
  File "<string>", line 2, in get_table_names
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\dialects\sqlite\base.py", line 1609, in get_table_names
    rs = connection.execute(s)
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 2244, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 1012, in execute
    return self._execute_text(object_, multiparams, params)
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 1181, in _execute_text
    ret = self._execute_context(
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 1323, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 1517, in _handle_dbapi_exception
    util.raise_(
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\base.py", line 1283, in _execute_context
    self.dialect.do_execute(
  File "C:\Python36\Lib\site-packages\kolibri\dist\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
[SQL: SELECT name FROM sqlite_master WHERE type='table' ORDER BY name]
(Background on this error at: http://sqlalche.me/e/4xp6)
```

Can you describe in more detail the exact flow that you were doing when this happened? I just want to isolate how this database file might have become malformed, so we can take steps to a) prevent that, and b) remedy it when it does happen.

For immediate resolution so you can continue your work, I would suggest deleting the files in the content/databases folder of the affected devices.

**Comment by lsolesen** [comment]
I download on one device. Then I use that device to do a local import on
the other machines. I do not think I did anything special, but it is a bit
strange that two computers ended up with malformed databases at more or
less the same time.

Sorry I cannot be of more help to the flow.

Which exact files and directors do you suggest I delete for a quick fix to
the issue.

fre. 12. maj 2023 16.28 skrev Richard Tibbles ***@***.***>:

**Comment by rtibbles** [comment]
> but it is a bit strange that two computers ended up with malformed databases at more or less the same time.

Yes, this is a bit unusual - and not something we've seen broadly reported before, which is why I was wondering if there was anything uncommon, but it doesn't seem so.

For it to have happened to _all_ the other devices, it does make me suspect that there is something amiss about the channel database file on the source machine.

For the quick fix, in the same folder as you found the `logs` folder to extract and upload the log files, there should be a folder called `content` and another in that called `databases`. Inside that there should be at least one file, with the file name `<channel_id>.sqlite3` where `<channel_id>` is the id you see in the URL bar when you are trying to do the content import.

I would be interested to look at this channel database file from the source machine or one of the importing machines, if you are able to upload it, just so I can see how the database image is malformed.

For the quick fix, deleting this file from the source and importing machines and redownloading it to the source machine should clear it up.

You can manually redownload the database file from `https://studio.learningequality.org/content/databases/<channel_id>.sqlite3` to replace it in the folder on the source machine.

**Comment by lsolesen** [comment]
One of the problem machines:

- [840681ae618f4ef381e8cbd04b92a5c2.zip](https://github.com/learningequality/kolibri/files/11466310/840681ae618f4ef381e8cbd04b92a5c2.zip)

From the source machine:

- [840681ae618f4ef381e8cbd04b92a5c2.zip](https://github.com/learningequality/kolibri/files/11466316/840681ae618f4ef381e8cbd04b92a5c2.zip)

There is one machine which has been synced with the source machine that still works correctly. So it only happened in two of the three machines. On the machine that works there is no -annotated.squlite3 and -upgrade-sqlite3 like on the two machines that stopped working correctly.

**Comment by lsolesen** [comment]
I tried deleting the .sqlite3-files for the channel and redownloading the .sqlite3-file from studio. It seems that my system is up and running again. Thanks.

**Comment by rtibbles** [comment]
Thanks for the extra information! Seems like something odd is happening during the upgrade calculation flow that is causing this issue.
