### ISSUE TITLE
Missing file kolibri/VERSION

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#1077]
## Summary

I'm having these error logs when running  the command `pip install -e .` based in `master` and `develop` branches 

```
pip install -e .
Obtaining file:///Users/user/Downloads/kolibri-develop
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/user/Downloads/kolibri-develop/setup.py", line 16, in <module>
        import kolibri
      File "/Users/user/Downloads/kolibri-develop/kolibri/__init__.py", line 9, in <module>
        __version__ = str(get_version('kolibri', __file__))
      File "/Users/user/Downloads/kolibri-develop/kolibri/utils/version.py", line 143, in get_version
        derive_version_from_git_tag(calling_dir) or derive_version_from_version_file(package) or
      File "/Users/user/Downloads/kolibri-develop/kolibri/utils/version.py", line 96, in derive_version_from_version_file
        string = pkgutil.get_data(package, 'VERSION').decode('utf-8')
      File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/pkgutil.py", line 629, in get_data
        return loader.get_data(resource_name)
      File "<frozen importlib._bootstrap>", line 1623, in get_data
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/user/Downloads/kolibri-develop/kolibri/VERSION'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/user/Downloads/kolibri-develop/
```

**Comment by rtibbles** [comment]
At the moment if you are doing `pip install -e .` you need git installed on the machine. I believe @aronasorman wanted to implement a fallback to address this issue, but until then, git is required if it is not coming from a pip package.

**Comment by mrpau-richard** [comment]
Hi @rtibbles I'm still having this issue even if I already installed `git` on my machine.

**Comment by aronasorman** [comment]
@mrpau-richard run `make writeversion` first before doing a `pip install -e .`.

**Comment by mrpau-richard** [comment]
Thanks @aronasorman, closing this.
