### ISSUE TITLE
Logging in a newly created coach user returns a blank screen

### ISSUE THREAD

**Issue by akolson** [learningequality/kolibri#10811]
## Observed behavior

Creating a coach user and logging in using the created credentials returns a blank screen

https://github.com/learningequality/kolibri/assets/5203639/d7b82cea-8bc2-404a-a310-56855c5cb420

## Errors and logs

```
vue-router.esm.js:2316 Error: Missing required 'facilityId' argument
    at Store.setClassList (pluginModule.js:70:1)
    at Array.wrappedActionHandler (vuex.esm.js:851:1)
    at Store.dispatch (vuex.esm.js:516:1)
    at Store.boundDispatch [as dispatch] (vuex.esm.js:406:1)
    at Object.handler [as CoachClassListPage] (index.js:30:1)
    at Router._hook (router.js:22:1)
    at iterator (vue-router.esm.js:2362:1)
    at step (vue-router.esm.js:2087:1)
    at vue-router.esm.js:2088:1
    at vue-router.esm.js:2384:1
```

## Expected behavior

Coach user should not be returned with a blank screen on login

## User-facing consequences

A coach user is not able to use kolibri

## Steps to reproduce

1. Login into a full device as superuser/admin
2. Create a coach user
3. Logout of superuser/admin
4. Login with created coach user

## Context

`Kolibri 0.16.0a14.dev0+git.124.g726134e8 ` 
MacOs
Chrome Version 114.0.5735.90 (Official Build) (arm64)

**Comment by pcenov** [comment]
@thanksameeelian this is also valid for an 'admin' user.
