### ISSUE TITLE
Facing issue while working in local , giving error.

### ISSUE THREAD

**Issue by GarvitSinghal47** [learningequality/kolibri#11034]
I am not sure this the correct place to raise this issue or ask for help as i am not able to find any contact method .

but i want to just ask till now the local setup of the repo is working fine , but from two days it is giving errors while running , so i tried to make or re-run the whole project from start but it is giving same error each time.

so below are the logs of the error after running kolibri manage migrate command.

```
Installed 2 object(s) from 1 fixture(s)
Error: Traceback (most recent call last):
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: jobs.func

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/e/open-source/kolibri/kolibri/utils/cli.py", line 193, in invoke
    initialize(**get_initialize_params())
  File "/mnt/e/open-source/kolibri/kolibri/utils/main.py", line 300, in initialize
    update(version, kolibri.__version__)
  File "/mnt/e/open-source/kolibri/kolibri/utils/main.py", line 366, in update
    run_upgrades(old_version, new_version)
  File "/mnt/e/open-source/kolibri/kolibri/core/upgrade.py", line 156, in run_upgrades
    version_upgrade()
  File "/mnt/e/open-source/kolibri/kolibri/core/upgrade.py", line 51, in __call__
    return self.upgrade()
  File "/mnt/e/open-source/kolibri/kolibri/core/content/upgrade.py", line 344, in synchronize_content_requests_upgrade
    automatic_resource_import.enqueue_if_not()
  File "/mnt/e/open-source/kolibri/kolibri/core/tasks/registry.py", line 309, in enqueue_if_not
    return job_storage.enqueue_job_if_not_enqueued(
  File "/mnt/e/open-source/kolibri/kolibri/core/tasks/storage.py", line 200, in enqueue_job_if_not_enqueued
    queued_jobs = self.filter_jobs(func=job.func, queue=queue, state=State.QUEUED)
  File "/mnt/e/open-source/kolibri/kolibri/core/tasks/storage.py", line 308, in filter_jobs
    orm_jobs = conn.execute(q)
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/home/garvit/.pyenv/versions/3.9.9/envs/kolibri-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: jobs.func
[SQL: SELECT jobs.id, jobs.state, jobs.func, jobs.priority, jobs.queue, jobs.saved_job, jobs.time_created, jobs.time_updated, jobs.interval, jobs.retry_interval, jobs.repeat, jobs.scheduled_time
FROM jobs
WHERE jobs.queue = ? AND jobs.state = ? AND jobs.func = ?]
[parameters: ('content', 'QUEUED', 'kolibri.core.content.tasks.automatic_resource_import')]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

sorry for asking it here , can you also tell me what is the correct method of contacting to the org if a face any issue means any mailing list or slack channel , if the org has any can you provide my the link to it.

**Comment by MisRob** [comment]
Hi @GarvitSinghal47, can you find your `.kolibri` directory (by default it's located at `~/.kolibri`) and remove `job_storage.sqlite3` file?

> sorry for asking it here , can you also tell me what is the correct method of contacting to the org if a face any issue means any mailing list or slack channel , if the org has any can you provide my the link to it

No worries. We recommend using the Q&A category of [Kolibri GitHub Discussions](https://github.com/learningequality/kolibri/discussions/categories/q-a) for a number of reasons. It is linked in a few places, but we're finding that the link is often unnoticed and are planning some discoverability improvements in the near future. Thank you for your feedback.

I will leave this issue open until you confirm you can run the development server again.

**Comment by GarvitSinghal47** [comment]
@MisRob now it is working fine, thx for the help.
