### ISSUE TITLE
Concurrency issues with multiple imported learners on a learn-only device

### ISSUE THREAD

**Issue by bjester** [learningequality/kolibri#11166]
## Observed behavior

When a learn-only device (LOD aka SoUD) has multiple learners imported, such as is now possible through the setup wizard, there is a high likelihood of concurrency related issues, such as `Database is locked` from concurrent attempts to sync data for both learners. Sync-related concurrency issues could cause many issues and failures, on both the client and server side of the sync. Additionally, some of the sync hooks in Kolibri are not intended to be invoked with this sort of concurrency. Generally speaking, the syncing mechanism isn't intended nor well-tested for concurrent use in this way within Kolibri.

## Errors and logs

Likely from concurrency issues with hooks: https://github.com/learningequality/kolibri/issues/11154

and:
```
ERROR 2023-08-25 17:00:05,051 kolibri.core.auth.sync_event_hook_utils UserSyncStatusHook.pre_transfer hook failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/sync_event_hook_utils.py", line 92, in _pre_transfer_handler
    hook.pre_transfer(**kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/device/kolibri_plugin.py", line 21, in pre_transfer
    defaults={"queued": False, "sync_session": context.sync_session},
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 489, in update_or_create
    obj.save(using=self.db)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 905, in _save_table
    forced_update)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 955, in _do_update
    return filtered._update(values) > 0
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 667, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 1204, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: database is locked
```

## Expected behavior

We manage automated learner syncs for LODs at the device level, and queue syncs both on the server it intends to sync with but also queue them internally for all available non-LODs with which syncing is desired, to avoid concurrency issues and maintain one sync at a time.

## User-facing consequences

Confusion on sync status and persistent failures that may occur due to timing of syncs.

## Steps to reproduce

Observed in https://github.com/learningequality/kolibri/pull/11127#issuecomment-1693515985 (has demonstrated steps and insights)

## Context

Kolibri 0.16

**Comment by marcellamaki** [comment]
Resolved with https://github.com/learningequality/kolibri/pull/11390
