### ISSUE TITLE
Content metadata_cache can't be used with normal Django views

### ISSUE THREAD

**Issue by dbnicholson** [learningequality/kolibri#11362]
## Observed behavior

In kolibri-explore-plugin we had a regular `View` that was using the [`metadata_cache`](https://github.com/learningequality/kolibri/blob/00010153e3c3329acb3540166819a1c68816d203/kolibri/core/content/api.py#L98) decorator for caching. Prior to 0.16.0-beta6 this was working fine, but since afa58e8c62bbcd960e0071dc88d1a6540b0d7ad8 this causes an exception with a no `add_post_render_callback` attribute. Unlike [Django's middleware](https://github.com/django/django/blob/c669cf279ae7b3e02a61db4fb077030a4db80e4f/django/middleware/cache.py#L100), `metadata_cache` doesn't check if the response has a `render` callable before using `add_post_render_callback`.

## Errors and logs

```
ERROR 2023-10-05 15:37:28,758 django.request Internal Server Error: /en/explore/app/7.0.0rc5.dev0gbf339f0.d20230920/default/
Traceback (most recent call last):
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/dan/src/kolibri/kolibri/kolibri/core/auth/middleware.py", line 119, in wrapper_func
    return view(*args, **kwargs)
  File "/home/dan/src/kolibri/kolibri/venv/lib/python3.9/site-packages/django/views/decorators/http.py", line 99, in inner
    response = func(request, *args, **kwargs)
  File "/home/dan/src/kolibri/kolibri/kolibri/core/content/api.py", line 118, in wrapper_func
    response.add_post_render_callback(
AttributeError: 'HttpResponse' object has no attribute 'add_post_render_callback'
```

## Expected behavior

It's a bug on our end that we were using that decorator since it wasn't intended for regular views and the view it's applied to isn't even associated with the content lifetime. Really I think someone just wanted the long caching without knowing the proper way to do it. However, it would be nice if either:

* It just worked for regular views. I think all that would be needed is the check like Django does.
* It threw a nicer exception that says not to use it on regular views.

## User-facing consequences

kolibri-explore-plugin fails when trying to show a custom channell view.

## Steps to reproduce

I believe if you install the [Endless Key flatpak](https://flathub.org/apps/org.endlessos.Key) right now it will fall over since it has Kolibri 0.16.0-beta6 without a fixed kolibri-explore-plugin.

## Context

Kolibri 0.16.0-beta6
Linux/Endless OS
Chrome (and via Endless Key flatpak)

**Comment by rtibbles** [comment]
I did wonder what that line was for! Happy to have that condition added in the decorator.
