### ISSUE TITLE
Android LODs - The syncing is still stopping for no obvious reason

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#11556]
## Observed behavior

A similar behavior was previously reported in https://github.com/learningequality/kolibri/issues/11524 - after setting up a LOD on an Android device the syncing is working correctly for some time and then it completely stops regardless of how many times I restart the server and the app on the device. 

## Expected behavior

Fully functioning sync with an Android LOD.

## Steps to reproduce the issue
1.  Install the [latest Beta 9 build asset](https://github.com/learningequality/kolibri/releases/tag/v0.16.0-beta9).
2. Setup a server and an Android LOD device connected to the server.
3. Start assigning lessons/quizzes to the LOD and observe the sync status.

## Logs

https://drive.google.com/drive/folders/1PQqlZZjZNR5RXUd7oW4L0UUaYsfYhVO8

## Usage Details
Windows 10, Ubuntu 22  - Chrome, Samsung phones running on Android 13 and Android 8

**Comment by pcenov** [comment]
@radinamatic

**Comment by pcenov** [comment]
@rtibbles I've followed all possible steps suggested at dontkillmyapp for my Samsung devices and the behavior is still the same.
Still after some additional investigation on my side with the official Beta 9 build on both my Android 7.1.1 and Android 8 devices the syncing happens only initially when the resources are being auto-downloaded to the devices for the first time and then never resumes. Probably an important note is that for both these devices when setting them up as a LOD in the setup wizard I always have to manually add the URL of the server (and this was working fine in the Beta 8 build).
The other Android 13 device syncs correctly for some time and then stops syncing. I have specifically excluded the app from being  restricted in terms of battery usage or being put to sleep. Yesterday I had this tested with Android 14 emulator and it also stopped syncing at some point.
In general regardless of the device limitations my expectation would be for the syncing to resume once I have manually restarted the app.

Here are the logs: https://drive.google.com/drive/folders/1PYE7oVPS2WKV-4Nju-jh7nxiltAsPFCC

**Comment by radinamatic** [comment]
My findings from the past few days of testing beta 9 are practically the same as those by @pcenov: with up to 4 LoDs connected to the server, syncing eventually stops for all of them. For some immediately after the initial user and the assignments import (so none of the learner progress manages to sync back to server), and for others the sync manages to display some learner progress in Class home, but inevitably fails after at most an hour or two. No amount of app restart, LoD reboot, server restarts and VM reboots ever manages to reestablish the syncing. 

Just to be sure, after trying and failing to maintain the sync on [Windows 10 VM](https://drive.google.com/drive/folders/1jXHg1lF1gpjD-fDT3JMp8hgdVkGzDVnv?usp=sharing), I repeated the tests on the [Windows 11 VM](https://drive.google.com/drive/folders/1IW18Fpp78sRI5Io48CKcm_Hy8lMO_bg1?usp=sharing) too, with the same results. I used 4 different Android devices: Redmi 10C (Android 13) , Moto g51 (Android 12) and Moto g6 (Android 9) phones and a tablet with Android 11, and made sure to deactivate any setting related to adaptive battery, power save and/or background processes (not all device have them and available UI options differ considerably) on all the devices prior to importing the user and trying to sync. 

I also went along and installed Android Studio since sometimes I would get smaller output of the `adb logcat` command, and when I finally figured out how to increase the buffer size for logcat, it produced a decent amount of logs (for tests on Windows 11 VM) that I hope will be helpful to do a better diagnostic. I used only `learningequality` as a filter, and it would be good to think if other or additional filters could serve us better for this operation.

**Comment by bjester** [comment]
Alright, the issue starts around here:
```
INFO 2023-11-24 14:06:41,500 android_app_plugin.kolibri_plugin Scheduling task kolibri.core.auth.tasks.soud_sync_processing for job 50 with delay 29.954143 and high priority True
INFO 2023-11-24 14:06:41,513 __main__ Ending Kolibri task worker, for job 50
INFO 2023-11-24 14:06:41,519 kolibri.core.discovery.utils.network.client Attempting connections to variations of the URL: http://192.168.100.2:8080/
INFO 2023-11-24 14:06:41,573 __main__ Starting Kolibri task worker, for job b873abc2fa334d68beb9099ed25abdce
INFO 2023-11-24 14:06:41,583 kolibri.core.discovery.utils.network.client Attempting connection to: http://192.168.100.2:8080/
INFO 2023-11-24 14:06:41,617 kolibri.core.discovery.utils.network.client Success! We connected to: http://192.168.100.2:8080/api/public/info/?v=3
INFO 2023-11-24 14:06:41,676 morango.management.commands.cleanupsyncs Closing SyncSession 1 of 1
INFO 2023-11-24 14:06:41,711 kolibri.core.device.soud [user=f942aae23c6f4abd28c5bfec1614c7c2] [server=b759f7d475b26397356134d8db5cd034] Checking SoUD sync
INFO 2023-11-24 14:06:41,721 __main__ Ending Kolibri task worker, for job b873abc2fa334d68beb9099ed25abdce
INFO 2023-11-24 14:06:41,788 kolibri.core.device.soud [user=f942aae23c6f4abd28c5bfec1614c7c2] [server=b759f7d475b26397356134d8db5cd034] SoUD sync ready
INFO 2023-11-24 14:06:41,827 kolibri.core.auth.tasks Enqueuing SoUD sync processing in 0:00:00
INFO 2023-11-24 14:06:41,842 android_app_plugin.kolibri_plugin Scheduling task kolibri.core.auth.tasks.soud_sync_processing for job 50 with delay 0 and high priority True
INFO 2023-11-24 14:06:41,866 __main__ Ending Kolibri task worker, for job d75331c07bab4e2622f1b7f02809b7de
INFO 2023-11-24 14:06:42,284 __main__ Ending Kolibri task worker, for job 4803986a448f805d537e5c68573b76d1
INFO 2023-11-24 14:06:42,456 kolibri.core.auth.tasks Skipping enqueue of SoUD sync processing: scheduled sooner
INFO 2023-11-24 14:06:42,498 __main__ Ending Kolibri task worker, for job d76c066ffb2b3a2f7bed75b2e32fdd12
```
Summarizing the above, the sync job ran, then was rescheduled to run in 29 seconds, then requeued to run immediately after a network discovery event. Around that time, 6m42s after the hour, the device goes briefly into a suspended state:
```
11-24 16:06:42.523   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: mSuspendCounter-
11-24 16:06:42.523   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: write mem+
11-24 16:06:50.854   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: write mem-
11-24 16:06:50.860   611  4287 E android.system.suspend@1.0-service: failed to read wakeup reasons: Invalid argument
11-24 16:06:50.860   611  4287 I android.system.suspend@1.0-service: Unknown/empty wakeup reason. Re-opening wakeup_reason file.
```
After that suspended state, the device has some logs about cellular connectivity, but nothing in regards to Kolibri. It seems that the cellular connectivity may have brought it back from the suspended state briefly before going back:
```
11-24 16:06:53.520   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: wakeup_count-
11-24 16:06:53.520   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: mSuspendCounter+
11-24 16:06:53.520   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: mSuspendCounter-
11-24 16:06:53.521   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: write mem+
11-24 16:07:49.080   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: write mem-
11-24 16:07:49.181   611  4287 I android.system.suspend@1.0-service: !@SystemSuspend: wakeup_count+
```
So then 1m7s after Kolibri scheduled the sync job to run immediately, things come back:
```
11-24 16:07:49.611 19976 20188 I python  : WARNING  2023-11-24 14:07:49,608 Zeroconf network service information could not be retrieved within 10.0 seconds
```
Then there's an Android-side crash:
```
11-24 16:07:50.865 21324 27783 I python  : /data/user/0/org.learningequality.Kolibri/files/app
11-24 16:07:50.865 21324 27783 I python  : /data/user/0/org.learningequality.Kolibri/files/app/_python_bundle/stdlib.zip:/data/user/0/org.learningequality.Kolibri/files/app/_python_bundle/modules
11-24 16:07:51.119 27778 27778 F DEBUG   : Build fingerprint: 'samsung/r7naeea/r7:13/TP1A.220624.014/N770FXXS9HWJ1:user/release-keys'
11-24 16:07:51.119 27778 27778 F DEBUG   : Revision: '5'
11-24 16:07:51.119 27778 27778 F DEBUG   : ABI: 'arm64'
11-24 16:07:51.119 27778 27778 F DEBUG   : Processor: '4'
11-24 16:07:51.119 27778 27778 F DEBUG   : Cmdline: org.learningequality.Kolibri:worker_TaskWorker
11-24 16:07:51.119 27778 27778 F DEBUG   : pid: 21324, tid: 27772, name: python_worker_t  >>> org.learningequality.Kolibri:worker_TaskWorker <<<
11-24 16:07:51.119 27778 27778 F DEBUG   :     lr  00000079e2d8b8d4  sp  0000007a4bee2610  pc  00000079e2e99fa0  pst 0000000020000000
11-24 16:07:51.119 27778 27778 F DEBUG   : backtrace:
11-24 16:07:51.119 27778 27778 F DEBUG   :       #00 pc 0000000000286fa0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #01 pc 00000000001788d0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #02 pc 0000000000284afc  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #03 pc 00000000002871c0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #04 pc 0000000000285c30  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyObject_GC_New+136)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #05 pc 000000000017eb84  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #06 pc 000000000014726c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (PyObject_GetIter+24)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #07 pc 00000000002273d8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+2760)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #08 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #09 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #10 pc 000000000015fe5c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #11 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #12 pc 0000000000228b54  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8772)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #13 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #14 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #15 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #16 pc 0000000000228f38  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+9768)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #17 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #18 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #19 pc 000000000015fe5c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #20 pc 000000000015d6c8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (PyVectorcall_Call+144)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #21 pc 0000000000229848  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+12088)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #22 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #23 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #24 pc 000000000015fe5c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #25 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #26 pc 0000000000228b54  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8772)
11-24 16:07:51.120 27778 27778 F DEBUG   :       #27 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.120 27778 27778 F DEBUG   :       #28 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #29 pc 000000000015fe5c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #30 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #31 pc 00000000002294f8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+11240)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #32 pc 000000000015dab8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #33 pc 000000000015fe5c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #34 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #35 pc 00000000002294f8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+11240)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #36 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #37 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #38 pc 000000000015fe5c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #39 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #40 pc 00000000002294f8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+11240)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #41 pc 000000000015dab8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #42 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #43 pc 0000000000229f0c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+13820)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #44 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #45 pc 000000000015da00  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyFunction_Vectorcall+232)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #46 pc 000000000022bf14  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #47 pc 0000000000228b54  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (_PyEval_EvalFrameDefault+8772)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #48 pc 000000000022cef0  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so
11-24 16:07:51.121 27778 27778 F DEBUG   :       #49 pc 000000000022683c  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (PyEval_EvalCode+76)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #50 pc 00000000002671cc  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libpython3.9.so (PyRun_SimpleFileExFlags+1116)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #51 pc 0000000000003ce8  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libmain.so (BuildId: 3bff6c1090a026f086eb9f2bd6ceb296dde9294c)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #52 pc 0000000000003450  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libmain.so (BuildId: 3bff6c1090a026f086eb9f2bd6ceb296dde9294c)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #53 pc 0000000000003540  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/lib/arm64/libmain.so (Java_org_kivy_android_PythonWorker_nativeStart+184) (BuildId: 3bff6c1090a026f086eb9f2bd6ceb296dde9294c)
11-24 16:07:51.121 27778 27778 F DEBUG   :       #54 pc 00000000000154bc  /data/app/~~J0jD3s71hNTU30EzoESY7g==/org.learningequality.Kolibri-jI1gXo37-gSr9tuIidkefw==/oat/arm64/base.odex (art_jni_trampoline+220)
```
but things are restarted, although eventually fail to run the sync job as well as other jobs with the same error:
```
11-24 16:07:51.269  1435  5625 W ActivityManager: Scheduling restart of crashed service org.learningequality.Kolibri/.TaskworkerWorkerService in 1000ms for connection
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper: Work [ id=1032c3f4-c0d3-47ac-8e12-7243112e77eb, tags={ kolibri_job_type:kolibri.core.auth.tasks.soud_sync_processing, kolibri_task_id:50, org.learningequality.Kolibri.TaskworkerWorker } ] failed because it threw an exception/error
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Binder died
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper:      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper:      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper:      at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
11-24 16:07:51.271 19976 20022 E WM-WorkerWrapper:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
11-24 16:07:51.273 19976 20022 I WM-WorkerWrapper: Worker result FAILURE for Work [ id=1032c3f4-c0d3-47ac-8e12-7243112e77eb, tags={ kolibri_job_type:kolibri.core.auth.tasks.soud_sync_processing, kolibri_task_id:50, org.learningequality.Kolibri.TaskworkerWorker } ]
```

**Comment by bjester** [comment]
Another error seen in at least 2 device logs, shown below, makes me feel fairly certain that reverting the most recent notification changes may return some reliability to syncing. Seems the notification change didn't fully resolve its issue anyway
```
11-23 19:59:59.520 13177 13203 E WM-WorkerWrapper: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
11-23 19:59:59.520 13177 13203 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:516)
11-23 19:59:59.520 13177 13203 E WM-WorkerWrapper: 	at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:475)
11-23 19:59:59.520 13177 13203 E WM-WorkerWrapper: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
11-23 19:59:59.520 13177 13203 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-23 19:59:59.520 13177 13203 E WM-WorkerWrapper: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
```
