### ISSUE TITLE
VF Installer not working on Mac OSX.11.2 for some users

### ISSUE THREAD

**Issue by carinediaz** [learningequality/kolibri#1166]
## Summary

Trying to install the pex file using https://docs.google.com/document/d/1frJ37D5S3uZkK2DIge3bzKyw4p5DLDDfi81OifGLVT8/edit#

Permission denied on `kolibri start`

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: vf-v0.3.0.pex
 - Operating system: OSX11.2 
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
Carines-MacBook-Pro:downloads carinediaz$ chmod +x kolibri-vf-v0.3.1-beta1.pex 
Carines-MacBook-Pro:downloads carinediaz$ 
Carines-MacBook-Pro:downloads carinediaz$ 
Carines-MacBook-Pro:downloads carinediaz$ 
Carines-MacBook-Pro:downloads carinediaz$ ./kolibri-vf-v0.3.1-beta1.pex start
Traceback (most recent call last):
  File ".bootstrap/_pex/pex.py", line 354, in execute
  File ".bootstrap/_pex/pex.py", line 82, in _activate
  File ".bootstrap/_pex/environment.py", line 135, in activate
  File ".bootstrap/_pex/environment.py", line 179, in _activate
  File ".bootstrap/_pex/environment.py", line 124, in update_candidate_distributions
  File ".bootstrap/_pex/environment.py", line 110, in load_internal_cache
  File ".bootstrap/_pex/environment.py", line 97, in write_zipped_internal_cache
  File ".bootstrap/_pex/util.py", line 178, in cache_distribution
  File ".bootstrap/_pex/common.py", line 124, in safe_open
  File ".bootstrap/_pex/common.py", line 112, in safe_mkdir
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/carinediaz/.pex/install/kolibri-0.3.1b1-py2.py3-none-any.whl.061599aaf7fff17b4c9c3fd6160807e9c24b319d.86535fee766a41b284b32f5c0388edfc'

```

## How to reproduce 
Followed directions on https://docs.google.com/document/d/1frJ37D5S3uZkK2DIge3bzKyw4p5DLDDfi81OifGLVT8/edit#

**Comment by DXCanas** [comment]
@indirectlylit, @carinediaz mentioned you helped her out with. Might be helpful to get some more specific reproduction steps

**Comment by indirectlylit** [comment]
the commands she pasted above were literally all I did:

* download the pex (tried both versions)
* `chmod +x kolibri-vf-v0.3.1-beta1.pex`
* `./kolibri-vf-v0.3.1-beta1.pex start`

Of course, that doesn't help us reproduce locally but there wasn't anything else to it on her machine.

**Comment by jeepurs** [comment]
Together, we just tried to change permissions on the Mac using
'''
chmod 777 kolibri-vf-v0.3.1-beta1.pex
./kolibri-vf-v0.3.1-beta1.pex start
''' 
Which didn't work either

**Comment by DXCanas** [comment]
Hey everyone,
Looked into the issue on @carinediaz's machine. For whatever reason, the temporary folder created by the pex file (`$HOME/.pex`) was owned by root. I `chown`ed it user her user account and was able to run the pex without issue
