### ISSUE TITLE
Using redis configuration breaks content navigation

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#11848]
## Overview

When redis is set to cache resources in kolibri 0.16 beta, navigation gets messy: every time a resource is feched it produces a server error.

#### Description and outcomes

This is the kind of error that is seen when a resource is accesed for the very first time. After refreshing the page the endpoint response is correct.

```
ERROR    2024-02-08 18:42:01,269 Internal Server Error: /api/content/contentnode/8036442b7dde5b34b88c0e52b385c1bf/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/middleware/security.py", line 40, in process_response
    if self.content_type_nosniff and 'x-content-type-options' not in response:
TypeError: argument of type 'bool' is not iterable
ERROR    2024-02-08 18:42:01,257 Internal Server Error: /api/content/contentnode/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/deprecation.py", line 142, in __call__
    response = self.process_response(request, response)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/middleware/security.py", line 40, in process_response
    if self.content_type_nosniff and 'x-content-type-options' not in response:
TypeError: argument of type 'bool' is not iterable

```

To reproduce it:
edit `options.ini` file in kolibri and add these lines (supossing a redis server is running):
```
[Cache]
CACHE_BACKEND = redis
CACHE_REDIS_MAXMEMORY_POLICY = allkeys-lru
CACHE_REDIS_MAXMEMORY = 1660575744
```

The browsing the library of installed channels or planning a lesson will produce the above errors

Related: This issue is the cause of this report https://github.com/learningequality/pi-gen/issues/16

**Comment by rtibbles** [comment]
Fixed in #11849
