### ISSUE TITLE
Unable to Close Panel After Adding Question with Empty Content in Channel

### ISSUE THREAD

**Issue by GarvitSinghal47** [learningequality/kolibri#11901]
## Issue Description
When attempting to add a question with empty content (no question inside the ID) in the "New Quiz" section under Coach > Class > Plan > Quizzes, while signed in as an admin or coach on the develop branch, the expected behavior is for the panel to close upon clicking the cross. However, the panel does not close as expected, and the screen gets stuck on that frame. Subsequently, users have to resort to using the back button to navigate out of this state.

## Observed Behavior
The panel does not close upon clicking the cross icon when attempting to add a question with empty content, resulting in the screen getting stuck on that frame.

## Errors and Logs
Upon encountering this issue, the following error is logged in the console:
index.vue:241 TypeError: Cannot read properties of undefined (reading 'length')
    at VueComponent.handleClosePanel (SectionSidePanel.vue:108:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at VueComponent.invoker (vue.runtime.esm.js:2188:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at Vue.$emit (vue.runtime.esm.js:3903:1)
    at VueComponent.closePanel (index.vue:241:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at VueComponent.invoker (vue.runtime.esm.js:2188:1)
    at invokeWithErrorHandling (vue.runtime.esm.js:1863:1)
    at Vue.$emit (vue.runtime.esm.js:3903:1)
    
## Expected Behavior
The panel should close upon clicking the cross icon, regardless of the content of the question being added, ensuring smooth navigation within the application.

## User-facing Consequences
This issue disrupts the user experience, particularly for admins and coaches trying to manage quizzes. It can lead to frustration and confusion, as users may not understand why the panel is not closing as expected.

## Steps to Reproduce
1. Sign in as an admin or coach.
2. Navigate to Coach > Class > Plan > Quizzes.
3. Enter the "New Quiz" section.
3. Attempt to add a question with empty content (no question inside the ID).
4. Try to close the panel using the cross icon.

https://github.com/learningequality/kolibri/assets/82756460/36a9bd4f-9a34-4141-8e22-4490de710378

**Comment by rtibbles** [comment]
I think this issue should be solved by this PR: https://github.com/learningequality/kolibri/pull/11862, once that's merged would be great if you could confirm @GarvitSinghal47!

**Comment by GarvitSinghal47** [comment]
@rtibbles Most likely, this issue will be resolved with the merging of PR #11862. I will confirm and inform you once the PR has been successfully merged.
