### ISSUE TITLE
User is not able to select whether to allow using mobile data in Mac app

### ISSUE THREAD

**Issue by poju3185** [learningequality/kolibri#11985]
## Observed behavior
When running mac app for the first time. A window asking whether to allow using mobile data pops up. However, user is not able to select either of them. Please refer to the video below.

https://github.com/learningequality/kolibri/assets/81625625/fbf491db-e1e3-4e0c-85d8-b6414deb3f35

 After some digging, I found the root of this issue is the frontend didn't correctly fetch devicesettings data.
```js
          client({ method: 'GET', url: this.settingsUrl })
            .then(({ data }) => {
              logging.log('mounted', isMetered);  // 'logging.log' doesn't exist, should be 'logging.info'
              logging.log(data); // Same as above
              this.extra_settings = data.extra_settings;
              this.selected = this.extra_settings.allow_download_on_metered_connection
                ? Options.USE_METERED
                : Options.DO_NOT_USE_METERED;
            })
            .catch(e => {
              logging.error(e);
            })
            .finally(() => (this.loading = false));
```
## Errors and logs
```console
MeteredConnectionNotificationModal.vue:101 [ERROR: packages/kolibri-common/components/MeteredConnectionNotificationModal.vue?vue&type=script&lang=js] TypeError: logging.log is not a function
    at MeteredConnectionNotificationModal.vue:93:1
```

```
[app-python-devserver] ERROR    2024-03-13 11:07:34,493 Internal Server Error: /api/device/devicesettings/
[app-python-devserver] Traceback (most recent call last):
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/django/core/handlers/exception.py", line 41, in inner
[app-python-devserver]     response = get_response(request)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 187, in _get_response
[app-python-devserver]     response = self.process_exception_by_middleware(e, request)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/django/core/handlers/base.py", line 185, in _get_response
[app-python-devserver]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[app-python-devserver]     return view_func(*args, **kwargs)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/django/views/generic/base.py", line 68, in view
[app-python-devserver]     return self.dispatch(request, *args, **kwargs)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 495, in dispatch
[app-python-devserver]     response = self.handle_exception(exc)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 455, in handle_exception
[app-python-devserver]     self.raise_uncaught_exception(exc)
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/rest_framework/views.py", line 492, in dispatch
[app-python-devserver]     response = handler(request, *args, **kwargs)
[app-python-devserver]   File "/Users/poju/Documents/gsoc/kolibri/kolibri/core/device/api.py", line 228, in patch
[app-python-devserver]     serializer.save()
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/rest_framework/serializers.py", line 209, in save
[app-python-devserver]     self.instance = self.update(self.instance, validated_data)
[app-python-devserver]   File "/Users/poju/Documents/gsoc/kolibri/kolibri/core/device/serializers.py", line 308, in update
[app-python-devserver]     instance = super(DeviceSettingsSerializer, self).update(
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/rest_framework/serializers.py", line 986, in update
[app-python-devserver]     instance.save()
[app-python-devserver]   File "/Users/poju/Documents/gsoc/kolibri/kolibri/core/device/models.py", line 164, in save
[app-python-devserver]     self.full_clean()
[app-python-devserver]   File "/Users/poju/.pyenv/versions/kolibri-py3.9/lib/python3.9/site-packages/django/db/models/base.py", line 1250, in full_clean
[app-python-devserver]     raise ValidationError(errors)
[app-python-devserver] django.core.exceptions.ValidationError: {'extra_settings': ["{'allow_download_on_metered_connection': True} does not have property 'enable_automatic_download'"]}
```

## Expected behavior

User should be able to select one of the options and proceed.

## User-facing consequences

User can't select either of the options. Causing the app unusable.

## Steps to reproduce

1. Clone the repo.
2. Follow the guide to build the project.
3. Run `yarn run app-devserver`
4. Fill out account info.
5. A pop-up window shows up asking allow using mobile data. 
6. User can't select either of the options.

## Context

* kolibri version 0.16.0a0.dev0+git.740.g16b90022
* Operating system Mac OS
* Browser Google Chrome/Safari

**Comment by rtibbles** [comment]
This was fixed in the course of #11820
