### ISSUE TITLE
500 error when importing facility from different device 

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#12299]
## Observed behavior
For @AlexVelezLl (0.17.0-alpha0 bug bash) during the setup flow, importing from an existing device was not working as expected. 
![image](https://github.com/learningequality/kolibri/assets/17235236/6f2aa87a-6a8c-44e6-b095-a5a084e631ef)

## Errors and logs

```
ERROR 2024-06-17 10:15:25,356 django.request Internal Server Error: /api/discovery/networklocation_facilities/59ba08844e8484c01d12b5fb54fa4123/
Traceback (most recent call last):
  File "/home/alexvelezll/.pex/installed_wheels/a319987fd510881ad7ed07d04a07b218a83ba205d6621d21a727bbf3d414153d/kolibri-0.17.0a0-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/alexvelezll/.pex/installed_wheels/a319987fd510881ad7ed07d04a07b218a83ba205d6621d21a727bbf3d414153d/kolibri-0.17.0a0-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alexvelezll/.pex/installed_wheels/a319987fd510881ad7ed07d04a07b218a83ba205d6621d21a727bbf3d414153d/kolibri-0.17.0a0-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/alexvelezll/.pex/installed_wheels/a319987fd510881ad7ed07d04a07b218a83ba205d6621d21a727bbf3d414153d/kolibri-0.17.0a0-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 104, in view
    self = cls(**initkwargs)
  File "/home/alexvelezll/.pex/installed_wheels/a319987fd510881ad7ed07d04a07b218a83ba205d6621d21a727bbf3d414153d/kolibri-0.17.0a0-py2.py3-none-any.whl/kolibri/core/api.py", line 149, in __init__
    raise TypeError("values must be defined as a tuple")
TypeError: values must be defined as a tuple
```

## Expected behavior
User should be able to import from other devices on the network, or be notified properly that there are no devices available 

## Steps to reproduce/Context
Clean setup on Kolibri
- Ubuntu 22.04.4 LTS | Chrome 125.0.6422.141

**Comment by marcellamaki** [comment]
@radinamatic @pcenov - can you try to reproduce this across a few other OSes/installers and see if there is any additional details we can add into the issue?

**Comment by pcenov** [comment]
Hi @marcellamaki here is a video of what I am observing:

https://github.com/learningequality/kolibri/assets/79847249/6ea19e99-33ae-4aa1-a3c7-ceaea52894b7

Logs:
[Ubuntu2ndDevice.zip](https://github.com/user-attachments/files/15886272/Ubuntu2ndDevice.zip)
[UbuntuServer.zip](https://github.com/user-attachments/files/15886273/UbuntuServer.zip)

The import is also not working at Device > Facilities.

A note that I reported this issue while testing the following PR: https://github.com/learningequality/kolibri/pull/12165 but I thought that it was caused by the Python changes made there.

Also I am able to replicate the issue on 2 Windows devices as well so it's not OS specific.
