### ISSUE TITLE
Impossible to download kolibri logs

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#12383]
## Observed behavior
Trying to generate logs in the facility -> data section of kolibri does not work.
Clicking on the buttons raises an error that can be seen in the browser console, but no feedback is given to the user

## Errors and logs
In the browser console
```
Kolibri Modules: kolibri.plugins.facility.app registered
index.vue:284 Use `dd` instead of `DD` (in `DD/MM/YYYY`) for formatting days of the month to the input `Tue May 14 2024 17:31:35 GMT+0200 (hora de verano de Europa central)`; see: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md
(anonymous) @ protectedTokens.mjs:16
(anonymous) @ format.mjs:416
format @ format.mjs:405
errorMessages @ index.vue:284
Watcher.get @ vue.runtime.esm.js:4495
Watcher.evaluate @ vue.runtime.esm.js:4597
(anonymous) @ vue.runtime.esm.js:4851
DataPagevue_type_template_id_fb8d84e6_scoped_true_render @ index.vue:6
(anonymous) @ vue-composition-api.mjs:1940
activateCurrentInstance @ vue-composition-api.mjs:1894
$options.render @ vue-composition-api.mjs:1939
Vue._render @ vue.runtime.esm.js:3569
updateComponent @ vue.runtime.esm.js:4081
Watcher.get @ vue.runtime.esm.js:4495
Watcher.run @ vue.runtime.esm.js:4570
flushSchedulerQueue @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
flushCallbacks @ vue.runtime.esm.js:1915
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1942
nextTick @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Watcher.update @ vue.runtime.esm.js:4560
Dep.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
sharedPropertyDefinition.set @ vue.runtime.esm.js:4644
click @ index.vue:4
invokeWithErrorHandling @ vue.runtime.esm.js:1863
invoker @ vue.runtime.esm.js:2188
invokeWithErrorHandling @ vue.runtime.esm.js:1863
Vue.$emit @ vue.runtime.esm.js:3903
handleClick @ KButton.vue:165
invokeWithErrorHandling @ vue.runtime.esm.js:1863
invoker @ vue.runtime.esm.js:2188
original._wrapper @ vue.runtime.esm.js:6961
Show 31 more frames
Show less
index.vue:4 RangeError: Use `dd` instead of `DD` (in `DD/MM/YYYY`) for formatting days of the month to the input `Tue May 14 2024 17:31:35 GMT+0200 (hora de verano de Europa central)`; see: https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md
    at protectedTokens.mjs:17:42
    at format.mjs:416:9
    at Array.map (<anonymous>)
    at format (format.mjs:405:6)
    at Sub.errorMessages (index.vue:284:1)
    at Watcher.get (vue.runtime.esm.js:4495:25)
    at Watcher.evaluate (vue.runtime.esm.js:4597:21)
    at Sub.errorMessages (vue.runtime.esm.js:4851:17)
    at Sub.DataPagevue_type_template_id_fb8d84e6_scoped_true_render (index.vue:6:3315)
    at vue-composition-api.mjs:1940:35
```

## Expected behavior
I expect the logs reports to be generated when clicking on the "Generate logs" buttons

## Steps to reproduce
Go to the Facility -> Data section and click on any of the two "Generate logs" buttons

## Context
Kolibri 0.17.0a0.dev0+git.148.g12b1bd5f
Brave browser (with Spanish settings, changing kolibri language didn't solve the problem, it's probably due to the date format settings)

**Comment by marcellamaki** [comment]
I think this is a duplicate of #12350 that @nucleogenesis is working on. Or if not exactly the same, a similar cause with the date formatting

**Comment by jredrejo** [comment]
> I think this is a duplicate of #12350 that @nucleogenesis is working on. Or if not exactly the same, a similar cause with the date formatting

you're right @marcellamaki . It's the same issue. I hadn't found that one, sorry for the noise

**Comment by marcellamaki** [comment]
No problem. I would always rather have duplicate issues reported than things missed!!
