### ISSUE TITLE
0.18 - Home > Class - The assigned lessons and quizzes are not visible to the learner

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#12955]
## Observed behavior

Observed on latest `develop `- when I sing in as a Learner and I go to Home > Class > <class> then I don't see any of my assigned lessons and quizzes. I can see the following error in the console:

```
TypeError: Cannot read properties of undefined (reading '$router')
    at setup (ClassAssignmentsPage.vue:64:1)
    at Ke (vue.runtime.common.prod.js:11:19108)
    at vue.runtime.common.prod.js:11:37000
    at _o (vue.runtime.common.prod.js:11:36904)
    at e._init (vue.runtime.common.prod.js:11:41637)
    at new i (vue.runtime.common.prod.js:11:39089)
    at vue.runtime.common.prod.js:11:29493
    at init (vue.runtime.common.prod.js:11:29336)
    at n (vue.runtime.common.prod.js:11:33371)
    at vue.runtime.common.prod.js:11:62186
```

https://github.com/user-attachments/assets/9ed5ffac-0b33-44ac-b34a-828aa703896c

Logs: [logs.zip](https://github.com/user-attachments/files/18165279/logs.zip)

## Expected behavior

All assigned lessons and quizzes should be visible.

## Steps to reproduce the issue

1. Install the latest develop build
2. As a Coach assign lessons and quizzes to a learner
3. As a Learner sign in and attempt to see the assigned lessons and resources

## Usage Details
Windows 11, Ubuntu 22  - Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by Ammog-Warrier** [comment]
Hi, could I be assigned this issue if it's still open? I went through the code base and believe I have an idea about why it's not working.

**Comment by LianaHarris360** [comment]
Hi @Ammog-Warrier , thanks for your interest in helping with this! This issue is not open for contributors at this time, those issues are marked with a "help wanted" label. You can take a look at some of those issues [here](https://github.com/search?q=org%3Alearningequality+is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+no%3Aassignee&type=issues).

**Comment by Ammog-Warrier** [comment]
@LianaHarris360 Ok Thank You very much. If i may just suggest, I think based on the error displayed the issue is because of $router isn't directly accessible in setup() in Vue3.  Using a userouter() inside the setup() probably solves it. Thank You again
