### ISSUE TITLE
As learner not able to start the existing exams

### ISSUE THREAD

**Issue by yogeshmhaskule** [learningequality/kolibri#1301]
## Summary
Learner is not able to start/continue the existing exam
## System information
 - Version: kolibri 0.4.0alpha4
 - Operating system: ubuntu 14.04
 - Browser: chrome and firefox

## How to reproduce

1. Create new user as learner.
2. Add created user into existing class. Where exam is assigned to same class.
3. Login as learner.
4. Click on Exam tab. Then click on start or continue button.

## Screenshots
![exam_tab](https://cloud.githubusercontent.com/assets/7850420/25334275/a0889268-290b-11e7-9b98-53a93061cab6.png)
![could_not_start_exam](https://cloud.githubusercontent.com/assets/7850420/25334281/a49093ba-290b-11e7-8903-188852f8c5cb.png)

**Comment by indirectlylit** [comment]
new task for handling missing metadata: #1309

**Comment by swapnil106111** [comment]
@rtibbles  Retested with channel ID (78eed5c0b59b30c0a40c94c17c849af6) provided by you. Working fine.

**Comment by rtibbles** [comment]
Thanks for the update @swapnil106111 - hopefully the fixes in the next alpha should make this robust on the testing channel also while we track down why the exercises in question are missing necessary data.

**Comment by indirectlylit** [comment]
I'm still getting an error here:

```
Uncaught (in promise) TypeError: Cannot read property 'assessmentmetadata' of undefined
    at assessmentMetaDataState (eval at <anonymous> (http://localhost:3000/js-dist/default_frontend-0.4.0alpha4.dev32.js:1064:1), <anonymous>:10:32)
    at selectQuestionFromExercise (eval at <anonymous> (http://localhost:3000/js-dist/default_frontend-0.4.0alpha4.dev32.js:1776:1), <anonymous>:12:28)
    at eval (eval at <anonymous> (http://localhost:3000/js-dist/learn_module-0.4.0alpha4.dev32.js:187:1), <anonymous>:622:25)
    at Array.map (native)
    at eval (eval at <anonymous> (http://localhost:3000/js-dist/learn_module-0.4.0alpha4.dev32.js:187:1), <anonymous>:621:49)
    at eval (eval at <anonymous> (http://localhost:3000/js-dist/default_frontend-0.4.0alpha4.dev32.js:1046:1), <anonymous>:37:7)
```

**Comment by rtibbles** [comment]
On the testing channel here?

**Comment by indirectlylit** [comment]
No, just my local khan academy channel

**Comment by indirectlylit** [comment]
this should be fixed, as long as the exam is in the currently-selected channel. (see follow-up issue #1341)
