### ISSUE TITLE
cannot enable `learn` plugin

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#186]
Steps to repo:
- rename your kolibri settings file
  - (e.g. from `~/.kolibri/kolibri_settings.json` to  `~/.kolibri/kolibri_settings.json.backup`)
- run `kolibri plugin kolibri.plugins.learn enable`

I get 

``` bash
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/kolibri/bin/kolibri", line 9, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/utils/cli.py", line 268, in main
    plugin(plugin_name, **arguments)
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/utils/cli.py", line 204, in plugin
    plugin_module = importlib.import_module(plugin_name + ".kolibri_plugin")
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/learn/kolibri_plugin.py", line 8, in <module>
    from . import hooks, urls
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/learn/urls.py", line 3, in <module>
    from . import views
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/plugins/learn/views.py", line 4, in <module>
    from kolibri.content.api import get_top_level_topics
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/content/api.py", line 6, in <module>
    from kolibri.content import models as KolibriContent
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/content/models.py", line 13, in <module>
    from mptt.models import MPTTModel, TreeForeignKey
  File "/Users/d/PythonEnvs/kolibri/lib/python2.7/site-packages/mptt/models.py", line 379, in <module>
    class MPTTModel(six.with_metaclass(MPTTModelBase, models.Model)):
  File "/Users/d/PythonEnvs/kolibri/lib/python2.7/site-packages/django/utils/six.py", line 808, in __new__
    return meta(name, bases, d)
  File "/Users/d/PythonEnvs/kolibri/lib/python2.7/site-packages/mptt/models.py", line 262, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "/Users/d/PythonEnvs/kolibri/lib/python2.7/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/d/PythonEnvs/kolibri/lib/python2.7/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/d/PythonEnvs/kolibri/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

---

Workaround for new Kolibri check-outs:

manually set your settings file to:

```
{"FIRST_RUN": false, "AUTO_SEARCH_PLUGINS": ["some.plugin.module.path"], "INSTALLED_APPS": ["kolibri.plugins.management", "kolibri.plugins.learn", "kolibri.plugins.document_pdf_render", "kolibri.plugins.video_mp4_render", "kolibri.plugins.audio_mp3_render"]}
```

**Comment by jamalex** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/201/commits/3206d432d5f87b7258817b91c08a1b44510e4ba8

**Comment by benjaoming** [comment]
Two options:

1) Running `django.setup()` before enabling/disabling a plugin. That way, we just *know* that the django stack is reading when loading `kolibri_plugin` which requires less carefulness when writing plugins.

2) Moving the import of `urls` modules to `MyKolibriPlugin.url_module`. This way, we know that loading `kolibri_plugin` is less error prone because it doesn't depend on a functional django stack. So for instance if a plugin has broken something in the Django stack (for instance its views or models are invalid), we can still enable/disable the plugin.

**Comment by benjaoming** [comment]
I'm wondering if option 1 is too restrictive. That way, a plugin cannot access its own models when it's being enabled. On the other hand, things like migrations may not have been fired.

Can anybody advice on what plugins currently HAVE to be able to do when enabled? I can't see that any of the core plugins have custom `enable()` class methods anyways.

**Comment by benjaoming** [comment]
> I'm wondering if option 1 is too restrictive. That way, a plugin cannot access its own models when it's being enabled. On the other hand, things like migrations may not have been fired.

Following up on this: Since one may run `enable->disable->enable`, with each operation starting and exiting Kolibri, I believe that plugins should not make lots of assumptions about initial states while running `enable`. This is just a caution.

Anyways, because commands such as `collectstatic` and `migrate` have to be run, we also have to run `django.setup()` anyways.

Here's a rough vision of what enabling a plugin could look like:

``` 
$ kolibri plugin enable kolibri.plugins.learn

Enabling plugin: kolibri.plugins.learn

Verifying dependencies... OK!
Collecting static assets (JS/CSS/images)........ OK!
Running database migrations............ OK!

Plugin enabled. Please start/restart Kolibri.
```

**Comment by benjaoming** [comment]
Replacing this issue with  #2510
