### ISSUE TITLE
Error running 0.5.0 on Mac

### ISSUE THREAD

**Issue by lauradanforth** [learningequality/kolibri#2069]
## Summary

Receiving an error message when running 0.5.0 on Mac OSX 10.11.6

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: 0.5.0
 - Operating system: OSX 10.11.6
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

379 static files copied to '/Users/lauradanforth/.kolibri/static'.
Operations to perform:
  Apply all migrations: sessions, admin, kolibriauth, morango, auth, content, contenttypes, exams, logger
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
INFO     Running 'kolibri start' as daemon (system service)
INFO     Kolibri running on:

	http://192.168.88.88:8080/
	http://127.0.0.1:8080/

## Screenshots

![image](https://user-images.githubusercontent.com/22602993/29896117-996a6292-8d90-11e7-84a4-664f17b2be3a.png)

Failed to run on either IP address

**Comment by rtibbles** [comment]
Note that this is not an error - but the fact that it gave you an 'unclean shutdown' when you ran status is concerning.

Possible that the status command is not Mac compatible @benjaoming?

**Comment by rtibbles** [comment]
After some digging, it seems that it will still run with `--foreground` but that daemonization seems to fail due to an OperationalError in the DB.

```
Traceback (most recent call last):
  File "/Users/lauradanforth/Downloads/kolibri-v0.5.0.pex/.bootstrap/_pex/pex.py", line 317, in execute
  File "/Users/lauradanforth/Downloads/kolibri-v0.5.0.pex/.bootstrap/_pex/pex.py", line 250, in _wrap_coverage
  File "/Users/lauradanforth/Downloads/kolibri-v0.5.0.pex/.bootstrap/_pex/pex.py", line 282, in _wrap_profiling
  File "/Users/lauradanforth/Downloads/kolibri-v0.5.0.pex/.bootstrap/_pex/pex.py", line 360, in _execute
  File "/Users/lauradanforth/Downloads/kolibri-v0.5.0.pex/.bootstrap/_pex/pex.py", line 418, in execute_entry
  File "/Users/lauradanforth/Downloads/kolibri-v0.5.0.pex/.bootstrap/_pex/pex.py", line 423, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/utils/cli.py", line 582, in main
    start(port, daemon=not arguments['--foreground'])
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/utils/cli.py", line 284, in start
    server.start(port=port)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/utils/server.py", line 69, in start
    update_channel_metadata_cache()
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/content/utils/annotation.py", line 18, in update_channel_metadata_cache
    ChannelMetadataCache.objects.exclude(id__in=db_names).delete()
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 599, in delete
    collector.collect(del_query)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/deletion.py", line 199, in collect
    reverse_dependency=reverse_dependency)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/deletion.py", line 97, in add
    if not objs:
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 266, in __nonzero__
    return type(self).__bool__(self)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 262, in __bool__
    self._fetch_all()
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/lauradanforth/.pex/install/kolibri-0.5.0-py2.py3-none-any.whl.a26359d468a5bc640f9c4a5eba738d8c2cad946c/kolibri-0.5.0-py2.py3-none-any.whl/kolibri/dist/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: locking protocol
```

**Comment by indirectlylit** [comment]
addressed by https://github.com/learningequality/kolibri/pull/2335
