### ISSUE TITLE
deleting a channel is a long-running operation but doesn't provide user feedback

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2140]
* Deleted khan academy (en) channel, 72GB
* From a user's perspective, nothing happened
* Refreshed - still there
* Pressed 'delete' again.

python error:

```
ERROR:sqlalchemy.pool.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4672602112 and this is thread id 4681015296
ERROR:sqlalchemy.pool.NullPool:Exception closing connection <sqlite3.Connection object at 0x113b56ce0>
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 446, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4672602112 and this is thread id 4681015296
ERROR:sqlalchemy.pool.NullPool:Exception during reset or similar
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
    fairy._reset(pool)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 829, in _reset
    pool._dialect.do_rollback(self)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 440, in do_rollback
    dbapi_connection.rollback()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4672602112 and this is thread id 4681015296
ERROR:sqlalchemy.pool.NullPool:Exception closing connection <sqlite3.Connection object at 0x111cd65a0>
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/pool.py", line 300, in _close_connection
    self._dialect.do_close(connection)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 446, in do_close
    dbapi_connection.close()
ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4672602112 and this is thread id 468101529
```

* CPU was very high for a while
* refreshed again, channel is gone now

----

We should provide some user feedback while the operation is occurring and prevent it from being triggered a second time

**Comment by rtibbles** [comment]
We should turn deletion into a polled task like import.

**Comment by jonboiser** [comment]
#2153
