### ISSUE TITLE
error during deletion

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2141]
tried deleting a channel and got this error:

```
ERROR    Internal Server Error: /api/channel/913efe9f14c65cb1b23402f21f056e99/
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "kolibri/content/api.py", line 41, in destroy
    models.LocalFile.objects.delete_orphans()
  File "kolibri/content/models.py", line 207, in delete_orphans
    self.delete_orphan_files()
  File "kolibri/content/models.py", line 199, in delete_orphan_files
    os.remove(paths.get_content_storage_file_path(file.get_filename()))
OSError: [Errno 2] No such file or directory: '/Users/d/.kolibri/content/storage/c/3/c382239a6bf295ce30a98e844475f979.png'
[11/Sep/2017 15:03:28] "DELETE /api/channel/913efe9f14c65cb1b23402f21f056e99/ HTTP/1.1" 500 94744
```

![image](https://user-images.githubusercontent.com/2367265/30298996-848c08c8-9702-11e7-8ae1-397ff1111b7c.png)

**Comment by rtibbles** [comment]
I thought I had fixed this already...

**Comment by rtibbles** [comment]
Oh no, I was catching only `IOError`, need to catch `OSError` too.

**Comment by jonboiser** [comment]
I was having that problem working on the config stuff, so I added that to the catch in

https://github.com/learningequality/kolibri/commit/9081fe9b6c787b44243eec3888b72b19ed32fa1b

**Comment by rtibbles** [comment]
Fixed in https://github.com/learningequality/kolibri/commit/9081fe9b6c787b44243eec3888b72b19ed32fa1b
