### ISSUE TITLE
Trying to import a channel when Internet isn't connected fails with a 500

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2242]
## Summary

I believe we used to show a graceful error message (validation-style) when you tried to import content from the internet and you weren't connected. In the latest version, it fails rather ungracefully with a 500 (and no chance to retry).

## System information

 - Version: latest 0.6
 - Operating system: Ubuntu
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
ERROR 2017-09-21 14:33:02,344 base Internal Server Error: /api/tasks/startremoteimport/
Traceback (most recent call last):
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/tasks/api.py", line 102, in startremoteimport
    get_content_database_file_url(channel_id)).status_code
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/requests/api.py", line 97, in head
    return request('head', url, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl.25703e51e5e72ed9c2589c2d2478ae8b2725774e/kolibri-0.6.dev020170921163803_git-py2.py3-none-any.whl/kolibri/dist/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='contentworkshop.learningequality.org', port=443): Max retries exceeded with url: /content/databases/17d7606476bd52f4ac94bd76b6f3aa8c.sqlite3 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efdf40f9790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

## How to reproduce

1. Go to content import page
1. Disconnect from internet
1. Try to import channel from internet

## Screenshots

![image](https://user-images.githubusercontent.com/618416/30720123-107e842a-9edb-11e7-8e04-6a3935145d18.png)

**Comment by aronasorman** [comment]
The appropriate response, might be to check if the string `Temporary failure in name resolution` is present in the error message, then return with a known response code that the frontend can return.

**Comment by jonboiser** [comment]
@aronasorman Checking for a pattern in the error string seems a little hacky to me. Is it possible for the backend to catch this error and return a 503 if the service is not available?

Apparently, there is some upcoming functionality as well to inform the user when the browser has lost its connection. IDK if it covers this case though.

**Comment by indirectlylit** [comment]
> Apparently, there is some upcoming functionality as well to inform the user when the browser has lost its connection. IDK if it covers this case though.

nope, that's independent. (`browser :: kolibri` vs `kolibri :: studio`)

**Comment by benjaoming** [comment]
I just learned the hard way that having centralized download functionality (that extends into becoming a kind of download manager) was necessary in KA Lite. It has a `download_file` function which is now core of (hopefully) all client-side download tasks.

Being worried about this, I went straight to the Kolibri code to check out what was done here, and I found `kolibri.utils.transfer` and some really nice patterns in the `importcontent` management command. And there's nothing left to desire from KA Lite lessons -- so just wanted to say: Great work on designing this!!!

**Comment by jonboiser** [comment]
Not sure if the OP is relevant anymore with the new design.

It would make sense to perhaps disable the "remote import" workflow when the Kolibri Studio is offline. A simple implementation may be to, when loading the "import from where" modal, do a HEAD  request to /api/remotechannels. The server could return a 200 or 503 depending on the state of Kolibri Studio.

**Comment by indirectlylit** [comment]
confirmed - this works pretty well now whether the network goes down during or before a transfer is initiated
