### ISSUE TITLE
windows devserver: unhandled exception when assets are still building

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2244]
This is not a critical issue, but the behavior is different between Windows and Linux devservers.

* run `kolibri manage devserver --debug -- --webpack`
* try loading a page before assets have compiled

There's an exception in the course of handling the 'webpack still in progress' exception:

```
Traceback (most recent call last):
  File "c:\users\jordan\k\lib\site-packages\django\core\handlers\base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\users\jordan\k\lib\site-packages\django\core\handlers\base.py", line 172, in get_response
    response = response.render()
  File "c:\users\jordan\k\lib\site-packages\django\template\response.py", line 160, in render
    self.content = self.rendered_content
  File "c:\users\jordan\k\lib\site-packages\django\template\response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "c:\users\jordan\k\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\jordan\k\lib\site-packages\django\template\library.py", line 201, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\Jordan\kolibri\kolibri\core\webpack\templatetags\webpack_tags.py", line 40, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "C:\Users\Jordan\kolibri\kolibri\core\webpack\hooks.py", line 383, in render_to_page_load_sync_html
    tags += list(self.js_and_css_tags())
  File "C:\Users\Jordan\kolibri\kolibri\core\webpack\hooks.py", line 254, in js_and_css_tags
    for chunk in self.sorted_chunks():
  File "C:\Users\Jordan\kolibri\kolibri\core\webpack\hooks.py", line 248, in sorted_chunks
    return sorted(filter(partial(filter_by_bidi, bidi), self.bundle), key=lambda x: x['name'].split('.')[-1])
  File "C:\Users\Jordan\kolibri\kolibri\core\webpack\hooks.py", line 139, in bundle
    for f in self._stats_file_content["files"]:
  File "c:\users\jordan\k\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Jordan\kolibri\kolibri\plugins\hooks.py", line 201, in inner
    return func(instance, *args, **kwargs)
  File "C:\Users\Jordan\kolibri\kolibri\core\webpack\hooks.py", line 130, in _stats_file_content
    raise WebpackError('Webpack build file missing, front-end assets cannot be loaded')
kolibri.core.webpack.hooks.WebpackError: Webpack build file missing, front-end assets cannot be loaded
```

observed by @jayoshih

**Comment by rtibbles** [comment]
I am not seeing the exception in the process of handling the exception here. The last raised exception is the WebpackError.

**Comment by rtibbles** [comment]
Closing this, please reopen if it recurs, but not seeing the reported issue here.
