### ISSUE TITLE
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: content_contentnode.id

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2323]
After importing a bunch of other channels and then trying to run importchannel for KA (en), received the following error:

```
jamalex@ace:~/Downloads$ KOLIBRI_HOME=/media/jamalex/BAA6-3872/KOLIBRI_DATA ./kolibri.pex manage importchannel -- network 1ceff53605e55bef987d88e0908658c5
INFO     Version was 0.6.dev020171001154142-export, new version: 0.6.dev020171001154436-export
INFO     Running update routines for new version...

0 static files copied to '/media/jamalex/BAA6-3872/KOLIBRI_DATA/static', 405 unmodified.
Operations to perform:
  Apply all migrations: sessions, admin, kolibriauth, morango, auth, content, contenttypes, exams, device, logger
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
INFO     Downloading data for channel id 1ceff53605e55bef987d88e0908658c5
 99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 39845888/40292352 [00:06<00:00, 6758492.87it/s]INFO     Importing ContentTag data
INFO:kolibri.content.utils.channel_import:Importing ContentTag data
INFO     Importing ContentNode_has_prerequisite data
INFO:kolibri.content.utils.channel_import:Importing ContentNode_has_prerequisite data
INFO     Importing ContentNode_related data
INFO:kolibri.content.utils.channel_import:Importing ContentNode_related data
INFO     Importing ContentNode_tags data
INFO:kolibri.content.utils.channel_import:Importing ContentNode_tags data
INFO     Importing ContentNode data
INFO:kolibri.content.utils.channel_import:Importing ContentNode data
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40292352/40292352 [00:08<00:00, 4793065.30it/s]
Traceback (most recent call last):
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 317, in execute
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 250, in _wrap_coverage
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 282, in _wrap_profiling
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 360, in _execute
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 418, in execute_entry
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 423, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/utils/cli.py", line 580, in main
    manage(command, args=django_args)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/utils/cli.py", line 411, in manage
    execute_from_command_line(argv=argv)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/tasks/management/commands/base.py", line 99, in handle
    return self.handle_async(*args, **options)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/content/management/commands/importchannel.py", line 89, in handle_async
    self.download_channel(options["channel_id"])
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/content/management/commands/importchannel.py", line 42, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/content/management/commands/importchannel.py", line 79, in _transfer
    channel_import.import_channel_from_local_db(channel_id)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/content/utils/channel_import.py", line 305, in import_channel_from_local_db
    import_manager.import_channel_data()
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/content/utils/channel_import.py", line 196, in import_channel_data
    unflushed_rows = self.table_import(model, row_mapper, table_mapper, unflushed_rows)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/content/utils/channel_import.py", line 179, in table_import
    self.destination.session.bulk_insert_mappings(DestinationRecord, data_to_insert)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/orm/session.py", line 2463, in bulk_insert_mappings
    return_defaults, False, render_nulls)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/orm/session.py", line 2536, in _bulk_save_mappings
    transaction.rollback(_capture_exception=True)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/orm/session.py", line 2531, in _bulk_save_mappings
    isstates, return_defaults, render_nulls)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/orm/persistence.py", line 69, in _bulk_insert
    bookkeeping=return_defaults)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/orm/persistence.py", line 799, in _emit_insert_statements
    execute(statement, multiparams)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/base.py", line 1159, in _execute_context
    context)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/sqlalchemy/engine/default.py", line 467, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: content_contentnode.id [SQL: u'INSERT INTO content_contentnode (id, title, content_id, channel_id, description, sort_order, license_owner, author, kind, available, stemmed_metaphone, lft, rght, tree_id, level, parent_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ((u'c6edbc3129c55ba99125266c3effa234', u'Math', u'39776b92b5a7522c90edc020fa25d247', '1ceff53605e55bef987d88e0908658c5', u'', 1.0, u'', u'', u'topic', 0, u'M0 MT', 2, 39253, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'41ca303fe94a593486a04f956d4b53e4', u'Science', u'70204a9f7b6c55e09d03c935fa69f320', '1ceff53605e55bef987d88e0908658c5', u'', 2.0, u'', u'', u'topic', 0, u'SNK', 39254, 46341, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'077c2922cf335ede9076875c0fdb7f58', u'Economics and finance', u'99998f7adce45182bfcbb061d58fc1d4', '1ceff53605e55bef987d88e0908658c5', u'', 3.0, u'', u'', u'topic', 0, u'AKNM ANT FNNK', 46342, 47557, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'654edc3be0a65e98937ccf2c4ee8cab9', u'Arts and humanities', u'f0cd3273f67c582eb6da1df95a4c1a9c', '1ceff53605e55bef987d88e0908658c5', u'', 4.0, u'', u'', u'topic', 0, u'ARTS ANT HMN', 47558, 53029, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'b63838e906b25050800a7aaba2f1b4af', u'Computing', u'4846cc6f49285268a6323007044b81a0', '1ceff53605e55bef987d88e0908658c5', u'', 5.0, u'', u'', u'topic', 0, u'KMPT', 53030, 53333, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'09afa3e6243650b49ad48c6d05328e5a', u'Test prep', u'af42a6d0c25154dc9a76d882e8b2b089', '1ceff53605e55bef987d88e0908658c5', u'', 6.0, u'', u'', u'topic', 0, u'TST PRP', 53334, 59243, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'd1f2610831f85079b7593141445ec390', u'Partner content', u'c509d0456ca45fa3a3b7bf310c1c8565', '1ceff53605e55bef987d88e0908658c5', u'', 7.0, u'', u'', u'topic', 0, u'PRTNR KNTNT', 59244, 61631, 14, 1, u'1ceff53605e55bef987d88e0908658c5'), (u'de15749aa01c5329b1fb7017981a958f', u'College, careers, and more', u'5d7a06786364595d9c7bbcb3e8e6b9bd', '1ceff53605e55bef987d88e0908658c5', u'', 8.0, u'', u'', u'topic', 0, u'KLJJ KLKK KRRSS ANT MR', 61632, 62379, 14, 1, u'1ceff53605e55bef987d88e0908658c5')  ... displaying 10 of 4679 total bound parameter sets ...  (u'58bf214bb27c5bb1a0305b48247a9e39', u'HIV and AIDS', u'02737875172e5336a728b0b0d3c8e940', '1ceff53605e55bef987d88e0908658c5', u'', 6.0, u'', u'', u'topic', 0, u'HF ANT ATS', 44251, 44274, 14, 4, u'5fe362a8d1fe53fbb49bfa4d39b22a93'), (u'd9981bd1390853c7a1fa517563c1392d', u'Malaria', u'092ff3136f6d511883dc5c72e170f918', '1ceff53605e55bef987d88e0908658c5', u'', 7.0, u'', u'', u'topic', 0, u'MLR', 44275, 44284, 14, 4, u'5fe362a8d1fe53fbb49bfa4d39b22a93'))]

**Comment by jamalex** [comment]
Ah, hmm, it seems it happens everytime on running any management command now. Probably because the database file was never fully imported, so it tries to do it again. This prevents the server from starting, etc.

**Comment by jamalex** [comment]
In trying to create a minimal replicable data folder, I copied the DB and the content database folder over to another data folder and ran from there. Got this confusing traceback:

```
Traceback (most recent call last):
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 317, in execute
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 250, in _wrap_coverage
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 282, in _wrap_profiling
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 360, in _execute
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 418, in execute_entry
  File "/home/jamalex/Downloads/kolibri.pex/.bootstrap/_pex/pex.py", line 423, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 192, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/utils/cli.py", line 571, in main
    initialize(debug=debug)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/utils/cli.py", line 156, in initialize
    django.setup()
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/core/apps.py", line 15, in ready
    self.activate_pragmas_on_start()
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/core/apps.py", line 57, in activate_pragmas_on_start
    cursor.execute("PRAGMA journal_mode=WAL;")
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/home/jamalex/.pex/install/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl.713535143afcf43fcd35c68f78249c139ee63b26/kolibri-0.6.dev020170930001134_git-py2.py3-none-any.whl/kolibri/dist/django/db/backends/sqlite3/base.py", line 321, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.DatabaseError: malformed database schema (Science)
```

**Comment by jamalex** [comment]
The last one ("malformed...") may have been unrelated -- I cleared out the data folder and copied the DB over again, and didn't get that one, just the original error (yay!).

**Comment by jamalex** [comment]
It seems it can be replicated just from the source content databases; nothing funny about my db.sqlite3; full set of DBs to put in `.kolibri/content/databases` here:
https://drive.google.com/open?id=0B1eobeaicL7IbkJCWUdoTldOdTg

**Comment by jamalex** [comment]
(Guessing that Studio must have somehow accidentally set the `node_id` for two Contentnodes across two different channels to the same value)

**Comment by jamalex** [comment]
CC @jayoshih

**Comment by jayoshih** [comment]
@jamalex These channels look like ricecooker channels- it's most likely failing when source ids are the same among children

**Comment by indirectlylit** [comment]
where does the root problem lie, and how can we address it?

**Comment by benjaoming** [comment]
Currently, I'm getting an error like the above for every other test I run with `tox`.

```
INFO     Going to daemon mode, logging to kolibri/.tox/py3.5/tmp/.kolibri/server.log
py3.5 runtests: commands[4] | coverage run -p kolibri stop
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.test
py3.5 runtests: commands[5] | py.test kolibri/utils/tests/test_version.py
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.test
Traceback (most recent call last):
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kolibri/.tox/py3.5/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/_pytest/config.py", line 50, in main
    config = _prepareconfig(args, plugins)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/_pytest/config.py", line 160, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/callers.py", line 196, in _multicall
    gen.send(outcome)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/_pytest/helpconfig.py", line 68, in pytest_cmdline_parse
    config = outcome.get_result()
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/_pytest/config.py", line 943, in pytest_cmdline_parse
    self.parse(args)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/_pytest/config.py", line 1108, in parse
    self._preparse(args, addopts=addopts)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/_pytest/config.py", line 1079, in _preparse
    args=args, parser=self._parser)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pytest_django/plugin.py", line 246, in pytest_load_initial_conftests
    _setup_django()
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/pytest_django/plugin.py", line 149, in _setup_django
    django.setup()
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/morango/apps.py", line 27, in ready
    InstanceIDModel.get_or_create_current_instance()
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/morango/models.py", line 122, in get_or_create_current_instance
    InstanceIDModel.objects.filter(current=True).update(current=False)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/models/query.py", line 628, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1149, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "kolibri/.tox/py3.5/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: database disk image is malformed
```

If this error occurs again, please check your database integrity witht this command:

    PRAGMA integrity_check

Example:

```
$ du -sh .tox/py3.5/tmp/.kolibri/db.sqlite3
252K	.tox/py3.5/tmp/.kolibri/db.sqlite3

$ sqlite3 .tox/py3.5/tmp/.kolibri/db.sqlite3 
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> PRAGMA integrity_check;
Error: database disk image is malformed
```

**Comment by benjaoming** [comment]
Very interesting! After running tests locally with tox, my database is left broken. I'm not even running the full test set, just `test_version` as in the above example (`tox -e py3.5 kolibri/utils/tests/test_version.py`)

So this does not immediately seem to be a real-life problem, but we should really investigate why the tests are making the database malformed.

**Comment by indirectlylit** [comment]
should this issue be merged with #2328?
