### ISSUE TITLE
Unable to export channel to USB with 0.6

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2425]
## Summary

After importing a channel from Internet, I'm unable to export the channel to USB. It shows that `Transfer failed. Please try again.`

## System information

*Please specify the Kolibri version you were using and your operating system!*

 - Version: latest 0.6 pex
 - Operating system: Mac OS X (tried with Ubuntu too, got the same error)
 - Browser: Chrome

## Traceback or relevant snippet from server.log or browser console

```
exception
:
"an integer is required"
id
:
"3062685efd7e4f9687e423b971684fe0"
percentage
:
0
status
:
"FAILED"
traceback
:
"Traceback (most recent call last):
File "/Users/lingyiwang/.pex/install/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl.86266a0e66c4e531f409941726296b52225647a7/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl/kolibri/dist/iceqube/worker/backends/inmem.py", line 75, in handle_finished_future

result = future.result()↵  File "/Users/lingyiwang/.pex/install/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl.86266a0e66c4e531f409941726296b52225647a7/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl/kolibri/dist/concurrent/futures/_base.py", line 422, in result

return self.__get_result()↵  File "/Users/lingyiwang/.pex/install/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl.86266a0e66c4e531f409941726296b52225647a7/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl/kolibri/dist/concurrent/futures/thread.py", line 62, in run

result = self.fn(*self.args, **self.kwargs)

File "/Users/lingyiwang/.pex/install/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl.86266a0e66c4e531f409941726296b52225647a7/kolibri-0.6.dev020171012072435_git-py2.py3-none-any.whl/kolibri/dist/iceqube/worker/backends/inmem.py", line 149, in wrap

raise e

TypeError: an integer is required↵"

```

## How to reproduce

1. Import a channel from internet
2. Export this channel to USB
3. Inspect the page --> Network to see the error

## Screenshots
<img width="640" alt="screen shot 2017-10-12 at 1 09 33 am" src="https://user-images.githubusercontent.com/19424916/31485824-0de57858-aeea-11e7-864a-14db026876ee.png">

**Comment by lyw07** [comment]
Looks like this is caused by `block_size` getting changed from 2097152 to None in `kolibri/content/utils/transfer.py`. I tried with changing it back to 2097152 and resolved this issue. But is this set to None for iceqube? @aronasorman
