### ISSUE TITLE
Changing language settings on devserver results in UnicodeException

### ISSUE THREAD

**Issue by alanchenz** [learningequality/kolibri#2541]
### Observed behavior

When I try to change the language to Arabic, Hindi, or Portuguese (unicode languages), the app crashes and throws UnicodeDecodeError.

### Expected behavior

After changing language, app should still run with all text in the selected language.

### User-facing consequences

Users in areas that use such languages would not be able to use the app to their language preferences.

### Errors and logs

Relevant errors and tracebacks from:

* the command line
* `~/.kolibri/kolibri.log`
* the browser console

```
ERROR    Internal Server Error: /management/facility
Traceback (most recent call last):
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\core\handlers\base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\core\handlers\base.py", line 172, in get_response
    response = response.render()
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\response.py", line 160, in render
    self.content = self.rendered_content
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\library.py", line 201, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\templatetags\webpack_tags.py", line 40, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\hooks.py", line 379, in render_to_page_load_sync_html
    if self.frontend_messages():
  File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\hooks.py", line 243, in frontend_messages
    json.load(f), separators=(',', ':'))
  File "C:\Users\alanc\AppData\Local\Programs\Python\Python35\Lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "c:\users\alanc\kolibri\kolibri\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 66: character maps to <undefined>
[27/Oct/2017 13:19:12] "GET /management/facility HTTP/1.1" 500 177256
ERROR    Internal Server Error: /management/facility
Traceback (most recent call last):
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\core\handlers\base.py", line 174, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\core\handlers\base.py", line 172, in get_response
    response = response.render()
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\response.py", line 160, in render
    self.content = self.rendered_content
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\response.py", line 137, in rendered_content
    content = template.render(context, self._request)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\backends\django.py", line 95, in render
    return self.template.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 206, in render
    return self._render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\loader_tags.py", line 173, in render
    return compiled_parent._render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 197, in _render
    return self.nodelist.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\loader_tags.py", line 69, in render
    result = block.nodelist.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 992, in render
    bit = node.render_annotated(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py", line 959, in render_annotated
    return self.render(context)
  File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\library.py", line 201, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\templatetags\webpack_tags.py", line 40, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\hooks.py", line 379, in render_to_page_load_sync_html
    if self.frontend_messages():
  File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\hooks.py", line 243, in frontend_messages
    json.load(f), separators=(',', ':'))
  File "C:\Users\alanc\AppData\Local\Programs\Python\Python35\Lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "c:\users\alanc\kolibri\kolibri\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 66: character maps to <undefined>

```

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/user

Django Version: 1.9.7
Python Version: 3.5.4
Installed Applications:
['kolibri.core',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'kolibri.auth.apps.KolibriAuthConfig',
 'kolibri.content',
 'kolibri.logger',
 'kolibri.tasks.apps.KolibriTasksConfig',
 'kolibri.core.deviceadmin',
 'kolibri.core.webpack',
 'kolibri.core.exams',
 'kolibri.core.device',
 'kolibri.core.discovery',
 'rest_framework',
 'django_js_reverse',
 'jsonfield',
 'morango',
 'kolibri.plugins.management',
 'kolibri.plugins.learn',
 'kolibri.plugins.document_pdf_render',
 'kolibri.plugins.html5_app_renderer',
 'kolibri.plugins.media_player',
 'kolibri.plugins.setup_wizard',
 'kolibri.plugins.coach',
 'kolibri.plugins.user',
 'kolibri.plugins.style_guide',
 'kolibri_exercise_perseus_plugin']
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'kolibri.core.device.middleware.KolibriLocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'kolibri.plugins.setup_wizard.middleware.SetupWizardMiddleware',
 'kolibri.auth.middleware.CustomAuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Template error:
In template C:\Users\alanc\Kolibri\kolibri\kolibri\plugins\user\templates\user\user.html, error at line 0
   charmap   1 : {% extends "kolibri/base.html" %}
   2 : {% load user_tags %}
   3 : {% load kolibri_tags %}
   4 : {% block content %}
   5 :   {% kolibri_bootstrap_collection 'facilitydataset' 'FacilityDatasetResource' facility_id=currentFacilityId %}
   6 :   {% user_async_assets %}
   7 :   {% user_assets %}
   8 : {% endblock %}
   9 : 

Traceback:

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\core\handlers\base.py" in get_response
  174.                     response = self.process_exception_by_middleware(e, request)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\core\handlers\base.py" in get_response
  172.                     response = response.render()

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\response.py" in render
  160.             self.content = self.rendered_content

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\response.py" in rendered_content
  137.         content = template.render(context, self._request)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\backends\django.py" in render
  95.             return self.template.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render
  206.                     return self._render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in _render
  197.         return self.nodelist.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render
  992.                 bit = node.render_annotated(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render_annotated
  959.             return self.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\loader_tags.py" in render
  173.         return compiled_parent._render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in _render
  197.         return self.nodelist.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render
  992.                 bit = node.render_annotated(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render_annotated
  959.             return self.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\loader_tags.py" in render
  69.                 result = block.nodelist.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render
  992.                 bit = node.render_annotated(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\base.py" in render_annotated
  959.             return self.render(context)

File "c:\users\alanc\kolibri\kolibri\lib\site-packages\django\template\library.py" in render
  201.         output = self.func(*resolved_args, **resolved_kwargs)

File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\templatetags\webpack_tags.py" in webpack_asset
  40.     return hook.render_to_page_load_sync_html()

File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\hooks.py" in render_to_page_load_sync_html
  379.         if self.frontend_messages():

File "C:\Users\alanc\Kolibri\kolibri\kolibri\core\webpack\hooks.py" in frontend_messages
  243.                         json.load(f), separators=(',', ':'))

File "C:\Users\alanc\AppData\Local\Programs\Python\Python35\Lib\json\__init__.py" in load
  265.     return loads(fp.read(),

File "c:\users\alanc\kolibri\kolibri\lib\encodings\cp1252.py" in decode
  23.         return codecs.charmap_decode(input,self.errors,decoding_table)[0]

Exception Type: UnicodeDecodeError at /user
Exception Value: 'charmap' codec can't decode byte 0x81 in position 66: character maps to <undefined>
```

### Steps to reproduce

Run the Kolibri devserver on Windows and change language settings to Arabic, Hindi, or Portuguese.

### Context

* Kolibri version: Develop Branch
* Operating system: Windows
* Browser: Google Chrome, Microsoft Edge, Mozilla Firefox

**Comment by jamalex** [comment]
Adding `{% csrf_token %}` to our base template should cover it.
https://docs.djangoproject.com/en/1.11/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-is-true

**Comment by indirectlylit** [comment]
Looks like it will be addressed by #2748

**Comment by rtibbles** [comment]
I don't think this issue has anything to do with this. It's a Unicode processing error.

**Comment by rtibbles** [comment]
I think this has more to do with running Kolibri inside git bash on a Windows machine, causing weird Unicode problems.

**Comment by indirectlylit** [comment]
closing - let's re-open if we see it again
