### ISSUE TITLE
on small screens, parts of some exercises are inaccessible

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2628]
### Observed behavior

parts of the exercise cannot be accessed:

![image](https://user-images.githubusercontent.com/2367265/32931058-fb68ca92-cb16-11e7-885d-5f414eca279c.png)

### Expected behavior

user should at least be able to scroll horizontally (since we can't reflow the exercise itself)

### User-facing consequences

some exercises are unusable

**Comment by indirectlylit** [comment]
working on this, but struggling to get perseus to build ...

```
    ERROR in ../perseus-plugin/kolibri_exercise_perseus_plugin/assets/src/module.js
    Module build failed: Error: Failed to load plugin html: Cannot find module 'eslint-plugin-html'
        at Function.Module._resolveFilename (module.js:455:15)
        at Function.resolve (internal/module.js:27:19)
        at Plugins.load (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config/plugins.js:133:29)
        at Array.forEach (native)
        at Plugins.loadAll (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config/plugins.js:173:21)
        at loadFromDisk (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config/config-file.js:536:35)
        at Object.load (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config/config-file.js:592:20)
        at Config.getLocalConfigHierarchy (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config.js:226:44)
        at Config.getConfigHierarchy (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config.js:180:43)
        at Config.getConfigVector (/Users/d/Projects/learning_equality/repos/kolibri/node_modules/eslint/lib/config.js:285:21)
```

**Comment by indirectlylit** [comment]
passing this to @rtibbles because it depends on publishing perseus to pypi
