### ISSUE TITLE
partially-complete transfers prevent a successful upgrade

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2729]
### Observed behavior

If Kolibri 0.6 is shut down while a transfer is in progress, running Kolibri 0.7 won't work

### Expected behavior

Upgrades should occur smoothly. Preferably the transfer can pick up where it left off, but if it needs to be canceled that's the next best solution.

### User-facing consequences

Kolibri is not usable after attempting to upgrade.

### Errors and logs

lots of this:

```
ERROR    Internal Server Error: /api/tasks/
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "kolibri/tasks/api.py", line 42, in list
    jobs_response = [_job_to_response(j) for j in get_client().all_jobs()]
  File "kolibri/tasks/api.py", line 427, in _job_to_response
    "type": job.extra_metadata.get("type"),
AttributeError: 'Job' object has no attribute 'extra_metadata'
```

### Steps to reproduce

* start up 0.6
* start a long-running import
* shut down 0.6 before import completes
* start up 0.7

### Context

* Kolibri version: 0.6 -> 0.7
* Operating system: OSX

**Comment by jonboiser** [comment]
Yeah, this looks like it's because of a breaking change to iceqube (Task v0.7 is not compatible with Task v0.6). The fix is to delete the Task DB, but maybe it would be better if this work an automatic step when upgrading.
