### ISSUE TITLE
When `kolibri start` fails in daemon mode, no indication to user (just in logs)

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#2867]
### Observed behavior

If starting the server fails (e.g. port is already taken), we still tell the user that it started and what addresses it should be available at.

### Expected behavior

If it fails to start, an error should be shown, and we shouldn't tell the user it's available at a certain set of addresses. We can probably wait in the parent process until the child process either errors or sends a success signal (or perhaps just stay in foreground mode and stream stdout/stderr from the child process until the server successfully starts, then go to background).

### User-facing consequences

Much confusion and frustration.

### Errors and logs

```
(kolibri) jamalex@ace:~/fle/kolibri$ KOLIBRI_HOME=~/.morango_bash2 ./kolibri-0.7.0.pex start --port=8002
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Running update routines for new version...

0 static files copied to '/home/jamalex/.morango_bash2/static', 406 unmodified.
Operations to perform:
  Apply all migrations: sessions, admin, kolibriauth, morango, auth, content, contenttypes, exams, device, logger
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
INFO     Running 'kolibri start' as daemon (system service)
INFO     Kolibri running on:

    http://127.0.0.1:8002/
    http://192.168.1.12:8002/
    http://172.17.0.1:8002/
    http://172.20.0.1:8002/

INFO     Going to daemon mode, logging to /home/jamalex/.morango_bash2/server.log

(kolibri) jamalex@ace:~/fle/kolibri$ cat /home/jamalex/.morango_bash2/server.log
INFO     Attempting a ping.
INFO     Started new MESSAGEPROCESSOR thread ID#bravo-skylark-kansas-arizona
INFO     Started new SCHEDULER thread ID#wolfram-steak-november-muppet
INFO     Started new WORKERMESSAGEHANDLER thread ID#twelve-orange-cold-pip
INFO     data: {"instance_id": "e8217b88d35498b5a4ae03acc2ad2dc2", "platform": "Linux-4.4.0-98-generic-x86_64-with-Ubuntu-16.04-xenial", "database_id": "e6c0c7ed659543e29c86ffbe55f6d668", "version": "0.7.0", "system_id": "", "mode": "", "language": "en", "sysversion": "2.7.12 (default, Nov 20 2017, 18:23:56) \n[GCC 5.4.0 20160609]", "uptime": 0, "node_id": "330ee011e851d40b249a"}
INFO     Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
INFO:kolibri.core.analytics.management.commands.ping:Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
ERROR:cherrypy.error:[07/Dec/2017:09:56:26] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x7f5d9cdc6f90>>
Traceback (most recent call last):
  File "kolibri/dist/cherrypy/process/wspbus.py", line 203, in publish
    output.append(listener(*args, **kwargs))
  File "kolibri/dist/cherrypy/_cpserver.py", line 168, in start
    ServerAdapter.start(self)
  File "kolibri/dist/cherrypy/process/servers.py", line 170, in start
    wait_for_free_port(*self.bind_addr)
  File "kolibri/dist/cherrypy/process/servers.py", line 438, in wait_for_free_port
    raise IOError("Port %r not free on %r" % (port, host))
IOError: Port 8002 not free on '0.0.0.0'
```
### Context

* Kolibri version: 0.7.0
* Operating system: Ubuntu

**Comment by jamalex** [comment]
On a similar note, more indication of the status of shutting down the server would be awesome. This is all it shows me when it successfully shuts down the server:

    $ ./kolibri-0.7.0.pex stop
    INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
    $

**Comment by lyw07** [comment]
I will try to fix this issue tomorrow

**Comment by benjaoming** [comment]
Sorry hadn't seen this issue before now. I would suggest closing it since it entails a slight paradox: Wanting to show foreground information to the user from a background process simply isn't possible.

However, doing a port availability check before deamonizing is something already raised as an issue: https://github.com/learningequality/kolibri/issues/3048

**Comment by indirectlylit** [comment]
closing this issue since the port case is addressed. other cases are listed in #3285
