### ISSUE TITLE
Out of memory when importing content channel

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#2879]
### Observed behavior

Content import fails on command line and through web interface when importing this content folder in the PraDigi channel: https://studio.learningequality.org/channels/620ef30860a65e7d8b2607ed03cc318f/edit/56dcbd6

### Cause

Kolibri uses up all RAM on machine (512MB) and 1G of Swap space 

<img width="772" alt="screen shot 2017-12-08 at 1 01 14 pm" src="https://user-images.githubusercontent.com/163966/33778944-dcc6e2d2-dc18-11e7-96b7-bdecb6079221.png">

right before crash:
```
root@pradigi-demo:/kolibrihome# free -h
             total       used       free     shared    buffers     cached
Mem:          594M       545M        48M         4K       280K       5.6M
-/+ buffers/cache:       539M        54M
Swap:         1.0G       996M        27M  <--- only 27MB of swap space left...
```

### Expected behavior

Import to finish

### User-facing consequences

cannot import certain channels

### Errors and logs

Nothing interesting, just stops at 8% and next thing we see is new INFO line from when Kolibri starts up again:
```
INFO:cherrypy.access.140236038787344:127.0.0.1 - - [08/Dec/2017:17:53:49] "GET /static/device_management_module/device_management_module0.7.0.css HTTP/1.0" 304 - "http://pradigi-demo.learningequality.org/management/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0"
INFO:cherrypy.access.140236038787344:127.0.0.1 - - [08/Dec/2017:17:53:49] "GET /static/device_management_module/device_management_module-0.7.0.js HTTP/1.0" 304 - "http://pradigi-demo.learningequality.org/management/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0"
  8%|8         | 377707260/4701760966 [00:20<00:03, 1312067839.62it/s]INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Running update routines for new version...
INFO     Running 'kolibri start' in foreground...
INFO     Kolibri running on:

	http://127.0.0.1:9090/
	http://10.142.0.28:9090/

INFO     Started new MESSAGEPROCESSOR thread ID#finch-salami-march-fish
INFO     Started new SCHEDULER thread ID#low-michigan-july-sweet
INFO     Started new WORKERMESSAGEHANDLER thread ID#vegan-artist-maryland-ack
INFO     Attempting a ping.
INFO     data: {"instance_id": "ca5abbbff7078625156f01841e87aa11", "platform": "Linux-3.16.0-4-amd64-x86_64-with-debian-8.8", "database_id": "9da5439de44d41ec93cba7f98eb25d29", "version": "0.7.0", "system_id": "", "mode": "", "language": "en", "sysversion": "2.7.9 (default, Jun 29 2016, 13:08:31) \n[GCC 4.9.2]", "uptime": 0, "node_id": "91a2d3405ea2ccfb574e"}
INFO:cherrypy.error:[08/Dec/2017:17:55:19] ENGINE Bus STARTING
INFO:cherrypy.error:[08/Dec/2017:17:55:19] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO     Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
INFO:kolibri.core.analytics.management.commands.ping:Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
INFO:cherrypy.error:[08/Dec/2017:17:55:19] ENGINE Serving on http://0.0.0.0:9090
INFO:cherrypy.error:[08/Dec/2017:17:55:19] ENGINE Bus STARTED

```

### Steps to reproduce

Go to http://pradigi-demo.learningequality.org and login and try to import the missing folder from the channel (all other content worked ok):

<img width="764" alt="step2 choose missing content" src="https://user-images.githubusercontent.com/163966/33778969-fa9d17fe-dc18-11e7-9951-a9b6093454ac.png">

import starts OK

<img width="727" alt="screen shot 2017-12-07 at 11 00 55 pm" src="https://user-images.githubusercontent.com/163966/33779054-5ba9c952-dc19-11e7-93db-1acb64c93ece.png">

but just stops and Kolibri restarts (not sure if Kolibri automatically restarts or supervisor script that watches restarts it)

### Context

noticed this failed yesterday, today isolated specific subfolder that is causing the crash

There are some errors in the js console, but not sure if they are relevant:

<img width="1277" alt="screen shot 2017-12-07 at 11 18 36 pm" src="https://user-images.githubusercontent.com/163966/33779092-816c6230-dc19-11e7-98e4-f90b4773e88d.png">

on the topic of js console errors this was in console while logging in:

<img width="1104" alt="screen shot 2017-12-08 at 12 53 28 pm" src="https://user-images.githubusercontent.com/163966/33779138-b20e6adc-dc19-11e7-90a5-d537efb939d6.png">

**Comment by ivanistheone** [comment]
Checking the content tree on sushibar,  I see this part of the channel subtree contains a 1.1G video node + a bunch of other large ones:
https://sushibar.learningequality.org/runs/abe7feea-73d2-4d31-98fc-de49b839babb/#tree

**Comment by ivanistheone** [comment]
I ran into this issue again today, this time with a 700MB file, which is weird since the machine has 600MB RAM + 1G swap.

```
[35.196.82.154] sudo: python /kolibrihome/kolibri-0.8.0.pex manage importcontent network ce1361bcf5955df596e8d988f7ba2c37

Fatal error: sudo() received nonzero return code 1 while executing!

Requested: python /kolibrihome/kolibri-0.8.0.pex manage importcontent network ce1361bcf5955df596e8d988f7ba2c37
Executed: sudo -S -p 'sudo password:'  -u "kolibri"  /bin/bash -l -c "export KOLIBRI_HOME=\"/kolibrihome\" && python /kolibrihome/kolibri-0.8.0.pex manage importcontent network ce1361bcf5955df596e8d988f7ba2c37"

============================================================================ Standard output ============================================================================

INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
 59%|███████████████████████████████████████████████████████████████████                                              | 1471996893/2481368931 [06:10<43:36, 385716.52it/s]
Traceback (most recent call last):                                                                                                          | 0/821165975 [00:00<?, ?it/s]
  File ".bootstrap/_pex/pex.py", line 365, in execute
  File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File ".bootstrap/_pex/pex.py", line 408, in _execute
  File ".bootstrap/_pex/pex.py", line 466, in execute_entry
  File ".bootstrap/_pex/pex.py", line 471, in execute_module
  File "/usr/lib/python2.7/runpy.py", line 180, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/utils/cli.py", line 652, in main
    manage(command, args=django_args)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/utils/cli.py", line 435, in manage
    execute_from_command_line(argv=argv)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/tasks/management/commands/base.py", line 99, in handle
    return self.handle_async(*args, **options)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/content/management/commands/importcontent.py", line 189, in handle_async
    renderable_only=options["renderable_only"])
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/content/management/commands/importcontent.py", line 113, in download_content
    self._transfer(DOWNLOAD_METHOD, channel_id, node_ids=node_ids, exclude_node_ids=exclude_node_ids, baseurl=baseurl, renderable_only=renderable_only)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/content/management/commands/importcontent.py", line 156, in _transfer
    for chunk in filetransfer:
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/content/utils/transfer.py", line 166, in next
    return super(FileDownload, self).next()
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/content/utils/transfer.py", line 85, in next
    chunk = next(self._content_iterator)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/kolibri/.pex/install/kolibri-0.8.0....whl/kolibri/dist/urllib3/response.py", line 380, in read
    data = self._fp.read()
  File "/usr/lib/python2.7/httplib.py", line 586, in read
    s = self._safe_read(self.length)
  File "/usr/lib/python2.7/httplib.py", line 698, in _safe_read
    return ''.join(s)
MemoryError
```

It's on the chef side to make sure video files are not huge (e.g. 500MB limit), but would be good to fix this on Kolibri side so that Kolibri running on computers with low ram and no swap won't run out of memory.

**Comment by pcenov** [comment]
@radina I'm not able to replicate this in 0.15.1

**Comment by radinamatic** [comment]
Thank you @pcenov, this is a very old issue and memory usage has been optimized since. Closing!
