### ISSUE TITLE
resolve warnings in developer docs

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#2960]
### Observed behavior

Currently lots of warnings when building the dev docs:

```
~/P/l/r/k/docs-developer (docs-warnings) $ sphinx-build ./ ./_build/
Running Sphinx v1.6.4
making output directory...
Initialize kolibri_settings.json..
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
Running Kolibri with the following settings: kolibri.deployment.default.settings.base
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 30 source files that are out of date
updating environment: 30 added, 0 changed, 0 removed
reading sources... [100%] upgrade                                                           
WARNING: /Users/d/Projects/learning_equality/repos/k2/docs-developer/content/implementation.rst:90: (WARNING/2) autodoc: failed to import module u'kolibri.content.constants.content_kinds'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named constants.content_kinds
WARNING: /Users/d/Projects/learning_equality/repos/k2/docs-developer/content/implementation.rst:91: (WARNING/2) autodoc: failed to import module u'kolibri.content.constants.extensions'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named constants.extensions
WARNING: /Users/d/Projects/learning_equality/repos/k2/docs-developer/content/implementation.rst:92: (WARNING/2) autodoc: failed to import module u'kolibri.content.constants.presets'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/d/PythonEnvs/le2/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
ImportError: No module named constants.presets
WARNING: /Users/d/Projects/learning_equality/repos/k2/docs-developer/dataflow/index.rst:138: (ERROR/3) Error in "code-block" directive:
maximum 1 argument(s) allowed, 16 supplied.

.. code-block:: javascript
  // corresponds to /api/content/<channelId>/contentnode/?popular=1
  const contentCollection = ContentNodeResource.getCollection({ channel_id: channelId }, { popular: 1 });
/Users/d/Projects/learning_equality/repos/k2/docs-developer/frontend_architecture.rst:121: WARNING: Unexpected indentation.
WARNING: /Users/d/Projects/learning_equality/repos/k2/docs-developer/getting_started.rst:247: (WARNING/2) Title underline too short.

Development
----------
WARNING: /Users/d/Projects/learning_equality/repos/k2/docs-developer/getting_started.rst:247: (WARNING/2) Title underline too short.

Development
----------
/Users/d/Projects/learning_equality/repos/k2/docs-developer/i18n.rst:31: WARNING: Inline literal start-string without end-string.
/Users/d/Projects/learning_equality/repos/k2/docs-developer/i18n.rst:80: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/Users/d/Projects/learning_equality/repos/k2/docs-developer/manual_testing.rst:3: WARNING: Duplicate explicit target name: "firefox add-on".
/Users/d/Projects/learning_equality/repos/k2/docs-developer/manual_testing.rst:3: WARNING: Duplicate explicit target name: "chrome extension".
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/d/Projects/learning_equality/repos/k2/docs-developer/authors.rst: WARNING: document isn't included in any toctree
/Users/d/Projects/learning_equality/repos/k2/docs-developer/changelog.rst: WARNING: document isn't included in any toctree
/Users/d/Projects/learning_equality/repos/k2/docs-developer/contributing/enforcement_manual.rst: WARNING: document isn't included in any toctree
/Users/d/Projects/learning_equality/repos/k2/docs-developer/contributing/index.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] upgrade                                                            
/Users/d/Projects/learning_equality/repos/k2/docs-developer/frontend_architecture.rst:72: WARNING: unknown document: asset_loading
/Users/d/Projects/learning_equality/repos/k2/docs-developer/frontend_architecture.rst:109: WARNING: unknown document: asset_loading
/Users/d/Projects/learning_equality/repos/k2/docs-developer/frontend_build_pipeline.rst:6: WARNING: unknown document: frontend
/Users/d/Projects/learning_equality/repos/k2/docs-developer/plugins.rst:12: WARNING: unknown document: ../user/cli
/Users/d/Projects/learning_equality/repos/k2/docs-developer/plugins.rst:21: WARNING: unknown document: frontend
/Users/d/Projects/learning_equality/repos/k2/docs-developer/release_process.rst:71: WARNING: undefined label: new_language (if the link has no caption the label must precede a section header)
generating indices... genindex py-modindex
highlighting module code... [100%] kolibri.auth.models                                      
writing additional pages... search
copying images... [100%] uap/./img/uap_crud_permissions.svg                                 
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 21 warnings.
```

### Expected behavior

no warnings

### User-facing consequences

possibility of broken docs

### Steps to reproduce

build using `sphinx-build`

### Context

* #2959
* #2598

**Comment by geoffrey1218** [comment]
I started working on this today and managed to resolve most of the errors. However, the biggest offender by far is the "document isn't included in any toctree" that appears for about 70 files in the docs-developer/py_modules folder, e.g. kolibri.auth.constants.rst, kolibri.auth.management.rst, kolibri.auth.management.commands.rst, kolibri.auth.migrations.rst, etc. It seems that those files are excluded from source control, so there isn't a way for me to fix this by manually inserting the documents into the relevant TOC trees and pushing the updated files. How should I update the contents of these files? 

Any insight @indirectlylit ? From the log you posted it doesn't look like these errors were around when this issue was created, so not sure if it's something that broke recently or just a problem in my environment.

**Comment by indirectlylit** [comment]
thanks @geoffrey1218!

I don't personally have much insight into these, but @benjaoming might.

> managed to resolve most of the errors

That's great. 

My recommendation would be to address as much as you can in the PR above, and then file individual issues for any remaining classes of errors. Then we can close this general-purpose ticket and tackle the remaining ones one-at-a-time.

**Comment by geoffrey1218** [comment]
Great, I opened issues for the other categories of errors. Once my pull request is merged, this issue can be closed.

**Comment by indirectlylit** [comment]
thank you!

**Comment by indirectlylit** [comment]
FYI, @geoffrey1218 feel free to submit a PR adding yourself to the AUTHORS file (if you'd like)
