### ISSUE TITLE
ping command fails: TypeError: float() argument must be a string or a number

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#2967]
### Observed behavior

I think this fails silently in its own thread. Happened on Python 2.7, not sure why, but traceback is easy to fix.

### Expected behavior

n/a

### User-facing consequences

None, but ping doesn't happen

### Errors and logs

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/media/archive/code/kolibri/kolibri/utils/server.py", line 98, in run
    call_command("ping")
  File ".virtualenvs/kolibri/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File ".virtualenvs/kolibri/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/media/archive/code/kolibri/kolibri/core/analytics/management/commands/ping.py", line 34, in handle
    interval = float(options.get("interval", DEFAULT_PING_INTERVAL))
TypeError: float() argument must be a string or a number

```

### Steps to reproduce

Sorry can't say for sure, was just reading a log.

### Context

Tell us about your environment, including:
 * Kolibri version: Either 0.7 or `develop` :)
 * Operating system: The best linux distro version 16.04
 * Browser: n/a

**Comment by indirectlylit** [comment]
cc @jamalex

**Comment by lyw07** [comment]
just to add on to steps to reproduce, we can get this error by doing `kolibri start --foreground`.

**Comment by jamalex** [comment]
Hmm, strange, I don't get this issue on the latest 0.7 -- I get he following with `kolibri start --foreground`:

```
INFO     data: {"instance_id": "f5be4b1e551a6b51dc44b4e97e0aee01", "platform": "Linux-4.4.0-103-generic-x86_64-with-Ubuntu-16.04-xenial", "database_id": "ef432ace33504bf2b4c695e544011331", "version": "0.7.0", "system_id": "", "mode": "", "language": "", "sysversion": "2.7.12 (default, Nov 20 2017, 18:23:56) \n[GCC 5.4.0 20160609]", "uptime": 0, "node_id": "bf2d679da6aefc2495b2"}
INFO:kolibri.core.analytics.management.commands.ping:data: {"instance_id": "f5be4b1e551a6b51dc44b4e97e0aee01", "platform": "Linux-4.4.0-103-generic-x86_64-with-Ubuntu-16.04-xenial", "database_id": "ef432ace33504bf2b4c695e544011331", "version": "0.7.0", "system_id": "", "mode": "", "language": "", "sysversion": "2.7.12 (default, Nov 20 2017, 18:23:56) \n[GCC 5.4.0 20160609]", "uptime": 0, "node_id": "bf2d679da6aefc2495b2"}
INFO:cherrypy.error:[08/Jan/2018:21:40:15] ENGINE Bus STARTING
INFO:cherrypy.error:[08/Jan/2018:21:40:15] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO:cherrypy.error:[08/Jan/2018:21:40:15] ENGINE Serving on http://0.0.0.0:8080
INFO:cherrypy.error:[08/Jan/2018:21:40:15] ENGINE Bus STARTED
INFO     Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
INFO:kolibri.core.analytics.management.commands.ping:Ping succeeded! (response: {}) Sleeping for 1440.0 minutes.
```

**Comment by jamalex** [comment]
Ah, on develop, however, I do get the above issue. Probably a symptom of some of the package upgrades (likely, Django). I'll work on a fix!

**Comment by jamalex** [comment]
Should be fixed in https://github.com/learningequality/kolibri/pull/3045 -- note that it'll need to be merged to `release-v0.7.x` and then from there merged up into `develop` (where the fix is needed).

**Comment by jamalex** [comment]
Fixed in #3045, but let's wait to close until https://github.com/learningequality/kolibri/pull/3055 is merged.
