### ISSUE TITLE
Not able to run kolibri with cherrypy 13.0.0

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#2971]
### Observed behavior

When running the latest pex or installing the latest whl file from develop branch, `kolibri` will fail.

This issue is related to https://github.com/jaraco/jaraco.classes/issues/2, as the dependency of `cherrypy`, `jaraco`, is a namespace package.

### Expected behavior

Kolibri should be able to run successfully

### User-facing consequences

Users are not able to use Kolibri

### Errors and logs

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/osboxes/.local/lib/python2.7/site-packages/kolibri/__main__.py", line 7, in <module>
    from kolibri.utils.cli import main
  File "/home/osboxes/.local/lib/python2.7/site-packages/kolibri/utils/cli.py", line 42, in <module>
    from . import server  # noqa
  File "/home/osboxes/.local/lib/python2.7/site-packages/kolibri/utils/server.py", line 6, in <module>
    import cherrypy
  File "/home/osboxes/.local/lib/python2.7/site-packages/kolibri/dist/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/home/osboxes/.local/lib/python2.7/site-packages/kolibri/dist/cherrypy/_cperror.py", line 128, in <module>
    from jaraco.classes.properties import classproperty
ImportError: No module named jaraco.classes.properties
```

### Steps to reproduce

1. Get the latest pex/whl from develop branch
2. Run `kolibri`

### Context

Kolibri version: 0.8
Operating system: Mac OS X/Ubuntu
Browser: Chrome

**Comment by indirectlylit** [comment]
I believe fixed by #2976?
