### ISSUE TITLE
Error in ping command - OperationalError: no such column: morango_instanceidmodel.macaddress

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3047]
### Observed behavior

Ping command dies - Kolibri works.

I think we need to up test coverage? @jamalex 

### Expected behavior

n/a

### User-facing consequences

Ping command dies

### Errors and logs

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/kolibri/utils/server.py", line 99, in run
    command.execute()
  File "/kolibri/dist/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/kolibri/core/analytics/management/commands/ping.py", line 43, in handle
    data = self.perform_ping(server)
  File "/kolibri/core/analytics/management/commands/ping.py", line 57, in perform_ping
    instance, _ = InstanceIDModel.get_or_create_current_instance()
  File "/kolibri/dist/morango/models.py", line 103, in get_or_create_current_instance
    obj, created = InstanceIDModel.objects.get_or_create(**kwargs)
  File "/kolibri/dist/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/kolibri/dist/django/db/models/query.py", line 465, in get_or_create
    return self.get(**lookup), False
  File "/kolibri/dist/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/kolibri/dist/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/kolibri/dist/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/kolibri/dist/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/kolibri/dist/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/kolibri/dist/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/kolibri/dist/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: morango_instanceidmodel.macaddress
```

### Steps to reproduce

    kolibri start --foreground

Notice that migrations are run before the error occurs.

### Context

After #3045 is merged, this happens

**Comment by jamalex** [comment]
Is it possible that you're using a new database on an old version (ghost migration)? Macaddress field was deleted in a recent version of Morango.

**Comment by benjaoming** [comment]
@jamalex it is possible that I use an old database on a new version, but then things should just get migrated. The error occurred while testing your PR branch, which I assume was a somewhat new version of develop. Can re-test...

**Comment by benjaoming** [comment]
Still happens after switching to the latest develop with `morango==0.2.2`

**Comment by benjaoming** [comment]
You're unable to reproduce?

**Comment by rtibbles** [comment]
I think there was some refactor in morango, and sometimes pyc files for migrations from non-pip released versions (that were later removed) got left lying around in the venv. Perhaps this is the issue? The only way I managed to get rid of them was with a clean venv.

**Comment by benjaoming** [comment]
*\*doh\**

I had an unclean `kolibri/dist`

Keep running into this issue while dev'ing, will try to think of some way to improve workflow so it stops happening.

Thanks for the pointer @rtibbles 

I assume indeed the issue then was that I was running a new database against an old version of Morango, which lived in `kolibri/dist`.

**Comment by indirectlylit** [comment]
> Keep running into this issue while dev'ing, will try to think of some way to improve workflow so it stops happening.

In our dev docs, [we recommend](http://kolibri-dev.readthedocs.io/en/develop/start/getting_started.html#install-project-dependencies) liberal use of this snippet:

```
make clean && pip install -r requirements.txt --upgrade && pip install -e . && yarn install
```

**Comment by rtibbles** [comment]
`make clean` can be problematic if you have messed up migrations though, because it will invoke kolibri.

**Comment by benjaoming** [comment]
@indirectlylit I avoid `make clean` in many cases because of `clean-static`, but it's true that it's a safer choice in general.
