### ISSUE TITLE
Management plugin isn't enabled, but enabling it requires the management plugin

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#3114]
I get this message when running any management command:

```
$ python -m kolibri shell
WARNING:root:No C Extensions available for this platform.
```

I subsequently cancel my command and try adding the management command first.

```
$ kolibri plugin kolibri.plugins.management enable
WARNING:root:No C Extensions available for this platform.
```

But then I immediately get this error:

```
Traceback (most recent call last):
  File "/Users/aron/.virtualenvs/kolibri2/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/utils/cli.py", line 569, in main
    initialize(debug=debug)
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/utils/cli.py", line 146, in initialize
    django.setup()
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/dist/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/dist/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/dist/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named management
```

I feel like during plugin disabling and enabling, we should try to find the minimal subset of modules we need to do that. Otherwise we'll get into this chicken and egg problem.

**Comment by jonboiser** [comment]
@aronasorman The `management` plugin is no more. It was split into two apps `device_management` and `facility_management`.

**Comment by jonboiser** [comment]
I've observed this too. I think there might be some residual code from before splitting these plugins.

**Comment by rtibbles** [comment]
Don't see any residual references to this in the code base. Please reopen this issue with a traceback if it is observed again.
