### ISSUE TITLE
Django 1.11 causing migration errors

### ISSUE THREAD

**Issue by aronasorman** [learningequality/kolibri#3118]
Running with Django 1.11 now causes this error:

```
Running migrations:
  Applying morango.0007_auto_20171128_1646...Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/__main__.py", line 8, in <module>
    main(args=sys.argv[1:])
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/utils/cli.py", line 592, in main
    start(port, daemon=daemon)
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/utils/cli.py", line 248, in start
    update()
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/utils/cli.py", line 226, in update
    _migrate_databases()
  File "/Users/aron/src/github.com/aronasorman/kolibri/kolibri/utils/cli.py", line 166, in _migrate_databases
    call_command("migrate", interactive=False, database=database)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 744, in state_forwards
    state.reload_model(app_label, self.name_lower, delay=True)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/state.py", line 166, in reload_model
    self._reload(related_models)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/state.py", line 199, in _reload
    self.apps.render_multiple(states_to_be_rendered)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/state.py", line 323, in render_multiple
    model.render(self)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/migrations/state.py", line 626, in render
    body,
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/models/base.py", line 162, in __new__
    new_class.add_to_class(obj_name, obj)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/models/base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "/Users/aron/.virtualenvs/kolibri/lib/python3.6/site-packages/django/db/models/manager.py", line 120, in contribute_to_class
    setattr(model, name, ManagerDescriptor(self))
```

Downgrading to 1.9.13 fixes this.

**Comment by aronasorman** [comment]
I think this only pops up if you're running all migrations, as there's a very specific migration that triggers this it seems.

**Comment by ralphiee22** [comment]
Was unable to reproduce from clean virtualenv from `develop` branch.
Can anyone else reproduce? @rtibbles

**Comment by rtibbles** [comment]
Yeah, I didn't see an issue, although I was mostly testing on Python 3.5 - could it be a 3.6 issue?
