### ISSUE TITLE
Allow KOLIBRI_HOME to include "~" or be relative

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#3128]
### Observed behavior

A user or deployment specialist should be able to specify `~` in `KOLIBRI_HOME`. This fails.

### Expected behavior

That the currently logged in user's home is resolved and used. We should use `os.path.expanduser`. Furthermore, if you specify a relative path like `KOLIBRI_HOME=.here`, then it also fails, so it should call `os.path.abspath` to expand a relative path according to the CWD (current working directory).

### User-facing consequences

Possibly minor, but anyone would be in their right mind to think that `~/` is valid.

### Errors and logs

```
➜  KOLIBRI_HOME="~/.kolibri" python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from kolibri.utils import conf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "kolibri/utils/conf.py", line 36, in <module>
    raise RuntimeError("The parent of your KOLIBRI_HOME does not exist: {}".format(parent))
RuntimeError: The parent of your KOLIBRI_HOME does not exist: ~
```

### Steps to reproduce

```
➜  KOLIBRI_HOME="~/.kolibri" python
```

### Context

n/a

**Comment by benjaoming** [comment]
Fixed in #3130
