### ISSUE TITLE
`generateuserdata` bails with unicode encoding error

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#3383]
### Observed behavior

```
C:\Users\meeti>kolibri manage generateuserdata
WARNING:root:No C Extensions available for this platform.

[37mINFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base[0m
INFO:kolibri.core.apps:Running Kolibri with the following settings: kolibri.deployment.default.settings.base
Generating 2 classroom object(s) for facility: Escuela de Demostración
Generating 20 user object(s) for class: Classroom 1A in facility: Escuela de Demostración
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Canal UNETE
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: CK-12
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Sikana EN
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Osmosis.org
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Open Stax
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Firki
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Blockly Games
Generating 79 user interaction(s) for user: "R Poulsen Otto"@"Escuela de Demostración" for channel: Khan Academy (en)
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Canal UNETE
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: CK-12
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Sikana EN
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Osmosis.org
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Open Stax
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Firki
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Blockly Games
Generating 77 user interaction(s) for user: "B"@"Escuela de Demostración" for channel: Khan Academy (en)
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Canal UNETE
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: CK-12
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Sikana EN
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Osmosis.org
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Open Stax
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Firki
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Blockly Games
Generating 49 user interaction(s) for user: "Barela A Lelia"@"Escuela de Demostración" for channel: Khan Academy (en)
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Canal UNETE
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: CK-12
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Sikana EN
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Osmosis.org
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Open Stax
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Firki
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Blockly Games
Generating 78 user interaction(s) for user: "Chimotofu"@"Escuela de Demostración" for channel: Khan Academy (en)
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Canal UNETE
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: CK-12
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Sikana EN
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Osmosis.org
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Open Stax
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Firki
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Blockly Games
Generating 73 user interaction(s) for user: "R Kellman Sánta"@"Escuela de Demostración" for channel: Khan Academy (en)
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Canal UNETE
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: CK-12
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Sikana EN
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Osmosis.org
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Open Stax
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Firki
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Blockly Games
Generating 42 user interaction(s) for user: "Karat D'Reli K"@"Escuela de Demostración" for channel: Khan Academy (en)
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Khan Academy (es)
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: EngageNY (es)
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: PhET Interactive Simulations
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Kolibri Demo 1
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: MIT Blossoms
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Aflatoun Academy (EN)
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: TESSA - Teacher Resources
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Touchable Earth (en)
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Canal UNETE
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: CK-12
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Sikana EN
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Osmosis.org
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Open Stax
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: PBS Learning Media
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Firki
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Tahrir Academy
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Kakuma - Content UX Master Channel
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Khan Academy (fr)
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Blockly Games
Generating 42 user interaction(s) for user: "Kawahara C"@"Escuela de Demostración" for channel: Khan Academy (en)
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\python27\scripts\kolibri.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\kolibri\utils\cli.py", line 652, in main
    manage(command, args=django_args)
  File "c:\python27\lib\site-packages\kolibri\utils\cli.py", line 435, in manage
    execute_from_command_line(argv=argv)
  File "c:\python27\lib\site-packages\kolibri\dist\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "c:\python27\lib\site-packages\kolibri\dist\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\python27\lib\site-packages\kolibri\dist\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\python27\lib\site-packages\kolibri\dist\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "c:\python27\lib\site-packages\kolibri\logger\management\commands\generateuserdata.py", line 90, in handle
    now=now
  File "c:\python27\lib\site-packages\kolibri\logger\utils\user_data.py", line 103, in add_channel_activity_for_user
    channel=channel.name
  File "c:\python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u6607' in position 45: character maps to <undefined>
```

### User-facing consequences

Second time I've seen this (of 2 times running `generateuserdata`), so I'm guessing it's frequently blocking full runs of the command (at least with a large set of content).

### Steps to reproduce

In case it's specific to the database in use (e.g. channel titles?), database files have been uploaded to Slack here:
https://learningequality.slack.com/files/U2ZEEE3FF/F9R97AFPT/db.sqlite3
https://learningequality.slack.com/files/U2ZEEE3FF/F9S0PPS0M/db.sqlite3-shm
https://learningequality.slack.com/files/U2ZEEE3FF/F9RSLBP18/db.sqlite3-wal

### Context

Kolibri 0.8.0 on Windows 10.

**Comment by jamalex** [comment]
(Given how it ran through successfully for multiple users, and then bailed right when starting a new user, I'm guessing it may be an issue with one of the user's names)

**Comment by rtibbles** [comment]
Hrm, what channels do you have installed for this also? (just in case it is a channel specific interaction)

**Comment by jamalex** [comment]
You can see the list of channels in the traceback. It cycles through each channel several times, though, before crashing, so I don't think it's the channel name after all. There's a name with an accent and a Chinese name in there that could be doing it.

**Comment by rtibbles** [comment]
Is this the first time you have run this command on Windows 10? Wondering why we have not seen this before now.

**Comment by jamalex** [comment]
I think where I last saw something like this on the other demo laptop, but didn't have time to report it then as I was in final packing mode for the Jukata trip.

**Comment by benjaoming** [comment]
This looks like a problem printing to the "lovely" Windows terminal. This has happened a lot before!

**Comment by benjaoming** [comment]
@jamalex another ting... in `kolibri.utils.env` you find this:

```
    # This was added in
    # https://github.com/learningequality/kolibri/pull/580
    # ...we need to (re)move it /benjaoming
    # Force python2 to interpret every string as unicode.
    if sys.version[0] == '2':
        reload(sys)  # noqa
        sys.setdefaultencoding('utf8')
```

Could you try disabling this? Am wondering if this can be a culprit in confusing terminal output encoding.

**Comment by rtibbles** [comment]
No longer using Py27 on Windows. Closing.
