### ISSUE TITLE
Mastery Model in KA but not Kolibri

### ISSUE THREAD

**Issue by mattjquinn** [learningequality/kolibri#3544]
I downloaded and installed Kolibri for use at a secondary school here in Tanzania. The install process and initial seeding of some content succeeded, but front-end errors are preventing all exercise sections from being usable. I don't know whether this is due to a problem with Kolibri proper or a problem within the embedded content itself. I have reproduced this in both versions 0.9.0 and 0.8.0 of Kolibri, using both Debian and Ubuntu as servers, with Debian, Ubuntu, and Windows 7 as clients, and with Firefox, Chrome, and IE as front-ends. Full bug report is below.

### Observed behavior
Upon opening an exercise topic, the exercises fail to appear on screen.

### Expected behavior
The exercises should appear, or some onscreen error should explain why they fail to appear.

### User-facing consequences
Learners can't view or complete exercise topics.

### Errors and logs
In the consoles for both Firefox and Chrome, the following two errors appear upon every page access for an exercise topic:

```
12:44:28.097 TypeError: a.MasteryModelGenerators[this.masteryModel.type] is not a function
Stack trace:
mOfNMasteryModel@http://localhost:8080/static/learn_module/learn_module-0.9.0.js:1:54213
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
kolibriGlobal</</Io.prototype.evaluate@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6648
Jt/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:18774
totalCorrectRequiredM@http://localhost:8080/static/learn_module/learn_module-0.9.0.js:1:54334
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
kolibriGlobal</</Io.prototype.evaluate@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6648
Jt/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:18774
r@http://localhost:8080/static/learn_module/learn_module-0.9.0.js:1:118487
kolibriGlobal</</</t.prototype._render@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:10437
r@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15576
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
Io@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5579
Lt@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15592
kolibriGlobal</</Me.prototype.$mount@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:25995
init@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:7169
c@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16725
u@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16354
d@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:17323
u@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16469
kolibriGlobal</</Di</<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:20942
kolibriGlobal</</</t.prototype._update@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:9423
r@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15566
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
Io@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5579
Lt@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15592
kolibriGlobal</</Me.prototype.$mount@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:25995
init@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:7169
c@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16725
u@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16354
d@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:17323
u@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16469
x@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:18923
S@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:19689
kolibriGlobal</</Di</<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:20993
kolibriGlobal</</</t.prototype._update@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:9399
r@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15566
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
kolibriGlobal</</Io.prototype.run@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6382
Bt@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:17005
ut/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:11113
at@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10940
A/</<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80903
A/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80773
c@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:55350
 1 default_frontend-0.9.0.js:8:10846
	it http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10846
	ot http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10768
	rt http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10634
	kolibriGlobal</</</t.prototype._render http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:10486
	r http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15576
	kolibriGlobal</</Io.prototype.get http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
	Io http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5579
	Lt http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15592
	kolibriGlobal</</Me.prototype.$mount http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:25995
	init http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:7169
	c http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16725
	u http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16354
	d http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:17323
	u http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16469
	kolibriGlobal</</Di</< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:20942
	kolibriGlobal</</</t.prototype._update http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:9423
	r http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15566
	kolibriGlobal</</Io.prototype.get http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
	Io http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5579
	Lt http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15592
	kolibriGlobal</</Me.prototype.$mount http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:25995
	init http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:7169
	c http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16725
	u http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16354
	d http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:17323
	u http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:16469
	x http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:18923
	S http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:19689
	kolibriGlobal</</Di</< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:20993
	kolibriGlobal</</</t.prototype._update http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:9399
	r http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15566
	kolibriGlobal</</Io.prototype.get http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
	kolibriGlobal</</Io.prototype.run http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6382
	Bt http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:17005
	ut/< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:11113
	at http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10940
	A/</< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80903
	A/< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80773
	c http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:55350
```

and

```
12:44:28.181 TypeError: a.MasteryModelGenerators[this.masteryModel.type] is not a function
Stack trace:
mOfNMasteryModel@http://localhost:8080/static/learn_module/learn_module-0.9.0.js:1:54213
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
kolibriGlobal</</Io.prototype.evaluate@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6648
Jt/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:18774
totalCorrectRequiredM@http://localhost:8080/static/learn_module/learn_module-0.9.0.js:1:54334
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
kolibriGlobal</</Io.prototype.evaluate@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6648
Jt/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:18774
r@http://localhost:8080/static/learn_module/learn_module-0.9.0.js:1:118487
kolibriGlobal</</</t.prototype._render@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:10437
r@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15576
kolibriGlobal</</Io.prototype.get@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
kolibriGlobal</</Io.prototype.run@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6382
Bt@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:17005
ut/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:11113
at@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10940
A/</<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80903
A/<@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80773
c@http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:55350
 1 default_frontend-0.9.0.js:8:10846
	it http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10846
	ot http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10768
	rt http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10634
	kolibriGlobal</</</t.prototype._render http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:10486
	r http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:15576
	kolibriGlobal</</Io.prototype.get http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:5649
	kolibriGlobal</</Io.prototype.run http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:6382
	Bt http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:17005
	ut/< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:11113
	at http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:8:10940
	A/</< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80903
	A/< http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:73:80773
	c http://localhost:8080/static/default_frontend/default_frontend-0.9.0.js:13:55350
```

### Steps to reproduce
I believe this error occurs on every exercise topic page. The two pages I explicitly checked were:

* _Hesabu kwa namba ndogo_
  * URL: http://localhost:8080/learn/#/topics/c/153e8bfec95f5ff9a7ac12dd58fe2e43
  * Navigation: Channels > Khan Academy Kiswahili > Hisabati > Awali > Kuhesabu na kuweka thamani > Kuhesabu namba ndogo > Hesabu kwa namba ndogo 
* _Test Yourself: Intro to JS: Drawing & Animation_
  * URL: http://192.168.43.248:8080/learn/#/topics/c/c8c847b2b0f25797b2f2c20331620fd9
  * Navigation: Channels > Khan Academy English > Computing > Computer programming > Intro to JS: Drawing and Animation > Test Yourself: Intro to JS: Drawing & Animation > Test Yourself: Intro to JS: Drawing and Animation

### Context
This is reproducible in two contexts, one for Kolibri 0.8 and another for 0.9:

#### Context 1
* Kolibri version	0.9.0
* Server URL 	http://192.168.43.248:8080/
* Database path	/var/kolibri/.kolibri/db.sqlite3
* Device name	tsadmin-Inspiron-15-3552
* Operating system	Linux-3.13.0-123-generic-x86_64-with-Ubuntu-14.04-trusty
* Free disk space	36 GB
* Server time	12:48:45 PM GMT+3 on April 16, 2018
* Server timezone	Africa/Dar_es_Salaam

_with browsers_:
* Firefox 54.0 64-bit (on Ubuntu 14.04)
* Firefox 58.0.1 64-bit (on Debian 9)
* Chrome 65.0.3325.181 64-bit (on Ubuntu 14.04)

#### Context 2
* Kolibri version	0.8.0
* Server URL 	http://192.168.43.248:8080/
* Database path	/var/kolibri/.kolibri/db.sqlite3
* Device name	tsadmin-Inspiron-15-3552
* Operating system	Linux-3.13.0-123-generic-x86_64-with-Ubuntu-14.04-trusty
* Free disk space	36 GB
* Server time	01:59:49 PM GMT+3 on April 16, 2018
* Server timezone	Africa/Dar_es_Salaam

_with browsers_:
* Firefox 54.0 64-bit (on Ubuntu 14.04)
* Firefox 58.0.1 64-bit (on Debian 9)
* Chrome 65.0.3325.181 64-bit (on Ubuntu 14.04)

#### Context 3
* Kolibri version	0.9.0
* Server URL 	http://192.168.43.124:8080/
* Database path	/var/kolibri/.kolibri/db.sqlite3
* Device name	jengamtandao-server
* Operating system	Linux-4.9.0-3-amd64-x86_64-with-debian-9.1
* Free disk space	5 GB
* Server time	7:12:38 PM GMT+3 on April 16, 2018
* Server timezone	US/Eastern

_with browsers_:
* Firefox 54.0 64-bit (on Ubuntu 14.04)
* Firefox 58.0.1 64-bit (on Debian 9)
* Internet Explorer 11.0.9600.18163 (on Windows 7)

**Comment by ralphiee22** [comment]
Hey @mattjquinn, thanks for filing the issue. 
For the exercise, `Test Yourself: Intro to JS: Drawing & Animation` it is referencing a mastery model which we have not ported into kolibri. But we will see if we can get this done or provide a helpful error.
As far as Khan Academy Swahili channel goes, we need to update the channel on studio. You won't have to re download all the content, so once the channel is updated it should be fairly quick to get the new data. I will post here once the channel has been updated.

**Comment by mattjquinn** [comment]
Thank you.

**Comment by ralphiee22** [comment]
Hello @mattjquinn, the Khan Academy Swahili channel has been updated. If you can please test it out and let us know if there are still issues.

**Comment by mattjquinn** [comment]
I have just tested the Khan Academy Swahili channel, the issue is now resolved there as I can complete the exercises without an JS error occurring.

I did test on the Khan Academy English channel and noticed that the error remains there. As the biggest channel on Kolibri and the one with the most exercises, is there someone who can fix this issue there as well? I'd like our students to be able to access the exercises in both channels.

**Comment by mattjquinn** [comment]
I'm referring to the Intro to JS exercise I mentioned above:

Test Yourself: Intro to JS: Drawing & Animation
* URL: http://192.168.43.248:8080/learn/#/topics/c/c8c847b2b0f25797b2f2c20331620fd9
* Navigation: Channels > Khan Academy English > Computing > Computer programming > Intro to JS: Drawing and Animation > Test Yourself: Intro to JS: Drawing & Animation > Test Yourself: Intro to JS: Drawing and Animation

You said earlier "it is referencing a mastery model which we have not ported into kolibri" - it'd be ideal if this work could be done as part of this issue. I'm heading up a STEM program at the school I'm at and want to point students to some self-directed exercises such as this one.

**Comment by indirectlylit** [comment]
cc @rtibbles

**Comment by indirectlylit** [comment]
at the least we should have a user-facing error

**Comment by indirectlylit** [comment]
this should have been resolved in an update to the KA channel.

@mattjquinn would you mind letting us know if you still see this issue after updating?

thank you!
