### ISSUE TITLE
When using postgres, unable to import content nodes with long field values

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#3600]
### Observed behavior

When running Kolibri with a Postgres DB backend, trying to import content that contains a `ContentNode` with `description` or `license_description` longer than 400 chars throws an error (see below).

### Expected behavior

When we run with a SQLite backend, it [happily ignores](https://chrisbartos.com/articles/sqlite-doesnt-care-about-your-max_length/) the violation of the `max_length` attribute on these fields. Postgres is more strict (as it should be).

Expectation would be one of the following:
- Don't allow published databases to have strings > 400 char in these fields to start with. The ship's probably already sailed on that one...
- Truncate these strings during import, to respect the 400 char limit. Simple, but kind of ugly.
- Increase this limit within the Kolibri schema. This is probably preferred...

### User-facing consequences

Prevents use of Postgres backend for many content sources (e.g. KA). We now have users wanting/trying to use Postgres, and we want to do performance testing on the same.

### Errors and logs

```
INFO:kolibri.content.utils.channel_import:Importing ContentNode data
Traceback (most recent call last):
  File ".virtualenvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "kolibri/utils/cli.py", line 653, in main
    start(port, daemon=daemon)
  File "kolibri/utils/cli.py", line 265, in start
    update()
  File "kolibri/utils/cli.py", line 249, in update
    update_channel_metadata()
  File "kolibri/content/utils/annotation.py", line 38, in update_channel_metadata
    import_channel_from_local_db(channel_id)
  File "kolibri/content/utils/channel_import.py", line 383, in import_channel_from_local_db
    import_manager.import_channel_data()
  File "kolibri/content/utils/channel_import.py", line 238, in import_channel_data
    raise e
sqlalchemy.exc.DataError: (psycopg2.DataError) value too long for type character varying(400)
```

### Steps to reproduce

1. Use a custom settings file (e.g. `pg_settings.py`) with something like:

```
from __future__ import absolute_import, print_function, unicode_literals

from kolibri.deployment.default.settings.base import *  # noqa

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'NAME': 'kolibri',
    },
}
```
2. 
3. Run `kolibri manage migrate` to initialize the database.
4. Run `kolibri manage importchannel network 1ceff53605e55bef987d88e0908658c5` to attempt to import a channel with fields that are too long.

### Context

Commit ddeed38c764d9f218ea067b4aeb3d5d514db8e96 on latest release-v0.9.x

**Comment by jamalex** [comment]
Looks as if these fields are `TextField` (no length limit) on Studio:

https://github.com/learningequality/studio/blob/develop/contentcuration/contentcuration/models.py#L573
https://github.com/learningequality/studio/blob/develop/contentcuration/contentcuration/models.py#L614

Going to write some regression tests in Kolibri, and then try switching the fields there to `TextField` as well.
