### ISSUE TITLE
Unable to export channel to USB

### ISSUE THREAD

**Issue by ralphiee22** [learningequality/kolibri#3641]
### Observed behavior

Can't export channel to a USB.

### Expected behavior

Able to export channel onto USB.

### User-facing consequences

Can't do sneakernet 👎 

### Errors and logs

```
ERROR 2018-05-10 14:22:32,089 exception Internal Server Error: /api/tasks/localdrive/
Traceback (most recent call last):
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/tasks/api.py", line 325, in localdrive
    drives = get_mounted_drives_with_channel_info()
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/utils/channels.py", line 94, in get_mounted_drives_with_channel_info
    drive.metadata["channels"] = get_channels_for_data_folder(drive.datafolder) if drive.datafolder else []
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/utils/channels.py", line 73, in get_channels_for_data_folder
    for path in enumerate_content_database_file_paths(get_content_database_dir_path(datafolder)):
  File "/Users/rafaelaguayo/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/utils/paths.py", line 43, in get_content_database_dir_path
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/KOLIBRI_DATA'
```

### Steps to reproduce

Try to export a channel onto a USB.

### Context

Kolibri 0.10.0 (develop)

**Comment by lyw07** [comment]
looks like it's similar to this issue: https://github.com/learningequality/kolibri/issues/3274? I will take a look at it

**Comment by ralphiee22** [comment]
Could be, but I was unable to replicate on kolibri 0.9.

**Comment by lyw07** [comment]
@ralphiee22 What is the path of the USB? Is it root?

**Comment by lyw07** [comment]
The issue is introduced by https://github.com/learningequality/kolibri/blob/develop/kolibri/content/utils/paths.py#L43 when the application checks the databases folder of each external drive https://github.com/learningequality/kolibri/blob/develop/kolibri/content/utils/channels.py#L73. Will work on this today.

**Comment by jonboiser** [comment]
This also happens when attempting to import from a localdrive.

**Comment by indirectlylit** [comment]
whoops, sounds like there's still an error

**Comment by lyw07** [comment]
@indirectlylit sorry what is the error now?

**Comment by jonboiser** [comment]
Nothing to do with the drivelist endpoint. This line

https://github.com/learningequality/kolibri/blob/develop/kolibri/content/utils/channels.py#L82

should have `root: channel.root_id`.

With the current code, initiating a transfer leads to a crash.

**Comment by jonboiser** [comment]
Now, I just tried it again, and it's assuming the `channelmetadata` table has a `root_pk` column. Not sure why it shifts like this.

**Comment by lyw07** [comment]
I guess it's because it's reading from source data, which contains the `root_pk` as a table column. It doesn't go through schema mapping, so it's `root_pk` instead of `root_id`?

**Comment by lyw07** [comment]
this issue should be fixed by https://github.com/learningequality/kolibri/pull/3658 and https://github.com/learningequality/kolibri/pull/3724, so closing it now.

**Comment by indirectlylit** [comment]
thanks!
