### ISSUE TITLE
versioning logic is preventing legitimate build from running

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3678]
### Observed behavior

Builds produced by #3670 won't run

### Expected behavior

* Builds should run
* version.py should log warnings but not raise assertion errors

### User-facing consequences

cannot deploy a demo server with contents of PR

### Errors and logs

```
Traceback (most recent call last):
  File "/Users/d/Downloads/k.pex/.bootstrap/_pex/pex.py", line 365, in execute
  File "/Users/d/Downloads/k.pex/.bootstrap/_pex/pex.py", line 293, in _wrap_coverage
  File "/Users/d/Downloads/k.pex/.bootstrap/_pex/pex.py", line 325, in _wrap_profiling
  File "/Users/d/Downloads/k.pex/.bootstrap/_pex/pex.py", line 408, in _execute
  File "/Users/d/Downloads/k.pex/.bootstrap/_pex/pex.py", line 466, in execute_entry
  File "/Users/d/Downloads/k.pex/.bootstrap/_pex/pex.py", line 471, in execute_module
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 170, in run_module
    mod_name, loader, code, fname = _get_module_details(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 109, in _get_module_details
    return _get_module_details(pkg_main_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 101, in _get_module_details
    loader = get_loader(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 464, in get_loader
    return find_loader(fullname)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 474, in find_loader
    for importer in iter_importers(fullname):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pkgutil.py", line 430, in iter_importers
    __import__(pkg)
  File "/Users/d/.pex/install/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl.91d012d9f9af841a8b424cdad441ab36ba71fa00/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl/kolibri/__init__.py", line 22, in <module>
    __version__ = str(get_version(VERSION))
  File "/Users/d/.pex/install/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl.91d012d9f9af841a8b424cdad441ab36ba71fa00/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl/kolibri/utils/lru_cache.py", line 137, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/d/.pex/install/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl.91d012d9f9af841a8b424cdad441ab36ba71fa00/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl/kolibri/utils/version.py", line 394, in get_version
    return get_prerelease_version(version)
  File "/Users/d/.pex/install/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl.91d012d9f9af841a8b424cdad441ab36ba71fa00/kolibri-0.10.0.dev3.dev_git_26_g9f3e263-py2.py3-none-any.whl/kolibri/utils/version.py", line 365, in get_prerelease_version
    version_file_base
AssertionError: kolibri/VERSION file inconsistent with kolibri.__version__.
__version__ is: (0, 10, 0, u'alpha', 0), file says: 0.10.0.dev3.dev+git-26-g9f3e263

0.10.0.dev0 should start with 0.10.0.dev3.dev+git-26-g9f3e263
```

### Steps to reproduce

* Create a build of 9f3e2634791b768f79944de568c802717995a0cd or download [this pex](https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri-buildkite-build-3670-6432-kolibri-0.10.0.dev3.dev_git-26-g9f3e263.pex?generation=1526521467667405&alt=media)
* Try to run

### Context

possibly related? #3251

**Comment by benjaoming** [comment]
This is dangerous, why is it expecting `0.10.0.dev3` ?

**Comment by indirectlylit** [comment]
> why is it expecting 0.10.0.dev3 ?

I assume because the nearest parent tag it found was alpha3

**Comment by indirectlylit** [comment]
Chronology of what happened:

* The feature branch was based off of `develop`. Builds were working. The most recent tag was `v0.10.0-alpha3`
* I merged the latest `develop` into the feature branch, which cause the builds to start failing.  One of the commits that got merged was tagged with `v0.10.0-alpha4`
* I tried rebasing on `develop` and force-pushing to the feature branch. This caused the build to work again, but required rewriting history on a shared branch

It seems as though:

1. the logic for identifying the most recent ancestor tag doesn't work because it references `dev3`, which I assume maps to `alpha3`
2. The validation message (`0.10.0.dev0 should start with 0.10.0.dev3.dev+git-26-g9f3e263`) is inaccurate/misleading

**Comment by indirectlylit** [comment]
Note: In the process of rebasing and re-writing the branch history, I deleted commit cc2c3d82d1d288b922f9145976c4c1f8b86db795 which is where I had switched from assertions to warning logs. However, I believe that logging warnings is more appropriate than raising assertions in application code. We should not kill the application at runtime because of versioning logic.

**Comment by benjaoming** [comment]
> `0.10.0.dev0 should start with 0.10.0.dev3.dev+git-26-g9f3e263`

Thanks for elaborating!

It wrongly swaps in `dev` for `alpha` (maybe because `alpha0` should normally be `dev`, whilst `alpha1` should remain unaltered).

The correct version for this release is `0.10.0a3.dev+git-26-g9f3e263`.

**Comment by indirectlylit** [comment]
Note that I was able to work around this issue, so it is not critical to fix

**Comment by indirectlylit** [comment]
another case... --^

**Comment by benjaoming** [comment]
> forgot to bump version number which caused failed build after already tagging.

@indirectlylit but this is more a case that raising AssertionError *is* the way to go :)

**Comment by indirectlylit** [comment]
definitely debatable, but we'll save that for another day. This is why I consider #3251 so important
