### ISSUE TITLE
unhandled exception - global name 'ContentNode' is not defined

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3873]
### Observed behavior

observed in logs of beta server:

```
Traceback (most recent call last):
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/rest_framework/backends.py", line 54, in filter_queryset
    return filter_class(request.query_params, queryset=queryset, request=request).qs
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/rest_framework/filterset.py", line 50, in qs
    return super(FilterSet, self).qs
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/filterset.py", line 220, in qs
    qs = filter_.filter(qs, value)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/filters.py", line 713, in __call__
    return self.method(qs, self.f.field_name, value)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/content/api.py", line 221, in filter_popular
    .filter(content_id__in=ContentNode.objects.values_list('content_id', flat=True).distinct()) \
NameError: global name 'ContentNode' is not defined
```

### Expected behavior

…

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

…

### Context

…

**Comment by ralphiee22** [comment]
Again this was due to me and jamie messing with the beta server.
