### ISSUE TITLE
AssertionError: 'img' is not a valid content storage filename

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3874]
### Observed behavior

These errors appeared over a hundred times on the beta server

### Expected behavior

no unhandled errors

### User-facing consequences

unknown

### Errors and logs

```
ERROR 2018-05-17 21:11:14,694 exception Internal Server Error: /zipcontent/img/more_gold_24px.svg
Traceback (most recent call last):
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/views.py", line 24, in get
    zipped_path = get_content_storage_file_path(zipped_filename)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/utils/paths.py", line 66, in get_content_storage_file_path
    assert VALID_STORAGE_FILENAME.match(filename), "'{}' is not a valid content storage filename".format(filename)
AssertionError: 'img' is not a valid content storage filename
ERROR 2018-05-17 21:11:14,726 exception Internal Server Error: /zipcontent/img/pdff.png
Traceback (most recent call last):
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/dist/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/views.py", line 24, in get
    zipped_path = get_content_storage_file_path(zipped_filename)
  File "/var/www/.pex/install/kolibri-0.10.0.dev3-py2.py3-none-any.whl.bb49be01e5773117e7cc586e1554f69a449a3672/kolibri-0.10.0.dev3-py2.py3-none-any.whl/kolibri/content/utils/paths.py", line 66, in get_content_storage_file_path
    assert VALID_STORAGE_FILENAME.match(filename), "'{}' is not a valid content storage filename".format(filename)
AssertionError: 'img' is not a valid content storage filename
ERROR 2018-05-17 21:11:25,358 exception Internal Server Error: /zipcontent/img/right.png
```

### Steps to reproduce

unknown

### Context

0.10.0

**Comment by jamalex** [comment]
This is because there's an HTML5 zip file that hasn't had its internal paths properly adjusted. It likely has a path like `../img/more_gold_24px.svg` in it. Not a Kolibri issue (though it would be nice if we could force the iframe sandbox to not allow paths above a certain level, but don't think we can, easily.

**Comment by indirectlylit** [comment]
@rtibbles I believe you may have worked on this recently?

**Comment by rtibbles** [comment]
This should now return a more semantic 404, yes.
