### ISSUE TITLE
OperationalError: only a single result allowed for a SELECT that is part of an expression

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3875]
### Observed behavior

unhandled error observed on beta server

### Expected behavior

no unhandled error

### User-facing consequences

unknown

### Errors and logs

```
ERROR 2018-06-23 00:27:05,457 exception Internal Server Error: /api/contentnode/
Traceback (most recent call last):
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/rest_framework/backends.py", line 54, in filter_queryset
    return filter_class(request.query_params, queryset=queryset, request=request).qs
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/rest_framework/filterset.py", line 50, in qs
    return super(FilterSet, self).qs
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/filterset.py", line 220, in qs
    qs = filter_.filter(qs, value)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django_filters/filters.py", line 713, in __call__
    return self.method(qs, self.f.field_name, value)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/content/api.py", line 228, in filter_popular
    cache.set(cache_key, most_popular, 60 * 10)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/core/cache/backends/locmem.py", line 75, in set
    pickled = pickle.dumps(value, pickle.HIGHEST_PROTOCOL)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 202, in __getstate__
    self._fetch_all()
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/www/.pex/install/kolibri-0.10.0b4-py2.py3-none-any.whl.ab4dd96ad3b5fc5918fc53d163a50fb24bcf54ec/kolibri-0.10.0b4-py2.py3-none-any.whl/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: only a single result allowed for a SELECT that is part of an expression
```

### Steps to reproduce

unknown

### Context

0.10.0

**Comment by ralphiee22** [comment]
oh me and @jamalex were messing with the beta server. This was a product of our changing some code in the pex.
