### ISSUE TITLE
deprovision 'server running' check doesn't work on devserver

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#3902]
### Observed behavior

I was able to deprovision while the devserver was running, bypassing this check: https://github.com/learningequality/kolibri/pull/3893/files#diff-65222f81f076190d58d35032f009b818R62

Then when refreshing, you get the flapping bird of death:

![image](https://user-images.githubusercontent.com/2367265/41941022-933f48f0-794f-11e8-985f-a62726811650.png)

### Expected behavior

deprovision command should not run if the devserver is currently running

### User-facing consequences

confusion for devs if they use the deprovision command

### Errors and logs

```
INFO     "GET /user/ HTTP/1.1" 200 9245
INFO:django.server:"GET /user/ HTTP/1.1" 200 9245
ERROR    Internal Server Error: /api/facilitydataset/
Traceback (most recent call last):
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 765, in data
    ret = super(ListSerializer, self).data
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/rest_framework/serializers.py", line 683, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    sql, params = self.as_sql()
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 441, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 373, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/sql/where.py", line 79, in as_sql
    sql, params = compiler.compile(child)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 373, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/lookups.py", line 170, in as_sql
    rhs_sql, rhs_params = self.process_rhs(compiler, connection)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/lookups.py", line 103, in process_rhs
    return self.get_db_prep_lookup(value, connection)
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/django/db/models/lookups.py", line 196, in get_db_prep_lookup
    [get_db_prep_value(value, connection, prepared=True)]
  File "/Users/d/Projects/learning_equality/repos/k010x/.venv/lib/python2.7/site-packages/morango/utils/uuids.py", line 38, in get_db_prep_value
    value = uuid.UUID(value)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 136, in __init__
    raise ValueError('badly formed hexadecimal UUID string')
ValueError: badly formed hexadecimal UUID string
ERROR    "GET /api/facilitydataset/?facility_id&1530049415187=1530049415187 HTTP/1.1" 500 7179
ERROR:django.server:"GET /api/facilitydataset/?facility_id&1530049415187=1530049415187 HTTP/1.1" 50
```

### Steps to reproduce

* start devserver in a terminal
* go through the setup wizard. keep the browser open and logged in
* in another terminal, run `kolibri manage deprovision`
* refresh browser

### Context

0.10.0

introduced in #3893

**Comment by rtibbles** [comment]
Fixed in develop - devserver now uses default server run behaviour.
