### ISSUE TITLE
Kolibri ImportError: No module named functools_lru_cache

### ISSUE THREAD

**Issue by arky** [learningequality/kolibri#4031]
Kolibri throws errors about missing 'functools_lru_cache' module. 

kolibri --version
Traceback (most recent call last):
  File "/usr/local/bin/kolibri", line 7, in <module>
    from kolibri.utils.cli import main
  File "/usr/local/lib/python2.7/dist-packages/kolibri/utils/cli.py", line 24, in <module>
    from . import server  # noqa
  File "/usr/local/lib/python2.7/dist-packages/kolibri/utils/server.py", line 6, in <module>
    import cherrypy
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/cherrypy/__init__.py", line 76, in <module>
    from . import _cprequest, _cpserver, _cptree, _cplogging, _cpconfig
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/cherrypy/_cprequest.py", line 11, in <module>
    from cherrypy import _cpreqbody
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/cherrypy/_cpreqbody.py", line 135, in <module>
    import cheroot.server
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/cheroot/server.py", line 66, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache

# Workaround 

$ pip install backports.functools_lru_cache
Collecting backports.functools_lru_cache
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Installing collected packages: backports.functools-lru-cache
Successfully installed backports.functools-lru-cache-1.5

$ kolibri --version
0.10.0
root@box:/opt/iiab/iiab# 

$ pip show kolibri
Name: kolibri
Version: 0.10.0
Summary: Kolibri - the offline app for universal education
Home-page: https://github.com/learningequality/kolibri
Author: Learning Equality
Author-email: info@learningequality.org
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 

$ python --version
Python 2.7.15

Debian 10 / Buster / Testing

**Comment by lyw07** [comment]
This error is caused by the cheroot version > 6.1.2, since we didn't pin the version of it in 0.10.0. We have had the fix in the current 0.10.x branch and will include the fix in 0.10.1 release.

**Comment by arky** [comment]
Thanks @lyw07 for shedding light on this issue.  For now I'll implement a check for correct version cheroot in Internet in a box installation script.

**Comment by lyw07** [comment]
@arky thank you for reporting this issue! Please let me know if it still doesn't work.
