### ISSUE TITLE
module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#4058]
### Observed behavior

This is an error reported by our user:
Getting a cryptography/OpenSSL related error when running any kolibri command on Odroid c2, with Ubuntu 16.04. 
The error traceback is in the `Errors and logs` section.

### Expected behavior

Users should be able to run any kolibri command successfully.

### User-facing consequences

Users cannot use kolibri

### Errors and logs

```
Traceback (most recent call last):

  File "/usr/bin/kolibri", line 9, in <module>

    load_entry_point('kolibri==0.10.0', 'console_scripts', 'kolibri')()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point

    return get_distribution(dist).load_entry_point(group, name)

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point

    return ep.load()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load

    return self.resolve()

  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 24, in <module>

    from . import server  # noqa

  File "/usr/lib/python3/dist-packages/kolibri/utils/server.py", line 8, in <module>

    import requests

  File "/usr/lib/python3/dist-packages/kolibri/dist/requests/__init__.py", line 84, in <module>

    from urllib3.contrib import pyopenssl

  File "/usr/lib/python3/dist-packages/kolibri/dist/urllib3/contrib/pyopenssl.py", line 46, in <module>

    import OpenSSL.SSL

  File "/usr/lib/python3/dist-packages/kolibri/dist/OpenSSL/__init__.py", line 8, in <module>

    from OpenSSL import crypto, SSL

  File "/usr/lib/python3/dist-packages/kolibri/dist/OpenSSL/SSL.py", line 115, in <module>

    if _lib.Cryptography_HAS_SSL_ST:

AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'
```

### Steps to reproduce

The following steps can reproduce this error from a working kolibri instance
1. Have a fresh installation of kolibri 0.10 on any machine
2. run `kolibri shell` to see if a warning saying `no c extensions exist` appears
3. install cryptography 1.2.3 in your current environment through `pip install cryptography==1.2.3`
4. If the warning appears, run any kolibri command again. The error should appear
5. If the warning doesn't show up, then in the `kolibri shell`, do `import cryptography` and `cryptography.__file__` to find out where your cryptography module exists and either delete it or move it to somewhere else. For example, if the result of `cryptography.__file__` is `kolibri/dist/cext/cp35/Linux/x86_64/cryptography/__init__.py`, then remove the entire folder `kolibri/dist/cext/cp35/Linux/x86_64/`. After that, run any kolibri command will lead to the error.

### Context

 * Kolibri version: 0.10.0
 * Operating system: Ubuntu 16.04 on Odroid c2 (Linux-aarch64)

**Comment by benjaoming** [comment]
Fixed in #4059 and released in 0.10.1
