### ISSUE TITLE
kolibri manage dbrestore broken in 0.10

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4113]
### Observed behavior

It seems that it's impossible to run `kolibri manage dbrestore` because another transaction is already running. Suspecting that a db connection is being prematurely opened during load time.

### Expected behavior

Command runs without connecting to database. This affects several commands as explained in #4112

### User-facing consequences

Users cannot restore from backups.

### Errors and logs

```
pi@raspberrypi:~ $ kolibri manage dbrestore /mnt/data/.kolibri/backups/db-v0.10.0_2018-08-06_16-09-09.dump 
WARNING:root:No C Extensions available for this platform.

INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO:kolibri.core.apps:Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Beginning database restore
INFO:kolibri.core.deviceadmin.management.commands.dbrestore:Beginning database restore
INFO     Using backup file: /mnt/data/.kolibri/backups/db-v0.10.0_2018-08-06_16-09-09.dump
INFO:kolibri.core.deviceadmin.management.commands.dbrestore:Using backup file: /mnt/data/.kolibri/backups/db-v0.10.0_2018-08-06_16-09-09.dump
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
sqlite3.OperationalError: cannot start a transaction within a transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/kolibri", line 9, in <module>
    load_entry_point('kolibri==0.10.1', 'console_scripts', 'kolibri')()
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 635, in main
    manage(command, args=django_args)
  File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 425, in manage
    execute_from_command_line(argv=argv)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/deviceadmin/management/commands/dbrestore.py", line 84, in handle
    dbrestore(use_backup)
  File "/usr/lib/python3/dist-packages/kolibri/core/deviceadmin/utils.py", line 148, in dbrestore
    DatabaseIDModel.objects.create()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/models.py", line 36, in create
    with transaction.atomic():
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/transaction.py", line 184, in __enter__
    connection.set_autocommit(False, force_begin_transaction_with_broken_autocommit=True)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/base/base.py", line 409, in set_autocommit
    self._start_transaction_under_autocommit()
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py", line 309, in _start_transaction_under_autocommit
    self.cursor().execute("BEGIN")
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/sqlite3/base.py", line 326, in execute
    return Database.Cursor.execute(self, query)
django.db.utils.OperationalError: cannot start a transaction within a transaction

```

### Steps to reproduce

Restore from a previous backup.

### Context

Tested on 0.10.1 final release, on a Raspberry Pi.

**Comment by benjaoming** [comment]
One possible way to troubleshoot this, would be to mock `django.db.connections` and fail if any database connections are opened while loading `kolibri.utils.cli` and calling `restore`.

**Comment by benjaoming** [comment]
I'm going to have to delay this, if we want 0.10.2 out... but I think we need a 0.10.3 milestone, anyways, given that there is a long time until 0.11!

**Comment by indirectlylit** [comment]
Do we actually need to maintain `dbrestore`? (My understanding is that it was created to address the malformed DB issues, but doesn't actually do that.) We could potentially just remove the command.

**Comment by benjaoming** [comment]
@indirectlylit haven't investigated the cause of this yet, and if the cause is that we have premature db connections, then it's not even the command that's broken.

**Comment by benjaoming** [comment]
Cannot reproduce this on 0.13.0b3
