### ISSUE TITLE
Old versions of pkg_resources have issues with advanced version strings

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#4215]
### Observed behavior

In this report from @indirectlylit, we find an issue running Kolibri with `pkg_resources` when the version string is more advanced than usual. The reported case is about a pre-release `0.11.0a4.dev0+git.193.gd88af03c`.

Ref: learningequality/kolibri#4056

### Expected behavior

There should be a compatible behavior that falls back instead of giving exceptions for these older versions, since they are usually part of the system's stdlib.

### User-facing consequences

Kolibri will not run pre-releases.

### Errors and logs

```
vagrant@vagrant-ubuntu-trusty-64:~$ 
vagrant@vagrant-ubuntu-trusty-64:~$ wget -O kolibri.deb 'https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri-buildkite-build-4056-7398-kolibri_0.11.0a4.dev0%2Bgit.193.gd88af03c-0ubuntu1_all.deb?generation=1532864592334507&alt=media'
--2018-09-04 14:57:53--  https://www.googleapis.com/download/storage/v1/b/le-downloads/o/kolibri-buildkite-build-4056-7398-kolibri_0.11.0a4.dev0%2Bgit.193.gd88af03c-0ubuntu1_all.deb?generation=1532864592334507&alt=media
Resolving www.googleapis.com (www.googleapis.com)... 172.217.4.138, 172.217.4.170, 172.217.5.74, ...
Connecting to www.googleapis.com (www.googleapis.com)|172.217.4.138|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38157036 (36M) [application/x-debian-package]
Saving to: ‘kolibri.deb’

100%[============================================================================================================================================================>] 38,157,036  20.4MB/s   in 1.8s   

2018-09-04 14:57:55 (20.4 MB/s) - ‘kolibri.deb’ saved [38157036/38157036]

vagrant@vagrant-ubuntu-trusty-64:~$ 
vagrant@vagrant-ubuntu-trusty-64:~$ sudo dpkg -i kolibri.deb 
Selecting previously unselected package kolibri.
(Reading database ... 63130 files and directories currently installed.)
Preparing to unpack kolibri.deb ...
cat: /etc/default/kolibri: No such file or directory
Unpacking kolibri (0.11.0a4.dev0+git.193.gd88af03c-0ubuntu1) ...
dpkg: dependency problems prevent configuration of kolibri:
 kolibri depends on python3-pkg-resources; however:
  Package python3-pkg-resources is not installed.

dpkg: error processing package kolibri (--install):
 dependency problems - leaving unconfigured
Processing triggers for ureadahead (0.100.0-16) ...
Errors were encountered while processing:
 kolibri
vagrant@vagrant-ubuntu-trusty-64:~$ 
vagrant@vagrant-ubuntu-trusty-64:~$ sudo apt-get install python3-pkg-resources
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  python3-setuptools
The following NEW packages will be installed:
  python3-pkg-resources
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 31.7 kB of archives.
After this operation, 157 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-pkg-resources all 3.3-1ubuntu2 [31.7 kB]
Fetched 31.7 kB in 0s (50.0 kB/s)          
Selecting previously unselected package python3-pkg-resources.
(Reading database ... 76269 files and directories currently installed.)
Preparing to unpack .../python3-pkg-resources_3.3-1ubuntu2_all.deb ...
Unpacking python3-pkg-resources (3.3-1ubuntu2) ...
Setting up python3-pkg-resources (3.3-1ubuntu2) ...
Setting up kolibri (0.11.0a4.dev0+git.193.gd88af03c-0ubuntu1) ...
 Removing any system startup links for /etc/init.d/kolibri ...
 Adding system startup for /etc/init.d/kolibri ...
   /etc/rc0.d/K20kolibri -> ../init.d/kolibri
   /etc/rc1.d/K20kolibri -> ../init.d/kolibri
   /etc/rc6.d/K20kolibri -> ../init.d/kolibri
   /etc/rc2.d/S20kolibri -> ../init.d/kolibri
   /etc/rc3.d/S20kolibri -> ../init.d/kolibri
   /etc/rc4.d/S20kolibri -> ../init.d/kolibri
   /etc/rc5.d/S20kolibri -> ../init.d/kolibri
Traceback (most recent call last):
  File "/usr/bin/kolibri", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 595, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", 'kolibri==0.11.0a4.dev0+git.193.gd88af03c', 'at', '+git.193.gd88af03c')
invoke-rc.d: initscript kolibri, action "start" failed.
Processing triggers for ureadahead (0.100.0-16) ...
vagrant@vagrant-ubuntu-trusty-64:~$ 
vagrant@vagrant-ubuntu-trusty-64:~$ 
```

### Steps to reproduce

Fetch an older version of pkg_resources, in this case it was 3.3.

### Context

Automated .deb build w/ Ubuntu 14.04 pkg_resources

**Comment by benjaoming** [comment]
I have raised a proposal to drop Trusty support entirely in the .deb.

`pip install` methods should be able to get around this by requiring a more recent version of `setuptools`.

**Comment by rtibbles** [comment]
I don't think we can actually fix this - we just need to be aware that we can't run arbitrary builds on 14.04.
