### ISSUE TITLE
Coach page has error on Xubuntu 17.04(32 bit)

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#4385]
### Observed behavior
When I click Coach page, there is an error message in the top. I checked the Lesson, Exam, Recent and Channel page. But error message still there, no resources, no exercises, no view can shown in Recent and Channel page.

![coach_page](https://user-images.githubusercontent.com/38421180/46718385-9c5be500-cc9d-11e8-8860-8fdf18cde970.png)

![lesson](https://user-images.githubusercontent.com/38421180/46718397-a7af1080-cc9d-11e8-8fee-0622e05b865c.png)

![channel](https://user-images.githubusercontent.com/38421180/46718428-b85f8680-cc9d-11e8-99cd-d0f3b898a0e9.png)

### Errors and logs
```
GET 
XHR 
http://127.0.0.1:8080/api/channel/ [HTTP/1.1 500 Internal Server Error 92ms]
Headers
Params
Response
Cookies
Call Stack
Content-LanguageenContent-Length27Content-Typetext/htmlDateWed, 10 Oct 2018 06:37:16 GMTServer0.0.0.0VaryAccept-Language, CookieX-Frame-OptionsSAMEORIGIN
Acceptapplication/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5Connectionkeep-aliveContent-Typeapplication/jsonCookiecsrftoken=kBQCvCtcsCGa1ZTfLzh62CmiAV5NwLgQKnuzNmKSIWI2MMqN0SOwquGjeG9euJkQ; kolibri=osmjokmzc74e7d87abzrltwyd3l9lg5xHost127.0.0.1:8080Refererhttp://127.0.0.1:8080/coach/User-AgentMozilla/5.0 (X11; Ubuntu; Linux i686; rv:52.0) Gecko/20100101 Firefox/52.0X-CSRFTokenkBQCvCtcsCGa1ZTfLzh62CmiAV5NwLgQKnuzNmKSIWI2MMqN0SOwquGjeG9euJkQ

[ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Object { request: Object, url: "/api/channel/?available=true&conten…", raw: XMLHttpRequest, status: Object, headers: Object, entity: "<h1>Server Error (500)</h1>" }  default_frontend-0.10.3b3.js:1:7809
	kolibriGlobal</</b.prototype.fetch/o</</< http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:1:7809
	z http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:3066
	$ http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:2712
	kolibriGlobal</</</o</</E.prototype.when http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:6940
	kolibriGlobal</</</o</</x.prototype.run http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:5777
	kolibriGlobal</</r</t.prototype._drain http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:91:537
	t/this.drain http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:91:204
	e http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:38:533
GET 
XHR 
http://127.0.0.1:8080/api/channel/ [HTTP/1.1 500 Internal Server Error 109ms]
Headers
Params
Response
Cookies
Call Stack
Content-LanguageenContent-Length27Content-Typetext/htmlDateWed, 10 Oct 2018 06:41:48 GMTServer0.0.0.0VaryAccept-Language, CookieX-Frame-OptionsSAMEORIGIN
Acceptapplication/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2Accept-Encodinggzip, deflateAccept-Languageen-US,en;q=0.5Connectionkeep-aliveContent-Typeapplication/jsonCookiecsrftoken=kBQCvCtcsCGa1ZTfLzh62CmiAV5NwLgQKnuzNmKSIWI2MMqN0SOwquGjeG9euJkQ; kolibri=osmjokmzc74e7d87abzrltwyd3l9lg5xHost127.0.0.1:8080Refererhttp://127.0.0.1:8080/coach/User-AgentMozilla/5.0 (X11; Ubuntu; Linux i686; rv:52.0) Gecko/20100101 Firefox/52.0X-CSRFTokenkBQCvCtcsCGa1ZTfLzh62CmiAV5NwLgQKnuzNmKSIWI2MMqN0SOwquGjeG9euJkQ
               
[ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Object { request: Object, url: "/api/channel/?available=true&has_ex…", raw: XMLHttpRequest, status: Object, headers: Object, entity: "<h1>Server Error (500)</h1>" }  default_frontend-0.10.3b3.js:1:7809
	kolibriGlobal</</b.prototype.fetch/o</</< http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:1:7809
	z http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:3066
	$ http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:2712
	kolibriGlobal</</</o</</E.prototype.when http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:6940
	kolibriGlobal</</</o</</x.prototype.run http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:90:5777
	kolibriGlobal</</r</t.prototype._drain http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:91:537
	t/this.drain http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:91:204
	e http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:38:533
[ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Object { request: Object, url: "/api/contentnode/?ids=&contentCache…", raw: XMLHttpRequest, status: Object, headers: Object, entity: "<h1>Server Error (500)</h1>" }  default_frontend-0.10.3b3.js:1:7809
TypeError: n is undefined
Stack trace:
E@http://127.0.0.1:8080/static/coach_module/coach_module-0.10.3b3.js:1:34225
a/c<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:18:2504
kolibriGlobal</</Io.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
kolibriGlobal</</Io.prototype.evaluate@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:6648
a/u@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:18:2561
r@http://127.0.0.1:8080/static/coach_module/coach_module-0.10.3b3.js:1:226566
kolibriGlobal</</</t.prototype._render@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:10437
Mt/r@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15586
kolibriGlobal</</Io.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
kolibriGlobal</</Io@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5579
Mt@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15602
kolibriGlobal</</Pe.prototype.$mount@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:25995
kolibriGlobal</</Po.init@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:7169
u@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16725
c@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16354
d@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:17323
c@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16469
x@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:18923
O@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:19689
kolibriGlobal</</Di</<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:20993
kolibriGlobal</</</t.prototype._update@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:9399
Mt/r@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15576
kolibriGlobal</</Io.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
kolibriGlobal</</Io.prototype.run@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:6382
Bt@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:17015
ct/<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:11123
at@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:10950
kolibriGlobal</A/</<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:78:95749
kolibriGlobal</A/<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:78:95619
kolibriGlobal</t.exports/u@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:54786
  default_frontend-0.10.3b3.js:8:10856
	it http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:10856
	ot http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:10778
	rt http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:10644
	kolibriGlobal</</</t.prototype._render http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:10486
	Mt/r http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15586
	kolibriGlobal</</Io.prototype.get http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
	kolibriGlobal</</Io http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5579
	Mt http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15602
	kolibriGlobal</</Pe.prototype.$mount http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:25995
	kolibriGlobal</</Po.init http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:7169
	u http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16725
	c http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16354
	d http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:17323
	c http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16469
	x http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:18923
	O http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:19689
	kolibriGlobal</</Di</< http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:20993
	kolibriGlobal</</</t.prototype._update http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:9399
	Mt/r http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15576
	kolibriGlobal</</Io.prototype.get http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
	kolibriGlobal</</Io.prototype.run http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:6382
	Bt http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:17015
	ct/< http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:11123
	at http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:10950
	kolibriGlobal</A/</< http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:78:95749
	kolibriGlobal</A/< http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:78:95619
	kolibriGlobal</t.exports/u http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:54786
[ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Object { request: Object, url: "/api/contentnode/?ids=&contentCache…", raw: XMLHttpRequest, status: Object, headers: Object, entity: "<h1>Server Error (500)</h1>" }  default_frontend-0.10.3b3.js:1:7809
TypeError: n is undefined
Stack trace:
E@http://127.0.0.1:8080/static/coach_module/coach_module-0.10.3b3.js:1:34225
a/c<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:18:2504
kolibriGlobal</</Io.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
kolibriGlobal</</Io.prototype.evaluate@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:6648
a/u@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:18:2561
r@http://127.0.0.1:8080/static/coach_module/coach_module-0.10.3b3.js:1:226566
kolibriGlobal</</</t.prototype._render@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:10437
Mt/r@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15586
kolibriGlobal</</Io.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
kolibriGlobal</</Io@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5579
Mt@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15602
kolibriGlobal</</Pe.prototype.$mount@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:25995
kolibriGlobal</</Po.init@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:7169
u@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16725
c@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16354
d@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:17323
c@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:16469
x@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:18923
O@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:19689
kolibriGlobal</</Di</<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:20993
kolibriGlobal</</</t.prototype._update@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:9399
Mt/r@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:15576
kolibriGlobal</</Io.prototype.get@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:5649
kolibriGlobal</</Io.prototype.run@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:6382
Bt@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:17015
ct/<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:11123
at@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:8:10950
kolibriGlobal</A/</<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:78:95749
kolibriGlobal</A/<@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:78:95619
kolibriGlobal</t.exports/u@http://127.0.0.1:8080/static/default_frontend/default_frontend-0.10.3b3.js:13:54786
  default_frontend-0.10.3b3.js:8:10856

```
[kolibri.log](https://github.com/learningequality/kolibri/files/2464125/kolibri.log)

### Context
* Kolibri version: 0.10.3b3
 * Operating system: Xubuntu 17.04 (32-bit)
 * Browser: Firefox 52.0.1 (32-bit)

**Comment by indirectlylit** [comment]
cc @ralphiee22 mind taking a look at this?

**Comment by benjaoming** [comment]
This should be the relevant exception from the log?

```
ERROR 2018-10-10 17:54:46,996 exception Internal Server Error: /api/contentnode/
Traceback (most recent call last):
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/content/api.py", line 65, in wrapper_func
    patch_response_headers(response, cache_timeout=timeout)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/utils/cache.py", line 266, in patch_response_headers
    response['Expires'] = http_date(time.time() + cache_timeout)
  File "/home/julius/.pex/install/kolibri-0.10.3b3-py2.py3-none-any.whl.a8027528fe6655464da378f4ac22bf50fd42ffd2/kolibri-0.10.3b3-py2.py3-none-any.whl/kolibri/dist/django/utils/http.py", line 144, in http_date
    return formatdate(epoch_seconds, usegmt=True)
  File "/usr/lib/python2.7/email/utils.py", line 161, in formatdate
    now = time.gmtime(timeval)
ValueError: timestamp out of range for platform time_t
```

**Comment by benjaoming** [comment]
@mrpau-julius For 0.10.3-beta3, can you reproduce this on other platforms? Or does it only happen on 32 bit Xubuntu 17.04?

**Comment by indirectlylit** [comment]
Also curious if this happens in 0.10.2?

**Comment by mrpau-julius** [comment]
@benjaoming only in 32 bit Xubuntu 17.04. I tried this on windows 10 and 7 both 32/64 bit. But this error not exists.

**Comment by mrpau-julius** [comment]
@indirectlylit This issue is not exists on 0.10.2. I finished tested this day.

**Comment by benjaoming** [comment]
It must be related to 32 bit stuff - @mrpau-julius can you test this again on your Xubuntu 17.04 32bit, but using an asset from #4400 ? Thanks :)

Great find btw!

**Comment by mrpau-julius** [comment]
@benjaoming sure I will test it now.

**Comment by benjaoming** [comment]
Fixed in #4400

**Comment by mrpau-julius** [comment]
@benjaoming This issues exists in kolibri 0.11.0beta1, cannot create resources, and exam. The recent and channel page has error display("Sorry! Something went wrong! ").

[kolibri.log](https://github.com/learningequality/kolibri/files/2478390/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/2478391/server.log)

**Comment by benjaoming** [comment]
@mrpau-julius - yes, current 0.10.x branch hasn't been merged upwards yet. I'll get to that ASAP!
