### ISSUE TITLE
analytics error: 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4414]
### Observed behavior

Error occurs while Kolibri is trying to send stats

### Expected behavior

No error

### User-facing consequences

Analytics not recorded

### Errors and logs

```
INFO:kolibri.core.analytics.management.commands.ping:Ping succeeded! (response: {'id': 87135})
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/d/Projects/learning_equality/repos/k011x/kolibri/utils/server.py", line 109, in run
    call_command("ping")
  File "/Users/d/Projects/learning_equality/repos/k011x/.venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/learning_equality/repos/k011x/.venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/learning_equality/repos/k011x/kolibri/core/analytics/management/commands/ping.py", line 58, in handle
    self.perform_statistics(server, data["id"])
  File "/Users/d/Projects/learning_equality/repos/k011x/kolibri/core/analytics/management/commands/ping.py", line 123, in perform_statistics
    jsondata = dump_zipped_json(data)
  File "/Users/d/Projects/learning_equality/repos/k011x/kolibri/core/analytics/utils.py", line 37, in dump_zipped_json
    jsondata = json.dumps(data)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

### Steps to reproduce

Start kolibri

### Context

Mac, Python 3, latest `release-v0.11.x`

-----

cc @ralphiee22 @jamalex

**Comment by jamalex** [comment]
On it! We got automated tests working for Python 3, but it seems the serialization wasn't covered by the tests. Will add a test and fix.

**Comment by jamalex** [comment]
Fixed: https://github.com/learningequality/kolibri/pull/4416
