### ISSUE TITLE
SyntaxError: Generator expression must be parenthesized

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#4459]
### Observed behavior

> [kolibri@tower kolibri-venv]$ . bin/activate
> (kolibri-venv) [kolibri@tower kolibri-venv]$ export KOLIBRI_HOME=/opt/kolibri; export  KOLIBRI_LISTEN_PORT=8087
> (kolibri-venv) [kolibri@tower kolibri-venv]$ /opt/kolibri/kolibri-venv/bin/kolibri start
> WARNING:root:No C Extensions available for this platform.
> 
> INFO     Option HTTP_PORT in section [Deployment] being overridden by environment variable KOLIBRI_LISTEN_PORT
> INFO:kolibri.utils.options:Option HTTP_PORT in section [Deployment] being overridden by environment variable KOLIBRI_LISTEN_PORT
> Traceback (most recent call last):
>   File "/opt/kolibri/kolibri-venv/bin/kolibri", line 11, in <module>
>     sys.exit(main())
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/utils/cli.py", line 604, in main
>     initialize(debug=debug)
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/utils/cli.py", line 133, in initialize
>     django.setup()
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/__init__.py", line 27, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/apps/registry.py", line 85, in populate
>     app_config = AppConfig.create(entry)
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/apps/config.py", line 94, in create
>     module = import_module(entry)
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/contrib/admin/__init__.py", line 4, in <module>
>     from django.contrib.admin.filters import (
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/contrib/admin/filters.py", line 10, in <module>
>     from django.contrib.admin.options import IncorrectLookupParameters
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/contrib/admin/options.py", line 12, in <module>
>     from django.contrib.admin import helpers, widgets
>   File "/opt/kolibri/kolibri-venv/lib/python3.7/site-packages/kolibri/dist/django/contrib/admin/widgets.py", line 152
>     '%s=%s' % (k, v) for k, v in params.items(),
>     ^
> SyntaxError: Generator expression must be parenthesized
> 

…

### Expected behavior
Server starts normally
…

### Errors and logs

Kolibri 0.10.3

$ uname -a
Linux tower 4.14.74-1-MANJARO #1 SMP PREEMPT Fri Oct 5 14:16:52 UTC 2018 x86_64 GNU/Linux
(kolibri-venv) [kolibri@tower kolibri-venv]$ 

[kolibri.log.txt](https://github.com/learningequality/kolibri/files/2494388/kolibri.log.txt)

**Comment by nobicycle** [comment]
Forgot https://github.com/learningequality/kolibri/issues/4182
Kolibri must be run under python 3.6 for the moment.
