### ISSUE TITLE
Channel UPDATE button doesn't work when importing from Studio Develop

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/kolibri#4545]
### Observed behavior

We want to import the develop-version of a channel (v6), on a demosever that had v4 of a channel installed.

Using the second import option,
<img width="231" alt="screen shot 2018-11-29 at 12 24 39 pm" src="https://user-images.githubusercontent.com/163966/49314747-6119ad80-f4b9-11e8-856d-3ddcf458b87a.png">
and adding develop as a network location:
<img width="231" alt="screen shot 2018-11-29 at 12 24 45 pm" src="https://user-images.githubusercontent.com/163966/49314750-65de6180-f4b9-11e8-96b2-23c3af8d43a8.png">

We are presented with this screen:
<img width="763" alt="kolibri_peer_import_doesn_update" src="https://user-images.githubusercontent.com/163966/49314716-48a99300-f4b9-11e8-8952-8bd9c5c25bc0.png">

where, clicking UPDATE does not update the files-available list (pressing UPDATE, kolibri progress bar shows up, things for a bit, then UI shows v4 file list again, exactly the same as before the UPDATE was clicked).

### Expected behavior

Should see the file list from v6 of the channel

### User-facing consequences

Users  might not be able to update channels from USB if they already have installed channel from studio.

Not sure though --- this could an issues specific to the fact we're using a "hack" to import from develop studio as if it was a Kolibri peer.

### Errors and logs

This is logs from an other occurence of the same bug, where v20 is available but Kolibri still shows v19 file list: 

http://35.196.115.213/device/#/content/channels/f9d3e0e46ea25789bbed672ff6a399ed?address_id=1

```
INFO 2018-11-30 20:41:48,442 client Attempting connection to: https://develop.studio.learningequality.org/
INFO 2018-11-30 20:41:48,604 client Success! We connected to: https://develop.studio.learningequality.org/api/public/info/
INFO 2018-11-30 20:41:59,711 importchannel Downloading data for channel id f9d3e0e46ea25789bbed672ff6a399ed
WARNING 2018-11-30 20:42:02,549 channel_import Version 19 of channel f9d3e0e46ea25789bbed672ff6a399ed already exists in database; cancelling import of version 19
```

Meanwhile in the JS console we see a steady steam of tasks API call happening --- as if waiting for soem status:
<img width="585" alt="screen shot 2018-11-29 at 12 17 58 pm" src="https://user-images.githubusercontent.com/163966/49314729-52cb9180-f4b9-11e8-8334-28a9d26a80f8.png">

### Steps to reproduce

  - Import a channel vN from studio
  - Try to update a channel vN+1 from develop studio

**Comment by radinamatic** [comment]
I can replicate when trying to import into my own Kolibri dev. Virtually same errors, even though the previous version I had was 16 (unable to update to version 20 from develop.studio):

```INFO     "POST /api/tasks/tasks/startremotechannelimport/ HTTP/1.1" 200 189
INFO:django.server:"POST /api/tasks/tasks/startremotechannelimport/ HTTP/1.1" 200 189
INFO     Downloading data for channel id f9d3e0e46ea25789bbed672ff6a399ed
INFO:kolibri.core.content.management.commands.importchannel:Downloading data for channel id f9d3e0e46ea25789bbed672ff6a399ed
DEBUG    URL to fetch: https://develop.studio.learningequality.org/content/databases/f9d3e0e46ea25789bbed672ff6a399ed.sqlite3
DEBUG:kolibri.core.content.management.commands.importchannel:URL to fetch: https://develop.studio.learningequality.org/content/databases/f9d3e0e46ea25789bbed672ff6a399ed.sqlite3
DEBUG    Not creating directory '/home/didivm/.kolibri/content/databases' as it already exists.
DEBUG:kolibri.core.content.utils.transfer:Not creating directory '/home/didivm/.kolibri/content/databases' as it already exists.
DEBUG    Destination: /home/didivm/.kolibri/content/databases/f9d3e0e46ea25789bbed672ff6a399ed.sqlite3
DEBUG:kolibri.core.content.management.commands.importchannel:Destination: /home/didivm/.kolibri/content/databases/f9d3e0e46ea25789bbed672ff6a399ed.sqlite3
INFO     "GET /api/tasks/tasks/?1543611869189=1543611869189 HTTP/1.1" 200 190
INFO:django.server:"GET /api/tasks/tasks/?1543611869189=1543611869189 HTTP/1.1" 200 190
 18%|████████████▌                                                        | 2097152/11487232 [00:00<00:02, 3311785.75it/s]INFO     "GET /api/tasks/tasks/?1543611870192=1543611870192 HTTP/1.1" 200 190
INFO:django.server:"GET /api/tasks/tasks/?1543611870192=1543611870192 HTTP/1.1" 200 190
 91%|██████████████████████████████████████████████████████████████      | 10485760/11487232 [00:00<00:00, 6001897.53it/s]WARNING  Version 19 of channel f9d3e0e46ea25789bbed672ff6a399ed already exists in database; cancelling import of version 19
WARNING:kolibri.core.content.utils.channel_import:Version 19 of channel f9d3e0e46ea25789bbed672ff6a399ed already exists in database; cancelling import of version 19
INFO     Setting availability of File objects based on LocalFile availability
INFO:kolibri.core.content.utils.annotation:Setting availability of File objects based on LocalFile availability
```

Getting some font warnings and errors too (cc @indirectlylit )

```
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_framework7.material.min.css HTTP/1.1" 200 20833
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_framework7.material.colors.min.css HTTP/1.1" 200 23691
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_framework7.material.colors.min.css HTTP/1.1" 200 23691
WARNING  "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_css?family=Roboto+Slab:400,300,100,700&subset=latin,greek,greek-ext,cyrillic-ext,cyrillic,latin-ext HTTP/1.1" 404 947
WARNING:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_css?family=Roboto+Slab:400,300,100,700&subset=latin,greek,greek-ext,cyrillic-ext,cyrillic,latin-ext HTTP/1.1" 404 947
WARNING  "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_css?family=Roboto:400,700,500,300,400italic,100&subset=latin,latin-ext HTTP/1.1" 404 934
WARNING:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_css?family=Roboto:400,700,500,300,400italic,100&subset=latin,latin-ext HTTP/1.1" 404 934
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/4_app.css HTTP/1.1" 200 8519
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/4_app.css HTTP/1.1" 200 8519
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_enc.js HTTP/1.1" 200 2765
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_enc.js HTTP/1.1" 200 2765
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_hash.js HTTP/1.1" 200 5106
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_hash.js HTTP/1.1" 200 5106
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_asblogo.png HTTP/1.1" 200 17505
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_asblogo.png HTTP/1.1" 200 17505
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_app.js HTTP/1.1" 200 21401
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_app.js HTTP/1.1" 200 21401
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_framework7.min.js HTTP/1.1" 200 75738
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_logowhite.png HTTP/1.1" 200 6826
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/left.png HTTP/1.1" 200 863
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/right.png HTTP/1.1" 200 856
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_framework7.min.js HTTP/1.1" 200 75738
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_asblogo.png HTTP/1.1" 200 17505
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_logowhite.png HTTP/1.1" 200 6826
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/left.png HTTP/1.1" 200 863
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/right.png HTTP/1.1" 200 856
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_asblogo.png HTTP/1.1" 200 17505
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_startsactive.png HTTP/1.1" 200 1415
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_startsactive.png HTTP/1.1" 200 1415
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/4_startsgold.png HTTP/1.1" 200 1359
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/4_startsgold.png HTTP/1.1" 200 1359
ERROR    Internal Server Error: /zipcontent/fonts/NotoSans.ttf
Traceback (most recent call last):
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "kolibri/core/content/api.py", line 57, in wrapper_func
    response = some_func(*args, **kwargs)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/views/decorators/clickjacking.py", line 58, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "kolibri/core/content/views.py", line 49, in get
    zipped_path = get_content_storage_file_path(zipped_filename)
  File "kolibri/core/content/utils/paths.py", line 73, in get_content_storage_file_path
    assert VALID_STORAGE_FILENAME.match(filename), "'{}' is not a valid content storage filename".format(filename)
AssertionError: 'fonts' is not a valid content storage filename
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_3017.png HTTP/1.1" 200 363146
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/2_3017.png HTTP/1.1" 200 363146
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_3016.png HTTP/1.1" 200 417727
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/1_3016.png HTTP/1.1" 200 417727
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_3015.png HTTP/1.1" 200 457335
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/0_3015.png HTTP/1.1" 200 457335
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/5_3020.png HTTP/1.1" 200 354156
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/5_3020.png HTTP/1.1" 200 354156
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_3018.png HTTP/1.1" 200 492128
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/3_3018.png HTTP/1.1" 200 492128
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/4_3019.png HTTP/1.1" 200 429539
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/4_3019.png HTTP/1.1" 200 429539
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/6_3021.png HTTP/1.1" 200 413587
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/6_3021.png HTTP/1.1" 200 413587
ERROR    "GET /zipcontent/fonts/NotoSans.ttf HTTP/1.1" 500 17697
ERROR:django.server:"GET /zipcontent/fonts/NotoSans.ttf HTTP/1.1" 500 17697
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/7_3022.png HTTP/1.1" 200 478518
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/7_3022.png HTTP/1.1" 200 478518
ERROR    Internal Server Error: /zipcontent/fonts/NotoSansEthiopic-Regular.ttf
Traceback (most recent call last):
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "kolibri/core/content/api.py", line 57, in wrapper_func
    response = some_func(*args, **kwargs)
  File "/home/didivm/.venvs/kolibri/local/lib/python2.7/site-packages/django/views/decorators/clickjacking.py", line 58, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "kolibri/core/content/views.py", line 49, in get
    zipped_path = get_content_storage_file_path(zipped_filename)
  File "kolibri/core/content/utils/paths.py", line 73, in get_content_storage_file_path
    assert VALID_STORAGE_FILENAME.match(filename), "'{}' is not a valid content storage filename".format(filename)
AssertionError: 'fonts' is not a valid content storage filename
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/8_3022.png HTTP/1.1" 200 478518
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/8_3022.png HTTP/1.1" 200 478518
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/10_3025.png HTTP/1.1" 200 547684
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/10_3025.png HTTP/1.1" 200 547684
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/11_3026.png HTTP/1.1" 200 523601
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/11_3026.png HTTP/1.1" 200 523601
INFO     "GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/9_3024.png HTTP/1.1" 200 417821
INFO:django.server:"GET /zipcontent/a463a541d489c5a20a3750fe80553c9f.zip/9_3024.png HTTP/1.1" 200 417821
ERROR    "GET /zipcontent/fonts/NotoSansEthiopic-Regular.ttf HTTP/1.1" 500 17743
ERROR:django.server:"GET /zipcontent/fonts/NotoSansEthiopic-Regular.ttf HTTP/1.1" 500 17743
INFO     "PATCH /api/logger/contentsessionlog/8c27062d6af4a8a0ede5e24af41787b7/ HTTP/1.1" 200 122
INFO:django.server:"PATCH /api/logger/contentsessionlog/8c27062d6af4a8a0ede5e24af41787b7/ HTTP/1.1" 200 122
```

**Comment by radinamatic** [comment]
Maybe related to https://github.com/learningequality/studio/issues/1112? 
cc @aronasorman

**Comment by indirectlylit** [comment]
Interesting. Looks very similar to an issue I ran into months ago: #3184

At the time, it sounded like the Channel version in the sqlite3 file was 1 version behind what you get when hitting /api/public/channels on Studio

@ivanistheone  would you be able to check if there's a similar discrepancy here?

**Comment by indirectlylit** [comment]
@radinamatic the errors you saw with fonts look like they're coming from the learner content view side. Any chance those occurred before trying to import?

**Comment by radinamatic** [comment]
@indirectlylit You are correct, the errors appeared in the log when I tried to open the imported resources inside Learn, but I can't say that I noticed them before.

**Comment by jamalex** [comment]
The font errors are just because of bad HTML5 zip files with ".." references (in CSS or HTML) that point up above the top-level index.html path level. Not a Kolibri error (though we should probably just swallow that kind of error, or handle them in some way, because a lot of our ZIPs have this problem).

(Browser is requesting `/zipcontent/fonts/NotoSansEthiopic-Regular.ttf`...)

**Comment by ivanistheone** [comment]
@indirectlylit  Here are some version numbers:

  - The version in the DB file on disk is v19 (see `/kolibrihome/content/databases/f9d3e0e46ea25789bbed672ff6a399ed.sqlite3`)

  - The  version advertised by develop.studio is 20 (see [here](https://develop.studio.learningequality.org/api/public/v1/channels)

  - The version in the DB that can be downloaded from develop is 19, see [here](https://develop.studio.learningequality.org/content/databases/f9d3e0e46ea25789bbed672ff6a399ed.sqlite3)

So this is not a Kolibri issue! For some reason, the version advertised by develop studio api `/api/public/v1/channels` and the published DB in `/content/databases/` differ by 1. Incrementing the DB version number when publishing is happening, just late by one...

**Comment by ivanistheone** [comment]
Possibly related: https://github.com/learningequality/studio/issues/1119

**Comment by ivanistheone** [comment]
This is really a studio (develop) issue, so moved here: https://github.com/learningequality/studio/issues/1124
