### ISSUE TITLE
esprima source parsing crashes node process due to spread operators

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#4768]
### Observed behavior

Esprima, used by `extract_$trs`, will sometimes crash the node build process.

When this happens:

* our build tools will cease to watch and rebuild the module
* there is no indication of which file caused esprima to crash

This appears to be due to a bug in Esprima which causes spread operators to sometimes not be properly parsed. For example, this parses correctly:

```javascript
export default [
  ...planLessonsRoutes,
  {
    name: 'PLAN_PAGE',
    path: '/:classId/plan',
    redirect: '/:classId/plan/lessons',
  },
];
```

However, this crashes Esprima:

```javascript
export default [
  {
    name: 'PLAN_PAGE',
    path: '/:classId/plan',
    redirect: '/:classId/plan/lessons',
  },
  ...planLessonsRoutes,
];
```

with this error

```
Kolibri: Building coach_module bundle...
(node:68914) UnhandledPromiseRejectionWarning: Error: Line 14: Unexpected token .
    at ErrorHandler.constructError (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:5028:27)
    at Parser.unexpectedTokenError (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:1985:39)
    at Parser.throwUnexpectedToken (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:1995:21)
    at Parser.consumeSemicolon (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:2297:23)
    at Parser.parseExportDeclaration (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:4893:23)
    at Parser.parseStatementListItem (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:3367:39)
    at Parser.parseModule (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:4715:29)
    at parse (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:122:38)
    at Object.parseModule (/Users/d/Projects/learning_equality/repos/k012x/node_modules/esprima/dist/esprima.js:139:13)
    at /Users/d/Projects/learning_equality/repos/k012x/packages/kolibri-tools/lib/extract_$trs.js:194:27
    at Array.forEach (<anonymous>)
    at /Users/d/Projects/learning_equality/repos/k012x/packages/kolibri-tools/lib/extract_$trs.js:86:26
    at _err0 (eval at create (/Users/d/Projects/learning_equality/repos/k012x/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at /Users/d/Projects/learning_equality/repos/k012x/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/Users/d/Projects/learning_equality/repos/k012x/node_modules/async/dist/async.js:992:24)
(node:68914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:68914) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected behavior

Preferably, we should upgrade Esprima to a version not affected by this bug.  

If that is not possible, we should at least make sure that the error is handled properly to help us find the offending code more easily.

### User-facing consequences

confusion during dev

### Context

0.12.0

----

side note - we should switch from 

```javascript
esprima.parse(module._source.source(), {
  sourceType: 'module',
});
```

to

```javascript
esprima.parseModule(module._source.source());
```

because the former has been deprecated

**Comment by indirectlylit** [comment]
cc @rtibbles

**Comment by rtibbles** [comment]
Hrm, yeah, this is why I switched to espree for some things, it has better support for later syntax. Will see about migrating all our code to use espree instead of esprima.
