### ISSUE TITLE
Device info page error on Windows

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#4966]
### Observed behavior
Device info page has an error on WIndows 7.

### Errors and logs
```
ERROR 2019-02-08 01:50:21,316 exception Internal Server Error: /api/device/deviceinfo/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\core\device\api.py", line 93, in get
    info['content_storage_free_space'] = get_free_space()
  File "C:\Python34\lib\site-packages\kolibri\utils\system.py", line 175, in get_free_space
    st = os.statvfs(os.path.realpath(path))
AttributeError: 'module' object has no attribute 'statvfs'

```

### Context
Tell us about your environment, including:
 * Kolibri version: 0.12-beta3
 * Operating system: Windows 7
 * Browser: Firefox 65.0

**Comment by radinamatic** [comment]
Confirmed on both `0.12.0.b3` (Chrome) and `0.12.0.b4` (FF v66):

![2019-02-10_22-52-34](https://user-images.githubusercontent.com/1457929/52541178-fc68b200-2d89-11e9-87d9-cd5adbcd5881.png)

![2019-02-10_23-15-03](https://user-images.githubusercontent.com/1457929/52541181-04c0ed00-2d8a-11e9-9070-f1d772a7e50e.png)

```
{
  "request": {
    "path": "/api/device/deviceinfo/",
    "params": {
      "1549840460253": 1549840460253
    },
    "headers": {
      "Content-Type": "application/json",
      "Accept": "application/json, application/json;q=0.8, text/plain;q=0.5, */*;q=0.2",
      "X-CSRFToken": "2spGsVp5bBXP81WIyjMf6Aqg2YHz2F0hpA7K00wYxoQIzcklH60YtHcPbDUzHbdm"
    },
    "method": "GET",
    "canceled": false
  },
  "url": "/api/device/deviceinfo/?1549840460253=1549840460253",
  "raw": {},
  "status": {
    "code": 500,
    "text": "Internal Server Error"
  },
  "headers": {
    "Content-Language": "en",
    "Content-Length": "27",
    "Content-Type": "text/html",
    "Date": "Sun, 10 Feb 2019 23:14:21 GMT",
    "Server": "0.0.0.0",
    "Vary": "Accept-Language, Cookie",
    "X-Frame-Options": "SAMEORIGIN"
  },
  "entity": "<h1>Server Error (500)</h1>"
}
```
