### ISSUE TITLE
Coach page javascript error

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5012]
### Observed behavior
Coach page has an javascript error when there's no class available.

### Expected behavior
Should add a message to create a class first before accessing the coach page.

### Errors and logs

![screen shot 2019-02-12 at 5 59 55 pm](https://user-images.githubusercontent.com/8663934/52627653-d9a4dd80-2ef0-11e9-9229-beb82996fbc7.png)

### Steps to reproduce
* Install the `Kolibri 0.12.x beta-4` on fresh installation.
* log in using super admin account.
* Navigate at the Coach page with no classes created.

### Context

Tell us about your environment, including:
 * Kolibri version: 0.12.x-beta-4
 * Operating system: Windows
 * Browser: IE11 & Google Chrome 72.0

…

**Comment by radinamatic** [comment]
Issue replicated on Windows 7 with Firefox:

![2019-02-12_15-33-54](https://user-images.githubusercontent.com/1457929/52647147-0b5f7980-2edc-11e9-9a81-1c655f611e23.png)

```
INFO 2019-02-10 15:06:43,591 cli Going to daemon mode, logging to C:\Users\IEUser\.kolibri\server.log
INFO 2019-02-10 15:06:43,607 ping Attempting a ping.
INFO 2019-02-10 15:06:43,763 utils Started new MESSAGEPROCESSOR thread ID#seventeen-network-spaghetti-kilo
INFO 2019-02-10 15:06:43,763 utils Started new SCHEDULER thread ID#winter-zebra-johnny-asparagus
INFO 2019-02-10 15:06:43,763 utils Started new WORKERMESSAGEHANDLER thread ID#cold-blue-charlie-texas
INFO 2019-02-10 15:06:44,700 ping Ping succeeded! (response: {'id': 177109, 'messages': []})
INFO 2019-02-10 15:06:45,185 ping Sleeping for 1440.0 minutes.
INFO 2019-02-10 15:06:45,216 vacuumsqlite Sqlite database Vacuum finished.
INFO 2019-02-10 15:06:45,216 vacuumsqlite Next Vacuum at 3AM local server time (in 713.2333333333333 minutes).
ERROR 2019-02-10 15:10:29,393 exception Internal Server Error: /api/device/deviceinfo/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\core\device\api.py", line 93, in get
    info['content_storage_free_space'] = get_free_space()
  File "C:\Python34\lib\site-packages\kolibri\utils\system.py", line 175, in get_free_space
    st = os.statvfs(os.path.realpath(path))
AttributeError: 'module' object has no attribute 'statvfs'
ERROR 2019-02-10 15:13:05,441 exception Internal Server Error: /api/device/deviceinfo/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\core\device\api.py", line 93, in get
    info['content_storage_free_space'] = get_free_space()
  File "C:\Python34\lib\site-packages\kolibri\utils\system.py", line 175, in get_free_space
    st = os.statvfs(os.path.realpath(path))
AttributeError: 'module' object has no attribute 'statvfs'
ERROR 2019-02-10 15:13:33,488 exception Internal Server Error: /api/device/deviceinfo/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\core\device\api.py", line 93, in get
    info['content_storage_free_space'] = get_free_space()
  File "C:\Python34\lib\site-packages\kolibri\utils\system.py", line 175, in get_free_space
    st = os.statvfs(os.path.realpath(path))
AttributeError: 'module' object has no attribute 'statvfs'
ERROR 2019-02-10 15:14:21,410 exception Internal Server Error: /api/device/deviceinfo/
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Python34\lib\site-packages\kolibri\dist\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\core\device\api.py", line 93, in get
    info['content_storage_free_space'] = get_free_space()
  File "C:\Python34\lib\site-packages\kolibri\utils\system.py", line 175, in get_free_space
    st = os.statvfs(os.path.realpath(path))
AttributeError: 'module' object has no attribute 'statvfs'
INFO 2019-02-12 07:32:18,971 options Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
INFO 2019-02-12 07:32:20,314 apps Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO 2019-02-12 07:32:20,939 tasks Initializing background log saving process
INFO 2019-02-12 07:32:21,049 vacuumsqlite Sqlite database Vacuum finished.
INFO 2019-02-12 07:32:21,080 cli Running update routines for new version...
INFO 2019-02-12 07:32:23,502 cli Running 'kolibri start' as daemon (system service)
INFO 2019-02-12 07:32:23,549 cli Kolibri running on:
```

**Comment by indirectlylit** [comment]
@radinamatic the server errors above are related to https://github.com/learningequality/kolibri/issues/4966, not this issue
