### ISSUE TITLE
`django-mptt` dependency missing from Kolibri setup

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#52]
## Issue

In the [setup instructions](https://github.com/learningequality/kolibri), `pip install -e .` is used to install Django and other dependencies. However running `kolibri manage runserver` on a fresh installations gives:

```
vagrant@kolibri ~> kolibri manage runserver
Unhandled exception in thread started by <function wrapper at 0x7fba4bb75938>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/kolibri/kolibri/auth/models.py", line 28, in <module>
    from mptt.models import MPTTModel, TreeForeignKey
ImportError: No module named mptt.models
^Cfish: Job 1, “kolibri manage runserver” terminated by signal SIGINT (Quit request from job control (^C))
```

## Work-around

The correct dependencies can be installed using

    pip install -r requirements.txt

## Analysis

If we're using  `pip install -e .` as the canonical way to install Kolibri's dependencies, all required packages should be included in the `install_requires` field in `setup.py`.

We should clarify how these differ from the dependencies listed the various requirements files, and potentially clean these up if there is redundancy.

**Comment by djallado** [comment]
There's a PR to improve the `README`. https://github.com/learningequality/kolibri/pull/29/files.

**Comment by benjaoming** [comment]
Thanks @djallado for the reminder to have that one merged :)
