### ISSUE TITLE
Kolibri fails to start when using Postgresql DB with a big content library with django.db.utils.DataError: integer out of range

### ISSUE THREAD

**Issue by dolfandringa** [learningequality/kolibri#5366]
### Observed behavior
Kolibri fails to start with PostgreSQL when trying to import a big content dataset (from Khan Academy). When copying a large amount of content (like the full Khan Academy library) folder and then starting starting kolibri, while running the postgres db engine, the server fails to start.

### Expected behavior

Server starts normally and import Khan Academy data.

### User-facing consequences

The server fails to start completely. After a second reboot, the data of the Khan academy library is listed, but with 0MB size.

### Errors and logs
Error in `journalctl -xe -u kolibri`:
```
Apr 15 18:37:53 pc13-H110M-H kolibri[11070]: INFO     Setting totals of coach content ContentNode objects with children for level 1
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:  OK
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]: Installed 2 object(s) from 1 fixture(s)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]: Traceback (most recent call last):
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     return self.cursor.execute(sql, params)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]: psycopg2.DataError: integer out of range
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]: The above exception was the direct cause of the following exception:
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]: Traceback (most recent call last):
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/bin/kolibri", line 9, in <module>
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     load_entry_point('kolibri==0.12.2', 'console_scripts', 'kolibri')()
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 673, in main
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     start(port, daemon=daemon)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 281, in start
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     update()
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 260, in update
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     update_channel_metadata()
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/annotation.py", line 49, in update_channel_metadata
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     annotate_content(channel_id)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/annotation.py", line 310, in annotate_content
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     update_content_metadata(channel_id)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/annotation.py", line 300, in update_content_metadata
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     calculate_channel_fields(channel_id)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/annotation.py", line 315, in calculate_channel_fields
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     calculate_published_size(channel)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/annotation.py", line 325, in calculate_published_size
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     channel.save()
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 808, in save
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     force_update=force_update, update_fields=update_fields)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 838, in save_base
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 905, in _save_table
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     forced_update)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/base.py", line 955, in _do_update
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     return filtered._update(values) > 0
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 667, in _update
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     return query.get_compiler(self.db).execute_sql(CURSOR)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 1204, in execute_sql
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     raise original_exception
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 889, in execute_sql
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     cursor.execute(sql, params)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     return self.cursor.execute(sql, params)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/utils.py", line 94, in __exit__
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/utils/six.py", line 685, in reraise
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     raise value.with_traceback(tb)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:   File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/backends/utils.py", line 64, in execute
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]:     return self.cursor.execute(sql, params)
Apr 15 18:37:54 pc13-H110M-H kolibri[11070]: django.db.utils.DataError: integer out of range
Apr 15 18:37:54 pc13-H110M-H systemd[1]: kolibri.service: Control process exited, code=exited status=1
Apr 15 18:37:54 pc13-H110M-H systemd[1]: Failed to start LSB: kolibri daemon, an offline education platform.
```

### Steps to reproduce

 * Install kolibri (actually tested with kolibri-server, but shouldn't make a difference)
 * Create a postgres db with `sudo -u postgres createuser $USER;sudo -u postgres createdb kolibri -O $USER`
 * Set the `DB_ENGINE = postgres` and `DB_NAME = kolibri` in options.ini in the `[Database]` section. (hostname, password, etc not needed)
 * Copy the content of the Khan academy to the content folder in ~/.kolibri/content/
 * Start kolibri with `systemctl start kolibri`
### Context

 * Kolibri 0.12.2-ubuntu1
 * Linux Mint 18.3 Cinnamon
 * Postgresql 9.5

**Comment by rtibbles** [comment]
Looks like whatever our integer field is being interpreted by the Django ORM in Postgres is insufficient to handle the filesize of Khan Academy.

**Comment by dolfandringa** [comment]
@rtibbles indeed. SQLite doesn't distinguish between different integer sizes, but postgresql does. The Khan Academy library is around 30Gb, which is 3.22e10 bytes. The maximum value for a PostgreSQL integer is 2.15e9 (4 bytes) I think. SQLite seems to dynamically allocate up to 8 bytes depending on the value. For PostgreSQL you need to define the field as a BigInteger to get 8 bytes.
