### ISSUE TITLE
Error reading /UserPath/kolibri/kolibri/core/kolibri_core_stats.json.

### ISSUE THREAD

**Issue by amodia** [learningequality/kolibri#55]
Branch: `Master`

**Current behavior**: when running `kolibri manage run server` and access the port [:8000](http://127.0.0.1:8000)  will spawn an error `Error reading /Users/user/kolibri/kolibri/core/kolibri_core_stats.json. Are you sure webpack has generated the file and the path is correct?`

**Steps to reproduce**

1. Follow the instructions to run kolibri at https://github.com/learningequality/kolibri#running-kolibri
1. After running the command `kolibri manage runserver` and access the port [:8000](http://127.0.0.1:8000)  will spawn the error.

**Here's the sample screenshot**

![screen shot 2016-04-12 at 1 33 37 pm](https://cloud.githubusercontent.com/assets/8663934/14450886/f997d060-00b4-11e6-8614-00b8792403a4.png)

**Comment by djallado** [comment]
I replicate this also. 
Here's my screenshot:
![error](https://cloud.githubusercontent.com/assets/8664071/14451603/f7aafb32-00ba-11e6-8cee-cfa5711dd454.png)

**Comment by MCGallaspy** [comment]
It's not very clear from the order, but you must (in a separate terminal) also run `npm run watch`. I'll amend the README.

**Comment by jamalex** [comment]
Adding this as help to anyone else facing this. I'm getting the same thing, and running `npm run watch` is throwing the following error:

```
$ npm run watch

> kolibri@0.0.1 watch /home/jamalex/fle/kolibri
> webpack --config webpack.config.dev.js --watch


/home/jamalex/fle/kolibri/assets/src/read_bundle_plugin.js:31
    var result = execSync("python kolibri/utils/webpack_config_export.py " + p
                 ^
TypeError: undefined is not a function
    at readBundlePlugin (/home/jamalex/fle/kolibri/assets/src/read_bundle_plugin.js:31:18)
    at recurseBundlePlugins (/home/jamalex/fle/kolibri/assets/src/recurse_bundle_plugins.js:52:22)
    at Object.<anonymous> (/home/jamalex/fle/kolibri/webpack.config.js:38:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jamalex/fle/kolibri/webpack.config.dev.js:9:15)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

It looks like `execSync` was added in Node v0.12, and the version of Node in the Ubuntu repos is 0.10, so I'll need to update via a PPA to get it working.

**Comment by jamalex** [comment]
I upgraded to node v6.0.0, and now trying to build gives a different error:

```
$ npm run build

> kolibri@0.0.1 build /home/jamalex/fle/kolibri
> webpack

Traceback (most recent call last):
  File "kolibri/utils/webpack_config_export.py", line 6, in <module>
    import cli
  File "/home/jamalex/fle/kolibri/kolibri/utils/cli.py", line 9, in <module>
    import kolibri
ImportError: No module named kolibri
child_process.js:513
    throw err;
    ^

Error: Command failed: python kolibri/utils/webpack_config_export.py kolibri.core.kolibri_plugin
Traceback (most recent call last):
  File "kolibri/utils/webpack_config_export.py", line 6, in <module>
    import cli
  File "/home/jamalex/fle/kolibri/kolibri/utils/cli.py", line 9, in <module>
    import kolibri
ImportError: No module named kolibri

    at checkExecSyncError (child_process.js:470:13)
    at execSync (child_process.js:510:13)
    at readBundlePlugin (/home/jamalex/fle/kolibri/assets/src/read_bundle_plugin.js:31:18)
    at recurseBundlePlugins (/home/jamalex/fle/kolibri/assets/src/recurse_bundle_plugins.js:52:22)
    at Object.<anonymous> (/home/jamalex/fle/kolibri/webpack.config.js:38:15)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

npm ERR! Linux 4.0.0-xps13
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! kolibri@0.0.1 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kolibri@0.0.1 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the kolibri package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs kolibri
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls kolibri
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/jamalex/fle/kolibri/npm-debug.log
```

I'm running from within a virtualenv. It seems maybe node's `execSync` stuff is somehow getting run outside the virtualenv, and hence can't import kolibri.

**Comment by rtibbles** [comment]
Note for people facing this issue in future, on Ubuntu using `nvm` is required to make this work.

This was updated in the README here: https://github.com/learningequality/kolibri/commit/57a0d34e29b3de77f749608784b40903f74a7abc
