### ISSUE TITLE
Failed to import a channel after I upgrade from 0.8

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#5535]
### Observed behavior
I can't import a channel after I upgrade from 0.8, There is an javascript errors. 

### Expected behavior
I should be able to import a channel after the upgrade.

### User-facing consequences

…

### Errors and logs
[kolibri.log](https://github.com/learningequality/kolibri/files/3210185/kolibri.log)
[server.log](https://github.com/learningequality/kolibri/files/3210186/server.log)

![Screen Shot 2019-05-23 at 11 53 27 AM](https://user-images.githubusercontent.com/8663934/58224816-c1472900-7d51-11e9-84ad-da7dbb70d214.png)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: v0.12.4-beta3
 * Operating system: Windows 7
 * Browser: Firefox 67.0

**Comment by indirectlylit** [comment]
from the logs:

```
[31mERROR    Job 6ab5744c545c45fdaba2778e602c07bf raised an exception: Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\kolibri\dist\iceqube\worker.py", line 61, in handle_finished_future
    result = future.result()
  File "C:\Python34\lib\concurrent\futures\_base.py", line 395, in result
    return self.__get_result()
  File "C:\Python34\lib\concurrent\futures\_base.py", line 354, in __get_result
    raise self._exception
  File "C:\Python34\lib\concurrent\futures\thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\iceqube\worker.py", line 206, in wrap
    raise e
  File "C:\Python34\lib\site-packages\kolibri\dist\iceqube\worker.py", line 202, in wrap
    return f(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\iceqube\classes.py", line 120, in y
    return func(*args, **kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "C:\Python34\lib\site-packages\kolibri\dist\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python34\lib\site-packages\kolibri\core\tasks\management\commands\base.py", line 84, in handle
    return self.handle_async(*args, **options)
  File "C:\Python34\lib\site-packages\kolibri\core\content\management\commands\importcontent.py", line 310, in handle_async
    renderable_only=options["renderable_only"],
  File "C:\Python34\lib\site-packages\kolibri\core\content\management\commands\importcontent.py", line 129, in download_content
    renderable_only=renderable_only,
  File "C:\Python34\lib\site-packages\kolibri\core\content\management\commands\importcontent.py", line 167, in _transfer
    if self.is_cancelled():
  File "C:\Python34\lib\site-packages\kolibri\core\tasks\management\commands\base.py", line 97, in is_cancelled
    self.check_for_cancel()
  File "C:\Python34\lib\site-packages\kolibri\dist\iceqube\worker.py", line 182, in _check_for_cancel
    future = self.future_job_mapping[job_id]
KeyError: '6ab5744c545c45fdaba2778e602c07bf'
```

cc @rtibbles thoughts?

**Comment by indirectlylit** [comment]
maybe trying to resume an old transfer?

**Comment by indirectlylit** [comment]
* start running a job
* have worker start
* ... restart server?
* thing might still be running background
* profit

possible work-around: restart server

**Comment by indirectlylit** [comment]
ref @rtibbles and cancel PRs

**Comment by nucleogenesis** [comment]
@mrpau-richard 

I have tried to replicate this error on Windows 7 several times with a few variations on when I start/stop the server during imports on both versions before and after upgrading. I have not been able to replicate the issue at all.

Based on discussion with @indirectlylit and @rtibbles - it would seem that this should be a one-off error that is resolved after restarting the server. @mrpau-richard : _Is that the case on your end with this issue?_

I'm not entirely clear on how I would go about processing a job that doesn't exist in the DB in order to test any additional error handling. 

I believe that we could just handle the `KeyError` exception received in this instance by changing [this line ](https://github.com/learningequality/kolibri/blob/03e6e053a5e5967281eca4d1f0983bef8fb0cda9/kolibri/core/tasks/management/commands/base.py#L99) as follows:

`except (UserCancelledError, KeyError):`

In this case, we would just treat the job as if it were canceled as the following line is `return True`. @rtibbles @indirectlylit what are your thoughts?

**Comment by rtibbles** [comment]
I think if the job does not exist, it sounds rather like it has been cancelled, so I think that's a nice quick fix!

**Comment by indirectlylit** [comment]
yup, sounds reasonable to me

**Comment by mrpau-richard** [comment]
> Based on discussion with @indirectlylit and @rtibbles - it would seem that this should be a one-off error that is resolved after restarting the server. @mrpau-richard : Is that the case on your end with this issue?

Yeah, I confirmed that will fix the issue. Let's just handle the `KeyError`  exception.
