### ISSUE TITLE
Export to drive lacks guiding fail messages and guidance about resuming

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#5952]
### Observed behavior

I'm trying to export to a locally mounted drive. The problem was that the plug wasn't working okay on the particular drive, hence it got uncleanly unmounted+mounted during the transfer. Afterwards, the export didn't work at all due to an input/output error on the NTFS filesystem mounted on Ubuntu Linux.

Using the export function to export large amounts of data has some lacks in terms of user guidance.

* [ ] Time elapsed would be really useful to estimate time left (I guess that's universal to all import/export)
* [ ] Input/output errors need more guidance: For instance "An input/output error occurred while writing {{path}}. Please check that you can write to this destination".
* [ ] Guidance about retrying: "Transfer failed. Please try again" is quite frustrating without information about whether resuming will work and how it works? Also, what happens to already written data? Will it be deleted?

![image](https://user-images.githubusercontent.com/374612/65394331-bdbdc000-dd8c-11e9-8690-3804c33239d9.png)

### Expected behavior

During exports that take many hours and are prone to fail under suboptimal conditions, guidance is critical.

### User-facing consequences

Planning time is hard - when can I go to sleep? When should I tell my colleague to come and fetch her drive? Can we deploy this tomorrow etc.

### Errors and logs

```

INFO 2019-09-22 22:08:02,526 exportchannel Exporting channel database for channel id 1ceff53605e55bef987d88e0908658c5 to /media/user/drive/KOLIBRI_DATA
INFO 2019-09-22 22:08:07,477 exportcontent Exporting content for channel id 1ceff53605e55bef987d88e0908658c5 to /media/user/drive/KOLIBRI_DATA
ERROR 2019-09-22 22:08:23,117 worker Job be4c91e574674c5e884c057c56cf1bc3 raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/iceqube/worker.py", line 63, in handle_finished_future
    result = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/iceqube/worker.py", line 208, in wrap
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/dist/iceqube/worker.py", line 204, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/iceqube/classes.py", line 120, in y
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/api.py", line 414, in _localexport
    check_for_cancel=check_for_cancel,
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 84, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/exportcontent.py", line 95, in handle_async
    copy = transfer.FileCopy(srcpath, dest)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/transfer.py", line 82, in __init__
    self.dest_file_obj = open(self.dest_tmp, "wb")
OSError: [Errno 5] Input/output error: '/media/user/drive/KOLIBRI_DATA/content/storage/f/b/fb424038fce8709c33b7bc30ec3b33ce.vtt.transfer'
```

### Steps to reproduce

Pull the plug on a drive while transferring (NB: will cause filesystem to have to be checked)

### Context

Kolibri 0.12.8

**Comment by indirectlylit** [comment]
cc @khangmach

**Comment by indirectlylit** [comment]
@benjaoming would you mind retesting using 0.13.0 beta?

**Comment by indirectlylit** [comment]
closing given 0.13 updates. Let's re-open if there are new issues to raise

**Comment by benjaoming** [comment]
Opened in https://github.com/learningequality/kolibri/issues/6686 -- but problems are still the same.
