### ISSUE TITLE
External plugins break kolibri if they don't have a locale dir 

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#5954]
### Observed behavior
Creating a new plugin to be installed with kolibri, after installing it using
`kolibri plugin enable plugin_name`
when trying to access to kolibri in the browser, there's a `500 server error` message.

Creating an empty `locale` dir in the plugin folder makes the error disappear.

### Expected behavior
There might be plugins not needing a locale dir. The error should not raise if the directory does not exist.

### User-facing consequences
_Correctly_ built plugins break kolibri after being installed and enabled.

### Errors and logs
Looking at logs/kolibri.text, this can be seen:
```
RROR 2019-09-25 20:22:29,455 exception Internal Server Error: /es-es/setup_wizard/
Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/datos/le/mio/kolibri/kolibri/core/webpack/templatetags/webpack_tags.py", line 42, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "/datos/le/mio/kolibri/kolibri/core/kolibri_plugin.py", line 151, in render_to_page_load_sync_html
    + list(self.js_and_css_tags())
  File "/datos/le/mio/kolibri/kolibri/core/webpack/hooks.py", line 263, in frontend_message_tag
    if self.frontend_messages():
  File "/datos/le/mio/kolibri/kolibri/core/webpack/hooks.py", line 213, in frontend_messages
    frontend_message_file = self.frontend_message_file(lang_code)
  File "/datos/le/mio/kolibri/kolibri/core/webpack/hooks.py", line 201, in frontend_message_file
    path, to_locale(lang_code), "LC_MESSAGES", message_file_name
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Steps to reproduce
Remove the `locale`dir from an external plugin, restart kolibri and try to access to it in the browser.

### Context
Develop version of kolibri

**Comment by rtibbles** [comment]
I think #5957 fixed this @jredrejo could you confirm?

**Comment by jredrejo** [comment]
Right, it's fixed now. Thanks.
