### ISSUE TITLE
zeroconf: 'NoneType' object has no attribute 'address'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6077]
### Observed behavior

unhandled error while starting up

### Expected behavior

no unhandled errors

### User-facing consequences

unknown

### Errors and logs

```
Exception in thread zeroconf-ServiceBrowser_Kolibri._sub._http._tcp.local.:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/d/.pex/install/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl.2a207c91c66d601df134ab0be317299b564f33c9/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl/kolibri/dist/zeroconf.py", line 1442, in run
    handler(self.zc)
  File "/Users/d/.pex/install/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl.2a207c91c66d601df134ab0be317299b564f33c9/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl/kolibri/dist/zeroconf.py", line 1383, in <lambda>
    state_change=state_change,
  File "/Users/d/.pex/install/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl.2a207c91c66d601df134ab0be317299b564f33c9/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl/kolibri/dist/zeroconf.py", line 1279, in fire
    h(**kwargs)
  File "/Users/d/.pex/install/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl.2a207c91c66d601df134ab0be317299b564f33c9/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl/kolibri/dist/zeroconf.py", line 1352, in on_change
    listener.add_service(*args)
  File "/Users/d/.pex/install/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl.2a207c91c66d601df134ab0be317299b564f33c9/kolibri-0.13.0.dev0+git.20191116091820-py2.py3-none-any.whl/kolibri/core/discovery/utils/network/search.py", line 108, in add_service
    ip = socket.inet_ntoa(info.address)
AttributeError: 'NoneType' object has no attribute 'address'
```

### Steps to reproduce

ran a pex from the latest `develop`

### Context

0.12.0 alpha 0

**Comment by indirectlylit** [comment]
@micahscopes were you ever able to reproduce this?

**Comment by indirectlylit** [comment]
also reported here: https://www.notion.so/learningequality/0-13-0-bug-bash-3-7eeb57a21dd14aaa8f672dca9981f3f9?p=97dfe058774c461981e65e526ff499c3

**Comment by jredrejo** [comment]
From Zeroconf code:
```
    def get_service_info(self, type_, name, timeout=3000):
        """Returns network's service information for a particular
        name and type, or None if no service matches by the timeout,
        which defaults to 3 seconds."""
```
Looking at Kolibri code:
```
        info = zeroconf.get_service_info(type, name)
        id = _id_from_name(name)
        ip = socket.inet_ntoa(info.address)
```

So this error is logical when the network information does not appear after 3 seconds, what can happen in some circumstances. Kolibri code should either increase the timeout or deal with this possibility.
