### ISSUE TITLE
zeroconf: Crashes when starting devserver

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#6080]
### Observed behavior
Tried to run devserver.
```
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 237, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 610, in services
    server.services()
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 167, in services
    run_services(port=port)
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 121, in run_services
    register_zeroconf_service(port=port, id=instance.id[:4])
  File "/home/richard/github/kolibri/kolibri/core/discovery/utils/network/search.py", line 160, in register_zeroconf_service
    ZEROCONF_STATE["service"].register()
  File "/home/richard/github/kolibri/kolibri/core/discovery/utils/network/search.py", line 68, in register
    properties=self.data,
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/zeroconf.py", line 1485, in __init__
    self._set_properties(properties)
  File "/home/richard/.virtualenvs/kolibri/local/lib/python2.7/site-packages/zeroconf.py", line 1516, in _set_properties
    result = b"".join((result, int2byte(len(item)), item))
ValueError: chr() arg not in range(256)
```

### Expected behavior
Devserver should run :)

**Comment by rtibbles** [comment]
Sorry, it seems that things still run as expected, it's just the zero conf service has crashed in the background - have updated the title.

**Comment by rtibbles** [comment]
The above error was on Python2, the error below is from Python 3:
```
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/kolibripy3/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 237, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 624, in services
    server.services()
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 151, in services
    run_services(port=port)
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 112, in run_services
    register_zeroconf_service(port=port, id=instance.id[:4])
  File "/home/richard/github/kolibri/kolibri/core/discovery/utils/network/search.py", line 160, in register_zeroconf_service
    ZEROCONF_STATE["service"].register()
  File "/home/richard/github/kolibri/kolibri/core/discovery/utils/network/search.py", line 68, in register
    properties=self.data,
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/zeroconf.py", line 1485, in __init__
    self._set_properties(properties)
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/zeroconf.py", line 1516, in _set_properties
    result = b"".join((result, int2byte(len(item)), item))
struct.error: ubyte format requires 0 <= number <= 255
```
