### ISSUE TITLE
unhandled JobNotFound error on startup

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6091]
### Observed behavior

Unhandled error during startup

### Expected behavior

no unhandled errors

### User-facing consequences

unknown - server seemed to start

### Errors and logs

```
ERROR:concurrent.futures:exception calling callback for <Future at 0x106f91e48 state=finished returned NoneType>
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 77, in handle_finished_future
    self.report_success(job.job_id, result)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 117, in report_success
    self.storage.complete_job(job_id)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/storage.py", line 240, in complete_job
    self._update_job(job_id, State.COMPLETED)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/storage.py", line 248, in _update_job
    job, orm_job = self._get_job_and_orm_job(job_id, session)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/storage.py", line 270, in _get_job_and_orm_job
    raise JobNotFound()
kolibri.core.tasks.exceptions.JobNotFound
```

### Steps to reproduce

…

### Context

…

**Comment by indirectlylit** [comment]
duplicate of https://github.com/learningequality/kolibri/issues/6041
