### ISSUE TITLE
mac app not working

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6125]
### Observed behavior

see thread here: https://learningequality.slack.com/archives/CN3DPD0K0/p1574370076004500

app fails to run: 

> ![image](https://user-images.githubusercontent.com/2367265/69464202-8ccd1d80-0d32-11ea-8187-cab806d24cd2.png)

### Expected behavior

app runs

### User-facing consequences

cannot use mac

### Errors and logs

```
d@slate ~/A/K/C/MacOS> ./Kolibri 
DEBUG:root:Found platforms: ['wx']
WARNING:root:Traceback (most recent call last):
  File "pew/wxpy/__init__.pyc", line 80, in <module>
  File "pew/wxpy/webview_chromium.pyc", line 10, in <module>
ModuleNotFoundError: No module named 'cefpython3'
WARNING:root:Chromium not found, loading wxWebView instead.
INFO:root:Initializing WebView?
INFO:root:Entering main.py...
WARNING:root:No C Extensions available for this platform.
Traceback (most recent call last):
  File "/Users/d/Applications/Kolibri.app/Contents/Resources/__boot__.py", line 98, in <module>
    _run()
  File "/Users/d/Applications/Kolibri.app/Contents/Resources/__boot__.py", line 82, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Users/d/Applications/Kolibri.app/Contents/Resources/main.py", line 66, in <module>
    from kolibri.core.logger.utils.handler import KolibriTimedRotatingFileHandler
ModuleNotFoundError: No module named 'kolibri.core.logger.utils.handler'
2019-11-21 13:00:29.817 Kolibri[84161:8201108] Kolibri Error
d@slate ~/A/K/C/MacOS [255]> 
```

### Steps to reproduce

download and run the latest built mac installer: 

https://github.com/learningequality/kolibri/releases/tag/v0.13.0-beta1

### Context

0.13.0 beta 1

**Comment by indirectlylit** [comment]
tracked in https://github.com/learningequality/kolibri-installer-mac/issues/15
