### ISSUE TITLE
No socket could be created - Address already in use

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6176]
### Observed behavior

reported by @jonboiser during the 0.13 beta 1 bug bash.

> Address already in use error (un-killable kolibri process)
> 
> Tried various `kill` commands, looked with `ps` for kolibri processes, etc. 
> 
> ![image](https://user-images.githubusercontent.com/2367265/69924737-cd7b1400-1461-11ea-9507-a5aa85e10aa5.png)

### Expected behavior

clean shutdowns and killable processes

### User-facing consequences

unknown

### Errors and logs

```
INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Running Kolibri
INFO     Kolibri running on:

	http://100.64.21.150:8080/
	http://127.0.0.1:8080/

INFO     Started new JOBCHECKER thread ID#78e51be7a8904e6e9959b0c717547510
INFO     Started new SCHEDULECHECKER thread ID#e3a91cf24b4342019dcdbc81294f5a6d
INFO     Registering ourselves to zeroconf network with id 'ff04'...
INFO     Added signal handlers for cleaning up on exit
INFO     Starting Kolibri 0.13.0b1
INFO     ENGINE Bus STARTING
ERROR    ENGINE Error in HTTP server: shutting down
Traceback (most recent call last):
  File "/Users/jon/.pex/install/kolibri-0.13.0b1-py2.py3-none-any.whl.19456b23b69e6cc27c9d8496eaba0ee63f8170bb/kolibri-0.13.0b1-py2.py3-none-any.whl/kolibri/dist/cherrypy/process/servers.py", line 225, in _start_http_thread
    self.httpserver.start()
  File "/Users/jon/.pex/install/kolibri-0.13.0b1-py2.py3-none-any.whl.19456b23b69e6cc27c9d8496eaba0ee63f8170bb/kolibri-0.13.0b1-py2.py3-none-any.whl/kolibri/dist/cheroot/server.py", line 1532, in start
    raise socket.error(msg)
error: No socket could be created -- (('0.0.0.0', 8080): Address already in use)

INFO     ENGINE Bus STOPPING
INFO     ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) already shut down
INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
```

### Steps to reproduce

unknown

### Context

0.13.0 beta 1

**Comment by indirectlylit** [comment]
cc @rtibbles is this the same zombie issue?

**Comment by rtibbles** [comment]
Almost certainly.

**Comment by indirectlylit** [comment]
closing as duplicate
