### ISSUE TITLE
/api/discovery/networklocation ValueError

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6216]
### Observed behavior

When attempting to add a new network location, I get this error:

![image](https://user-images.githubusercontent.com/2367265/70190894-0efeff80-16ac-11ea-9491-4828be43d670.png)

### Expected behavior

should be able to add a new network location

### User-facing consequences

cannot import from network 

### Errors and logs

```
ERROR    Internal Server Error: /api/discovery/networklocation/
Traceback (most recent call last):
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 686, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/rest_framework/fields.py", line 962, in to_representation
    return int(value)
ValueError: invalid literal for int() with base 10: '3bd17cb4-3f3f-464d-a150-796cd0eb83bb'
ERROR    "GET /api/discovery/networklocation/?1575502549861=1575502549861 HTTP/1.1" 500 32657
```

### Steps to reproduce

* run devserver
* import from network

### Context

0.13.0 beta 3

**Comment by indirectlylit** [comment]
probably due to interactions with testing https://github.com/learningequality/kolibri/pull/6207
