### ISSUE TITLE
channel listings failed to be generated until restart of devserver

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6221]
### Observed behavior

My UI got stuck in the channel loading state. restarted the devserver, and things started working again

![image](https://user-images.githubusercontent.com/2367265/70251131-d1de5000-1733-11ea-8833-6e3e355e141a.png)

I saw one job in the DB with:

* `state`: `QUEUED`
* `queue`: `no_waiting`

![image](https://user-images.githubusercontent.com/2367265/70251200-ecb0c480-1733-11ea-9cef-7187c882f323.png)

Refreshing the page adds another one:

![image](https://user-images.githubusercontent.com/2367265/70251275-0baf5680-1734-11ea-99e6-b9b25f275994.png)

### Expected behavior

channel listings should always generate

### User-facing consequences

could not import

### Errors and logs

none initially. After restarting the server I saw:

```
ERROR    An error occurred during channel import: (sqlite3.DatabaseError) database disk image is malformed [SQL: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"] (Background on this error at: http://sqlalche.me/e/4xp6)
ERROR    Job a3719a64713542cabdd333d0861e6f3c raised an exception: Traceback (most recent call last):
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.DatabaseError: database disk image is malformed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 218, in wrap
    return f(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/job.py", line 180, in y
    raise e
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/job.py", line 176, in y
    result = func(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/management/commands/base.py", line 96, in handle
    return self.handle_async(*args, **options)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importchannel.py", line 209, in handle_async
    options["channel_id"], options["baseurl"], options["no_upgrade"]
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importchannel.py", line 96, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importchannel.py", line 133, in _transfer
    filetransfer, channel_id, dest, no_upgrade=no_upgrade
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importchannel.py", line 195, in _start_file_transfer
    retry_import(e, skip_404=False)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/utils/import_export_content.py", line 159, in retry_import
    raise e
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importchannel.py", line 180, in _start_file_transfer
    channel_id, self.is_cancelled
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importchannel.py", line 29, in import_channel_by_id
    channel_id, cancel_check=cancel_check
  File "/Users/d/Projects/le/k013x/kolibri/core/content/utils/channel_import.py", line 798, in import_channel_from_local_db
    import_manager = initialize_import_manager(channel_id, cancel_check=cancel_check)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/utils/channel_import.py", line 754, in initialize_import_manager
    source or get_content_database_file_path(channel_id)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/utils/channels.py", line 72, in read_channel_metadata_from_db_file
    source = Bridge(sqlite_file_path=channeldbpath)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/utils/sqlalchemybridge.py", line 283, in __init__
    db_matches_schema(BASES[self.schema_version], self.session)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/utils/check_schema_db.py", line 24, in db_matches_schema
    tables = iengine.get_table_names()
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 201, in get_table_names
    self.bind, schema, info_cache=self.info_cache)
  File "<string>", line 2, in get_table_names
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/reflection.py", line 54, in cache
    ret = fn(self, con, *args, **kw)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1160, in get_table_names
    rs = connection.execute(s)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2075, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 942, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1104, in _execute_text
    statement, parameters
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"] (Background on this error at: http://sqlalche.me/e/4xp6)

ERROR    Tried to update job with id a3719a64713542cabdd333d0861e6f3c with state FAILED but it was not found
```

### Steps to reproduce

I simply tried to import

### Context

0.13.0 beta 3

**Comment by rtibbles** [comment]
Seems like the worker process that should have been executing this died - and/or the job database got corrupted.

**Comment by indirectlylit** [comment]
closing because this occurred before lots of recent changes
