### ISSUE TITLE
Database image is malformed, and zombie attacks

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6247]
### Observed behavior

error during import

### Expected behavior

no errors

### User-facing consequences

unknown

### Errors and logs

```
ERROR    An error occurred during channel import: (sqlite3.DatabaseError) database disk image is malformed [SQL: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"] (Background on this error at: http://sqlalche.me/e/4xp6)
ERROR    Job 06e506288730459588547b07cec1499e raised an exception: Traceback (most recent call last):
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/Users/d/Projects/le/k013x/.venv/lib/python2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/d/Projects/le/k013x/.venv/lib/python2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
DatabaseError: (sqlite3.DatabaseError) database disk image is malformed [SQL: "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"] (Background on this error at: http://sqlalche.me/e/4xp6)
```

### Steps to reproduce

unknown

### Context

0.13.0 beta4

**Comment by rtibbles** [comment]
My suspicion is that this is most likely caused by zombie processes (also the pickle issue https://github.com/learningequality/kolibri/issues/6238 seems like it could be another symptom, with py2/3 crossover).

**Comment by benjaoming** [comment]
We also have seen an issue with `dbbackup` during an upgrade in 0.12.8: #6201 

As Richard notes: This was produced in a development, any chance that virtualenvs have switched between Python 2.7 and 3.x on the same `.kolibri` data?

**Comment by indirectlylit** [comment]
yes, it is possible

**Comment by indirectlylit** [comment]
Similarly reported by @jamalex during the bug bash:

https://www.notion.so/learningequality/Database-disk-image-is-malformed-when-importing-channel-created-and-recently-published-on-Studio-e668a9dfd5f24ab693295a06311a1cc1

> Restarting the server fixed this (`sudo service kolibri restart`).
> 
> But `sudo service kolibri stop` still left the server running, so it seems the `kolibri` service shouldn't have been running in the first place (see [https://www.notion.so/learningequality/0-13-0-bug-bash-2-775cb90a4bda4c59afe29a21b0153b59?p=6f4f88aa7ee844f39dfb1df458951ca0](https://www.notion.so/learningequality/0-13-0-bug-bash-2-775cb90a4bda4c59afe29a21b0153b59?p=6f4f88aa7ee844f39dfb1df458951ca0)).

error: 

```
INFO 2019-12-05 14:51:45,103 importchannel Downloading data for channel id 8ac01227c2ce4cf9a37ab75ab9f5e225
ERROR 2019-12-05 14:51:46,574 importchannel An error occurred during channel import: database disk image is malformed
ERROR 2019-12-05 14:51:47,337 worker Job 91475b29384641a3865db4d32b32daa3 raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
    result = future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/worker.py", line 222, in wrap
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/worker.py", line 218, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 180, in y
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 176, in y
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 96, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 209, in handle_async
    options["channel_id"], options["baseurl"], options["no_upgrade"]
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 96, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 133, in _transfer
    filetransfer, channel_id, dest, no_upgrade=no_upgrade
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 195, in _start_file_transfer
    retry_import(e, skip_404=False)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/import_export_content.py", line 159, in retry_import
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 178, in _start_file_transfer
    with db_task_write_lock:
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/recipes.py", line 172, in __enter__
    self.acquire()
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/recipes.py", line 147, in acquire
    value, count = self._cache.get(self._key, default=(None, 0))
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 1190, in get
    rows = self._sql(select, (db_key, raw, time.time())).fetchall()
sqlite3.DatabaseError: database disk image is malformed
```

**Comment by indirectlylit** [comment]
probably same underlying issue as https://github.com/learningequality/kolibri/issues/6238

**Comment by indirectlylit** [comment]
closing as "probably fixed". let's keep an eye out for zombies...
