### ISSUE TITLE
module 'le_utils.constants.format_presets' has no attribute 'SLIDESHOW_MANIFEST'

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6265]
### Observed behavior

Latest `release-v0.13.x` running on a 0.12.8 `.kolibri`, have run `pip install -r requirements.txt`.

I have `le-utils==0.1.20`.

### Errors and logs

```
➜  kolibri git:(release-v0.13.x) kolibri manage shell           
Traceback (most recent call last):
  File "/home/user/.virtualenvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/code/kolibri/kolibri/utils/cli.py", line 34, in <module>
    from kolibri.core.deviceadmin.utils import IncompatibleDatabase
  File "/code/kolibri/kolibri/core/deviceadmin/utils.py", line 13, in <module>
    from kolibri.core.tasks.main import scheduler
  File "/code/kolibri/kolibri/core/tasks/main.py", line 8, in <module>
    from kolibri.core.tasks.queue import Queue
  File "/code/kolibri/kolibri/core/tasks/queue.py", line 1, in <module>
    from kolibri.core.tasks.job import Job
  File "/code/kolibri/kolibri/core/tasks/job.py", line 5, in <module>
    from kolibri.core.tasks.utils import current_state_tracker
  File "/code/kolibri/kolibri/core/tasks/utils.py", line 10, in <module>
    from kolibri.deployment.default.cache import diskcache_location
  File "/code/kolibri/kolibri/deployment/default/cache.py", line 8, in <module>
    cache_options = OPTIONS["Cache"]
  File "/code/kolibri/kolibri/dist/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/code/kolibri/kolibri/dist/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/code/kolibri/kolibri/utils/conf.py", line 54, in __initialize_options
    return read_options_file(KOLIBRI_HOME)
  File "/code/kolibri/kolibri/utils/options.py", line 233, in read_options_file
    conf = ConfigObj(ini_path, configspec=get_configspec())
  File "/code/kolibri/kolibri/utils/options.py", line 201, in get_configspec
    for section, opts in option_spec.items():
  File "/code/kolibri/kolibri/dist/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/code/kolibri/kolibri/dist/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/code/kolibri/kolibri/utils/options.py", line 187, in __get_option_spec
    return extend_config_spec(base_option_spec)
  File "/code/kolibri/kolibri/plugins/utils/options.py", line 67, in extend_config_spec
    for plugin_instance in registered_plugins:
  File "/code/kolibri/kolibri/dist/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/code/kolibri/kolibri/dist/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/code/kolibri/kolibri/plugins/registry.py", line 131, in __initialize
    registry.register_plugins(config.ACTIVE_PLUGINS)
  File "/code/kolibri/kolibri/plugins/registry.py", line 79, in register_plugins
    plugin_object = initialize_kolibri_plugin(app)
  File "/code/kolibri/kolibri/plugins/utils/__init__.py", line 147, in initialize_kolibri_plugin
    plugin_module = importlib.import_module(plugin_name + ".kolibri_plugin")
  File "/home/user/.virtualenvs/kolibri/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/code/kolibri/kolibri/plugins/slideshow_viewer/kolibri_plugin.py", line 17, in <module>
    class SlideshowRenderAsset(content_hooks.ContentRendererHook):
  File "/code/kolibri/kolibri/plugins/slideshow_viewer/kolibri_plugin.py", line 19, in SlideshowRenderAsset
    presets = (format_presets.SLIDESHOW_MANIFEST,)
AttributeError: module 'le_utils.constants.format_presets' has no attribute 'SLIDESHOW_MANIFEST'
```

Content of plugins.json:

```
{
  "DISABLED_PLUGINS": [],
  "INSTALLED_PLUGINS": [
    "kolibri.plugins.media_player",
    "kolibri.plugins.pdf_viewer",
    "kolibri.plugins.user",
    "kolibri.plugins.epub_viewer",
    "kolibri.plugins.device",
    "kolibri.plugins.learn",
    "kolibri.plugins.setup_wizard",
    "kolibri.plugins.slideshow_viewer",
    "kolibri.plugins.default_theme",
    "kolibri.plugins.html5_viewer",
    "kolibri.plugins.coach",
    "kolibri_exercise_perseus_plugin",
    "kolibri.plugins.facility"
  ],
  "PLUGIN_VERSIONS": {
    "kolibri.plugins.coach": "0.13.0b3",
    "kolibri.plugins.default_theme": "0.13.0b3",
    "kolibri.plugins.device": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri.plugins.epub_viewer": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri.plugins.facility": "0.13.0b3",
    "kolibri.plugins.html5_viewer": "0.13.0b3",
    "kolibri.plugins.learn": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri.plugins.media_player": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri.plugins.pdf_viewer": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri.plugins.setup_wizard": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri.plugins.slideshow_viewer": "0.13.0b3",
    "kolibri.plugins.user": "0.13.0b4.dev0+git.39.gf61c65c4",
    "kolibri_exercise_perseus_plugin": "1.2.2a3"
  },
  "UPDATED_PLUGINS": []
}
```

`pip freeze`

```
➜  kolibri git:(release-v0.13.x) pip freeze
appdirs==1.4.3
argh==0.26.2
args==0.1.0
aspy.yaml==1.2.0
attrs==19.1.0
black==19.3b0
cached-property==1.5.1
certifi==2019.3.9
cfgv==1.6.0
chardet==3.0.4
cheroot==6.1.2
CherryPy==13.0.1
Click==7.0
clint==0.5.1
colorlog==3.2.0
configobj==5.0.6
coreapi==2.3.3
coreschema==0.0.4
diskcache==4.1.0
Django==1.11.23
django-debug-panel==0.8.3
django-debug-toolbar==1.9.1
django-filter==1.1.0
django-ipware==1.1.6
django-js-asset==1.2.2
django-js-reverse==0.9.1
django-mptt==0.9.1
django-oidc-provider==0.7.0
django-redis-cache==2.0.0
django-rest-swagger==2.2.0
djangorestframework==3.9.1
djangorestframework-csv==2.1.0
docopt==0.6.2
enum-compat==0.0.2
flake8==3.5.0
flake8-builtins==1.4.1
fonttools==3.29.0
future==0.16.0
futures==3.1.1
html5lib==1.0.1
iceqube==0.4
identify==1.4.2
idna==2.7
ifcfg==0.19
importlib-metadata==0.18
importlib-resources==1.0.2
itypes==1.1.0
Jinja2==2.10.1
jsonfield==2.0.2
-e git+git@github.com:benjaoming/kolibri.git@f61c65c46468d2ac47432e41922f74588127d300#egg=kolibri
kolibri-exercise-perseus-plugin==1.2.2a3
le-utils==0.1.20
livereload==2.6.0
MarkupSafe==1.1.1
mccabe==0.6.1
Metafone==0.5
morango==0.4.9
more-itertools==7.0.0
nodeenv==1.3.3
openapi-codec==1.3.2
packaging==19.0
pathtools==0.1.2
pluggy==0.9.0
port-for==0.3.1
portend==2.4
porter2stemmer==1.0
pre-commit==1.15.1
py==1.8.0
pyasn1==0.4.5
pycodestyle==2.3.1
pycountry==17.5.14
pycryptodomex==3.8.2
pyflakes==1.6.0
pyjwkest==1.4.2
pyparsing==2.4.0
python-dateutil==2.7.5
pytz==2018.5
PyYAML==5.1
redis==3.2.1
requests==2.21.0
requests-toolbelt==0.8.0
rsa==3.4.2
semver==2.8.1
sentry-sdk==0.7.9
simplejson==3.16.0
six==1.11.0
sphinx-autobuild==0.7.1
SQLAlchemy==1.2.10
sqlparse==0.3.0
tabulate==0.8.2
tempora==1.12
toml==0.10.0
tornado==6.0.2
tox==3.1.3
tqdm==4.24.0
tzlocal==1.5.1
ua-parser==0.8.0
unicodecsv==0.14.1
uritemplate==3.0.0
urllib3==1.24.3
user-agents==1.1.0
virtualenv==16.5.0
watchdog==0.9.0
webencodings==0.5.1
zeroconf-py2compat==0.19.3
zipp==0.5.1
```

### Steps to reproduce

n/a

**Comment by indirectlylit** [comment]
@nucleogenesis curious that we haven't seen this before. I don't actually see `SLIDESHOW_MANIFEST` in `format_presets`. thoughts?

**Comment by rtibbles** [comment]
https://github.com/learningequality/le-utils/blob/master/le_utils/constants/format_presets.py#L66

**Comment by indirectlylit** [comment]
search failed me

**Comment by rtibbles** [comment]
It is present in version `0.1.20` of le-utils also, this is most likely caused by out of date pyc files.

**Comment by benjaoming** [comment]
Ay this was caused by artifacts in the `dist/` folder. Sorries.
