### ISSUE TITLE
database locking during use of the mac app

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6334]
### Observed behavior

reported by @jtamiace during bug bash 3 (beta 5).

Unsure if the issue is still persisting. cc @micahscopes  @rtibbles 

### Expected behavior

no DB locks

### User-facing consequences

Cannot load

* Reports —> Quizzes
* Plan —> Quizzes
* Reports —> Learners

### Errors and logs

snippet

```
[37mINFO     Started new JOBCHECKER thread ID#6a8af5f5ce0348c5b606e4a99743914c[0m
[37mINFO     Started new JOBCHECKER thread ID#bd4016a401334a0baf5299b7bf914af5[0m
[37mINFO     Started new SCHEDULECHECKER thread ID#7a85562b06a64a618cc77a25e4e1bf0b[0m
[37mINFO     Registering ourselves to zeroconf network with id 'c4e8ee42361476268fa8df826080d91d'...[0m
Error pinging Kolibri server: <urlopen error [Errno 61] Connection refused>
Kolibri server not yet started, checking again in one second...
[33mWARNING  Error adding signal handlers for cleaning up on exit[0m
[37mINFO     Starting Kolibri 0.13.0b5[0m
[37mINFO     ENGINE Bus STARTING[0m
Starting new HTTPS connection (1): telemetry.learningequality.org:443
[37mINFO     ENGINE Serving on http://0.0.0.0:5000[0m
[37mINFO     ENGINE Bus STARTED[0m
https://telemetry.learningequality.org:443 "POST /api/v1/pingback HTTP/1.1" 200 40
[37mINFO     Ping succeeded! (response: {'id': 499581, 'messages': []})[0m
[37mINFO     Kolibri instance '9c461c2b46fb492ba491b03a172b8934' joined zeroconf network; service info: {'id': '9c461c2b46fb492ba491b03a172b8934', 'ip': '192.168.1.7', 'local': False, 'port': 8000, 'host': '9c461c2b46fb492ba491b03a172b8934.kolibri.local', 'base_url': 'http://192.168.1.7:8000/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.0b4.dev0+git.39.gf61c65c4', 'instance_id': '9c461c2b46fb492ba491b03a172b8934', 'device_name': 'Rafaels-MacBook-Pro-3.local', 'operating_system': 'Darwin'}
[0m
Persisted View State: {}
[37mINFO     127.0.0.1 - - "GET /static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.13.0b5.js HTTP/1.1" 200 354408 "http://localhost:5000/en/user/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko)"[0m
[37mINFO     Kolibri instance 'cbc52f9c7ece0c274a00749b1134e3ee' joined zeroconf network; service info: {'id': 'cbc52f9c7ece0c274a00749b1134e3ee', 'ip': '192.168.1.34', 'local': False, 'port': 5000, 'host': 'cbc52f9c7ece0c274a00749b1134e3ee.kolibri.local', 'base_url': 'http://192.168.1.34:5000/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.0b5', 'instance_id': 'cbc52f9c7ece0c274a00749b1134e3ee', 'device_name': 'Khangs-MacBook-Pro.local', 'operating_system': 'Darwin'}
[0m
Starting new HTTPS connection (1): telemetry.learningequality.org:443
https://telemetry.learningequality.org:443 "POST /api/v1/statistics HTTP/1.1" 200 22
Exception in thread zeroconf-ServiceBrowser_Kolibri._sub._http._tcp.local.:
Traceback (most recent call last):
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/query.py", line 480, in update_or_create
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/query.py", line 380, in get
kolibri.core.discovery.models.DoesNotExist: DynamicNetworkLocation matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/backends/utils.py", line 64, in execute
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/backends/sqlite3/base.py", line 328, in execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.pyc", line 916, in _bootstrap_inner
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/zeroconf.py", line 1443, in run
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/zeroconf.py", line 1384, in <lambda>
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/zeroconf.py", line 1280, in fire
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/zeroconf.py", line 1353, in on_change
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/core/discovery/utils/network/search.py", line 137, in add_service
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/core/discovery/models.py", line 95, in update_or_create
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/query.py", line 484, in update_or_create
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/query.py", line 500, in _create_object_from_params
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/query.py", line 394, in create
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/core/discovery/models.py", line 114, in save
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/base.py", line 808, in save
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/base.py", line 838, in save_base
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/base.py", line 924, in _save_table
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/base.py", line 963, in _do_insert
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/manager.py", line 85, in manager_method
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/query.py", line 1079, in _insert
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/models/sql/compiler.py", line 1112, in execute_sql
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/backends/utils.py", line 64, in execute
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/utils.py", line 94, in __exit__
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/utils/six.py", line 685, in reraise
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/backends/utils.py", line 64, in execute
  File "/Applications/Kolibri.app/Contents/Resources/lib/python3.6/kolibri/dist/django/db/backends/sqlite3/base.py", line 328, in execute
django.db.utils.OperationalError: database is locked
```

full logs:

[kolibri.txt](https://github.com/learningequality/kolibri/files/3966095/kolibri.txt)
[kolibri-app.txt](https://github.com/learningequality/kolibri/files/3966096/kolibri-app.txt)

### Steps to reproduce

unknown

### Context

mac app

0.13.0 beta 5

**Comment by indirectlylit** [comment]
migrating to #6408
