### ISSUE TITLE
Occasional REMOTEIMPORTCHANNEL errors before viewing topics/resources to import

### ISSUE THREAD

**Issue by jonboiser** [learningequality/kolibri#6350]
# Observed behavior

When starting REMOTECHANNELIMPORT tasks from Studio, they will occasionally fail, showing an error page before getting to the topics list. ~This seems to happen after the first time you check out the channel (meaning that the sqlite3 file for the channel has been downloaded already)~ Seems to happen more reliably if you don't already have the sqlite file, based on recent experience.

The response from the task queue has these two tasks (in this order)

Similar to the errors seen in #6282 
```
exception: "[Errno 2] No such file or directory: '/Users/jon/.kolibri/content/databases/02cf4629326743af81b4a3e9836eaa10.sqlite3.transfer'"

```

A different kind of error
```
traceback: "Traceback (most recent call last):
File "/Users/jon/Github/kolibri/kolibri/core/tasks/worker.py", line 69, in handle_finished_future
result = future.result()
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 428, in result
return self.__get_result()
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/Users/jon/Github/kolibri/kolibri/core/tasks/worker.py", line 222, in wrap
raise e
File "/Users/jon/Github/kolibri/kolibri/core/tasks/worker.py", line 218, in wrap
return f(*args, **kwargs)
File "/Users/jon/Github/kolibri/kolibri/core/tasks/job.py", line 180, in y
# If any error occurs, clear the job tracker and reraise
File "/Users/jon/Github/kolibri/kolibri/core/tasks/job.py", line 176, in y
File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
return command.execute(*args, **defaults)
File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
output = self.handle(*args, **options)
File "/Users/jon/Github/kolibri/kolibri/core/tasks/management/commands/base.py", line 96, in handle
return self.handle_async(*args, **options)
File "/Users/jon/Github/kolibri/kolibri/core/content/management/commands/importchannel.py", line 209, in handle_async
options["channel_id"], options["baseurl"], options["no_upgrade"]
File "/Users/jon/Github/kolibri/kolibri/core/content/management/commands/importchannel.py", line 96, in download_channel
self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
File "/Users/jon/Github/kolibri/kolibri/core/content/management/commands/importchannel.py", line 133, in _transfer
filetransfer, channel_id, dest, no_upgrade=no_upgrade
File "/Users/jon/Github/kolibri/kolibri/core/content/management/commands/importchannel.py", line 195, in _start_file_transfer
retry_import(e, skip_404=False)
File "/Users/jon/Github/kolibri/kolibri/core/content/utils/import_export_content.py", line 159, in retry_import
raise e
File "/Users/jon/Github/kolibri/kolibri/core/content/management/commands/importchannel.py", line 180, in _start_file_transfer
channel_id, self.is_cancelled
File "/Users/jon/Github/kolibri/kolibri/core/content/management/commands/importchannel.py", line 29, in import_channel_by_id
channel_id, cancel_check=cancel_check
File "/Users/jon/Github/kolibri/kolibri/core/content/utils/channel_import.py", line 804, in import_channel_from_local_db
channel = ChannelMetadata.objects.get(id=channel_id)
File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/db/models/query.py", line 380, in get
self.model._meta.object_name
kolibri.core.content.models.DoesNotExist: ChannelMetadata matching query does not exist.
"

```
### Expected behavior

On the backend, no `importchannel` errors esp. if the sqlite file has been downloaded already.

On the front-end, can maybe try to avoid starting this task to begin with, but the backend problem should be fixed too.

### User-facing consequences

…

### Errors and logs

…

### Steps to reproduce

1. From Device > Channels page, 1. Click Import, 2. Click Kolibri Studio, 3. Choose a channel you've seen already once, 4. get error 5. if you didn't get an error, go back between the channels list page and the select topics page,

### Context
Kolibri 0.13 beta 7

**Comment by jonboiser** [comment]
People are having trouble reproducing this, so moving the milestone while I figure out what's specific about my environment that might be causing this.

**Comment by rtibbles** [comment]
Not reproduced recently, closing.
