### ISSUE TITLE
kolibri stuck if STATUS_FAILED_TO_START

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6457]
### Observed behavior

CC: @jredrejo 

One of the scenarios I ran into with some startup issues on a Raspberry Pi was a start lock without a PID file. This creates a status `STATUS_FAILED_TO_START`.

I will open a PR for this.

Here is an example of a traceback where `service kolibri-server restart` stops working because it cannot stop the Kolibri.

```
Jan 13 19:25:10 raspberrypi kolibri-server[10970]: start-stop-daemon: matching on world-writable pidfile /var/run/kolibri-server/uwsgi.pid is insecure
Jan 13 19:25:10 raspberrypi systemd[1]: Reloading A high performance web server and a reverse proxy server.
Jan 13 19:25:10 raspberrypi systemd[1]: Reloaded A high performance web server and a reverse proxy server.
Jan 13 19:25:11 raspberrypi systemd[1]: Stopping LSB: kolibri daemon, an offline education platform...
Jan 13 19:25:12 raspberrypi systemd[1]: Started Session c25 of user pi.
Jan 13 19:25:12 raspberrypi kolibri[11084]: WARNING:root:No C Extensions available for this platform.
Jan 13 19:25:15 raspberrypi kolibri[11084]: #033[37mINFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base#033[0m
Jan 13 19:25:16 raspberrypi kolibri[11084]: #033[31mERROR    During graceful shutdown, server says: Failed to start (check log file: /home/pi/.kolibri/logs/daemon.txt) (6)#033[0m
Jan 13 19:25:16 raspberrypi kolibri[11084]: #033[31mERROR    Not responding, killing with force#033[0m
Jan 13 19:25:16 raspberrypi kolibri[11084]: #033[31mERROR    Could not read .pid file
Jan 13 19:25:16 raspberrypi kolibri[11084]: #033[0m
Jan 13 19:25:16 raspberrypi kolibri[11084]: Traceback (most recent call last):
Jan 13 19:25:16 raspberrypi kolibri[11084]:   File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 327, in stop
Jan 13 19:25:16 raspberrypi kolibri[11084]:     pid, __, __ = server.get_status()
Jan 13 19:25:16 raspberrypi kolibri[11084]:   File "/usr/lib/python3/dist-packages/kolibri/utils/server.py", line 399, in get_status
Jan 13 19:25:16 raspberrypi kolibri[11084]:     raise NotRunning(STATUS_FAILED_TO_START)
Jan 13 19:25:16 raspberrypi kolibri[11084]: kolibri.utils.server.NotRunning
Jan 13 19:25:16 raspberrypi kolibri[11084]: During handling of the above exception, another exception occurred:
Jan 13 19:25:16 raspberrypi kolibri[11084]: Traceback (most recent call last):
Jan 13 19:25:16 raspberrypi kolibri[11084]:   File "/usr/bin/kolibri", line 11, in <module>
Jan 13 19:25:16 raspberrypi kolibri[11084]:     load_entry_point('kolibri==0.12.9', 'console_scripts', 'kolibri')()
Jan 13 19:25:16 raspberrypi kolibri[11084]:   File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 626, in main
Jan 13 19:25:16 raspberrypi kolibri[11084]:     stop()
Jan 13 19:25:16 raspberrypi kolibri[11084]:   File "/usr/lib/python3/dist-packages/kolibri/utils/cli.py", line 349, in stop
Jan 13 19:25:16 raspberrypi kolibri[11084]:     server.stop(force=True)
Jan 13 19:25:16 raspberrypi kolibri[11084]:   File "/usr/lib/python3/dist-packages/kolibri/utils/server.py", line 221, in stop
Jan 13 19:25:16 raspberrypi kolibri[11084]:     os.unlink(PID_FILE)
Jan 13 19:25:16 raspberrypi kolibri[11084]: FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/.kolibri/server.pid'
```

### Expected behavior

We should not try to remove `PID_FILE` if it does not exist.

### User-facing consequences

I think this can be created, since it's either a race condition or due to terminated system services.

### Errors and logs

n/a

### Steps to reproduce

n/a

### Context

0.12 and 0.13

**Comment by benjaoming** [comment]
Okay, I was fixing the issue on an old release-v0.13.x and there is some new behavior that I didn't anticipate in https://github.com/learningequality/kolibri/pull/6286
