### ISSUE TITLE
disk I/O error and sqlite3.OperationalError: cannot rollback - no transaction is active

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6460]
# Observed behavior

Running into this with kolibri-server on a Raspberry Pi when accessing Import listing for a channel.

NB! The issue was fixed / not reproducible after restarting the kolibri background service (i.e. kolibri w/o CherryPy HTTP service)

Channel: Tried Sikana English and Tessa, both failing with the same issue. I have plenty of disk space and checked that everything was writable. No upgrades had been done prior to this.

The visual part... first this:

![image](https://user-images.githubusercontent.com/374612/72297789-fa276b80-365c-11ea-99c8-52a8b7a2d54c.png)

Then this:

![image](https://user-images.githubusercontent.com/374612/72297739-d2d09e80-365c-11ea-9807-0e256be3a689.png)

```
TypeError: An id must be specified
```

### Expected behavior

Errors be gone

### User-facing consequences

Can't import channels

### Errors and logs

```

INFO 2020-01-13 22:37:48,737 importchannel Downloading data for channel id a9b25ac9814742c883ce1b0579448337
ERROR 2020-01-13 22:37:50,003 importchannel An error occurred during channel import: cannot rollback - no transaction is active
ERROR 2020-01-13 22:37:50,286 worker Job 6612074c0523480080968960a01c8bf7 raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 762, in _transact
    yield sql, filenames.append
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 734, in transact
    yield
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/recipes.py", line 147, in acquire
    value, count = self._cache.get(self._key, default=(None, 0))
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 1190, in get
    rows = self._sql(select, (db_key, raw, time.time())).fetchall()
sqlite3.OperationalError: disk I/O error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/worker.py", line 73, in handle_finished_future
    result = future.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/worker.py", line 228, in wrap
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/worker.py", line 224, in wrap
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 184, in y
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 178, in y
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 96, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 209, in handle_async
    options["channel_id"], options["baseurl"], options["no_upgrade"]
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 96, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 133, in _transfer
    filetransfer, channel_id, dest, no_upgrade=no_upgrade
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 195, in _start_file_transfer
    retry_import(e, skip_404=False)
  File "/usr/lib/python3/dist-packages/kolibri/core/content/utils/import_export_content.py", line 159, in retry_import
    raise e
  File "/usr/lib/python3/dist-packages/kolibri/core/content/management/commands/importchannel.py", line 178, in _start_file_transfer
    with db_task_write_lock:
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/recipes.py", line 172, in __enter__
    self.acquire()
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/recipes.py", line 153, in acquire
    return
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 734, in transact
    yield
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/kolibri/dist/diskcache/core.py", line 767, in _transact
    sql('ROLLBACK')
sqlite3.OperationalError: cannot rollback - no transaction is active
```

### Steps to reproduce

Not sure what I'm doing wrong with this installation. It's been maintained through a series of upgrades and experiments, but the fact that the problem went away after restarting the background service confuses me a bit.

### Context

kolibri 0.13.0
kolibri-server 0.3.6

**Comment by rtibbles** [comment]
We've not seen any replications of this recently, closing for now.
