### ISSUE TITLE
unable to see channel tree and import content from disk with postgresql

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6541]
### Observed behavior

When I'm trying to import channel from studio/disk, I'm not able to see the detailed channel tree, although I'm still able to import the entire channel by clicking `Select all`.

<img width="1211" alt="Screen Shot 2020-02-12 at 10 32 20 AM" src="https://user-images.githubusercontent.com/19424916/74365661-5fb56780-4d83-11ea-97e6-8161e5f7dae0.png">

I can confirm that this is not an issue in 0.12.9. It doesn't exist in 0.13.0 with sqlite either.

Another issue is that I'm unable to import content from disk.

### Expected behavior

Users should be able to see what content is available in the channel

### User-facing consequences

Users don't know what content is available

### Errors and logs

For the second error:
```
ERROR    Internal Server Error: /device/api/importexportsizeview
Traceback (most recent call last):
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/plugins/device/api.py", line 114, in post
    peer_id=peer_id,
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/core/content/utils/import_export_content.py", line 76, in get_nodes_to_transfer
    nodes_to_include = nodes_to_include.filter_by_uuids(file_based_node_id_list)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/core/mixins.py", line 133, in filter_by_uuids
    return self._by_uuids(ids, validate, id_field, True)
  File "/Users/lingyiwang/.venvs/test/lib/python2.7/site-packages/kolibri/core/mixins.py", line 150, in _by_uuids
    UUID(identifier, version=4)
  File "/usr/local/Cellar/python@2/2.7.17_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/uuid.py", line 133, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'UUID' object has no attribute 'replace'
```

### Steps to reproduce

1. set up postgres connection
2. import a channel

### Context

Kolibri version: 0.13.0
Operating system: MacOSX
Database: postgresql 12.1

**Comment by lyw07** [comment]
fixed in #6544
