### ISSUE TITLE
Migrating from 0.6 to 0.13 breaks

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#6543]
### Observed behavior

Using a 0.6 database, trying to run migrations using the 0.13 codebase threw an exception, seemingly because there's no "default facility".

### Expected behavior

Successful upgrade migration.

### User-facing consequences

Inability to upgrade, being left in an intermediate state.

### Errors and logs
```
  Applying device.0005_auto_20191203_0951...Traceback (most recent call last):
  File "/home/jamalex/.local/bin/kolibri", line 10, in <module>
    sys.exit(main())
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/utils/cli.py", line 237, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/utils/cli.py", line 650, in manage
    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/dist/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/jamalex/.local/lib/python2.7/site-packages/kolibri/core/device/migrations/0005_auto_20191203_0951.py", line 16, in migrate_allow_guest_access
    allow_guest_access = default_facility.dataset.allow_guest_access
AttributeError: 'NoneType' object has no attribute 'dataset'
```

…

### Steps to reproduce

(private) database example can be provided upon request.

**Comment by jamalex** [comment]
Flagging for @bjester since it looks like he may be familiar with the migration.

**Comment by rtibbles** [comment]
Won't fix!
