### ISSUE TITLE
did not see progress importing a large channel, and then could not cancel it (maybe devserver?)

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6562]
### Observed behavior

* Tried to import KA Bulgarian. It was downloading from the network, but I didn't see any progress changing. (stayed on 0%)
* Tried to cancel it, and it got stuck in this state:

![image](https://user-images.githubusercontent.com/2367265/74490016-0ed56a00-4e7c-11ea-8274-fa9fd8597e30.png)

### Expected behavior

both importing and canceling work as expected

### User-facing consequences

Unknown. This may have been a devserver-specific interaction

### Errors and logs

no errors except that when trying to cancel, I got this:

```
CRITICAL:concurrent.futures:Exception in worker
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 224, in wrap
    return f(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/job.py", line 178, in y
    result = func(*args, **kwargs)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/api.py", line 710, in _remoteimport
    call_command(
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/le/k013x/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/management/commands/base.py", line 96, in handle
    return self.handle_async(*args, **options)
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importcontent.py", line 428, in handle_async
    self.download_content(
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importcontent.py", line 152, in download_content
    self._transfer(
  File "/Users/d/Projects/le/k013x/kolibri/core/content/management/commands/importcontent.py", line 351, in _transfer
    self.cancel()
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/management/commands/base.py", line 122, in cancel
    return self.check_for_cancel()
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/management/commands/base.py", line 104, in check_for_cancel
    self.job.check_for_cancel()
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/job.py", line 139, in check_for_cancel
    self.check_for_cancel_method(self.job_id)
  File "/Users/d/Projects/le/k013x/kolibri/core/tasks/worker.py", line 208, in _check_for_cancel
    raise UserCancelledError()
kolibri.core.tasks.exceptions.UserCancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 80, in _worker
    work_item.run()
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 59, in run
    self.future.set_exception(exc)
  File "/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 539, in set_exception
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
concurrent.futures._base.InvalidStateError: CANCELLED: <Future at 0x10c452f10 state=cancelled>
```

### Steps to reproduce

* Ran devserver locally
* Started import of KA Bulgarian
* Made a local Python change which restarted the Django process
* Tried canceling

### Context

0.13.1 beta 2

**Comment by jonboiser** [comment]
The task might have gotten hung up for various reasons, but I'm noting that not every task-creating function in `core.tasks.api` has handlers for `UserCancelledError` (`_localexport` does).

Maybe we need to add handlers for this error for _all_ tasks

**Comment by radinamatic** [comment]
Tried to import the full KA Bulgarian channel on Windows 10 with beta2 EXE asset installed. Import started correctly and arrived to 4%, when I decided to cancel. It took full 5 minutes for the cancel task to finish.

![cancel-import](https://user-images.githubusercontent.com/1457929/74491675-9a76e700-4ecc-11ea-95ff-88adcf3b83fa.gif)

**Comment by pcenov** [comment]
Cannot replicate the initially reported issue in 0.15.1.
As noted by @radinamatic currently the Channel import starts correctly and then when I hit the Cancel button I have to wait for about 3 minutes for the task to finish:
![2022-03-24_14-27-13](https://user-images.githubusercontent.com/79847249/159916345-2cbf7b2f-5bb0-4aa3-a97b-d1b9069edc89.png)

**Comment by rtibbles** [comment]
I think the original issue as reported is fixed (and I think was actually a consequence of running the old dev server by itself, which did not also run the task runner).

I'm going to close this - @radinamatic @pcenov if you think the long time to cancel is sufficiently problematic to require further investigation, please file a follow up issue for that!
