### ISSUE TITLE
Logged zeroconf ERROR on exit (edge case?)

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#6610]
### Observed behavior

When exiting with `CTRL+C` from `kolibri start --foreground`, an error is logged in rare cases.

CC: @micahscopes - you might understand this quicker than me?

Ref: https://github.com/learningequality/kolibri/pull/6113

### Expected behavior

Exits cleanly

### User-facing consequences

None, currently we log this edge case. So either it's anticipated and should be silenced, or we should figure out why it happens?

### Errors and logs

```
ERROR:zeroconf:Unknown error, possibly benign: ValueError('list.remove(x): x not in list',)
Traceback (most recent call last):
  File "/home/benjamin/.virtualenvs/kolibri/lib/python3.6/site-packages/zeroconf.py", line 2089, in remove_listener
    self.listeners.remove(listener)
ValueError: list.remove(x): x not in list
```

### Steps to reproduce

Unfortunately, this was a rare incident, so I cannot reproduce it.

### Context

0.13.x branch

**Comment by benjaoming** [comment]
Potentially related odd exit behaviors reported here: https://community.learningequality.org/t/stop-job-on-raspberry-pi-when-shutting-down/1482/9?

CC: @jamalex

**Comment by benjaoming** [comment]
Here's another error, on 0.13.2.dev

```
INFO     ENGINE Bus STOPPING
INFO     ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
INFO     Kolibri instance 'bb83e66afbf6e41049f5fe0d5ff1a45f' has left the zeroconf network.
WARNING  JOBCHECKER shut down event received; closing.
WARNING  JOBCHECKER shut down event received; closing.
WARNING  SCHEDULECHECKER shut down event received; closing.
^CINFO     ENGINE Caught signal SIGINT.
INFO     ENGINE Bus STOPPING
INFO     ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) already shut down
INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
ERROR    ENGINE Error in 'stop' listener <bound method ServicesPlugin.stop of <kolibri.utils.server.ServicesPlugin object at 0x7f50556a2128>>
Traceback (most recent call last):
  File "/home/user/.virtualenvs/kolibri-test-ipad/lib/python3.6/site-packages/kolibri/dist/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/home/user/.virtualenvs/kolibri-test-ipad/lib/python3.6/site-packages/kolibri/utils/server.py", line 117, in stop
    unregister_zeroconf_service()
  File "/home/user/.virtualenvs/kolibri-test-ipad/lib/python3.6/site-packages/kolibri/core/discovery/utils/network/search.py", line 208, in unregister_zeroconf_service
    ZEROCONF_STATE["zeroconf"].close()
  File "/home/user/.virtualenvs/kolibri-test-ipad/lib/python3.6/site-packages/kolibri/dist/zeroconf.py", line 2264, in close
    self.remove_all_service_listeners()
  File "/home/user/.virtualenvs/kolibri-test-ipad/lib/python3.6/site-packages/kolibri/dist/zeroconf.py", line 1869, in remove_all_service_listeners
    self.remove_service_listener(listener)
  File "/home/user/.virtualenvs/kolibri-test-ipad/lib/python3.6/site-packages/kolibri/dist/zeroconf.py", line 1864, in remove_service_listener
    del self.browsersKeyError: <kolibri.core.discovery.utils.network.search.KolibriZeroconfListener object at 0x7f5054c62cc0>
```

**Comment by rtibbles** [comment]
No recent reports, closing. Please reopen if it recurs.
