### ISSUE TITLE
network discovery error on Windows 10: JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#6615]
### Observed behavior

On startup, observed unhandled JSON errors when running Kolibri in foreground in Windows

### Expected behavior

No unhandled error

### User-facing consequences

* Might prevent network discovery?
* Unhandled exceptions will cause confusion while debugging

### Errors and logs

```
C:\Users\IEUser>kolibri start --foreground
[37mINFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE[0m
[37mINFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base[0m
[37mINFO     Running Kolibri[0m
[37mINFO     Kolibri running on:
[0m
        http://10.0.2.15:8080/

[37mINFO     Starting Kolibri 0.13.1[0m
[37mINFO     ENGINE Listening for SIGINT.[0m
[37mINFO     ENGINE Listening for SIGTERM.[0m
[37mINFO     ENGINE Bus STARTING[0m
[37mINFO     Started new JOBCHECKER thread ID#0d0388159e174e9093a7ed176eb108f8[0m
[37mINFO     Started new JOBCHECKER thread ID#a2fe0081d5044727baeb1ba17e90d57d[0m
[37mINFO     Started new SCHEDULECHECKER thread ID#3d24b5cbdb144373b7518c4530b22d52[0m
[37mINFO     Registering ourselves to zeroconf network with id 'e6bba31a6ecc89563edecea04f4dad57'...[0m
Exception in thread zeroconf-ServiceBrowser_Kolibri._sub._http._tcp.local.:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1443, in run
    handler(self.zc)
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1384, in <lambda>
    state_change=state_change,
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1280, in fire
    h(**kwargs)
  File "C:\Python34\lib\site-packages\kolibri\dist\zeroconf.py", line 1353, in on_change
    listener.add_service(*args)
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\network\search.py", line 137, in add_service
    bytes.decode(key): json.loads(val) for (key, val) in info.properties.items()
  File "C:\Python34\lib\site-packages\kolibri\core\discovery\utils\network\search.py", line 137, in <dictcomp>
    bytes.decode(key): json.loads(val) for (key, val) in info.properties.items()
  File "C:\Python34\lib\json\__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

[37mINFO     ENGINE Serving on http://0.0.0.0:8080[0m
[37mINFO     ENGINE Bus STARTED[0m
[37mINFO     Ping succeeded! (response: {'messages': [], 'id': 648632})[0m
```

### Steps to reproduce

* Installed Kolibri on a win10 VM
* Shut it down via the GUI
* Opened a command promp
* Ran `kolibri start --foreground`

### Context

0.13.1

**Comment by indirectlylit** [comment]
cc @micahscopes curious if you've encountered something like this before?

**Comment by jamalex** [comment]
I'm seeing this on a RACHEL-Plus running  0.14.6:
```
INFO     Registering ourselves to zeroconf network with id '91951bd8e9c6443ad2ab06b7e40abbc1'...
Exception in thread zeroconf-ServiceBrowser_Kolibri._sub._http._tcp.local.:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3/dist-packages/kolibri/dist/zeroconf.py", line 1444, in run
    handler(self.zc)
  File "/usr/lib/python3/dist-packages/kolibri/dist/zeroconf.py", line 1385, in <lambda>
    state_change=state_change,
  File "/usr/lib/python3/dist-packages/kolibri/dist/zeroconf.py", line 1281, in fire
    h(**kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/zeroconf.py", line 1354, in on_change
    listener.add_service(*args)
  File "/usr/lib/python3/dist-packages/kolibri/core/discovery/utils/network/search.py", line 137, in add_service
    bytes.decode(key): json.loads(val) for (key, val) in info.properties.items()
  File "/usr/lib/python3/dist-packages/kolibri/core/discovery/utils/network/search.py", line 137, in <dictcomp>
    bytes.decode(key): json.loads(val) for (key, val) in info.properties.items()
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

INFO     ENGINE Serving on http://0.0.0.0:9090
```

`mdns-scan` doesn't seem to show any other Kolibri instances on the local network.

**Comment by rtibbles** [comment]
Seems like this error will only occur on Python 3.4 and 3.5 - so this should no longer affect Windows installer versions of Kolibri that now use Python 3.6. https://docs.python.org/3/whatsnew/3.6.html#json

**Comment by radinamatic** [comment]
Out of curiosity I tested and can confirm it's not extant on `0.14.7-rc7` on Windows 10! 👍🏽 

![Win10 (start)  Running  - Oracle VM VirtualBox_076](https://user-images.githubusercontent.com/1457929/115282832-f0879000-a14a-11eb-8f51-6080ce0fb2f2.png)
