### ISSUE TITLE
Kolibri server won't start

### ISSUE THREAD

**Issue by astroanax** [learningequality/kolibri#6728]
### Observed behavior

So when I was unable to use Kolibri on my browser, I decided to check the status of kolibri. This is what the terminal returned - 

```
WARNING:root:No C Extensions available for this platform.

Failed to start (check log file: /data/data/com.termux/files/home/.kolibri/logs/daemon.txt) (6)
```

### Expected behavior

I expected it to start a session on http://192.168.0.113:8080/, but chrome says this site can't be reached

### User-facing consequences

…

### Errors and logs

Here is the log from daemon.txt

```
INFO     Starting Kolibri 0.13.1
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/_pslinux.py", line 167, in wrapper
    return fun(self, *args, **kwargs)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/_pslinux.py", line 251, in create_time
    bt = BOOT_TIME or boot_time()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/_pslinux.py", line 191, in boot_time
    with open_binary(path) as f:
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/common.py", line 147, in open_binary
    return io.open(fname, "rb", **kwargs)
PermissionError: [Errno 13] Permission denied: '/proc/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/kolibri-0.13.1.pex/.bootstrap/_pex/pex.py", line 349, in execute
  File "/data/data/com.termux/files/home/kolibri-0.13.1.pex/.bootstrap/_pex/pex.py", line 281, in _wrap_coverage
  File "/data/data/com.termux/files/home/kolibri-0.13.1.pex/.bootstrap/_pex/pex.py", line 312, in _wrap_profiling
  File "/data/data/com.termux/files/home/kolibri-0.13.1.pex/.bootstrap/_pex/pex.py", line 394, in _execute
  File "/data/data/com.termux/files/home/kolibri-0.13.1.pex/.bootstrap/_pex/pex.py", line 506, in execute_entry
  File "/data/data/com.termux/files/home/kolibri-0.13.1.pex/.bootstrap/_pex/pex.py", line 513, in execute_module
  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 209, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/data/data/com.termux/files/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/__main__.py", line 11, in <module>
    main(args=sys.argv[1:])
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/cli.py", line 243, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/cli.py", line 486, in start
    server.start(port=port, serve_http=serve_http)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/server.py", line 151, in start
    run_server(port=port, serve_http=serve_http)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/server.py", line 279, in run_server
    configure_http_server(port)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/server.py", line 207, in configure_http_server
    from kolibri.deployment.default.wsgi import application
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/deployment/default/wsgi.py", line 24, in <module>
    application = get_wsgi_application()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 80, in load_middleware
    middleware = import_string(middleware_path)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/dist/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/data/data/com.termux/files/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/core/analytics/middleware.py", line 28, in <module>
    kolibri_process = psutil.Process()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/__init__.py", line 218, in __init__
    self._init(pid)
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/__init__.py", line 239, in _init
    self.create_time()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/__init__.py", line 266, in create_time
    self._create_time = self._proc.create_time()
  File "/data/data/com.termux/files/home/.pex/install/kolibri-0.13.1-py2.py3-none-any.whl.0b47b6edfe7824575cf78b5965aac1f2d383bbb2/kolibri-0.13.1-py2.py3-none-any.whl/kolibri/utils/pskolibri/_pslinux.py", line 170, in wrapper
    raise AccessDenied()
kolibri.utils.pskolibri.common.AccessDenied
```

### Steps to reproduce

…

### Context

I have Kolibri version 0.13
      I am running this on Termux on Android 8.0
      I am using the Chrome browser

**Comment by indirectlylit** [comment]
Hi @Rehan-Phantom - unfortunately running Kolibri under Termux is not supported. For context, on the specific error you're getting see [this thread](https://github.com/termux/termux-app/issues/299).

That said, we are actively working on support for Kolibri in Android, and hope to have something ready to share publicly later this year.
