### ISSUE TITLE
Workaround: Python 3.8 error when generating documentation

### ISSUE THREAD

**Issue by Lewiscowles1986** [learningequality/kolibri#6922]
### Observed behavior

python deprecated a library in an upstream dependency. This caused `make docs` to unexpectedly fail for me on windows 10 64-bit using a python virtual environment, and `pip install -r requirements/docs.txt` followed by `make docs`

### Expected behavior

Non upstream errors (I'm fine with my docs edits needing work)

### User-facing consequences

* Inability to contribute to documentation & build

### Errors and logs

```
$ make docs
C:/Program Files/Git/mingw64/bin/make.exe -C docs clean
make[1]: Entering directory 'C:/Users/lewis/projects/kolibri/docs'
rm -rf _build/*
make[1]: Leaving directory 'C:/Users/lewis/projects/kolibri/docs'
C:/Program Files/Git/mingw64/bin/make.exe -C docs html
make[1]: Entering directory 'C:/Users/lewis/projects/kolibri/docs'
sphinx-build -b html -W -d _build/doctrees   . _build/html
Running Sphinx v2.4.4
WARNING:root:No C Extensions available for this platform.

INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sphinx\config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sphinx\util\pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "C:\Users\lewis\projects\kolibri\docs\conf.py", line 40, in <module>
    django.setup()
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.ready()
  File "C:\Users\lewis\projects\kolibri\kolibri\core\content\apps.py", line 15, in ready
    from kolibri.core.content.utils.sqlalchemybridge import prepare_bases
  File "C:\Users\lewis\projects\kolibri\kolibri\core\content\utils\sqlalchemybridge.py", line 8, in <module>
    from sqlalchemy import ColumnDefault
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sqlalchemy\__init__.py", line 9, in <module>
    from .sql import (
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sqlalchemy\sql\__init__.py", line 8, in <module>
    from .expression import (
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sqlalchemy\sql\expression.py", line 34, in <module>
    from .visitors import Visitable
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 28, in <module>
    from .. import util
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sqlalchemy\util\__init__.py", line 8, in <module>
    from .compat import callable, cmp, reduce,  \
  File "c:\users\lewis\projects\kolibri\.venv\lib\site-packages\sqlalchemy\util\compat.py", line 234, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

make[1]: *** [Makefile:53: html] Error 2
make[1]: Leaving directory 'C:/Users/lewis/projects/kolibri/docs'
make: *** [Makefile:102: docs] Error 2
(.venv) 
```

### Steps to reproduce

pip install virtualenv
virtualenv .venv
.venv/Scripts/activate
pip install -r requirements/docs.txt
make docs

### Context

 * Kolibri version : `develop` branch
 * Operating system: `Windows 10 64-bit`
 * Browser: N/A
 * Terminal: `Git Bash + make`
 * Python: `3.8`

### Workaround

The patch is pretty simple. I simply changed `kolibri\.venv\lib\site-packages\sqlalchemy\util\compat.py:234` 

#### From

```python
    time_func = time.clock
```

#### To

```python
    time_func = time.perf_counter
```

**Comment by Lewiscowles1986** [comment]
This also looks like it's fixed in sqlalchemy master, so maybe that needs a version bump?

**Comment by rtibbles** [comment]
SQL Alchemy has now been upgraded, so this issue should be fixed.
