### ISSUE TITLE
Kolibri translate server not working in 0.13.3

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#6976]
### Observed behavior

The kolibri-translate.learningequality.org server returns 500 after being upgraded to 0.13.3

### Expected behavior

server returns 200 and should be working after upgrade

### User-facing consequences

translators are not able to translate

### Errors and logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 207, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "./kolibri/core/webpack/templatetags/webpack_tags.py", line 42, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "./kolibri/core/kolibri_plugin.py", line 92, in render_to_page_load_sync_html
    + self.navigation_tags()
  File "./kolibri/core/webpack/hooks.py", line 285, in plugin_data_tag
    if self.plugin_data:
  File "./kolibri/core/kolibri_plugin.py", line 101, in plugin_data
    "languageGlobals": self.language_globals(),
  File "./kolibri/core/kolibri_plugin.py", line 112, in language_globals
    lang_info = i18n.KOLIBRI_LANGUAGE_INFO[code]
KeyError: u'ach-ug'
```

### Steps to reproduce

Use `kolibri.deployment.default.settings.translation` as the django settings module to run Kolibri

### Context

Kolibri version: 0.13.3

**Comment by indirectlylit** [comment]
important for 0.14 string freeze
