### ISSUE TITLE
"Kolibri stop" command is not working in Windows

### ISSUE THREAD

**Issue by mrpau-julius** [learningequality/kolibri#7103]
### Observed behavior

There's an error when I used `kolibri stop` in command prompt.
![image](https://user-images.githubusercontent.com/38421180/85169568-986bcd00-b29e-11ea-8edb-dfad88b5a8b9.png)

### Expected behavior

User can stop running the Kolibri using `kolibri stop` command.
### User-facing consequences

…

### Errors and logs

```
Microsoft Windows [Version 10.0.18362.836]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Zech Enoch Legaspi>kolibri stop
WARNING:root:No C Extensions available for this platform.

[37mINFO     Initiating shutdown of Kolibri[0m
OSError: [WinError 87] The parameter is incorrect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\kolibri.exe\__main__.py", line 9, in <module>
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\kolibri\utils\cli.py", line 223, in invoke
    return super(KolibriCommand, self).invoke(ctx)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\utils\cli.py", line 557, in stop
    server.stop(pid=pid)
  File "c:\python36\lib\site-packages\kolibri\utils\server.py", line 169, in stop
    kill_pid(pid)
  File "c:\python36\lib\site-packages\kolibri\utils\system.py", line 102, in _windows_kill_pid
    _kill_pid(pid, signal.CTRL_C_EVENT)
  File "c:\python36\lib\site-packages\kolibri\utils\system.py", line 56, in _kill_pid
    os.kill(pid, softkill_signal_number)
SystemError: <built-in function kill> returned a result with an error set

```

### Steps to reproduce

…

### Context

* Kolibri version: 0.13.3 and 0.14.0 beta 2
 * Operating system: Windows 7 and 10
 * Browser: n/a

**Comment by cpauya** [comment]
I also experienced this while testing `release-0.14.0-beta2` last week:
<img width="1016" alt="Screen Shot 2020-06-19 at 6 27 22 PM" src="https://user-images.githubusercontent.com/175580/85262284-2662d600-b4a0-11ea-948c-dca0c715c220.png">

**Comment by bjester** [comment]
I'm able to reproduce this issue.

**Comment by bjester** [comment]
I also receive the following error on startup. Unsure yet if it's related.
```
--- Logging error ---
Traceback (most recent call last):
  File "c:\python36\lib\logging\__init__.py", line 997, in emit
    stream.write(self.terminator)
OSError: [WinError 6] The handle is invalid
Call stack:
  File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python36\Scripts\kolibri.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python36\lib\site-packages\kolibri\utils\cli.py", line 276, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python36\lib\site-packages\kolibri\dist\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\utils\cli.py", line 548, in start
    server.start(port=port, serve_http=serve_http)
  File "c:\python36\lib\site-packages\kolibri\utils\server.py", line 154, in start
    logger.info("Starting Kolibri {version}".format(version=kolibri.__version__))
Message: 'Starting Kolibri 0.14.0b6'
Arguments: ()
INFO     ENGINE Listening for SIGTERM.
INFO     ENGINE Listening for SIGINT.
INFO     ENGINE Bus STARTING
INFO     Starting scheduler workers.
INFO     Registering ourselves to zeroconf network with id '28929954a727c99ef7bb34180038bbf0'...
INFO     ENGINE Serving on http://0.0.0.0:8080
INFO     ENGINE Bus STARTED
INFO     Ping succeeded! (response: {'id': 873618, 'messages': []})
```

**Comment by rtibbles** [comment]
As well as erroring like this, it also fails to produce a clean shutdown.
