### ISSUE TITLE
Can't load coach page on IE11

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7189]
### Observed behavior
After I logged in as coach the IE11 browser display empty and an `object error` show in the console 

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
![c1](https://user-images.githubusercontent.com/8663934/85792904-cc476680-b766-11ea-9092-a9ec82e698fd.PNG)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: release-v0.14.0b5
 * Operating system: Windows 7
 * Browser: IE11

**Comment by cpauya** [comment]
Sadly I also saw this while testing [v0.14.0-beta6](https://github.com/learningequality/kolibri/releases/tag/v0.14.0-beta6) in IE11 on Win7 VM.  It doesn't manifest in Firefox v77 or Chrome v83.

I was following this Gherkin story [coach-change-language.feature](https://github.com/learningequality/kolibri/blob/release-v0.14.x/integration_testing/features/coach/coach-change-language.feature).

It loaded during initial testing (using English) but when I changed the language at the login page to French/Espanol now it won't load. 

<img width="1016" alt="Screen Shot 2020-06-29 at 4 58 46 PM" src="https://user-images.githubusercontent.com/175580/85994738-cda8b580-ba2a-11ea-897d-4ecb2b444634.png">

It has the same error on the page as reported above, I'm putting it here for reference:
```
TypeError: Unable to get property 'split' of undefined or null reference
   {
      [functions]: ,
      __proto__: { },
      description: "Unable to get property 'split' of undefined or null reference",
      message: "Unable to get property 'split' of undefined or null reference",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Unable to get property 'split' of undefined or null reference
   at createRouterError (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b6.js:1:431681)
   at createNavigationRedirectedError (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b6.js:1:431189)
   at Anonymous function (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b6.js:1:435470)
   at beforeEnter (http://127.0.0.1:8080/static/kolibri.plugins.coach.app/kolibri.plugins.coach.app-0.14.0b6.js:1:1066707)
   at iterator (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b6.js:1:435069)
   at step (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b6.js:1:429516)
   at Anonymous function (http://127.0.0.1:8080/static/kolibri.core.default_frontend/kolibri.core.default_frontend-0.14.0b6.js:1:429544)
   at Anonymous fu"
   }
```

Kolibri log files:
[2020-06-29-mon--1--ie11 console.txt](https://github.com/learningequality/kolibri/files/4844848/2020-06-29-mon--1--ie11.console.txt)
[daemon.txt](https://github.com/learningequality/kolibri/files/4844849/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/4844850/kolibri.txt)

Notes:
1. I tried to load the English page at: http://127.0.0.1:8080/en/coach/#/ but didn't work.
1. I tried InPrivate Browsing to login as coach, but now the coach page doesn't load.
1. As a work-around in IE11, I'd go to http://127.0.0.1:8080/logout/ to logout the current user, then Kolibri will load, but the Coach page still won't.
1. They all have the same error in the IE11 console.

**Comment by mrpau-richard** [comment]
I can also reproduced this on 0.14.0 beta 6 released.

**Comment by jonboiser** [comment]
@mrpau-richard I believe this was caused by a low-level bug in the vue-router library. I updated the library here a1e2d6d9cdc428fee92af8ca49a2bd49cf9db15d and tested it on Browserstack (IE11/Win 10).

Could you please test this out again on beta 7? (available soon)

**Comment by mrpau-richard** [comment]
I confirmed that beta 7 fixed this issue.
![c1](https://user-images.githubusercontent.com/8663934/86120683-5563f200-bb07-11ea-9767-85ecb2bbf028.PNG)

Thanks @jonboiser
