### ISSUE TITLE
Available drives not showing on import local channel contents

### ISSUE THREAD

**Issue by mrpau-richard** [learningequality/kolibri#7194]
### Observed behavior
Available drives not showing on import local channel contents. But I tried on export one drive show.

### Expected behavior

…

### User-facing consequences

…

### Errors and logs
This is on export content there is one drive available
![c1](https://user-images.githubusercontent.com/8663934/85831128-5d96f700-b7c0-11ea-8148-d94130c3a43a.PNG)

At the import no drives are available 
![temp](https://user-images.githubusercontent.com/8663934/85831205-84552d80-b7c0-11ea-8c6a-a9449b008074.gif)

### Steps to reproduce

…

### Context

Tell us about your environment, including:
 * Kolibri version: release-v0.14.0b5
 * Operating system: Windows 7
 * Browser: IE11 Firefox 77 Chrome 83

**Comment by radinamatic** [comment]
I also had issues locating external drives on Ubuntu, but was 100% sure it wasn't the USB drive :confused: 
Will retest with other USBs and confirm!

**Comment by jonboiser** [comment]
@mrpau-richard @radinamatic Could you try to get some logs when you see this? I just reproduced it and got a pretty informative server log here pointing to the recent addition of the `tagline` field on the `channelmetadata` model. 

The channels that are likely on the USB were exported awhile ago, before we added that tagline field

```
ERROR    Internal Server Error: /api/tasks/tasks/localdrive/
Traceback (most recent call last):
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/jon/.local/share/virtualenvs/kolibri-UH8N_Uf0/lib/python3.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/jon/Github/kolibri/kolibri/core/tasks/api.py", line 589, in localdrive
    drives = get_mounted_drives_with_channel_info()
  File "/Users/jon/Github/kolibri/kolibri/core/content/utils/channels.py", line 148, in get_mounted_drives_with_channel_info
    get_channels_for_data_folder(drive.datafolder) if drive.datafolder else []
  File "/Users/jon/Github/kolibri/kolibri/core/content/utils/channels.py", line 126, in get_channels_for_data_folder
    "tagline": channel.tagline,
AttributeError: 'content_channelmetadata' object has no attribute 'tagline'
ERROR    "GET /api/tasks/tasks/localdrive/?1593638668124=1593638668124 HTTP/1.1" 500 33728```

**Comment by jonboiser** [comment]
Yeah, fixing the offending line in `utils.channel` got the Select Drive modal working for me again.

**Comment by jonboiser** [comment]
@radinamatic @mrpau-richard Would you mind seeing if this has been fixed for you in `0.14.0beta8`?

**Comment by radinamatic** [comment]
I'm able to see and import from local USB drives with `0.14.0beta8` on Windows 10! :+1: 

Seeing some weirdness in modal height when displayed on large screens first, but then re-scales well screen is made smaller :confused: 

![local-import](https://user-images.githubusercontent.com/1457929/87077625-b3898700-c223-11ea-97a9-203be3d99b47.gif)

Will re-test on Win 7 & Ubuntu to confirm!

**Comment by jonboiser** [comment]
Yeah, the modal issue has been with us for awhile (cc @ralphiee22) 😄

**Comment by radinamatic** [comment]
Import from USB drives with `0.14.0beta9` on Windows 7: :heavy_check_mark: 

![Selection_781](https://user-images.githubusercontent.com/1457929/87098400-7800b400-c247-11ea-8383-3ddc04940730.png)

Modal issue is there too, goes away with resizing :woman_shrugging:

**Comment by ralphiee22** [comment]
Leave it for me until October 💥
