### ISSUE TITLE
Broken task progress loader during channel import

### ISSUE THREAD

**Issue by MisRob** [learningequality/kolibri#7196]
Reported by @cpauya in #7046.

### Observed behavior

_...during import the progress bar moves back and forth and the values indicate ... 20%, 50%, 25%, 65%,... 90%, 131%, 93%, 100% in order_

![84504509-a5148200-acee-11ea-96f6-5a04e8fe729d](https://user-images.githubusercontent.com/13509191/85872805-8cb56480-b7d0-11ea-8b15-6918d1404d4f.png)

### Expected behavior

Progress bar works smoothly.

### User-facing consequences

Confusion.

### Errors and logs
[kolibri.txt](https://github.com/learningequality/kolibri/files/4837742/kolibri.txt)
[console-export-2020-6-12_21-2-48.txt](https://github.com/learningequality/kolibri/files/4837743/console-export-2020-6-12_21-2-48.txt)
[debug.txt](https://github.com/learningequality/kolibri/files/4837744/debug.txt)

It seems that there is only one problem in logs that might be related

```
ERROR 2020-06-12 20:36:03,107 django.request Internal Server Error: /en/user/
Traceback (most recent call last):
  File "/Users/cyril/w/le/kolibri/kolibri/core/device/utils.py", line 26, in get_device_setting
    device_settings = DeviceSettings.objects.get()
  File "/Users/cyril/w/le/kolibri/kolibri/core/device/models.py", line 41, in get
    model = super(DeviceSettingsManager, self).get(**kwargs)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
kolibri.core.device.models.DoesNotExist: DeviceSettings matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/Users/cyril/.local/share/virtualenvs/kolibri-cG-2Tn9P/lib/python3.7/site-packages/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/Users/cyril/w/le/kolibri/kolibri/core/webpack/templatetags/webpack_tags.py", line 42, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "/Users/cyril/w/le/kolibri/kolibri/core/webpack/hooks.py", line 384, in render_to_page_load_sync_html
    + list(self.js_and_css_tags())
  File "/Users/cyril/w/le/kolibri/kolibri/core/webpack/hooks.py", line 289, in plugin_data_tag
    if self.plugin_data:
  File "/Users/cyril/w/le/kolibri/kolibri/plugins/user/kolibri_plugin.py", line 42, in plugin_data
    "allowGuestAccess": get_device_setting("allow_guest_access"),
  File "/Users/cyril/w/le/kolibri/kolibri/core/device/utils.py", line 33, in get_device_setting
    raise DeviceNotProvisioned
kolibri.core.device.utils.DeviceNotProvisioned
```

### Steps to reproduce

1. Navigate to [import resources selection](http://127.0.0.1:8000/en/device/#/content/channels)
2. Import a channel

### Context

- Kolibri version: release-v0.14.x branch
- Operating system: macOS v10.14.6 Mojave
- Browser: Firefox v77.0.1
- Python: v3.7.7

**Comment by rtibbles** [comment]
The DeviceNotProvisioned Error should now be being handled due to this PR: #7024 (which was merged by 0.14.0-beta3) so I think that's a red herring here.

**Comment by jonboiser** [comment]
The up-down progress/percentages is similar to this old issue https://github.com/learningequality/kolibri/issues/5904.

I don't think we figure out the exact cause in that issue; it just went away on its own...

But the fact that the percentages are going up and down indicates that the numerator and denominator (number of resources? number of files?) used to calculate the percentage are likely changing as the Task is getting run.

**Comment by indirectlylit** [comment]
Do we know if this happens often, or just occasionally?

**Comment by MisRob** [comment]
I haven't seen it happen at all so far, not even after watching quite lots of import attempts in Firefox and Chrome (though not sure about the behavior in long term as I don't run Kolibri very often)

**Comment by indirectlylit** [comment]
closing until we can pin down steps to repro
