### ISSUE TITLE
Kolibri 0.14 blows up when run inside a Docker image without ifconfig/ip

### ISSUE THREAD

**Issue by jamalex** [learningequality/kolibri#7207]
### Observed behavior

Error starting Kolibri inside a simple Ubuntu Docker image, because ifcfg version 0.20 and above started throwing exceptions when ifconfig/ip were not found, instead of silently returning an empty list. See https://github.com/ftao/python-ifcfg/issues/55

### Errors and logs
```
root@00d7fca3e507:/# kolibri start --port 8989 --debug --foreground
WARNING:root:No C Extensions available for this platform.

WARNING:ifcfg:Neither `ifconfig` (`ifconfig -a`) nor `ip` (`ip address show`) commands are available, listing network interfaces is likely to fail
DEBUG    Loaded kolibri plugin: kolibri.core
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
ERROR:ifcfg.parser:/bin/sh: 1: ip: not found

INFO     Running Kolibri
ERROR:ifcfg.parser:/bin/sh: 1: ip: not found

Traceback (most recent call last):
  File "/usr/local/bin/kolibri", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/kolibri/utils/cli.py", line 276, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/utils/cli.py", line 513, in start
    __, urls = server.get_urls(listen_port=port)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/utils/server.py", line 525, in get_urls
    for ip in get_all_addresses():
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/zeroconf.py", line 1743, in get_all_addresses
    set(iface["inet"] for iface in get_network_interfaces() if iface["inet"])
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/zeroconf.py", line 1738, in get_network_interfaces
    return ifcfg.interfaces().values()
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/ifcfg/__init__.py", line 70, in interfaces
    return Parser(ifconfig=ifconfig).interfaces
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/ifcfg/parser.py", line 30, in __init__
    self.parse(self.ifconfig_data)
  File "/usr/local/lib/python3.6/dist-packages/kolibri/dist/ifcfg/parser.py", line 57, in parse
    raise ValueError("Non-zero return code, reporting error-code '{}'".format(errors))
ValueError: Non-zero return code, reporting error-code '/bin/sh: 1: ip: not found
'
```

### Resolution

Given this now seems to be the intended behavior of ifcfg, I will update python-zeroconf-py2compat to handle the exception.

**Comment by jamalex** [comment]
Fixed in https://github.com/learningequality/kolibri/pull/7209
