### ISSUE TITLE
issues during re-import of a directly exported CSV

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7235]
### Observed behavior

1. When exporting and then trying to re-import we see: `Value in column 'Class name' is too many characters`
2. Then after proceeding, we see:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/worker.py", line 71, in handle_finished_future
    result = future.result()
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/worker.py", line 216, in wrap
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/job.py", line 178, in y
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/management/commands/base.py", line 110, in handle
    return self.handle_async(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/auth/management/commands/bulkimportusers.py", line 898, in handle_async
    self.remove_memberships(keeping_users, classes[0], classes[1])
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/auth/management/commands/bulkimportusers.py", line 782, in remove_memberships
    collection__name__in=users_assigned[user.username]
KeyError: u'\xc0ngeles_Torres'
```

### Expected behavior

1. Length validation should be applied to individual class names, not to the list of class names
2. Anything that can be exported should also be imported without issue
3. Unit tests should be updated to include the cases here

### Steps to reproduce

* log in to the PF server as an admin
* export a CSV
* import the CSV

### Context

reproduced in the PF build, but likely applies to 0.14 beta6

**Comment by jredrejo** [comment]
@indirectlylit in order to reproduce the UTF-8 issue, could  you attach the affected db here? I have tried several combinations and I haven't been able to reproduce it, could it be the file is being exported in an old windows version not supporting UTF?
