### ISSUE TITLE
database locking error after trying to upgrade a channel

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#7284]
### Observed behavior

Channel upgrade failed on https://kolibri-beta.learningequality.org/ 

https://www.notion.so/learningequality/Post-upgrade-redirect-gets-Error-Page-with-500-error-seems-related-to-known-DeviceInfo-endpoint-iss-e1d88b7b29694864a1dbfc6f744fd387

### Errors and logs

client: 

```js
{
  "data": "<h1>Server Error (500)</h1>",
  "status": 500,
  "statusText": "",
  "headers": {
    "alt-svc": "h3-27=\":443\"; ma=86400, h3-28=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
    "cf-cache-status": "DYNAMIC",
    "cf-ray": "5b0504841cfa7fe4-SAN",
    "cf-request-id": "03d701269100007fe4bcb2c200000001",
    "content-type": "text/html",
    "date": "Thu, 09 Jul 2020 21:07:59 GMT",
    "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
    "server": "cloudflare",
    "status": "500",
    "vary": "Cookie",
    "x-frame-options": "SAMEORIGIN"
  },
  "config": {
    "url": "/api/device/deviceinfo/",
    "params": {
      "1594328878690": 1594328878690
    },
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "X-Requested-With": "XMLHttpRequest",
      "X-CSRFToken": "eAmJKS2udmkpo9GehW3PynJRXlWWRfwmQ2NhgruuHkgv9mjrUvAeoC7IOh6n5uQd"
    },
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "timeout": 0,
    "xsrfCookieName": "kolibri_csrftoken",
    "xsrfHeaderName": "X-CSRFToken",
    "maxContentLength": -1,
    "method": "get"
  },
  "request": {
    "__sentry_xhr__": {
      "method": "GET",
      "url": "/api/device/deviceinfo/?1594328878690=1594328878690",
      "status_code": 500
    }
  }
}
```

server:

```
INFO 2020-07-09 21:07:58,551 cherrypy.access 10.52.2.4 - - "GET /api/tasks/facilitytasks/" 200 0 "https://kolibri-beta.learningequality.org/en/facility/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
INFO 2020-07-09 21:07:58,819 cherrypy.access 10.52.2.4 - - "GET /api/device/devicename/" 200 0 "https://kolibri-beta.learningequality.org/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
INFO 2020-07-09 21:07:59,042 cherrypy.access 10.52.2.4 - - "GET /api/content/remotechannel/64357585cb8c4861b42d26e6a9c8828a/" 200 0 "https://kolibri-beta.learningequality.org/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
ERROR 2020-07-09 21:07:59,103 django.request Internal Server Error: /api/device/deviceinfo/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "./kolibri/core/device/api.py", line 93, in get
    instance_model = InstanceIDModel.get_or_create_current_instance()[0]
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/morango/models/core.py", line 141, in get_or_create_current_instance
    current=False
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/query.py", line 650, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 1204, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: database is locked
INFO 2020-07-09 21:07:59,339 cherrypy.access 10.52.2.4 - - "GET /api/device/deviceinfo/" 500 0 "https://kolibri-beta.learningequality.org/en/device/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
INFO 2020-07-09 21:07:59,525 cherrypy.access 10.52.2.4 - - "GET /api/tasks/facilitytasks/" 200 0 "https://kolibri-beta.learningequality.org/en/facility/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36"
```

### Steps to reproduce

upgrade a channel on the beta server

### Context

0.14.0 beta 9

**Comment by jamalex** [comment]
Potential Morango fix here: https://github.com/learningequality/morango/pull/87

After that's been reviewed, I can release it so we can do broader testing in Kolibri.

**Comment by jamalex** [comment]
Fix to help address this in https://github.com/learningequality/kolibri/pull/7331
