### ISSUE TITLE
Kolibri web not loading using manual instructions

### ISSUE THREAD

**Issue by luandro** [learningequality/kolibri#7291]
Installed on Pi using the instructions from [raspberry_pi_manual](https://kolibri.readthedocs.io/en/latest/install/raspberry_pi_manual.html).

### Observed behavior

I first installed with python using `pip3 install kolibri` and everything worked fine. Then I uninstalled it and tried the `apt-get` method, which installed fine and `kolibri status` shows it's running, but when trying to access Kolibri I got this:

![kolibri_no_load](https://user-images.githubusercontent.com/693728/87231815-a9d16200-c390-11ea-8edb-1fe10a87e153.jpg)

Seems some assets aren't starting right. So I did a `apt remove kolibri kolibri-server` and tried re-installing. After this second install I keep getting this page. After hours it hasn't changed.

![kolibri_no_load_2](https://user-images.githubusercontent.com/693728/87231805-97efbf00-c390-11ea-9a84-02a89067860e.jpg)

### Expected behavior
Expected everything to work fine as python install does.

### Errors and logs
Here the log, can't tell is there's anything relevant on it:
```
INFO 2020-07-11 19:42:25,373 search Registering ourselves to zeroconf network with id '51e61a1b3b6d4bef8d9566fe8050cc33'...
INFO 2020-07-11 19:42:25,789 search Kolibri instance '4263680adb33fc3fe08211160748d52e' joined zeroconf network; service info: {'id': '4263680adb33fc3fe08211160748d52e', 'ip': '10.147.249.54', 'local': True, 'port': 8080, 'host': '4263680adb33fc3fe08211160748d52e.kolibri.local', 'base_url': 'http://10.147.249.54:8080/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.3', 'instance_id': '4263680adb33fc3fe08211160748d52e', 'device_name': 'servidor-sa', 'operating_system': 'Linux'}
INFO 2020-07-11 19:42:25,934 search Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33' joined zeroconf network; service info: {'id': '51e61a1b3b6d4bef8d9566fe8050cc33', 'ip': '10.147.249.54', 'local': True, 'port': 8080, 'host': '51e61a1b3b6d4bef8d9566fe8050cc33.kolibri.local', 'base_url': 'http://10.147.249.54:8080/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.3', 'instance_id': '51e61a1b3b6d4bef8d9566fe8050cc33', 'device_name': 'servidor-sa', 'operating_system': 'Linux'}
INFO 2020-07-11 19:42:26,300 cherrypy.error ENGINE Bus STARTED
INFO 2020-07-11 19:42:29,883 utils Ping succeeded! (response: {'id': 899867, 'messages': []})
INFO 2020-07-11 19:42:30,898 utils Ping succeeded! (response: {'id': 899868, 'messages': []})
WARNING 2020-07-11 20:06:27,017 options Options file /home/pi/.kolibri/options.ini has been updated; server restart is required before change will take effect.
INFO 2020-07-11 20:06:33,519 apps Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO 2020-07-11 20:06:34,332 cli Running Kolibri as background process
INFO 2020-07-11 20:06:34,368 cli Kolibri running on:

INFO 2020-07-11 20:06:34,369 cli Going to background mode, logging to /home/pi/.kolibri/logs/kolibri.txt
INFO 2020-07-11 20:06:34,391 server Starting Kolibri 0.13.3
INFO 2020-07-11 20:06:34,499 cherrypy.error ENGINE Listening for SIGTERM.
INFO 2020-07-11 20:06:34,502 cherrypy.error ENGINE Listening for SIGHUP.
INFO 2020-07-11 20:06:34,503 cherrypy.error ENGINE Listening for SIGUSR1.
INFO 2020-07-11 20:06:34,504 cherrypy.error ENGINE Listening for SIGINT.
INFO 2020-07-11 20:06:34,505 cherrypy.error ENGINE Bus STARTING
INFO 2020-07-11 20:06:35,743 utils Started new JOBCHECKER thread ID#66d584a8978d4761ba26caae53ed46a4
INFO 2020-07-11 20:06:35,751 utils Started new JOBCHECKER thread ID#80893cd464954738810f81e1fdb0a78b
INFO 2020-07-11 20:06:35,752 utils Started new SCHEDULECHECKER thread ID#dd6c9faa391544caa8d875a32858d86b
INFO 2020-07-11 20:06:35,890 search Registering ourselves to zeroconf network with id '51e61a1b3b6d4bef8d9566fe8050cc33'...
WARNING 2020-07-11 20:06:36,391 search 
                        A new Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33-2' was seen on the zeroconf network,
                        but we had trouble getting the information we needed about it.
                        Service info:
                        {'id': '51e61a1b3b6d4bef8d9566fe8050cc33-2', 'ip': '127.0.0.1', 'local': True, 'port': 8080, 'host': '51e61a1b3b6d4bef8d9566fe8050cc33-2.kolibri.local', 'base_url': 'http://127.0.0.1:8080/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.3', 'instance_id': '51e61a1b3b6d4bef8d9566fe8050cc33', 'device_name': 'servidor-sa', 'operating_system': 'Linux'}
                        The following exception was raised:
                        Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 480, in update_or_create
    obj = self.select_for_update().get(**lookup)
kolibri.core.discovery.models.DoesNotExist: DynamicNetworkLocation matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/discovery/utils/network/search.py", line 148, in add_service
    dict(base_url=base_url, **device_info), id=id,
django.core.exceptions.ValidationError: {'instance_id': ['`instance_id` and `id` must be the same']}

                        
WARNING 2020-07-11 20:06:36,406 search 
                        A new Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33-2' was seen on the zeroconf network,
                        but we had trouble getting the information we needed about it.
                        Service info:
                        {'id': '51e61a1b3b6d4bef8d9566fe8050cc33-2', 'ip': '127.0.0.1', 'local': True, 'port': 8080, 'host': '51e61a1b3b6d4bef8d9566fe8050cc33-2.kolibri.local', 'base_url': 'http://127.0.0.1:8080/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.3', 'instance_id': '51e61a1b3b6d4bef8d9566fe8050cc33', 'device_name': 'servidor-sa', 'operating_system': 'Linux'}
                        The following exception was raised:
                        Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 480, in update_or_create
    obj = self.select_for_update().get(**lookup)
kolibri.core.discovery.models.DoesNotExist: DynamicNetworkLocation matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/discovery/utils/network/search.py", line 148, in add_service
    dict(base_url=base_url, **device_info), id=id,
django.core.exceptions.ValidationError: {'instance_id': ['`instance_id` and `id` must be the same']}

                        
INFO 2020-07-11 20:06:36,540 search Kolibri instance '4263680adb33fc3fe08211160748d52e' joined zeroconf network; service info: {'id': '4263680adb33fc3fe08211160748d52e', 'ip': '10.147.249.54', 'local': True, 'port': 8080, 'host': '4263680adb33fc3fe08211160748d52e.kolibri.local', 'base_url': 'http://10.147.249.54:8080/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.3', 'instance_id': '4263680adb33fc3fe08211160748d52e', 'device_name': 'servidor-sa', 'operating_system': 'Linux'}
WARNING 2020-07-11 20:06:36,621 search 
                        A new Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33-2' was seen on the zeroconf network,
                        but we had trouble getting the information we needed about it.
                        Service info:
                        {'id': '51e61a1b3b6d4bef8d9566fe8050cc33-2', 'ip': '10.147.249.54', 'local': True, 'port': 8080, 'host': '51e61a1b3b6d4bef8d9566fe8050cc33-2.kolibri.local', 'base_url': 'http://10.147.249.54:8080/', 'self': False, 'application': 'kolibri', 'kolibri_version': '0.13.3', 'instance_id': '51e61a1b3b6d4bef8d9566fe8050cc33', 'device_name': 'servidor-sa', 'operating_system': 'Linux'}
                        The following exception was raised:
                        Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/db/models/query.py", line 480, in update_or_create
    obj = self.select_for_update().get(**lookup)
kolibri.core.discovery.models.DoesNotExist: DynamicNetworkLocation matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/discovery/utils/network/search.py", line 148, in add_service
    dict(base_url=base_url, **device_info), id=id,
django.core.exceptions.ValidationError: {'instance_id': ['`instance_id` and `id` must be the same']}

                        
INFO 2020-07-11 20:06:36,894 cherrypy.error ENGINE Serving on http://0.0.0.0:8080
INFO 2020-07-11 20:06:36,896 cherrypy.error ENGINE Bus STARTED
INFO 2020-07-11 20:06:42,460 system Initiating shutdown of Kolibri
INFO 2020-07-11 20:06:42,461 system Waiting for Kolibri to finish shutting down
INFO 2020-07-11 20:06:42,461 cherrypy.error ENGINE Caught signal SIGTERM.
INFO 2020-07-11 20:06:42,479 cherrypy.error ENGINE Bus STOPPING
INFO 2020-07-11 20:06:42,490 cherrypy.error ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8080)) shut down
INFO 2020-07-11 20:06:42,494 search Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33-2' has left the zeroconf network.
INFO 2020-07-11 20:06:42,498 search Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33-2' has left the zeroconf network.
INFO 2020-07-11 20:06:42,500 search Kolibri instance '51e61a1b3b6d4bef8d9566fe8050cc33-2' has left the zeroconf network.
WARNING 2020-07-11 20:06:42,674 utils JOBCHECKER shut down event received; closing.
WARNING 2020-07-11 20:06:42,675 utils JOBCHECKER shut down event received; closing.
INFO 2020-07-11 20:06:42,746 cherrypy.error ENGINE Bus STOPPED
INFO 2020-07-11 20:06:42,748 cherrypy.error ENGINE Bus EXITING
INFO 2020-07-11 20:06:42,749 cherrypy.error ENGINE Bus EXITED
INFO 2020-07-11 20:06:42,750 cherrypy.error ENGINE Waiting for child threads to terminate...
INFO 2020-07-11 20:06:42,752 cherrypy.error ENGINE Waiting for thread SCHEDULECHECKER-dd6c9faa391544caa8d875a32858d86b.
WARNING 2020-07-11 20:06:42,832 utils SCHEDULECHECKER shut down event received; closing.
INFO 2020-07-11 20:06:43,980 cli Kolibri server has successfully been stopped.
INFO 2020-07-11 20:06:44,246 utils Ping succeeded! (response: {'id': 899892, 'messages': []})

```

### Steps to reproduce
Follow manual instalation instructions on a Raspberry Pi 3+.

### Context
Kolibri: 0.13.3
Raspbian Buster 

### Update
- After `apt remove kolibri kolibri-server` and `pip3 install kolibri` I get the same problem of assets not loading...

**Comment by luandro** [comment]
So after a clean start, and installing without python (with apt) from the start solved the problem.
