### ISSUE TITLE
incompatible code between the kolibri source code and kolibri sentry plugin

### ISSUE THREAD

**Issue by lyw07** [learningequality/kolibri#7379]
### Observed behavior

On kolibri-beta server that uses sentry plugin, the upgrade to the latest beta failed

### Expected behavior

upgrade should be successful

### User-facing consequences

can't upgrade the beta server to the latest beta

### Errors and logs

```
Traceback (most recent call last):
  File "/usr/local/bin/kolibri", line 7, in <module>
    from kolibri.utils.cli import main
  File "/usr/local/lib/python2.7/dist-packages/kolibri/utils/cli.py", line 29, in <module>
    from . import sanity_checks
  File "/usr/local/lib/python2.7/dist-packages/kolibri/utils/sanity_checks.py", line 14, in <module>
    from .server import get_status
  File "/usr/local/lib/python2.7/dist-packages/kolibri/utils/server.py", line 18, in <module>
    from kolibri.core.deviceadmin.utils import schedule_vacuum
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/deviceadmin/utils.py", line 13, in <module>
    from kolibri.core.tasks.main import scheduler
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/main.py", line 11, in <module>
    from kolibri.core.tasks.queue import Queue
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/queue.py", line 1, in <module>
    from kolibri.core.tasks.job import Job
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/job.py", line 7, in <module>
    from kolibri.core.tasks.utils import current_state_tracker
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/tasks/utils.py", line 123, in <module>
    db_task_write_lock = get_process_lock("db_task_write_lock")
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/utils/cache.py", line 49, in get_process_lock
    cache = process_cache.cache("locks")
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/utils/cache.py", line 17, in __get_process_cache
    return caches["process_cache"]
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/core/cache/__init__.py", line 75, in __getitem__
    if alias not in settings.CACHES:
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/deployment/default/settings/base.py", line 357, in <module>
    apply_settings(sys.modules[__name__])
  File "/usr/local/lib/python2.7/dist-packages/kolibri/plugins/utils/settings.py", line 133, in apply_settings
    plugin_settings_module = plugin_instance.settings_module
  File "/usr/local/lib/python2.7/dist-packages/kolibri/plugins/__init__.py", line 345, in settings_module
    module = self._return_module(self.django_settings)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/plugins/__init__.py", line 245, in _return_module
    return import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/kolibri_sentry_plugin/settings.py", line 6, in <module>
    from kolibri.utils.server import installation_type
ImportError: cannot import name installation_type
```

### Steps to reproduce

…

### Context

0.14.0b14

**Comment by rtibbles** [comment]
The import is still there, I think the issue is from this commit:

https://github.com/learningequality/kolibri/commit/48ae5e7e2f0eaa504520cdb906c96c67da45cee0#diff-601cde52caf17fa9d77c64ca9e73e927R14

The import needs to be done inside the scope of the calling function instead, as this is resulting in circular import issues, I think.

**Comment by rtibbles** [comment]
This is not the case - must be something else.
