### ISSUE TITLE
Running kolibri in dev mode, with redis cache breaks it all

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#7385]
### Observed behavior
When redis is set as the cache backend, 
running
`yarn django-devserver `
does not work

### Expected behavior
Dev mode should work correctly

### User-facing consequences
None, it only affects to poor developers

### Errors and logs
```
Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/datos/le/mio/kolibri/kolibri/utils/cli.py", line 29, in <module>
    from . import sanity_checks
  File "/datos/le/mio/kolibri/kolibri/utils/sanity_checks.py", line 14, in <module>
    from .server import get_status
  File "/datos/le/mio/kolibri/kolibri/utils/server.py", line 18, in <module>
    from kolibri.core.deviceadmin.utils import schedule_vacuum
  File "/datos/le/mio/kolibri/kolibri/core/deviceadmin/utils.py", line 13, in <module>
    from kolibri.core.tasks.main import scheduler
  File "/datos/le/mio/kolibri/kolibri/core/tasks/main.py", line 11, in <module>
    from kolibri.core.tasks.queue import Queue
  File "/datos/le/mio/kolibri/kolibri/core/tasks/queue.py", line 1, in <module>
    from kolibri.core.tasks.job import Job
  File "/datos/le/mio/kolibri/kolibri/core/tasks/job.py", line 7, in <module>
    from kolibri.core.tasks.utils import current_state_tracker
  File "/datos/le/mio/kolibri/kolibri/core/tasks/utils.py", line 123, in <module>
    db_task_write_lock = get_process_lock("db_task_write_lock")
  File "/datos/le/mio/kolibri/kolibri/core/utils/cache.py", line 39, in get_process_lock
    return process_cache.lock(
  File "/datos/le/mio/kolibri/venv/lib/python3.6/site-packages/django/utils/functional.py", line 239, in inner
    return func(self._wrapped, *args)
AttributeError: 'LocMemCache' object has no attribute 'lock'
```

### Steps to reproduce
1. Edit `options.ini `to add
```
[Cache]
CACHE_BACKEND = redis
```
2. `run yarn django-devserver`

### Context
Relates to #7300 

The problem relies on the file kolibri/core/utils/cache.py
We should either change this code
```
def __get_process_cache():
    try:
        return caches["process_cache"]
    except InvalidCacheBackendError:
        return caches["default"]
```
to ensure `process_cache` uses redis when in dev mode

or capture the error and return `RLock` in dev mode

**Comment by bjester** [comment]
The issue appears to originate from this line https://github.com/learningequality/kolibri/blob/release-v0.14.x/kolibri/deployment/default/settings/dev.py#L32

**Comment by rtibbles** [comment]
This was originally created as a DummyCache to avoid caching during development, but at some point in the past was switched to LocMemCache - I think removing the CACHES configuration override from the dev settings is the solution here.

**Comment by thesujai** [comment]
@rtibbles i would like to be assigned this one

**Comment by AlexVelezLl** [comment]
Hi! @thesujai! Sure! I will assign this issue to you :smiley:. Let us know if you need something!
