### ISSUE TITLE
"sqlite3.OperationalError: too many SQL variables" when trying to import large channels

### ISSUE THREAD

**Issue by intelliant01** [learningequality/kolibri#7478]
### Observed behavior

When trying to import significantly large amounts of contents have experienced this error -

```
ERROR 2020-08-17 09:20:24,790 kolibri.core.tasks.worker Job 737e2e6f419f498181e9c9cdb629102c raised an exception: Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/base.py", line 1283, in _execute_context
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/default.py", line 590, in do_execute
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/core/tasks/worker.py", line 72, in handle_finished_future
  File "/home/kivy/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/concurrent/futures/_base.py", line 432, in result
  File "/home/kivy/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/concurrent/futures/_base.py", line 388, in __get_result
  File "/home/kivy/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/concurrent/futures/thread.py", line 57, in run
  File "/home/kivy/build/android/kolibri/core/tasks/worker.py", line 217, in wrap
  File "/home/kivy/build/android/kolibri/core/tasks/job.py", line 194, in y
  File "/home/kivy/build/android/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
  File "/home/kivy/build/android/kolibri/dist/django/core/management/base.py", line 330, in execute
  File "/home/kivy/build/android/kolibri/core/tasks/management/commands/base.py", line 113, in handle
  File "/home/kivy/build/android/kolibri/core/content/management/commands/importcontent.py", line 451, in handle_async
  File "/home/kivy/build/android/kolibri/core/content/management/commands/importcontent.py", line 180, in copy_content
  File "/home/kivy/build/android/kolibri/core/content/management/commands/importcontent.py", line 366, in _transfer
  File "/home/kivy/build/android/kolibri/core/content/utils/annotation.py", line 659, in set_content_visibility
  File "/home/kivy/build/android/kolibri/core/content/utils/annotation.py", line 389, in mark_local_files_as_available
  File "/home/kivy/build/android/kolibri/core/content/utils/annotation.py", line 409, in mark_local_files_availability
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/base.py", line 1020, in execute
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/base.py", line 1323, in _execute_context
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/base.py", line 1517, in _handle_dbapi_exception
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/util/compat.py", line 178, in raise_
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/base.py", line 1283, in _execute_context
  File "/home/kivy/build/android/kolibri/dist/sqlalchemy/engine/default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) too many SQL variables
[SQL: UPDATE content_localfile SET available=? WHERE content_localfile.id IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 
```

"Large amount" could be resources totalling to around 100 MB+ from channels such as "Khan Academy" or "CK-12". It is mostly the number of resources that seem to matter than the size.

The imports are reported as failed in the UI.
If upon subsequent attempts we import smaller chunks (<100 MB) of resources, the imports progress much quickly and are reported as successful in the UI as well. This also indicates that the content transfer is happening properly and it is only the post processing part that seems to fail.

Have experienced this in imports irrespective of source and destination platforms. Either could be Windows, Linux or Android. 
 
### Expected behavior

Channel resource imports should not fail.

### User-facing consequences

Very inconvenient to get started when large amounts of resources can't be imported at once.

### Errors and logs

Attached log contains multiple instances of `sqlite3.OperationalError: too many SQL variable` errors.

[kolibri.txt](https://github.com/learningequality/kolibri/files/5085999/kolibri.txt)

### Steps to reproduce

Initiate an import of large number of resources i.e. at least size worth of 100 MB from channels such as KA or CK-12. For example, all Math Grade 1 content from KA.

### Context

Kolibri 0.14.1
Irrespective of environment.

**Comment by jamalex** [comment]
Would you be able to give it a try using the following build from #7479?

- [WHL](https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/1760/jobs/cf27997d-afdd-4a98-af5f-68e746817062/artifacts/2a12f9eb-4690-462b-b6ac-ef9873daa6b8)
- [PEX](https://buildkite.com/organizations/learningequality/pipelines/kolibri-python-package/builds/1760/jobs/cf27997d-afdd-4a98-af5f-68e746817062/artifacts/19a817c2-2b6b-4185-ace9-9cfca295361c)

Thanks!

**Comment by cyberorg** [comment]
> Would you be able to give it a try using the following build from #7479?

Fixed in 0.14.2

Thanks!

**Comment by intelliant01** [comment]
@jamalex @rtibbles I now see this when trying to import from a large channel such as Khan Academy (English - CBSE...) -

![image](https://user-images.githubusercontent.com/2577060/90643447-4240e900-e251-11ea-8660-8c589c76d3f9.png)

The browser UI reports as disconnected and reconnects in 30 seconds.

Simultaneously, I see this in the log -

```
INFO 2020-08-19 19:11:13,372 cherrypy.access 127.0.0.1 - - "GET /device/api/device_channel/2fd54ca47a8f59c99fcefaaa3894c19e/" 200 0 "http://localhost:8080/en/device/" "Mozilla/5.0 (X11; Ubuntu; Linux aarch64; rv:79.0) Gecko/20100101 Firefox/79.0"
WARNING 2020-08-19 19:11:17,826 kolibri.core.content.utils.sqlalchemybridge 
                More than 10000 UUIDs passed to filter by checksums method,
                these should be batched into separate querysets to avoid SQL Query too large errors in SQLite
            
INFO 2020-08-19 19:11:43,995 kolibri.core.content.utils.annotation Setting availability to True of 1505 LocalFile objects based on passed in checksums
INFO 2020-08-19 19:11:45,769 kolibri.core.content.utils.annotation Setting availability of non-topic ContentNode objects based on LocalFile availability in 5 batches of 10000
INFO 2020-08-19 19:11:46,775 kolibri.core.content.utils.annotation Annotating ContentNode objects with children for 5 levels
INFO 2020-08-19 19:12:12,535 kolibri.core.content.utils.annotation Annotating ContentNode objects with children for level 5
INFO 2020-08-19 19:12:12,847 kolibri.core.content.utils.annotation Annotating ContentNode objects with children for level 4
INFO 2020-08-19 19:12:12,881 kolibri.core.content.utils.annotation Annotating ContentNode objects with children for level 3
INFO 2020-08-19 19:12:12,896 kolibri.core.content.utils.annotation Annotating ContentNode objects with children for level 2
INFO 2020-08-19 19:12:12,911 kolibri.core.content.utils.annotation Annotating ContentNode objects with children for level 1
WARNING 2020-08-19 19:12:20,437 kolibri.core.content.management.commands.importcontent 26 files are skipped, because errors occurred during the import.


```

This is with Kolibri 0.14.2 peers.

Does this quality to reopen this issue or should I create a new one?

**Comment by rtibbles** [comment]
Did the import succeed? I don't see any indication that it didn't, so seems like a different issue.

**Comment by intelliant01** [comment]
Yes the import did succeed. I shall be watchful of reappearance of this and shall file a new issue thereafter only. Have not been able to replicate this since its occurance.
