### ISSUE TITLE
Incorrect sizes reported for peer import (Android)

### ISSUE THREAD

**Issue by MasakoOllivier** [learningequality/kolibri#7507]
### Observed behavior

I'm testing Kolibri on Android 10. I'd like to report 2 issues here together since I think they're related.

1) During the import from a peer Kolibri on Mac, the "Total size" shown is the entire KA size (54 GB) on Studio, not the actual KA size on Kolibri on Mac (16 GB).  By the way, on Android, the "On your device" shows 0 resources while the size is 148MB because there were files left on the device after I deleted the KA channel that I originally imported from Studio. This Kolibri on Android shows 0 channels. 

2) As I mentioned above, I'm trying to import a channel on Kolibri on Mac to Android 10 device. Mac Kolibri shows 3 folders, which I imported from Studio. But the list of folders shown on Android has more than 3. This problem also happens on another Kolibri on Mac.

This is the screenshot for peer import of KA on Android 10.

![image](https://user-images.githubusercontent.com/70489926/92433996-78d49a00-f153-11ea-8840-1cdf2529740b.png)

Folder list for peer import on Android 10

![image](https://user-images.githubusercontent.com/70489926/92434812-a6224780-f155-11ea-8add-3756299fe005.png)

Folder list on Mac peer

![image](https://user-images.githubusercontent.com/70489926/92434911-e681c580-f155-11ea-9a44-9e503dcc3db2.png)

### Expected behavior

It should show the correct total size on the peer and 0mb for on your device size (since I deleted the channel).

### User-facing consequences

User may think that they can import content that is not on the peer.

### Errors and logs

Kevin isn't sure if it's related to this problem, but this is the only error we see in the logs.

```
ERROR 2020-09-01 16:56:18,060 django.request Internal Server Error: /api/discovery/staticnetworklocation/
Traceback (most recent call last):
  File "/home/kivy/build/android/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
  File "/home/kivy/build/android/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
  File "/home/kivy/build/android/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
  File "/home/kivy/build/android/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
  File "/home/kivy/build/android/kolibri/dist/rest_framework/viewsets.py", line 116, in view
  File "/home/kivy/build/android/kolibri/dist/rest_framework/views.py", line 495, in dispatch
  File "/home/kivy/build/android/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
  File "/home/kivy/build/android/kolibri/dist/rest_framework/views.py", line 492, in dispatch
  File "/home/kivy/build/android/kolibri/dist/rest_framework/mixins.py", line 20, in create
  File "/home/kivy/build/android/kolibri/dist/rest_framework/serializers.py", line 236, in is_valid
  File "/home/kivy/build/android/kolibri/dist/rest_framework/serializers.py", line 434, in run_validation
  File "/home/kivy/build/android/kolibri/dist/rest_framework/serializers.py", line 493, in to_internal_value
  File "/home/kivy/build/android/kolibri/core/discovery/serializers.py", line 44, in validate_base_url
  File "/home/kivy/build/android/kolibri/core/discovery/utils/network/client.py", line 30, in __init__
  File "/home/kivy/build/android/kolibri/core/discovery/utils/network/client.py", line 49, in _attempt_connections
  File "/home/kivy/build/android/kolibri/dist/requests/models.py", line 897, in json
  File "/home/kivy/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/json/__init__.py", line 357, in loads
  File "/home/kivy/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/json/decoder.py", line 337, in decode
  File "/home/kivy/.local/share/python-for-android/build/other_builds/python3/armeabi-v7a__ndk_target_21/python3/Lib/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Steps to reproduce

1) Import only 2-3 KA channel folders from Studio onto one Kolibri instance. Then try to use peer import to import them onto a different Kolibri instance and see if the total size matches the one on the peer, not Studio.

2) Try to import from a peer and compare the folders on the peer and the destination device.

### Context

Kolibri version: 0.14.3
Operating system: Android 10
Browser: Android App
Device: Nokia 1.3

**Comment by MasakoOllivier** [comment]
Something very strange happened. I'm using the same Android device I mentioned in the report above. (Nokia 1.3; Android 10)

Right after the device is connected to a local peer (Mac), it said 16 GB for "total size" (which is what's on the peer) and 0 resources and 0MB for "on your device" for the first 5-10 seconds and then the numbers changed to 54 GB and 148 MB, as shown in the screenshot. This is the very first time I noticed this and I haven't been able to reproduce this  yet.

I don't know if this means anything, but thought I'd let you guys know.

**Comment by rtibbles** [comment]
There are various things that can go wrong during these calculations for peer and disk import, so I imagine something like that might be at play. Any other logs you can dig up (even ones that are not error tracebacks) would be helpful in narrowing this down.

**Comment by MasakoOllivier** [comment]
Here is a zip file of the logs folder on the Android 10 device. 

[logs-android10.zip](https://github.com/learningequality/kolibri/files/5192268/logs-android10.zip)

**Comment by MasakoOllivier** [comment]
By the way, I tried to see if the information on the device (the total size and the listing) would be the same as the ones on the peer if there is no internet. It didn't make any difference (they were the same as shown in the screenshots).

**Comment by pcenov** [comment]
@radinamatic I'm not able to replicate this one in 0.16.b10

**Comment by radinamatic** [comment]
Closing as not extant on the latest 0.16 build.
