### ISSUE TITLE
Importing sanity checks into cli.py triggers OPTIONS evaluation

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#7682]
### Observed behavior
```
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/kolibripy3/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/richard/github/kolibri/kolibri/utils/cli.py", line 29, in <module>
    from . import sanity_checks
  File "/home/richard/github/kolibri/kolibri/utils/sanity_checks.py", line 14, in <module>
    from .server import get_status
  File "/home/richard/github/kolibri/kolibri/utils/server.py", line 20, in <module>
    from kolibri.core.deviceadmin.utils import schedule_vacuum
  File "/home/richard/github/kolibri/kolibri/core/deviceadmin/utils.py", line 13, in <module>
    from kolibri.core.tasks.main import scheduler
  File "/home/richard/github/kolibri/kolibri/core/tasks/main.py", line 11, in <module>
    from kolibri.core.tasks.queue import Queue
  File "/home/richard/github/kolibri/kolibri/core/tasks/queue.py", line 1, in <module>
    from kolibri.core.tasks.job import Job
  File "/home/richard/github/kolibri/kolibri/core/tasks/job.py", line 7, in <module>
    from kolibri.core.tasks.utils import current_state_tracker
  File "/home/richard/github/kolibri/kolibri/core/tasks/utils.py", line 123, in <module>
    db_task_write_lock = ProcessLock("db_task_write_lock")
  File "/home/richard/github/kolibri/kolibri/core/utils/cache.py", line 34, in __init__
    self.expire = expire if expire else OPTIONS["Cache"]["CACHE_LOCK_TTL"]
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/home/richard/github/kolibri/kolibri/utils/conf.py", line 54, in __initialize_options
    return read_options_file(KOLIBRI_HOME)
  File "/home/richard/github/kolibri/kolibri/utils/options.py", line 465, in read_options_file
    conf = ConfigObj(ini_path, configspec=get_configspec())
  File "/home/richard/github/kolibri/kolibri/utils/options.py", line 429, in get_configspec
    for section, opts in option_spec.items():
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/home/richard/.virtualenvs/kolibripy3/lib/python3.6/site-packages/django/utils/functional.py", line 386, in _setup
    self._wrapped = self._setupfunc()
  File "/home/richard/github/kolibri/kolibri/utils/options.py", line 415, in _get_option_spec
    return extend_config_spec(base_option_spec)
  File "/home/richard/github/kolibri/kolibri/plugins/utils/options.py", line 116, in extend_config_spec
    option_spec, base_config_spec, plugin_specs, module_path, final_spec
  File "/home/richard/github/kolibri/kolibri/plugins/utils/options.py", line 47, in __process_config_spec
    section, name, base_config_spec, plugin_specs, module_path
  File "/home/richard/github/kolibri/kolibri/plugins/utils/options.py", line 17, in __validate_config_option
    raise ValueError("Cannot overwrite a core Kolibri options spec option")
```

While disabling a plugin, just because sanity_checks gets imported in the cli module, nothing is executed.

**Comment by rtibbles** [comment]
This is a regression caused by #7640
