### ISSUE TITLE
Issue with development setup

### ISSUE THREAD

**Issue by shivangtripathi** [learningequality/kolibri#7839]
### Observed behavior

I'm trying to contribute to kolibri codebase and followed all the steps for development setup but I'm getting some error.
Can anyone please help me here  ?
### Errors and logs

```
ERROR    ENGINE Error in 'start' listener <bound method ServicesPlugin.start of <kolibri.utils.server.ServicesPlugin object at 0x7fb755ab1220>>
Traceback (most recent call last):
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: morango_databaseidmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/home/sverus/Documents/GSOC-2021/kolibri/kolibri/utils/server.py", line 117, in start
    register_zeroconf_service(port=self.port)
  File "/home/sverus/Documents/GSOC-2021/kolibri/kolibri/core/discovery/utils/network/search.py", line 188, in register_zeroconf_service
    device_info = get_device_info()
  File "/home/sverus/Documents/GSOC-2021/kolibri/kolibri/core/public/utils.py", line 12, in get_device_info
    instance_model = InstanceIDModel.get_or_create_current_instance()  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/morango/models/core.py", line 142, in get_or_create_current_instance
    database_id=DatabaseIDModel.get_or_create_current_database_id().id
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/morango/models/core.py", line 82, in get_or_create_current_database_id
    return cls.objects.get(current=True)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/sverus/Documents/GSOC-2021/kolibri/venv/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: morango_databaseidmodel
```

### Steps to reproduce

After cloning the kolibri repo and installing all the dependencies , run yarn run devserver

### Context

 
Operating system : Ubuntu

**Comment by ashmeet13** [comment]
Hi!
I was facing this same issue. I believe this was since before running `yarn run devserver` the Django models were not migrated.
Current work around for me was following the [advanced guide](https://kolibri-dev.readthedocs.io/en/develop/getting_started.html#development-server-advanced) - 

Start django in a terminal using - 
```
kolibri manage --debug runserver --settings=kolibri.deployment.default.settings.dev "0.0.0.0:8000"
```
This command migrates the tables for us. After this you can continue using yarn in another terminal as suggested in the advance guide or go back to a single terminal using `yarn run devserver`

---

I think the documentation should be updated with this step or alternative? Or have we missed some step that should have migrated the tables for us?

**Comment by shivangtripathi** [comment]
Thanks @ashmeet13  . It worked for me !
