### ISSUE TITLE
Export  Fail in Kolibri 14.6 (Linux)

### ISSUE THREAD

**Issue by nobicycle** [learningequality/kolibri#7923]
Hello,

I have an export directory:

```
$ ls -l /KOLIBRI_DATA/
total 4
drwxr-xr-x 3 kolibri kolibri 4096 Mar 25 09:26 content


```

In the GUI, this is recognised. I tried an export and obtained:

```
Tasks
Failed

Export 'Using Studio: Your Content Workspace for Kolibri'
Started by 'admin'

```
And the 25M of data did not appear where it should:
> du -h /KOLIBRI_DATA/
4.0K	/KOLIBRI_DATA/content/databases
8.0K	/KOLIBRI_DATA/content
12K	/KOLIBRI_DATA/

Default Python in Manjaro/Arch  Linux is 3.9, - it seems to be working fine.

[daemon.txt](https://github.com/learningequality/kolibri/files/6201525/daemon.txt)
[kolibri.txt](https://github.com/learningequality/kolibri/files/6201526/kolibri.txt)

**Comment by nobicycle** [comment]
I did a CLI export and obtained:
```
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Invoking command exportchannel b62c5c2139a65fb2aaf68987a25b28a1 /KOLIBRI_DATA
INFO     Exporting channel database for channel id b62c5c2139a65fb2aaf68987a25b28a1 to /KOLIBRI_DATA
Traceback (most recent call last):
  File "/opt/kolibri/kolibri-venv/bin/kolibri", line 8, in <module>
    sys.exit(main())
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/utils/cli.py", line 277, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/utils/cli.py", line 727, in manage
    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/content/management/commands/exportchannel.py", line 31, in handle_async
    with transfer.FileCopy(src, dest, cancel_check=self.is_cancelled) as copy:
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/content/utils/transfer.py", line 107, in __enter__
    self.start()
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/content/utils/transfer.py", line 282, in start
    self.total_size = os.path.getsize(self.source)
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/opt/kolibri/.kolibri/content/databases/b62c5c2139a65fb2aaf68987a25b28a1.sqlite3'
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Invoking command exportcontent b62c5c2139a65fb2aaf68987a25b28a1 /KOLIBRI_DATA
INFO     Exporting content for channel id b62c5c2139a65fb2aaf68987a25b28a1 to /KOLIBRI_DATA
Traceback (most recent call last):
  File "/opt/kolibri/kolibri-venv/bin/kolibri", line 8, in <module>
    sys.exit(main())
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/utils/cli.py", line 277, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/utils/cli.py", line 727, in manage
    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/content/management/commands/exportcontent.py", line 75, in handle_async
    ) = get_import_export_data(channel_id, node_ids, exclude_node_ids, True)
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/content/utils/import_export_content.py", line 125, in get_import_export_data
    max_rght, dynamic_chunksize = _calculate_batch_params(
  File "/opt/kolibri/kolibri-venv/lib/python3.9/site-packages/kolibri/core/content/utils/import_export_content.py", line 53, in _calculate_batch_params
    min(CHUNKSIZE, ceil(250 * max_rght / (constraint_count or 1)))
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

```
This issue may be related https://github.com/learningequality/kolibri/issues/7910 bevause the content directory was redirected in my installation.

**Comment by rtibbles** [comment]
This seems to be an edge case when attempting to export a channel that does not exist - is the CLI invocation definitely using the same env vars as the system service env vars that you set in #7910?

**Comment by rtibbles** [comment]
Error messages could be better, but seems like this is attempting to export from the wrong place.
