### ISSUE TITLE
yarn devserver w/ new KOLIBRI_HOME fails initialization and startup

### ISSUE THREAD

**Issue by nucleogenesis** [learningequality/kolibri#7952]
### Observed behavior

When the `KOLIBRI_HOME` points to a nonexistent location, `yarn devserver` fails _the first time_.

Logs below - but it fails on what seems to be a migration that expects `morango` to exist already.

### Expected behavior

Kolibri's devserver should start the first time every time.

### User-facing consequences

Only affects those who use the devserver. `kolibri start` doesn't have issues.

### Errors and logs

```
yarn run v1.22.5
$ npm-run-all --parallel python-devserver-no-update lint-frontend:watch:format hashi-dev watch 
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1617631047423-0.5062880459486847/node but npm is using /home/jacob/.config/nvm/10.24.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> kolibri-root@0.12.0-dev.1 python-devserver-no-update /home/jacob/Code/LearningEquality/kolibri
> kolibri start --debug --skip-update --foreground --port=8000 --settings=kolibri.deployment.default.settings.dev

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1617631047423-0.5062880459486847/node but npm is using /home/jacob/.config/nvm/10.24.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> kolibri-root@0.12.0-dev.1 lint-frontend:watch:format /home/jacob/Code/LearningEquality/kolibri
> yarn run lint-frontend --monitor --write

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1617631047423-0.5062880459486847/node but npm is using /home/jacob/.config/nvm/10.24.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> kolibri-root@0.12.0-dev.1 hashi-dev /home/jacob/Code/LearningEquality/kolibri
> yarn workspace hashi run dev

npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1617631047423-0.5062880459486847/node but npm is using /home/jacob/.config/nvm/10.24.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> kolibri-root@0.12.0-dev.1 watch /home/jacob/Code/LearningEquality/kolibri
> kolibri-tools build dev --file ./build_tools/build_plugins.txt

INFO: No C extensions are available for this platform
$ kolibri-tools lint --pattern '{kolibri*/**/assets,packages,build_tools}/**/*.{js,vue,scss,less,css}' --ignore '**/node_modules/**','**/static/**','**/packages/kolibri-core-for-export/**' --monitor --write
$ yarn run build-base --mode=development --watch
Gathering relevant modules from ['kolibri.core', 'kolibri.plugins.*']
INFO: No C extensions are available for this platform
Writing webpack_json output to /tmp/202135-2519-32xfjn.dj32e.json
INFO: Writing webpack_json output to /tmp/202135-2519-32xfjn.dj32e.json
INFO: Initialized plugins.json
$ webpack --config ./webpack.config.js --mode=development --watch
INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
Kolibri Linter: Initializing watcher for the following patterns: {kolibri*/**/assets,packages,build_tools}/**/*.{js,vue,scss,less,css}

webpack is watching the files…

Kolibri Build: Building 'kolibri.core.frontend_head_assets' bundle...
Kolibri Build: Building 'kolibri.core.default_frontend' bundle...
ℹ ｢wds｣: Project is running at http://0.0.0.0:3000/
ℹ ｢wds｣: webpack output is served from http://localhost:3000/js-dist/
ℹ ｢wds｣: Content not from webpack is served from /home/jacob/Code/LearningEquality/kolibri
ℹ ｢wds｣: Project is running at http://0.0.0.0:3001/
ℹ ｢wds｣: webpack output is served from http://localhost:3001/js-dist/
ℹ ｢wds｣: Content not from webpack is served from /home/jacob/Code/LearningEquality/kolibri
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.dev
Hash: b4e4d8505031a0312b60
Version: webpack 4.6.0
Time: 1054ms
Built at: 04/05/2021 6:57:31 AM
                             Asset     Size  Chunks             Chunk Names
hashiframe-b4e4d8505031a0312b60.js  137 KiB    main  [emitted]  main
Entrypoint main = hashiframe-b4e4d8505031a0312b60.js
[./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {main} [built]
[./src/SCORM.js] 22.5 KiB {main} [built]
[./src/baseShim.js] 1.46 KiB {main} [built]
[./src/baseStorage.js] 4.8 KiB {main} [built]
[./src/compat.js] 559 bytes {main} [built]
[./src/cookie.js] 8.2 KiB {main} [built]
[./src/hashiBase.js] 208 bytes {main} [built]
[./src/iframe.js] 175 bytes {main} [built]
[./src/iframeClient.js] 3.85 KiB {main} [built]
[./src/localStorage.js] 912 bytes {main} [built]
[./src/mediator.js] 3 KiB {main} [built]
[./src/patchIndexedDB.js] 1.29 KiB {main} [built]
[./src/sessionStorage.js] 1.08 KiB {main} [built]
    + 51 hidden modules
INFO     Running Kolibri
INFO     Kolibri running on:

	http://127.0.0.1:8000/
	http://172.17.0.1:8000/
	http://172.18.0.1:8000/
	http://192.168.122.1:8000/
	http://192.168.1.105:8000/

INFO     Starting Kolibri 0.15.0.dev0+git.20210323224100
INFO     ENGINE Listening for SIGTERM.
INFO     ENGINE Listening for SIGHUP.
INFO     ENGINE Listening for SIGUSR1.
INFO     ENGINE Listening for SIGINT.
INFO     ENGINE Bus STARTING
Kolibri Build: Completed 'kolibri.core.frontend_head_assets' bundle in 1.326s!
INFO     Starting scheduler workers.
ERROR    ENGINE Error in 'start' listener <bound method ServicesPlugin.start of <kolibri.utils.server.ServicesPlugin object at 0x7fa234a28210>>
Traceback (most recent call last):
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: morango_databaseidmodel

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/cherrypy/process/wspbus.py", line 230, in publish
    output.append(listener(*args, **kwargs))
  File "/home/jacob/Code/LearningEquality/kolibri/kolibri/utils/server.py", line 117, in start
    register_zeroconf_service(port=self.port)
  File "/home/jacob/Code/LearningEquality/kolibri/kolibri/core/discovery/utils/network/search.py", line 188, in register_zeroconf_service
    device_info = get_device_info()
  File "/home/jacob/Code/LearningEquality/kolibri/kolibri/core/public/utils.py", line 12, in get_device_info
    instance_model = InstanceIDModel.get_or_create_current_instance()  File "/home/jacob/.pyenv/versions/3.7.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/morango/models/core.py", line 142, in get_or_create_current_instance
    database_id=DatabaseIDModel.get_or_create_current_database_id().id
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/morango/models/core.py", line 82, in get_or_create_current_database_id
    return cls.objects.get(current=True)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/query.py", line 374, in get
    num = len(clone)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/query.py", line 232, in __len__
    self._fetch_all()
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: morango_databaseidmodel

INFO     ENGINE Started monitor thread 'Autoreloader'.
INFO     ENGINE Serving on http://0.0.0.0:8888
INFO     ENGINE Serving on http://0.0.0.0:8000
ERROR    ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/cherrypy/process/wspbus.py", line 268, in start
    self.publish('start')
  File "/home/jacob/Code/LearningEquality/kolibri/venv/lib/python3.7/site-packages/cherrypy/process/wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OperationalError('no such table: morango_databaseidmodel')

INFO     ENGINE Bus STOPPING
INFO     ENGINE HTTP Server cheroot.wsgi.Server(('0.0.0.0', 8888)) shut down
INFO     ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 8000)) shut down
INFO     ENGINE Stopped thread 'Autoreloader'.
INFO     Asking job schedulers to shut down.
INFO     Asking job schedulers to shut down.
INFO     Asking job schedulers to shut down.
INFO     Asking job schedulers to shut down.
INFO     Asking job schedulers to shut down.
INFO     Asking job schedulers to shut down.
INFO     ENGINE Bus STOPPED
INFO     ENGINE Bus EXITING
INFO     ENGINE Bus EXITED
npm ERR! code ELIFECYCLE
npm ERR! errno 70
npm ERR! kolibri-root@0.12.0-dev.1 python-devserver-no-update: `kolibri start --debug --skip-update --foreground --port=8000 --settings=kolibri.deployment.default.settings.dev`
npm ERR! Exit status 70
npm ERR! 
npm ERR! Failed at the kolibri-root@0.12.0-dev.1 python-devserver-no-update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jacob/.npm/_logs/2021-04-05T13_57_33_754Z-debug.log
ERROR: "python-devserver-no-update" exited with 70.
error Command failed with exit code 1.
```

### Steps to reproduce

Set your `KOLIBRI_HOME` env var to a folder that doesn't exist.

Run `yarn devserver` - see it fail - run it again and see it succeed.

### Context

[develop@a82f6f27](https://github.com/learningequality/kolibri/commit/7fb314bd90aebcdda41b4f590d12803ca82f6f27)
Debian 10
n/a

**Comment by rtibbles** [comment]
I am unable to replicate this on latest develop - have tried twice with non-existent KOLIBRI_HOME dirs and both times the migrations have run and there are no errors at startup.

**Comment by jonboiser** [comment]
I think this is the exact issue #7938 was supposed to fix.

**Comment by rtibbles** [comment]
Yes - although @nucleogenesis reports the commit that is current HEAD of develop, so this is particularly confusing.

**Comment by jonboiser** [comment]
@nucleogenesis Could you try this again? I'm noticing in the logs, the `devserver` script is still running the old invokations e.g. `npm-run-all --parallel python-devserver-no-update` instead of `run-p python-devserver ...`

**Comment by nucleogenesis** [comment]
@jonboiser bah I fetched but didn't `pull` the changes so I was actually at the wrong commit on develop. Sorry.
