### ISSUE TITLE
Cannot import resources from any source

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8012]
## Observed behavior
After installing the Kolibri https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc6 I cannot import resources from any source (Kolibri Studio, Local network or internet, Attached drive or memory card) because each time I attempt to do so I see a "Sorry! Something went wrong!" error. Importing channels is still functioning correctly on https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc4

## Errors and logs

```
xhr.js:178 GET http://127.0.0.1:8080/device/api/device_channel/000409f81dbe5d1ba67101cb9fed4530/?include_fields=total_resources%2Ctotal_file_size%2Con_device_resources%2Con_device_file_size%2Cnew_resource_count%2Cnew_resource_total_size&1618575976623=1618575976623 404 (Not Found)
(anonymous) @ xhr.js:178
module.exports @ xhr.js:12
module.exports @ dispatchRequest.js:50
Promise.then (async)
Axios.request @ Axios.js:61
(anonymous) @ bind.js:9
client @ client.js:105
Resource.client @ api-resource.js:989
(anonymous) @ api-resource.js:75
Promise.then (async)
(anonymous) @ api-resource.js:68
ConditionalPromise @ conditionalPromise.js:12
Model.fetch @ api-resource.js:67
Resource.fetchModel @ api-resource.js:754
(anonymous) @ apiChannelMetadata.js:7
getChannelWithContentSizes @ apiChannelMetadata.js:6
showSelectContentPage @ handlers.js:161
handler @ wizardTransitionRoutes.js:66
Router._hook @ router.js:22
iterator @ vue-router.esm.js:2225
step @ vue-router.esm.js:1896
(anonymous) @ vue-router.esm.js:1897
(anonymous) @ vue-router.esm.js:2247
(anonymous) @ app.js:23
iterator @ vue-router.esm.js:2225
step @ vue-router.esm.js:1896
step @ vue-router.esm.js:1900
runQueue @ vue-router.esm.js:1904
History.confirmTransition @ vue-router.esm.js:2255
History.transitionTo @ vue-router.esm.js:2125
HashHistory.push @ vue-router.esm.js:2595
VueRouter.push @ vue-router.esm.js:2916
handler @ vue-router.esm.js:1100
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917
api-resource.js:89 [ERROR: kolibri/core/assets/src/api-resource.js] An error occurred Error: Request failed with status code 404
    at module.exports (createError.js:16)
    at module.exports (settle.js:17)
    at XMLHttpRequest.request.onreadystatechange (xhr.js:61)
(anonymous) @ api-resource.js:89
Promise.then (async)
(anonymous) @ api-resource.js:75
Promise.then (async)
(anonymous) @ api-resource.js:68
ConditionalPromise @ conditionalPromise.js:12
Model.fetch @ api-resource.js:67
Resource.fetchModel @ api-resource.js:754
(anonymous) @ apiChannelMetadata.js:7
getChannelWithContentSizes @ apiChannelMetadata.js:6
showSelectContentPage @ handlers.js:161
handler @ wizardTransitionRoutes.js:66
Router._hook @ router.js:22
iterator @ vue-router.esm.js:2225
step @ vue-router.esm.js:1896
(anonymous) @ vue-router.esm.js:1897
(anonymous) @ vue-router.esm.js:2247
(anonymous) @ app.js:23
iterator @ vue-router.esm.js:2225
step @ vue-router.esm.js:1896
step @ vue-router.esm.js:1900
runQueue @ vue-router.esm.js:1904
History.confirmTransition @ vue-router.esm.js:2255
History.transitionTo @ vue-router.esm.js:2125
HashHistory.push @ vue-router.esm.js:2595
VueRouter.push @ vue-router.esm.js:2916
handler @ vue-router.esm.js:1100
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6917
handlers.js:171 ^^^ 404 (Not Found) error returned while requesting "/device/api/device_channel/000409f81dbe5d1ba67101cb9fed4530/..." is an expected response.
api-resource.js:752 Uncaught (in promise) TypeError: An id must be specified
    at Resource.fetchModel (api-resource.js:752)
    at updateTreeViewTopic (handlers.js:267)
    at handlers.js:236

Uncaught (in promise) TypeError: An id must be specified
    at Resource.fetchModel (api-resource.js:752)
    at updateTreeViewTopic (handlers.js:267)
    at handlers.js:236
```

## Expected behavior
A super admin user should be able to import channels.

## Steps to reproduce
1. Install https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc6 on any of the supported operating systems.
2. Sign in as an admin.
3. Navigate to Device/Channels
4. Click the Import button
5. Make sure that Kolibri Studio (online) is selected as a source and click Continue (note that this is valid for the other two options as well).
6. Click the Select resources button of any of the displayed channels.
7. A "Generating channel listing. This could take a few minutes" message is displayed and after a while this is replaced with a "Sorry! Something went wrong!" error.

![2021-04-16_15-36-26](https://user-images.githubusercontent.com/79847249/115025186-b6f42200-9ec9-11eb-881e-b7f616561b03.png)

## Context
 * Kolibri version: https://github.com/learningequality/kolibri/releases/tag/v0.14.7-rc6
 * Operating system: Windows 10, Ubuntu, Mac OS Catalina
 * Browser: Chrome, Firefox

**Comment by radinamatic** [comment]
Identical issue happens when trying to import from Studio on Kolibri Beta site 😕

**Comment by jonboiser** [comment]
Here's the error I get when running an import locally (also at the same spot as Petar, i.e. step 7)

```
OperationalError: (sqlite3.OperationalError) database is locked
[SQL: REPLACE INTO content_contenttag ('id', 'tag_name') SELECT source.id, source.tag_name FROM sourcedb.content_contenttag AS source]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Here are the reports on Sentry: https://sentry.io/organizations/learningequality/issues/?project=1378215&query=is%3Aunresolved%20release%3A0.14.7rc6

Full traceback:
```
RROR    Job cb5825c11fe942bda54066ad7208991b raised an exception: Traceback (most recent call last):
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 72, in handle_finished_future
    result = future.result()
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/dist/py2only/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/tasks/worker.py", line 217, in wrap
    return f(*args, **kwargs)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/tasks/job.py", line 194, in y
    result = func(*args, **kwargs)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py", line 188, in handle_async
    options["channel_id"], options["baseurl"], options["no_upgrade"]
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py", line 95, in download_channel
    self._transfer(DOWNLOAD_METHOD, channel_id, baseurl, no_upgrade=no_upgrade)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py", line 135, in _transfer
    filetransfer, channel_id, dest, no_upgrade=no_upgrade
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py", line 173, in _start_file_transfer
    import_ran = import_channel_by_id(channel_id, self.is_cancelled)
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/management/commands/importchannel.py", line 28, in import_channel_by_id
    channel_id, cancel_check=cancel_check
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/utils/channel_import.py", line 803, in import_channel_from_local_db
    import_ran = import_manager.import_channel_data()
  File "/Users/jon/.pex/install/kolibri-0.14.7rc6-py2.py3-none-any.whl.545676bd6418d48851794d131be541c815a1eecc/kolibri-0.14.7rc6-py2.py3-none-any.whl/kolibri/core/content/utils/channel_import.py", line 624, in import_channel_data
    raise e
OperationalError: (sqlite3.OperationalError) database is locked
[SQL: REPLACE INTO content_contenttag ('id', 'tag_name') SELECT source.id, source.tag_name FROM sourcedb.content_contenttag AS source]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by bjester** [comment]
As @rtibbles noted, the issue appears to be:
> caused by the SQLAlchemy db queries not being properly embedded in the transaction that is being opened by django in the db_lock context manager.
