### ISSUE TITLE
Deleting unused files in slow filesystems does not work

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#8155]
## Observed behavior
Having problems trying to import a channel with multiple files that have changed. It's even impossible to delete the channel files and start again because of database timeouts when using deletecontent

## Errors and logs
In a kolibri shell:
```

>>> from kolibri.core.content.models import LocalFile
>>> unused_files = LocalFile.objects.get_unused_files()
>>> unused_files.count()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/query.py", line 364, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/sql/query.py", line 499, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/sql/query.py", line 480, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: canceling statement due to statement timeout
```

Also:
```
>>> LocalFile.objects.delete_unused_files()
<generator object delete_unused_files at 0x7feebe8df1e0>
>>> for file in LocalFile.objects.delete_unused_files():
...     print(str(file))
... 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/kolibri/core/content/models.py", line 257, in delete_unused_files
    for file in self.get_unused_files():
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/usr/local/lib/python2.7/dist-packages/kolibri/dist/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
OperationalError: canceling statement due to statement timeout

```
This is happening in a Mexico UNW server while trying to delete a channel to reimport it again, as upgrading is not working either.

https://github.com/learningequality/kolibri/blob/v0.14.7/kolibri/core/content/models.py#L271-L274 is the code failing

This produces this query:
```
SELECT "content_localfile"."id",
       "content_localfile"."extension",
       "content_localfile"."available",
       "content_localfile"."file_size"
FROM "content_localfile"
LEFT OUTER JOIN "content_file" ON ("content_localfile"."id" = "content_file"."local_file_id")
WHERE ((NOT ("content_localfile"."id" IN
               (SELECT U1."local_file_id" AS Col1
                FROM "content_file" U1
                INNER JOIN "content_contentnode" U2 ON (U1."contentnode_id" = U2."id")
                WHERE U2."available" =TRUE))
        OR "content_file"."id" IS NULL)
       AND "content_localfile"."available" = TRUE)
```
that timeouts in the Postgresql db
`OperationalError: canceling statement due to statement timeout`

## Expected behavior
`kolibri manage deletechannel 4f87bc8aab92410d96689bf7b9ccdfa8`
should work fine

## User-facing consequences
Upgrading or importing a channel in the server is not possible

## Steps to reproduce
Specified in the above logs

## Context
Mexico UNW pod
kolibri 0.14.7

**Comment by rtibbles** [comment]
Fixed in #8156
