### ISSUE TITLE
Wrong error message when syncing without proper credentials

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#8235]
## Observed behavior

Trying to sync an user using credentials of a coach, without admin permissions, returns a 500 Server Error. I was expecting some kind of Unauthorized error

## Errors and logs
```
jose@jose-xps:/tmp$ python3 kolibri-0.15.0a2.pex manage sync --baseurl "http://10.8.0.1:8080/" --facility "0c247b28ad893a6cdaaab26a08467727" --username "profjose" --password "profjose" --user "19f03619fce90507d8fb24347d904e92"
INFO     Option RUN_MODE in section [Deployment] being overridden by environment variable KOLIBRI_RUN_MODE
INFO     Running Kolibri with the following settings: kolibri.deployment.default.settings.base
INFO     Importing 'tasks' module from django apps
INFO     Invoking command sync --baseurl http://10.8.0.1:8080/ --facility 0c247b28ad893a6cdaaab26a08467727 --username profjose --password profjose --user 19f03619fce90507d8fb24347d904e92
INFO     Attempting connections to variations of the URL: http://10.8.0.1:8080/
INFO     Attempting connection to: http://10.8.0.1:8080/
INFO     Success! We connected to: http://10.8.0.1:8080/api/public/info/?v=2
ERROR    HTTPError Reason: (no response)
Traceback (most recent call last):
  File "/tmp/kolibri-0.15.0a2.pex/.bootstrap/_pex/pex.py", line 349, in execute
  File "/tmp/kolibri-0.15.0a2.pex/.bootstrap/_pex/pex.py", line 281, in _wrap_coverage
  File "/tmp/kolibri-0.15.0a2.pex/.bootstrap/_pex/pex.py", line 312, in _wrap_profiling
  File "/tmp/kolibri-0.15.0a2.pex/.bootstrap/_pex/pex.py", line 394, in _execute
  File "/tmp/kolibri-0.15.0a2.pex/.bootstrap/_pex/pex.py", line 506, in execute_entry
  File "/tmp/kolibri-0.15.0a2.pex/.bootstrap/_pex/pex.py", line 513, in execute_module
  File "/usr/lib/python3.8/runpy.py", line 210, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/__main__.py", line 11, in <module>
    main(args=sys.argv[1:])
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/utils/cli.py", line 194, in invoke
    return super(KolibriDjangoCommand, self).invoke(ctx)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/utils/cli.py", line 362, in manage
    execute_from_command_line(["kolibri manage"] + ctx.args)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/core/auth/management/commands/sync.py", line 151, in handle_async
    client_cert, server_cert, username = get_client_and_server_certs(
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/core/auth/management/utils.py", line 230, in get_client_and_server_certs
    client_cert = nc.certificate_signing_request(
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/morango/sync/syncsession.py", line 356, in certificate_signing_request
    csr_resp = self._certificate_signing(data, userargs, password)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/morango/sync/syncsession.py", line 429, in _certificate_signing
    return self.session.post(
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/morango/sync/session.py", line 66, in request
    raise req_err
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/morango/sync/session.py", line 55, in request
    response.raise_for_status()
  File "/home/jose/.pex/install/kolibri-0.15.0a2-py2.py3-none-any.whl.cec1f081fd1cbbd85f2d51b8bd2ec20de32fe99d/kolibri-0.15.0a2-py2.py3-none-any.whl/kolibri/dist/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.8.0.1:8080/api/morango/v1/certificates/

```

## Expected behavior
Expected a message saying I have no permissions plus a right error code

## User-facing consequences

Not knowing if the server is broken or it's my fault

## Steps to reproduce

Included with the error logs

## Context

 * Kolibri version kolibri-0.15.0a2.pex/
 * Linux

**Comment by jredrejo** [comment]
Tested with kolibri 0.16 beta10.
A coach user is synced, if the proper credentials are given, but the synced user has only learner permissions in the synced facility.
This seems to be fine according to the current kolibri LOD syncing rules.
