### ISSUE TITLE
shutting down devserver throws innaccurate TransferCanceled exception

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#828]
## Summary

I successfully imported a channel. However - much later, when I closed the server - I got an unhandled exception saying that the transfer had been cancelled.

## System information

* Kolibri `develop` branch
* OSX 10.9
* Python 2.7

## Traceback or relevant snippet from server.log or browser console

Initial content import appeared to complete from the web UI. Output in console is less clear on that:

```
[21/Jan/2017 00:42:02] "GET /api/tasks/ HTTP/1.1" 200 2
[21/Jan/2017 00:42:03] "GET /api/tasks/ HTTP/1.1" 200 2
[21/Jan/2017 00:42:04] "GET /api/tasks/ HTTP/1.1" 200 2
[21/Jan/2017 00:42:04] "POST /api/tasks/startremoteimport/ HTTP/1.1" 200 115
00:42:05 [Q] INFO Got job for worker 11392
00:42:05 [Q] INFO Process-1:1:1 processing [alabama-maine-potato-iowa]
[21/Jan/2017 00:42:05] "GET /api/tasks/ HTTP/1.1" 200 120
INFO     Downloading data for channel id 7db80873586841e4a1c249b2bb8ba62d
DEBUG    URL to fetch: https://contentworkshop.learningequality.org/content/databases/7db80873586841e4a1c249b2bb8ba62d.sqlite3
DEBUG    Destination: /Users/d/.kolibri/content/databases/7db80873586841e4a1c249b2bb8ba62d.sqlite3
DEBUG:kolibri.content.management.commands.importchannel:Destination: /Users/d/.kolibri/content/databases/7db80873586841e4a1c249b2bb8ba62d.sqlite3
100%|████████████████████████████████| 84992/84992 [00:00<00:00, 1211626.36it/s]
 22%|████▋                | 233704058/1041864914 [00:00<00:01, 759135065.62it/s][21/Jan/2017 00:42:06] "GET /api/tasks/ HTTP/1.1" 200 216
100%|███████████████████| 1041864914/1041864914 [00:00<00:00, 1314730766.12it/s]
00:42:06 [Q] INFO Processed [alabama-maine-potato-iowa]
[21/Jan/2017 00:42:07] "GET /api/tasks/ HTTP/1.1" 200 181
[21/Jan/2017 00:42:08] "GET /api/tasks/ HTTP/1.1" 200 181
[21/Jan/2017 00:42:09] "GET /api/tasks/ HTTP/1.1" 200 181
[21/Jan/2017 00:42:10] "GET /api/tasks/ HTTP/1.1" 200 181
No handlers could be found for logger "django_q.models"
[21/Jan/2017 00:42:10] "POST /api/tasks/cleartask/ HTTP/1.1" 200 2
[21/Jan/2017 00:42:11] "GET /api/tasks/ HTTP/1.1" 200 2
[21/Jan/2017 00:42:11] "GET /coach/ HTTP/1.1" 200 9026
[21/Jan/2017 00:42:12] "GET /api/currentfacility/ HTTP/1.1" 200 3
[21/Jan/2017 00:42:12] "GET /api/content/ HTTP/1.1" 200 883
[21/Jan/2017 00:42:13] "GET /coach/api/7db80873586841e4a1c249b2bb8ba62d/facility/1/contentsummary/860f3b6ad1a14b47baee3a60765e0657/ HTTP/1.1" 200 357
[21/Jan/2017 00:42:13] "GET /coach/api/7db80873586841e4a1c249b2bb8ba62d/860f3b6ad1a14b47baee3a60765e0657/facility/1/contentreport/ HTTP/1.1" 200 989
[21/Jan/2017 00:42:14] "GET /coach/ HTTP/1.1" 200 9026
[21/Jan/2017 00:42:15] "GET /api/content/ HTTP/1.1" 200 883
```

Lots of time passes. Then I press <kbd>ctrl</kbd>+<kbd>c</kbd> and:

```
^C03:14:11 [Q] INFO Q Cluster-11390 stopping.
Process Process-1:1:1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/d/PythonEnvs/le/lib/python2.7/site-packages/django_q/cluster.py", line 358, in worker
    for task in iter(task_queue.get, 'STOP'):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
  File "/Users/d/Projects/learning_equality/repos/kolibri/kolibri/content/utils/transfer.py", line 104, in _kill_gracefully
    raise TransferCanceled("The transfer was canceled.")
TransferCanceled: The transfer was canceled.
```

## Real-life consequences (anything community should be aware of, for instance how it affects your deployment)

Unhandled exception and unexpected behavior might be indicative of more bugs lurking.

Perhaps related to #614?

**Comment by jonboiser** [comment]
I was able to reproduce this.

@jamalex 
At this line https://github.com/jonboiser/kolibri/blame/last-updated/kolibri/content/utils/transfer.py#L48

An event handler is set up for 'CTRL-C', which says to throw that 'TransferCanceled' exception.

Is that event handler supposed to be removed when the Transfer is concluded?

**Comment by jonboiser** [comment]
The Ctrl-C handler was recently commented-out, as a move towards performing this action on web UI instead of terminal.
