### ISSUE TITLE
After syncing failing because of a server error, the user does not try to sync ever again

### ISSUE THREAD

**Issue by jredrejo** [learningequality/kolibri#8340]
## Observed behavior
While trying to sync a server error happened.
After that the user didn't try to sync again

## Errors and logs

```
ERROR    HTTPError Reason: (no response)
ERROR    500 Server Error: Internal Server Error for url: http://10.8.0.1:8080/api/morango/v1/transfersessions/
ERROR    Job 78d88154a276c3971a2615be3755674f raised an exception: Traceback (most recent call last):
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/controller.py", line 236, in _invoke_middleware
    result = middleware(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/registry.py", line 228, in __call__
    result = operation(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/operations.py", line 544, in __call__
    result = self.handle(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/operations.py", line 1040, in handle
    self.create_transfer_session(context)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/operations.py", line 875, in create_transfer_session
    return context.connection._create_transfer_session(
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/syncsession.py", line 445, in _create_transfer_session
    return self.session.post(self.urlresolve(api_urls.TRANSFERSESSION), json=data)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/session.py", line 66, in request
    raise req_err
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/session.py", line 55, in request
    response.raise_for_status()
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://10.8.0.1:8080/api/morango/v1/transfersessions/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datos/le/mio/kolibri/kolibri/core/tasks/worker.py", line 66, in handle_finished_future
    result = future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/job.py", line 111, in execute_job
    result = func(*args, **kwargs)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/datos/le/mio/kolibri/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/datos/le/mio/kolibri/kolibri/core/auth/management/commands/sync.py", line 239, in handle_async
    self._handle_pull(
  File "/datos/le/mio/kolibri/kolibri/core/auth/management/commands/sync.py", line 357, in _handle_pull
    sync_client.initialize(Filter(filt))
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/syncsession.py", line 645, in initialize
    self.proceed_to_and_wait_for(transfer_stages.SERIALIZING)
  File "/datos/le/mio/kolibri/venv/lib/python3.8/site-packages/morango/sync/syncsession.py", line 610, in proceed_to_and_wait_for
    raise_from(
  File "<string>", line 2, in raise_from
morango.errors.MorangoError: Stage `serializing` failed

```

## Expected behavior
After a server error, sync should be tried again

## User-facing consequences
Needs to restart the server to sync again

**Comment by jredrejo** [comment]
Fixed in #8342
