### ISSUE TITLE
'Device can not sync with itself'  and 'too many open files' errors

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/kolibri#8391]
## Observed behavior

"Target" SOUD device running as `devserver` on port 8000 with its own `KOLIBRI_HOME`:

```
INFO: 127.0.0.1 - - "GET /api/public/info/" 200 0 "" "python-requests/2.21.0"
INFO     Success! We connected to: http://127.0.0.1:8000/api/public/info/?v=2
INFO: 127.0.0.1 - - "GET /api/morango/v1/morangoinfo/1/" 200 0 "" "python-requests/2.21.0"
ERROR    Error syncing user 71e93f65d3ad8472f6e72fc2cf9312e5 to server http://127.0.0.1:9999
INFO: Requeueing to sync with server http://127.0.0.1:9999 for user 71e93f65d3ad8472f6e72fc2cf9312e5 in 5 seconds
ERROR    Job bd25c620f6038ac28b85c0534cc4df70 raised an exception: Traceback (most recent call last):
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/worker.py", line 66, in handle_finished_future
    result = future.result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/job.py", line 111, in execute_job
    result = func(*args, **kwargs)
  File "/Users/d/Projects/le/kolibri/kolibri/core/public/utils.py", line 94, in peer_sync
    call_command("sync", **kwargs)
  File "/Users/d/Projects/le/kolibri/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/Users/d/Projects/le/kolibri/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/d/Projects/le/kolibri/kolibri/core/tasks/management/commands/base.py", line 119, in handle
    return self.handle_async(*args, **options)
  File "/Users/d/Projects/le/kolibri/kolibri/core/auth/management/commands/sync.py", line 134, in handle_async
    raise CommandError(
django.core.management.base.CommandError: Device can not sync with itself. Please recheck base URL and try again.
```

"Source" device running as production server on port 9999 with its own `KOLIBRI_HOME`.

Saw lots of these:

```
Traceback (most recent call last):
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/utils/deprecation.py", line 140, in __call__
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 43, in inner
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
  File "/Users/d/.pyenv/versions/3.7.11/lib/python3.7/logging/__init__.py", line 1407, in error
  File "/Users/d/.pyenv/versions/3.7.11/lib/python3.7/logging/__init__.py", line 1514, in _log
  File "/Users/d/.pyenv/versions/3.7.11/lib/python3.7/logging/__init__.py", line 1524, in handle
  File "/Users/d/.pyenv/versions/3.7.11/lib/python3.7/logging/__init__.py", line 1586, in callHandlers
  File "/Users/d/.pyenv/versions/3.7.11/lib/python3.7/logging/__init__.py", line 894, in handle
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/utils/log.py", line 119, in emit
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/views/debug.py", line 334, in get_traceback_text
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/base.py", line 207, in render
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/base.py", line 990, in render
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/base.py", line 957, in render_annotated
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/base.py", line 1040, in render
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/base.py", line 736, in resolve
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/template/defaultfilters.py", line 764, in date
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/utils/formats.py", line 162, in date_format
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/utils/formats.py", line 129, in get_format
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/utils/formats.py", line 98, in get_format_modules
  File "/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/utils/formats.py", line 86, in iter_format_modules
  File "/Users/d/.pyenv/versions/3.7.11/lib/python3.7/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
OSError: [Errno 24] Too many open files: '/Users/d/Projects/le/kolibri-2/.venv/lib/python3.7/site-packages/django/conf/locale'
```

followed by lots of stuff like this:

```
SQL: SELECT jobs.id AS jobs_id, jobs.state AS jobs_state, jobs.queue_order AS jobs_queue_order, jobs.queue AS jobs_queue, jobs.obj AS jobs_obj, jobs.time_created AS jobs_time_created, jobs.time_updated AS jobs_time_updated 
FROM jobs 
WHERE jobs.queue IN (?) AND jobs.state = ? ORDER BY jobs.queue_order
 LIMIT ? OFFSET ?]
[parameters: ('kolibri', 'QUEUED', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
WARNING  Got an exception running <bound method Worker.check_jobs of <kolibri.core.tasks.worker.Worker object at 0x10e4b6b90>>: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/e3q8)
WARNING  Got an exception running <bound method Worker.check_jobs of <kolibri.core.tasks.worker.Worker object at 0x10e4b6e10>>: (sqlite3.OperationalError) unable to open database file
[SQL: SELECT jobs.id AS jobs_id, jobs.state AS jobs_state, jobs.queue_order AS jobs_queue_order, jobs.queue AS jobs_queue, jobs.obj AS jobs_obj, jobs.time_created AS jobs_time_created, jobs.time_updated AS jobs_time_updated 
FROM jobs 
WHERE jobs.queue IN (?) AND jobs.state = ? ORDER BY jobs.queue_order
 LIMIT ? OFFSET ?]
[parameters: ('no_waiting', 'QUEUED', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
WARNING  Got an exception running <bound method Scheduler.check_schedule of <kolibri.core.tasks.scheduler.Scheduler object at 0x10de41410>>: (sqlite3.OperationalError) unable to open database file
[SQL: SELECT scheduledjobs.id AS scheduledjobs_id, scheduledjobs.interval AS scheduledjobs_interval, scheduledjobs.repeat AS scheduledjobs_repeat, scheduledjobs.queue AS scheduledjobs_queue, scheduledjobs.obj AS scheduledjobs_obj, scheduledjobs.scheduled_time AS scheduledjobs_scheduled_time 
FROM scheduledjobs 
WHERE scheduledjobs.queue = ? AND scheduledjobs.scheduled_time <= ?]
[parameters: ('kolibri', '2021-09-03 17:57:38.106192')]
```

Full logs:

* [target-logs.txt](https://github.com/learningequality/kolibri/files/7107772/target-logs.txt)
* [source-logs.txt](https://github.com/learningequality/kolibri/files/7107773/source-logs.txt)

## Context

source device running latest develop. target device running code from #8370

**Comment by rtibbles** [comment]
I am guessing `device cannot sync with itself` is a result of both the devices having the same device ID by virtue of them running on the same hardware and hence having the same MAC address.

**Comment by indirectlylit** [comment]
possibly. It was a bit weird because the system ran for quite some time before throwing that error though (see target logs)

**Comment by indirectlylit** [comment]
(also if running two Kolibri instances on separate ports is not supported for testing syncing, I could use some guidance on recommended test setup)

**Comment by jamalex** [comment]
As long as you're running with different databases (not just a copy-paste of the DB file), you are fine running multiple instances on the same computer on different ports. the "database_id", which is generated fresh for each new database, is one of the inputs into calculating the instance_id.

**Comment by jamalex** [comment]
>Success! We connected to: http://127.0.0.1:8000/api/public/info/?v=2

Is it actually connecting to itself for some reason?

**Comment by jamalex** [comment]
The INFO line above the first error says "Requeueing" for port 9999, but it's possible the sync that's shown with the error there was it trying to sync with itself for some reason?

**Comment by indirectlylit** [comment]
have not reproduced lately
