### ISSUE TITLE
Process cache can cause 'too many open files'

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8618]
## Observed behavior
500 errors caused by having too many open file handles at once!

## Errors and logs
```
ERROR    Internal Server Error: /en/auth/

Traceback (most recent call last):

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 217, in _get_response

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 215, in _get_response

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/response.py", line 107, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/response.py", line 84, in rendered_content

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/backends/django.py", line 66, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 207, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 199, in _render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 990, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 957, in render_annotated

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/loader_tags.py", line 177, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 199, in _render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 990, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 957, in render_annotated

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/dist/django/template/library.py", line 203, in render

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/core/webpack/templatetags/webpack_tags.py", line 42, in webpack_asset

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/core/kolibri_plugin.py", line 178, in render_to_page_load_sync_html

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/core/webpack/hooks.py", line 223, in js_and_css_tags

File "/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/core/webpack/hooks.py", line 345, in get_filecontent

File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 898, in open

IOError: [Errno 24] Too many open files: u'/Users/lauradanforth/.pex/install/kolibri-0.15.0b1-py2.py3-none-any.whl.3134d3aa97d8173c47655647faade689af511cd9/kolibri-0.15.0b1-py2.py3-none-any.whl/kolibri/core/static/kolibri.core.frontend_head_assets/kolibri.core.frontend_head_assets-0.15.0b1.js'
```

## Expected behavior
We should not have so many files open that it causes an issue for any OS.

## Context
Version 0.15.0b1
OS: MacOS

**Comment by lauradanforth** [comment]
From the Activity Monitor log:
```
cwd
/Users/lauradanforth/Downloads
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/Python
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_locale.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/zlib.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_functools.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_collections.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/operator.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/itertools.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_heapq.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/bz2.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/grp.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/math.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/binascii.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_hashlib.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_random.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cStringIO.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/fcntl.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/time.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_struct.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/strop.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ctypes.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/select.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_socket.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_ssl.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_scproxy.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/datetime.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/pyexpat.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_json.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_bisect.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/unicodedata.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/termios.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/cPickle.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/array.so
txt
/Library/Preferences/Logging/.plist-cache.17ovdbe4
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/future_builtins.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_sqlite3.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_multiprocessing.so
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_csv.so
txt
/Users/lauradanforth/.kolibri/process_cache/000/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/002/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/003/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/004/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/005/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/006/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/007/cache.db-shm
txt
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_elementtree.so
txt
/Users/lauradanforth/.kolibri/process_cache/004/cache.db
txt
/usr/lib/dyld
0
/dev/ttys000
1
/dev/ttys000
2
/dev/ttys000
3
->0xe2523b9a54df4ba9
4
*:http-alt
5
/dev/urandom
6
*:57213
7
->0xb21be54e34b672a3
8
/Users/lauradanforth/.kolibri/process_cache/000/cache.db
9
/Users/lauradanforth/.kolibri/process_cache/000/cache.db-wal
10
/Users/lauradanforth/.kolibri/process_cache/000/cache.db-shm
11
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
12
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
13
[ctl com.apple.netsrc id 6 unit 33]
14
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-shm
15
/Users/lauradanforth/.kolibri/process_cache/002/cache.db
16
/Users/lauradanforth/.kolibri/process_cache/002/cache.db-wal
17
/Users/lauradanforth/.kolibri/process_cache/002/cache.db-shm
18
/Users/lauradanforth/.kolibri/process_cache/003/cache.db
19
/Users/lauradanforth/.kolibri/process_cache/003/cache.db-wal
20
/Users/lauradanforth/.kolibri/process_cache/003/cache.db-shm
21
/Users/lauradanforth/.kolibri/process_cache/004/cache.db
22
/Users/lauradanforth/.kolibri/process_cache/004/cache.db-wal
23
/Users/lauradanforth/.kolibri/process_cache/004/cache.db-shm
24
/Users/lauradanforth/.kolibri/process_cache/005/cache.db
25
/Users/lauradanforth/.kolibri/process_cache/005/cache.db-wal
26
/Users/lauradanforth/.kolibri/process_cache/005/cache.db-shm
27
/Users/lauradanforth/.kolibri/process_cache/006/cache.db
28
/Users/lauradanforth/.kolibri/process_cache/006/cache.db-wal
29
/Users/lauradanforth/.kolibri/process_cache/006/cache.db-shm
30
/Users/lauradanforth/.kolibri/process_cache/007/cache.db
31
/Users/lauradanforth/.kolibri/process_cache/007/cache.db-wal
32
/Users/lauradanforth/.kolibri/process_cache/007/cache.db-shm
33
count=0, state=0xa
34
/Users/lauradanforth/.kolibri/logs/kolibri.txt
35
/Users/lauradanforth/.kolibri/logs/debug.txt
36
*:mdns
37
*:mdns
38
*:mdns
39
/Users/lauradanforth/.kolibri/networklocation.sqlite3
40
count=0, state=0xa
41
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
42
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
43
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
44
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
45
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
46
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
47
/Users/lauradanforth/.kolibri/process_cache/004/cache.db
48
/Users/lauradanforth/.kolibri/process_cache/004/cache.db-wal
49
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
50
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
51
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
52
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
53
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
54
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
55
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
56
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
57
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
58
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
59
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
60
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
61
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
62
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
63
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
64
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
65
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
66
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
67
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
68
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
69
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
70
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
71
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
72
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
73
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
74
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
75
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
76
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
77
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
78
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
79
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
80
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
81
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
82
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
83
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
84
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
85
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
86
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
87
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
88
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
89
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
90
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
91
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
92
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
93
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
94
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
95
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
96
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
97
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
98
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
99
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
100
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
101
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
102
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
103
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
104
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
105
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
106
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
107
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
108
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
109
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
110
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
111
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
112
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
113
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
114
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
115
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
116
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
117
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
118
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
119
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
120
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
121
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
122
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
123
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
124
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
125
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
126
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
127
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
128
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
129
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
130
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
131
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
132
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
133
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
135
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
136
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
137
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
138
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
139
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
140
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
141
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
142
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
143
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
144
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
145
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
146
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
147
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
148
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
149
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
150
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
151
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
152
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
153
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
154
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
155
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
156
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
157
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
158
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
159
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
160
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
161
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
162
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
163
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
164
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
165
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
166
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
167
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
168
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
169
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
170
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
171
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
172
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
173
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
174
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
175
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
176
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
177
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
178
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
179
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
180
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
181
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
182
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
183
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
184
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
185
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
186
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
187
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
188
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
189
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
190
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
191
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
192
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
193
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
194
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
195
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
196
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
197
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
198
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
199
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
200
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
201
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
202
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
203
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
204
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
205
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
206
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
207
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
208
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
209
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
210
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
211
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
212
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
213
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
214
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
215
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
216
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
217
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
218
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
219
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
220
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
221
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
222
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
223
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
224
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
225
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
226
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
227
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
228
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
229
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
230
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
231
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
232
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
233
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
234
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
235
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
236
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
237
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
238
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
239
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
240
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
241
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
242
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
243
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
244
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
245
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
246
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
247
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
248
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
249
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
250
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
251
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
252
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
254
/Users/lauradanforth/.kolibri/process_cache/001/cache.db
255
/Users/lauradanforth/.kolibri/process_cache/001/cache.db-wal
```

**Comment by rtibbles** [comment]
I think the reason this has occurred now is because of this commit: https://github.com/learningequality/kolibri/commit/7e71861d0845f92386deff0b13bffe13e3ec6548#diff-cb6c0f86a32632cac86043c281d79adf4f2d8ac10ad41b75c733a8b57d1e6988 the removal of the built files cache has resulted in additional disk access.

I think we shouldn't revert this commit, but might be good to add memory caching of the stats files and inline JS files contents to avoid extra reads to disk. Can just add this as attributes on the `WebpackBundleHook` so that they are persisted across requests.

**Comment by bjester** [comment]
It appears that with every new request, it opens new file descriptors:
```
lrwx------ 1 bjester bjester 64 Nov 10 08:38 61 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db-wal
lrwx------ 1 bjester bjester 64 Nov 10 08:39 62 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db
lrwx------ 1 bjester bjester 64 Nov 10 08:39 63 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db-wal
lrwx------ 1 bjester bjester 64 Nov 10 08:39 64 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db
lrwx------ 1 bjester bjester 64 Nov 10 08:39 65 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db-wal
lrwx------ 1 bjester bjester 64 Nov 10 08:39 66 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db
lrwx------ 1 bjester bjester 64 Nov 10 08:39 67 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db-wal
lrwx------ 1 bjester bjester 64 Nov 10 08:39 68 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/004/cache.db
lrwx------ 1 bjester bjester 64 Nov 10 08:39 69 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/004/cache.db-wal
lrwx------ 1 bjester bjester 64 Nov 10 08:39 70 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db
lrwx------ 1 bjester bjester 64 Nov 10 08:39 71 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db-wal
lrwx------ 1 bjester bjester 64 Nov 10 08:39 73 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db
lrwx------ 1 bjester bjester 64 Nov 10 08:39 74 -> /home/bjester/.kolibri-pexer/kolibri-0.15.0b1.dev0_git.29.g817885eb/python-8080/process_cache/001/cache.db-wal
```

**Comment by bjester** [comment]
This occurs on 0.14.7 as well, but the caching that was removed mitigated the quantity of fds.

**Comment by bjester** [comment]
Okay so putting some debugging logs into the diskcache lib, it appears that the approach it uses to manage the connection isn't working correctly. So it's constantly re-opening connections but not actually closing the connection. I should have also seen `Successfully closed cache connection` if it actually closed an existing connection
```
WARNING: PID mismatch | None != 46912 | closing and re-opening cache connection
WARNING: Closing cache connection
WARNING: Opening cache connection | 46912
```

**Comment by indirectlylit** [comment]
@bjester this isn't something I have much experience with but let me know if I can help with testing or debugging

**Comment by bjester** [comment]
@indirectlylit Since this is no longer specific to Macs, I will unassign you from the issue. Thanks!
