### ISSUE TITLE
Search - Getting a 500 error after having applied too many filters

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#8737]
## Observed behavior
When searching I'm getting a 500 error after having applied too many filters. The issue could be caused by the fake data used but should be further investigated.

## Expected behavior
Fully functional search functionality. 

## Steps to reproduce the issue
1. Install the following [build.](https://github.com/learningequality/kolibri/releases/tag/v0.15.0-beta2)
2. Import some channels and run the following management command: `kolibri manage labeltestdata `
3. Filter by as many criteria as possible

## Additional information

![2021-11-18_19-35-32](https://user-images.githubusercontent.com/79847249/142470762-279635ad-7bba-456b-8a6f-514730c49e84.png)

## Logs

[logs.zip](https://github.com/learningequality/kolibri/files/7564984/logs.zip)

## Usage Details
 - OS: Windows 10
 - Browser: Chrome

**Comment by pcenov** [comment]
@radinamatic

**Comment by rtibbles** [comment]
Oh wow, that's interesting, this actually caused a too many SQL variables error!

```
ERROR 2021-11-18 19:34:18,963 django.request Internal Server Error: /api/content/contentnode/
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: too many SQL variables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\handlers\exception.py", line 41, in inner
    response = get_response(request)
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "c:\python36\lib\site-packages\kolibri\dist\django\core\handlers\base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "c:\python36\lib\site-packages\kolibri\dist\django\views\decorators\csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\dist\rest_framework\viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\dist\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\auth\middleware.py", line 107, in wrapper_func
    return view(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\content\api.py", line 90, in wrapper_func
    response = some_func(*args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\dist\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "c:\python36\lib\site-packages\kolibri\dist\rest_framework\views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "c:\python36\lib\site-packages\kolibri\dist\rest_framework\views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "c:\python36\lib\site-packages\kolibri\dist\rest_framework\views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "c:\python36\lib\site-packages\kolibri\core\api.py", line 329, in list
    return self.get_paginated_response(self.serialize(queryset))
  File "c:\python36\lib\site-packages\kolibri\dist\rest_framework\generics.py", line 180, in get_paginated_response
    return self.paginator.get_paginated_response(data)
  File "c:\python36\lib\site-packages\kolibri\core\content\api.py", line 474, in get_paginated_response
    ("labels", get_available_metadata_labels(self.queryset)),
  File "c:\python36\lib\site-packages\kolibri\core\content\utils\search.py", line 109, in get_available_metadata_labels
    result = queryset.values(*all_values).first()
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\query.py", line 567, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\query.py", line 250, in __iter__
    self._fetch_all()
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\query.py", line 106, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch):
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\sql\compiler.py", line 841, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch)
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\sql\compiler.py", line 899, in execute_sql
    raise original_exception
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\models\sql\compiler.py", line 889, in execute_sql
    cursor.execute(sql, params)
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "c:\python36\lib\site-packages\kolibri\dist\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "c:\python36\lib\site-packages\kolibri\dist\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: too many SQL variables
```
