### ISSUE TITLE
Build error did not break the build.

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#8960]
## Observed behavior
Frontend build for a plugin broke, but the build still exited with a 0 error code.

## Errors and logs
```
Kolibri Build: Failed to compile 'kolibri.plugins.coach.app' bundle!
./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$core-time".
        on line 590 of /home/richard/github/kolibri/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue
>>     transition: all $core-time;

   --------------------^

Kolibri Production Build: There was a build error for kolibri.plugins.coach.app
Kolibri Production Build: 
ERROR in ./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true& (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--3-2!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true&)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable: "$core-time".
        on line 590 of /home/richard/github/kolibri/kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue
>>     transition: all $core-time;

   --------------------^

    at runLoaders (/home/richard/github/kolibri/node_modules/webpack/lib/NormalModule.js:316:20)
    at /home/richard/github/kolibri/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/richard/github/kolibri/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/richard/github/kolibri/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.render [as callback] (/home/richard/github/kolibri/node_modules/sass-loader/dist/index.js:73:7)
    at Object.done [as callback] (/home/richard/github/kolibri/node_modules/neo-async/async.js:8067:18)
    at options.error (/home/richard/github/kolibri/node_modules/node-sass/lib/index.js:294:32)
 @ ./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue?vue&type=style&index=0&id=7c60ddb1&lang=scss&scoped=true& 1:0-531 1:547-550 1:552-1080 1:552-1080
 @ ./kolibri/plugins/coach/assets/src/views/plan/LessonResourceSelectionPage/index.vue
 @ ./kolibri/plugins/coach/assets/src/routes/planLessonsRoutes.js
 @ ./kolibri/plugins/coach/assets/src/routes/planRoutes.js
 @ ./kolibri/plugins/coach/assets/src/routes/index.js
 @ ./kolibri/plugins/coach/assets/src/app.js
```

And yet still showed:
```
Kolibri Build: Initial build complete in 51.808 seconds
```

## Expected behavior
Build failure should result in non-zero exit code.

**Comment by rtibbles** [comment]
Fixed in #9014
