### ISSUE TITLE
500 error when refreshing /en/device/ due to transaction error (during single-user-syncing from this user)

### ISSUE THREAD

**Issue by marcellamaki** [learningequality/kolibri#9418]
from 0.15.3-a0 bug bash 

## Errors and logs

```
ERROR 2022-05-06 14:24:10,549 django.request Internal Server Error: /en/device/
Traceback (most recent call last):
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/http.py", line 88, in inner
    res_etag = etag_func(request, *args, **kwargs) if etag_func else None
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/decorators.py", line 363, in calculate_spa_etag
    etag = render_and_cache(response, CACHE_KEY_TEMPLATE.format(request.path))
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/decorators.py", line 342, in render_and_cache
    response.render()
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/response.py", line 84, in rendered_content
    content = template.render(context, self._request)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/django/template/library.py", line 203, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/webpack/templatetags/webpack_tags.py", line 42, in webpack_asset
    return hook.render_to_page_load_sync_html()
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/kolibri_plugin.py", line 107, in render_to_page_load_sync_html
    + self.navigation_tags()
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/webpack/hooks.py", line 263, in plugin_data_tag
    if self.plugin_data:
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/kolibri_plugin.py", line 127, in plugin_data
    "contentCacheKey": ContentCacheKey.get_cache_key(),
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/core/device/models.py", line 159, in get_cache_key
    cache.set(CONTENT_CACHE_KEY_CACHE_KEY, key, 5000)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/diskcache/djangocache.py", line 147, in set
    return self._cache.set(key, value, timeout, read, tag, retry)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/diskcache/fanout.py", line 97, in set
    return shard.set(key, value, expire, read, tag, retry)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/diskcache/core.py", line 842, in set
    return True
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/jamalex/.pex/install/kolibri-0.15.2-py2.py3-none-any.whl.b1f6d8c79573a7c7990a890cbd916d25e85a6288/kolibri-0.15.2-py2.py3-none-any.whl/kolibri/dist/diskcache/core.py", line 767, in _transact
    sql('ROLLBACK')
OperationalError: cannot rollback - no transaction is active
```
-->

…

## Expected behavior
Page should still be available while single user syncing is happening

## Context
Jamie	Ubuntu 20.04	Chrome

**Comment by rtibbles** [comment]
This and #9417 are the same issue at heart - the disk cache throwing some sort of error and it being unhandled. We should wrap our use of diskcache to catch these errors and instead return no value.

Alternatively, maybe we should update our version of diskcache.
