### ISSUE TITLE
django_q.routers does not exist

### ISSUE THREAD

**Issue by benjaoming** [learningequality/kolibri#951]
## Summary

Starting Kolibri for the first time or running migrations for the first time, produces the below error

## System information

Both `master` and `release` branches.

## Traceback or relevant snippet from server.log or browser console

```
➜  kolibri git:(master) kolibri manage migrate
Traceback (most recent call last):
  File ".virtualenvs/kolibri/bin/kolibri", line 11, in <module>
    load_entry_point('kolibri', 'console_scripts', 'kolibri')()
  File "/media/archive/code/kolibri/kolibri/utils/cli.py", line 273, in main
    manage(command, args=django_args)
  File "/media/archive/code/kolibri/kolibri/utils/cli.py", line 193, in manage
    execute_from_command_line(argv=argv)
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/management/base.py", line 398, in execute
    self.check()
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/models/base.py", line 1178, in check
    errors.extend(cls._check_fields(**kwargs))
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/models/base.py", line 1255, in _check_fields
    errors.extend(field.check(**kwargs))
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 925, in check
    errors = super(AutoField, self).check(**kwargs)
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 208, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 316, in _check_backend_specific_checks
    if router.allow_migrate(db, app_label, model=self.model):
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/utils.py", line 294, in allow_migrate
    for router in self.routers:
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/db/utils.py", line 252, in routers
    router = import_string(r)()
  File ".virtualenvs/kolibri/lib/python3.5/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File ".virtualenvs/kolibri/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django_q.router'

```

## How to reproduce

You need a clean `.kolibri`

**Comment by aronasorman** [comment]
Will try to reproduce next week.

**Comment by benjaoming** [comment]
Still reproducing this on `master` and clean `.kolibri`.

**Comment by benjaoming** [comment]
Still reproducing this on fresh `develop` with fresh `~/.kolibri` - can anybody say what's happening? I have `django_q` installed.

**Comment by benjaoming** [comment]
AHA! Removed my virtualenv and started over, and now it works. Unfortunately, that way I lost evidence of the issue.. so all I can positively say is that "yes, django_q was installed", but somehow it wasn't able to import it.. perhaps some kind of half-baked installation.
