### ISSUE TITLE
AttributeError: module 'markdown' has no attribute 'version'

### ISSUE THREAD

**Issue by antil0l** [learningequality/kolibri#9583]
so this is the error i was getting after a full system update on arch linux, i fixed the issue with changing `~/.local/lib/python3.10/site-packages/kolibri/dist/rest_framework/compat.py`, only changed the lines 176 and 179 (if u just scroll down to see the solution)

```
INFO: No C extensions are available for this platform
INFO     Option DEBUG in section [Server] being overridden by environment variable KOLIBRI_DEBUG
INFO     Option DEBUG_LOG_DATABASE in section [Server] being overridden by environment variable KOLIBRI_DEBUG_LOG_DATABASE
Error: Traceback (most recent call last):
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/utils/cli.py", line 193, in invoke
    initialize(**get_initialize_params())
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/utils/main.py", line 284, in initialize
    _setup_django()
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/utils/main.py", line 153, in _setup_django
    django.setup()
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/dist/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/dist/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/dist/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/core/models.py", line 12, in <module>
    registered_plugins.register_non_plugins(settings.INSTALLED_APPS)
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/plugins/registry.py", line 150, in register_non_plugins
    initialize_kolibri_plugin(app)
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/plugins/utils/__init__.py", line 145, in initialize_kolibri_plugin
    plugin_module = importlib.import_module(plugin_name + ".kolibri_plugin")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/core/auth/kolibri_plugin.py", line 3, in <module>
    from kolibri.core.auth.sync_operations import KolibriSingleUserSyncOperation
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/core/auth/sync_operations.py", line 5, in <module>
    from morango.sync.operations import BaseOperation
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/dist/morango/sync/operations.py", line 18, in <module>
    from rest_framework.exceptions import ValidationError
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/dist/rest_framework/exceptions.py", line 18, in <module>
    from rest_framework.compat import unicode_to_repr
  File "/home/lol/.local/lib/python3.10/site-packages/kolibri/dist/rest_framework/compat.py", line 176, in <module>
    if markdown.version <= '2.2':
AttributeError: module 'markdown' has no attribute 'version'
```
---

this is the part i edited, basically added __ to both sides of the versions  
```py
    if markdown.__version__ <= '2.2':
        HEADERID_EXT_PATH = 'headerid'
        LEVEL_PARAM = 'level'
    elif markdown.__version__ < '2.6':
        HEADERID_EXT_PATH = 'markdown.extensions.headerid'
        LEVEL_PARAM = 'level'
```
---

apparently the folder that the file is in is populated automatically, i have no idea what to do about that, or whether anyone else has ever had this issue at all

**Comment by rtibbles** [comment]
`markdown` is an optional dependency of Django REST Framework - it appears that since version 3.4, `markdown` no longer supports the `version` property, as it had previously been deprecated.

I would suggest either uninstalling the markdown library, or pinning it to a version less than 3.4.

**Comment by rtibbles** [comment]
Going to close this as resolved - thanks for posting!
