### ISSUE TITLE
Add sanity check to ensure that Job Storage tables are ready

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#9613]
## Observed behavior
In 0.15 the deletion and recreation of Job Storage tables at every restart was removed. This means that there are some possible scenarios where Kolibri could attempt to start, but the storage tables do not exist.

## Errors and logs
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/kolibri/dist/magicbus/base.py", line 215, in _transition
    return self.publish(newstate, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/kolibri/dist/magicbus/base.py", line 291, in publish
    raise exc
magicbus.base.ChannelFailures: ProgrammingError('(psycopg2.errors.UndefinedColumn) column scheduledjobs.saved_job does not exist\nLINE 1: ...peat, scheduledjobs.queue AS scheduledjobs_queue, scheduledj...\n       
```

## Expected behavior
Kolibri should check that these tables are accessible and recreate them if not.

**Comment by rtibbles** [comment]
Fixed in #9722
