### ISSUE TITLE
develop: Kolibri fails to initialize after registering a custom plugin

### ISSUE THREAD

**Issue by manuq** [learningequality/kolibri#9693]
## Observed behavior
On the Android app using the develop branch: trying to register a custom plugin makes the `initialize()` fail with:

## Errors and logs
```
09-03 00:47:15.778  9445  9527 I python  : Traceback (most recent call last):
09-03 00:47:15.779  9445  9527 I python  :   File "/sysroot/home/manuq/eos/hack/gitrepos/kolibri-installer-android/src/main.py", line 238, in <module>
09-03 00:47:15.779  9445  9527 I python  :   File "/sysroot/home/manuq/eos/hack/gitrepos/kolibri-installer-android/src/main.py", line 209, in start_kolibri
09-03 00:47:15.779  9445  9527 I python  :   File "/sysroot/home/manuq/eos/hack/gitrepos/kolibri-installer-android/src/kolibri/utils/main.py", line 281, in initialize
09-03 00:47:15.779  9445  9527 I python  :   File "/sysroot/home/manuq/eos/hack/gitrepos/kolibri-installer-android/src/kolibri/utils/main.py", line 196, in _upgrades_before_django_setup
09-03 00:47:15.780  9445  9527 I python  :   File "/sysroot/home/manuq/eos/hack/gitrepos/kolibri-installer-android/src/kolibri/plugins/utils/__init__.py", line 397, in autoremove_unavailable_plugins
09-03 00:47:15.780  9445  9527 I python  : RuntimeError: Attempted to update plugins when registry is initialized
09-03 00:47:15.780  9445  9527 I python  : Python for android ended.
```

## Expected behavior
Using Kolibri v0.15 we were able to do something like the following to replace the Learn plugin by another custom plugin:
```
from kolibri.utils.cli import initialize
from kolibri.main import disable_plugin
from kolibri.main import enable_plugin
from kolibri.plugins.registry import registered_plugins

enable_plugin("kolibri.plugins.app")
disable_plugin("kolibri.plugins.learn")
registered_plugins.register_plugins(["kolibri_explore_plugin"])
enable_plugin("kolibri_explore_plugin")

# later:
# we need to initialize Kolibri to allow us to access the app key
initialize()
```

**Comment by rtibbles** [comment]
This is intended behaviour - you are prematurely initializing the plugin registry with the call to `registered_plugins.register_plugins` - this is also unnecessary for what you are trying to achieve.
