### ISSUE TITLE
When logged in as an admin, using a migrated postgres database, the classroom summary API endpoint can return a 500

### ISSUE THREAD

**Issue by rtibbles** [learningequality/kolibri#9903]
## Observed behavior
When logged in as an admin (but not for a coach viewing the same class) this error was observed:
```
Traceback (most recent call last):
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/dist/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/plugins/coach/class_summary_api.py", line 352, in retrieve
    lesson_data, learners_data, classroom
  File "/home/ec2-user/.pex/install/kolibri-0.15.8-py2.py3-none-any.whl.0baa536de4c69a649285ff6cbd1cc0e9f3cdfdda/kolibri-0.15.8-py2.py3-none-any.whl/kolibri/plugins/coach/class_summary_api.py", line 144, in content_status_serializer
    return map(map_content_logs, content_log_values)
TypeError: argument 2 to map() must support iteration
```

## Context
0.15.8 pex file
Linux

A Kolibri instance migrated from SQLite to Postgresql.

**Comment by rtibbles** [comment]
It seems like this is this Django error: https://code.djangoproject.com/ticket/26600

**Comment by rtibbles** [comment]
It's possible this may be symptomatic of an underlying postgres query timeout - so we should ensure that in the admin case this is not returning more data than it ought.
