### ISSUE TITLE
0.16 - Import facility is not functioning

### ISSUE THREAD

**Issue by pcenov** [learningequality/kolibri#9934]
## Observed behavior
Every time I attempt to import a facility I am getting an error at step 2 of 4: Remotely preparing data

## Expected behavior
Fully operational facility import functionality.

## Steps to reproduce the issue
1. Install the the following [0. 16 build ](https://buildkite.com/learningequality/kolibri-debian/builds/5491) 
2. Go to Device > Facilities and try to import a facility.

## Video

https://user-images.githubusercontent.com/79847249/208684180-673c0a70-760b-4b6f-b9b7-c8a4b4395838.mp4

## Error details:

```
ERROR 2022-12-20 15:43:28,452 kolibri.core.tasks.job Job 9d4555d955ed4ef3ae8b579102c7603b raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 270, in execute
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/registry.py", line 223, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/tasks.py", line 381, in peerfacilityimport
    call_command(command, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 28, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/commands/sync.py", line 180, in handle_async
    self._sync(sync_session_client, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/utils.py", line 435, in _sync
    pull_filter,
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/utils.py", line 539, in _pull
    sync_client.run()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 650, in run
    transfer_session=self.current_transfer_session
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/utils.py", line 225, in __enter__
    self.started.fire()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/utils.py", line 192, in fire
    handler(**fire_kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/utils.py", line 192, in fire
    handler(**fire_kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/utils.py", line 668, in handler
    increment=math.ceil(progress - tracker.progress),
AttributeError: 'Command' object has no attribute 'progress'

INFO 2022-12-20 15:43:39,144 kolibri.core.discovery.utils.network.client Attempting connections to variations of the URL: http://192.168.100.176:8080/
INFO 2022-12-20 15:43:39,145 kolibri.core.discovery.utils.network.client Attempting connection to: http://192.168.100.176:8080/
INFO 2022-12-20 15:43:39,215 kolibri.core.discovery.utils.network.client Success! We connected to: http://192.168.100.176:8080/api/public/info/?v=2
INFO 2022-12-20 15:43:40,377 kolibri.core.auth.management.utils Remotely preparing data
ERROR 2022-12-20 15:43:42,197 kolibri.core.tasks.job Job 9d4555d955ed4ef3ae8b579102c7603b raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/job.py", line 270, in execute
    result = func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/registry.py", line 223, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/tasks.py", line 381, in peerfacilityimport
    call_command(command, **kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3/dist-packages/kolibri/dist/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/tasks/management/commands/base.py", line 28, in handle
    return self.handle_async(*args, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/commands/sync.py", line 180, in handle_async
    self._sync(sync_session_client, **options)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/utils.py", line 435, in _sync
    pull_filter,
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/utils.py", line 539, in _pull
    sync_client.run()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/syncsession.py", line 650, in run
    transfer_session=self.current_transfer_session
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/utils.py", line 225, in __enter__
    self.started.fire()
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/utils.py", line 192, in fire
    handler(**fire_kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/dist/morango/sync/utils.py", line 192, in fire
    handler(**fire_kwargs)
  File "/usr/lib/python3/dist-packages/kolibri/core/auth/management/utils.py", line 668, in handler
    increment=math.ceil(progress - tracker.progress),
AttributeError: 'Command' object has no attribute 'progress'
```

## Usage Details
Windows 10, Ubuntu - Chrome, Firefox

**Comment by pcenov** [comment]
@radinamatic
